- packages/amplify_analytics_pinpoint/CHANGELOG.md
- packages/amplify_analytics_plugin_interface/CHANGELOG.md
- packages/amplify_auth_cognito/CHANGELOG.md
- packages/amplify_auth_plugin_interface/CHANGELOG.md
- packages/amplify_core/CHANGELOG.md
- packages/amplify_core_plugin_interface/CHANGELOG.md
- packages/amplify_storage_plugin_interface/CHANGELOG.md
- packages/amplify_storage_s3/CHANGELOG.md
* Update changelogs for version `0.0.1-dev.0` to all packages
> chore: update initial changelog for all packages [skip ci]

- packages/amplify_core/pubspec.yaml
> fix: add auth plugin interface to core dependencies

- packages/amplify_analytics_pinpoint/pubspec.yaml
- packages/amplify_analytics_plugin_interface/pubspec.yaml
- packages/amplify_auth_cognito/pubspec.yaml
- packages/amplify_auth_plugin_interface/pubspec.yaml
- packages/amplify_storage_plugin_interface/pubspec.yaml
- packages/amplify_storage_s3/pubspec.yaml
> fix: fix package dependencies

- packages/amplify_analytics_pinpoint/CHANGELOG.md
- packages/amplify_analytics_pinpoint/pubspec.yaml
- packages/amplify_analytics_plugin_interface/CHANGELOG.md
- packages/amplify_analytics_plugin_interface/pubspec.yaml
- packages/amplify_auth_cognito/CHANGELOG.md
- packages/amplify_auth_cognito/pubspec.yaml
- packages/amplify_auth_plugin_interface/CHANGELOG.md
- packages/amplify_auth_plugin_interface/pubspec.yaml
- packages/amplify_core/CHANGELOG.md
- packages/amplify_core/pubspec.yaml
- packages/amplify_core_plugin_interface/CHANGELOG.md
- packages/amplify_core_plugin_interface/pubspec.yaml
- packages/amplify_storage_plugin_interface/CHANGELOG.md
- packages/amplify_storage_plugin_interface/pubspec.yaml
- packages/amplify_storage_s3/CHANGELOG.md
- packages/amplify_storage_s3/pubspec.yaml
> fix: fix meta dependency version [skip ci]

- README.md
> Fix getting started link

- README.md
README update directs readers to the instructions for installing the correct flutter preview verison.
> fix(README): update cli link

- README.md
- packages/amplify_auth_cognito/example/lib/main.dart
- packages/amplify_auth_cognito/test/amplify_auth_cognito_getCurrentUser_test.dart
- packages/amplify_core_plugin_interface/lib/amplify_auth_category.dart
> fix(amplify_auth_cognito): methodname typo

- packages/amplify_auth_cognito/android/build.gradle
- packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPluginTest.kt
Fixing gradle version of cognito gradle dep.
> fix(amplify_auth_cognito): gradle cognito

- packages/amplify_storage_s3/android/build.gradle
Upgrade aws-storage-s3 version in build.gradle to match core
> fix(amplify_storage_s3): upgrade aws-storage-s3 version

- example/README.md
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/Pages/LandingPage.dart
- example/lib/Views/SignInView.dart
- example/lib/main.dart
Remove cognito feetch auto session example - this needs to be fixed on Amplify iOS first
Clarify key points for using the sample in the Readme.
> Fix Sample App

- .github/ISSUE_TEMPLATE/bug_report.md
- packages/amplify_analytics_pinpoint/README.md
- packages/amplify_analytics_plugin_interface/README.md
- packages/amplify_analytics_plugin_interface/pubspec.yaml
- packages/amplify_auth_cognito/README.md
- packages/amplify_auth_plugin_interface/README.md
- packages/amplify_auth_plugin_interface/pubspec.yaml
- packages/amplify_core/README.md
- packages/amplify_core/pubspec.yaml
- packages/amplify_core_plugin_interface/README.md
- packages/amplify_core_plugin_interface/pubspec.yaml
- packages/amplify_storage_plugin_interface/README.md
- packages/amplify_storage_plugin_interface/pubspec.yaml
- packages/amplify_storage_s3/README.md
* Update all package README.md files to match the description field in pubspec.
> chore: update package README's to match pubspec

- .github/ISSUE_TEMPLATE/bug_report.md
> Fix typo in bug template

- example/pubspec.yaml
- packages/amplify_analytics_pinpoint/CHANGELOG.md
- packages/amplify_analytics_pinpoint/pubspec.yaml
- packages/amplify_analytics_plugin_interface/CHANGELOG.md
- packages/amplify_analytics_plugin_interface/pubspec.yaml
- packages/amplify_auth_cognito/CHANGELOG.md
- packages/amplify_auth_cognito/pubspec.yaml
- packages/amplify_auth_plugin_interface/CHANGELOG.md
- packages/amplify_auth_plugin_interface/pubspec.yaml
- packages/amplify_core/CHANGELOG.md
- packages/amplify_core/pubspec.yaml
- packages/amplify_core_plugin_interface/CHANGELOG.md
- packages/amplify_core_plugin_interface/pubspec.yaml
- packages/amplify_storage_plugin_interface/CHANGELOG.md
- packages/amplify_storage_plugin_interface/pubspec.yaml
- packages/amplify_storage_s3/CHANGELOG.md
- packages/amplify_storage_s3/pubspec.yaml
Merging released code into master (version bumps and changelogs)
> chore(release): Publish 10-08-2020

- packages/amplify_datastore/README.md
> chore: add developer docs for datastore library

- packages/amplify_datastore/lib/method_channel_datastore.dart
Removes QueryPredicate from delete method channel
> fix(amplify_datastore) remove QueryPredicate

- packages/amplify_datastore/ios/amplify_datastore.podspec
> Add API plugin dependency for online sync

- packages/amplify_analytics_pinpoint/android/build.gradle
- packages/amplify_auth_cognito/android/build.gradle
- packages/amplify_core/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_storage_s3/android/build.gradle
> Upgrade android library to 1.6.2

- packages/amplify_auth_cognito/lib/event_channel_auth_cognito.dart
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/DataStoreHubEventStreamHandler.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterHubElement.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterHubEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterModelSyncedEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterNetworkStatusEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterOutboxMutationEnqueuedEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterOutboxMutationProcessedEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterOutboxStatusEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterReadyEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterSubscriptionsEstablishedEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterSyncMetaData.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterSyncQueriesReadyEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterSyncQueriesStartedEvent.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStoreHubTest.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePluginTest.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/Latch.kt
- packages/amplify_datastore/example/lib/main.dart
- packages/amplify_datastore/lib/amplify_datastore.dart
- packages/amplify_datastore/lib/event_channel_datastore.dart
- packages/amplify_datastore/test/resources/hub/modelSyncedEvent.json
- packages/amplify_datastore/test/resources/hub/networkStatusEvent.json
- packages/amplify_datastore/test/resources/hub/outboxMutationEnqueuedEvent.json
- packages/amplify_datastore/test/resources/hub/outboxMutationProcessedEvent.json
- packages/amplify_datastore/test/resources/hub/outboxStatusEvent.json
- packages/amplify_datastore/test/resources/hub/readyEvent.json
- packages/amplify_datastore/test/resources/hub/subscriptionsEstablishedEvent.json
- packages/amplify_datastore/test/resources/hub/syncQueriesReadyEvent.json
- packages/amplify_datastore/test/resources/hub/syncQueriesStartedEvent.json
> feat(amplify_datastore) Android/Dart Hub Events (#197)

- packages/amplify_core/pubspec.yaml
Description of changes:*
adds datastore interface dep to core
> adds datastore interface dep to core

- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePluginTest.kt
fixes android unit tests by passing hub handler to constructor
> fix(amplify_datastore) android test fix

- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePluginTest.kt
Passes mockHubHandler to test plugin constructor.
> fix(amplify_datastore) fix Android tests

- packages/amplify_analytics_pinpoint/android/build.gradle
- packages/amplify_auth_cognito/android/build.gradle
- packages/amplify_core/android/build.gradle
- packages/amplify_core/pubspec.yaml
- packages/amplify_datastore/android/build.gradle
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/DataStoreObserveEventStreamHandler.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePluginTest.kt
- packages/amplify_datastore/example/lib/amplifyconfiguration.dart
- packages/amplify_datastore/example/lib/codegen/Blog.dart
- packages/amplify_datastore/example/lib/codegen/ModelProvider.dart
- packages/amplify_datastore/example/lib/codegen/Post.dart
- packages/amplify_datastore/example/lib/event_display_widgets.dart
- packages/amplify_datastore/example/lib/main.dart
- packages/amplify_datastore/example/lib/queries_display_widgets.dart
- packages/amplify_datastore/example/lib/save_model_widgets.dart
- packages/amplify_storage_s3/android/build.gradle
> DataStore testapp

- packages/amplify_datastore/example/ios/amplify_datastore_unit_tests/DataStoreHubEventStreamHandlerTests.swift
> fix(amplify_datastore) fix ios hub tests

- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterHubElement.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterOutboxMutationEnqueuedEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterOutboxMutationProcessedEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterSyncMetaData.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStoreHubTest.kt
Accounts for new amplify-android version in datastore hub event handler (android).
> Hub outboxmutation fix

- packages/amplify_analytics_pinpoint/android/build.gradle
- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt
- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt
- packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPluginTest.kt
- packages/amplify_auth_cognito/example/ios/amplify_auth_cognito_tests/amplify_auth_cognito_tests.swift
- packages/amplify_auth_cognito/example/lib/main.dart
- packages/amplify_auth_cognito/ios/Classes/AuthCognitoBridge.swift
- packages/amplify_auth_cognito/ios/Classes/FlutterFetchCognitoSessionResult.swift
- packages/amplify_auth_cognito/lib/method_channel_auth_cognito.dart
- packages/amplify_auth_cognito/lib/src/CognitoSession/AWSCognitoUserPoolTokens.dart
- packages/amplify_auth_cognito/lib/src/CognitoSession/AWSCredentials.dart
- packages/amplify_auth_cognito/lib/src/CognitoSession/CognitoAuthSession.dart
- packages/amplify_auth_cognito/test/amplify_auth_cognito_fetchSession_test.dart
#148 
#163 
#178 
This PR addresses several platform-specific discrepencies between Android and iOS which have resulted in bugs.
> fix(amplify_auth_cognito) guest creds, userpool-only config, and access tokens

- packages/amplify_core/ios/amplify_core.podspec
Changes ios version back to 11.
> fix(amplify_core) change ios version back to 11

- README.md
- packages/amplify_analytics_pinpoint/CHANGELOG.md
- packages/amplify_analytics_plugin_interface/CHANGELOG.md
- packages/amplify_core/CHANGELOG.md
- packages/amplify_core_plugin_interface/CHANGELOG.md
- packages/amplify_datastore/CHANGELOG.md
- packages/amplify_datastore_plugin_interface/CHANGELOG.md
- packages/amplify_storage_plugin_interface/CHANGELOG.md
- packages/amplify_storage_s3/CHANGELOG.md
> Update readme and changelog in preparation of datastore release

- packages/amplify_auth_cognito/CHANGELOG.md
- packages/amplify_auth_plugin_interface/CHANGELOG.md
Updates auth plugin changelog.
> chore(amplify_auth_cognito) update changelog

- packages/amplify_datastore/example/README.md
Update readme of the datastore app to show how to use the app.
Rendered version: https://github.com/Amplifiyer/amplify-flutter/tree/update-example-app-readme/packages/amplify_datastore/example
> chore(amplify_datastore) Update readme of the sample app

- example/android/app/src/main/kotlin/com/example/sample_app/MainActivity.kt
- packages/amplify_analytics_pinpoint/android/src/test/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPluginTest.kt
- packages/amplify_analytics_pinpoint/example/android/app/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint_example/MainActivity.kt
- packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPluginTest.kt
- packages/amplify_auth_cognito/example/android/app/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito_example/MainActivity.kt
- packages/amplify_core/android/src/test/kotlin/com/amazonaws/amplify/amplify_core/AmplifyCoreTest.kt
- packages/amplify_core/example/android/app/src/main/kotlin/com/amplifyframework/flutter/amplify_core_example/MainActivity.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/Latch.kt
- packages/amplify_datastore/example/android/app/src/main/kotlin/com/amazonaws/amplify/amplify_datastore_example/MainActivity.kt
- packages/amplify_storage_s3/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/types/FlutterDownloadFileRequest.kt
- packages/amplify_storage_s3/example/android/app/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3_example/MainActivity.kt
> chore: add some missing headers on kotlin files

- packages/amplify_analytics_pinpoint/CHANGELOG.md
- packages/amplify_analytics_plugin_interface/CHANGELOG.md
- packages/amplify_auth_cognito/CHANGELOG.md
- packages/amplify_auth_plugin_interface/CHANGELOG.md
- packages/amplify_core/CHANGELOG.md
- packages/amplify_core_plugin_interface/CHANGELOG.md
- packages/amplify_datastore/CHANGELOG.md
- packages/amplify_datastore_plugin_interface/CHANGELOG.md
- packages/amplify_storage_plugin_interface/CHANGELOG.md
- packages/amplify_storage_s3/CHANGELOG.md
Updates amplify_datastore CHANGELOG.md.
> chore: update changelogs

- example/pubspec.yaml
- packages/amplify_analytics_pinpoint/pubspec.yaml
- packages/amplify_analytics_plugin_interface/pubspec.yaml
- packages/amplify_api/pubspec.yaml
- packages/amplify_auth_cognito/pubspec.yaml
- packages/amplify_auth_plugin_interface/pubspec.yaml
- packages/amplify_core/pubspec.yaml
- packages/amplify_core_plugin_interface/pubspec.yaml
- packages/amplify_datastore/example/pubspec.yaml
- packages/amplify_datastore/pubspec.yaml
- packages/amplify_datastore_plugin_interface/pubspec.yaml
- packages/amplify_storage_plugin_interface/pubspec.yaml
- packages/amplify_storage_s3/pubspec.yaml
This commit bumps the package versions and removes local paths in preparation for the release.
> chore(release): Update package versions

- packages/amplify_flutter/lib/amplify.dart
- packages/amplify_flutter/lib/categories/amplify_api_category.dart
- packages/amplify_flutter/lib/categories/amplify_auth_category.dart
- packages/amplify_flutter/lib/categories/amplify_datastore_category.dart
- packages/amplify_flutter/lib/categories/amplify_storage_category.dart
- packages/amplify_flutter/pubspec.yaml
- packages/amplify_flutter/test/amplify_test.dart
Several other enhancements including error messages, documentation and unit tests.
*Issue #, if available:* Fixes #300, #302, #124
> fix(amplify_flutter): Add a new method isConfigured to Amplify

- README.md
Update readme.md with updates to the library.
* Add API and GraphQL category as supported.
* Update code sample based on the refactor changes.
* Add note for upcoming breaking changes.
> Update readme with updates to the library.

- example/pubspec.yaml
- packages/amplify_analytics_pinpoint/CHANGELOG.md
- packages/amplify_analytics_pinpoint/pubspec.yaml
- packages/amplify_analytics_plugin_interface/CHANGELOG.md
- packages/amplify_analytics_plugin_interface/pubspec.yaml
- packages/amplify_api/CHANGELOG.md
- packages/amplify_api/pubspec.yaml
- packages/amplify_api_plugin_interface/CHANGELOG.md
- packages/amplify_api_plugin_interface/pubspec.yaml
- packages/amplify_auth_cognito/CHANGELOG.md
- packages/amplify_auth_cognito/pubspec.yaml
- packages/amplify_auth_plugin_interface/CHANGELOG.md
- packages/amplify_auth_plugin_interface/pubspec.yaml
- packages/amplify_core/CHANGELOG.md
- packages/amplify_core/pubspec.yaml
- packages/amplify_datastore/CHANGELOG.md
- packages/amplify_datastore/pubspec.yaml
- packages/amplify_datastore_plugin_interface/CHANGELOG.md
- packages/amplify_datastore_plugin_interface/pubspec.yaml
- packages/amplify_flutter/pubspec.yaml
- packages/amplify_storage_plugin_interface/CHANGELOG.md
- packages/amplify_storage_plugin_interface/pubspec.yaml
- packages/amplify_storage_s3/CHANGELOG.md
- packages/amplify_storage_s3/pubspec.yaml
Add changelog and upgrade version for release 0.0.2-dev.1
> Add changelog and upgrade version for release 0.0.2-dev.1

- packages/amplify_analytics_pinpoint/android/build.gradle
- packages/amplify_api/android/build.gradle
- packages/amplify_auth_cognito/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_flutter/android/build.gradle
- packages/amplify_storage_s3/android/build.gradle
*Issue #, if available:* fixes #330
*Description of changes:* update amplify-android library version to 1.6.10
> chore: update amplify-android library version to 1.6.10

- packages/amplify_datastore/example/lib/main.dart
- packages/amplify_datastore/lib/method_channel_datastore.dart
> fix(amplify_datastore): fix minor error handling in datastore dart code

- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterSignInWithWebUIRequest.kt
- packages/amplify_auth_cognito/example/ios/unit_tests/amplify_auth_cognito_tests.swift
- packages/amplify_auth_cognito/example/lib/Widgets/SignInWidget.dart
- packages/amplify_auth_cognito/ios/Classes/FlutterSignInWithWebUIRequest.swift
- packages/amplify_auth_cognito/test/amplify_auth_cognito_signInWithWebUI_test.dart
- packages/amplify_auth_plugin_interface/lib/src/SignIn/AuthProvider.dart
Adds sign in with apple to hosted ui providers, and simplifies amazon enum.
[omchiii](https://github.com/omchiii) should be listed as co-author on this commit.
> feat: sign in with apple

- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt
- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterSignInWithWebUIRequest.kt
> fix(amplify_datastore): fix compile issue with newer gradle plugin

- packages/amplify_api/example/lib/graphql_api_view.dart
- packages/amplify_flutter/lib/categories/amplify_api_category.dart
Add `@required` annotation for subscribe callbacks
> Add @required annotation for subscribe callbacks

- .circleci/config.yml
- packages/amplify_api/example/ios/Podfile
- packages/amplify_datastore/example/ios/Podfile
Upgrades melos in circleci config.
> fix: upgrade melos

- packages/amplify_api/pubspec.yaml
- packages/amplify_api_plugin_interface/pubspec.yaml
- packages/amplify_core/pubspec.yaml
- packages/amplify_datastore/pubspec.yaml
- packages/amplify_datastore_plugin_interface/pubspec.yaml
- packages/amplify_flutter/pubspec.yaml
Removes upper constraints in pubspec files.
> chore: remove upper constraints for flutter 2.0

- packages/amplify_api/CHANGELOG.md
- packages/amplify_api_plugin_interface/CHANGELOG.md
- packages/amplify_core/CHANGELOG.md
- packages/amplify_datastore/CHANGELOG.md
- packages/amplify_datastore_plugin_interface/CHANGELOG.md
- packages/amplify_flutter/CHANGELOG.md
> chore: updated changelogs

- packages/amplify_flutter/lib/amplify.dart
- packages/amplify_flutter/test/amplify_test.dart
fix: swallows exception on hot restart
> fix: swallows exception on hot restart

- packages/amplify_analytics_pinpoint/android/build.gradle
- packages/amplify_api/android/build.gradle
- packages/amplify_auth_cognito/android/build.gradle
- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt
- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterConfirmSignInRequest.kt
- packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPluginTest.kt
- packages/amplify_auth_cognito/example/ios/unit_tests/amplify_auth_cognito_tests.swift
- packages/amplify_auth_cognito/ios/Classes/AuthCognitoBridge.swift
- packages/amplify_auth_cognito/ios/Classes/FlutterConfirmSignInRequest.swift
- packages/amplify_auth_cognito/lib/src/CognitoSignIn/CognitoConfirmSignInOptions.dart
- packages/amplify_auth_cognito/test/amplify_auth_cognito_confirmSignIn_test.dart
- packages/amplify_auth_cognito/test/amplify_auth_cognito_signin_test.dart
- packages/amplify_auth_plugin_interface/lib/src/SignIn/ConfirmSignInRequest.dart
- packages/amplify_core/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_flutter/android/build.gradle
- packages/amplify_storage_s3/android/build.gradle
#532 
Adds support for ConfirmSignInOptions
> fix: Confirm sign in options

- packages/amplify_analytics_pinpoint/example/pubspec.yaml
- packages/amplify_analytics_pinpoint/lib/amplify_analytics_pinpoint.dart
- packages/amplify_analytics_pinpoint/lib/method_channel_amplify.dart
- packages/amplify_analytics_pinpoint/pubspec.yaml
> Null safety analytics

- .gitignore
- packages/amplify_storage_s3/example/.gitignore
- packages/amplify_storage_s3/example/ios/Podfile
- packages/amplify_storage_s3/lib/amplify_storage_s3.dart
- packages/amplify_storage_s3/lib/method_channel_storage_s3.dart
- packages/amplify_storage_s3/lib/src/S3DownloadFile/S3DownloadFileOptions.dart
- packages/amplify_storage_s3/lib/src/S3GetUrl/S3GetUrlOptions.dart
- packages/amplify_storage_s3/lib/src/S3List/S3ListOptions.dart
- packages/amplify_storage_s3/lib/src/S3UploadFile/S3UploadFileOptions.dart
- packages/amplify_storage_s3/pubspec.yaml
> Null safety storage

- example/lib/Pages/LandingPage.dart
- example/lib/Views/ImageLineItem.dart
- example/lib/Views/ImagePreview.dart
- example/lib/Views/ImageUploader.dart
- example/pubspec.yaml
Example App fixes from Null Safety
> Example app null safety fixes

- packages/amplify_analytics_pinpoint/android/build.gradle
- packages/amplify_api/android/build.gradle
- packages/amplify_auth_cognito/android/build.gradle
- packages/amplify_core/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/DataStoreHubEventStreamHandler.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/DataStoreObserveEventStreamHandler.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterHubElement.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/model/FlutterModelSchema.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/model/FlutterSerializedModel.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/model/FlutterSubscriptionEvent.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStoreHubTest.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePluginTest.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/FlutterSerializedModelData.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/SchemaData.kt
- packages/amplify_datastore/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- packages/amplify_flutter/android/build.gradle
- packages/amplify_storage_s3/android/build.gradle
**Issue #, if available:**
Related to #615 and #602
**Description of changes:**
Upgrade amplify-android version to integrate a few bug fixes in Android.
----
> chore: upgrade amplify-android to 1.19.0

- packages/amplify_analytics_pinpoint/ios/amplify_analytics_pinpoint.podspec
- packages/amplify_api/ios/amplify_api.podspec
- packages/amplify_auth_cognito/ios/amplify_auth_cognito.podspec
- packages/amplify_datastore/ios/amplify_datastore.podspec
- packages/amplify_flutter/ios/amplify_flutter.podspec
- packages/amplify_storage_s3/ios/amplify_storage_s3.podspec
This will bring in a hosted ui-related improvement from amplify-ios.
> fix: amplify-ios version bump

- example/pubspec.yaml
- packages/amplify_analytics_pinpoint/pubspec.yaml
- packages/amplify_analytics_plugin_interface/pubspec.yaml
- packages/amplify_api/pubspec.yaml
- packages/amplify_api_plugin_interface/pubspec.yaml
- packages/amplify_auth_cognito/pubspec.yaml
- packages/amplify_auth_plugin_interface/pubspec.yaml
- packages/amplify_core/pubspec.yaml
- packages/amplify_datastore/pubspec.yaml
- packages/amplify_datastore_plugin_interface/pubspec.yaml
- packages/amplify_flutter/lib/amplify.dart
- packages/amplify_flutter/pubspec.yaml
- packages/amplify_storage_plugin_interface/pubspec.yaml
- packages/amplify_storage_s3/pubspec.yaml
> chore: release 0.2.0-nullsafety.1

- packages/amplify_flutter/lib/categories/amplify_datastore_category.dart
@*Issue #, if available:*
Quick PR to fix compile issues, need to do a force cast as model provider is nullable type now. 
> fix(amplify_datstore): mprovider compile issue

- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/utils/AuthCodeDeliveryDetailsSerialization.kt
- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/utils/UserAttributeSerialization.kt
- packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPluginTest.kt
- packages/amplify_auth_cognito/ios/Classes/Utils/UserAttributeSerialization.swift
*Issue #, if available:* N/A
- Update the serialization of the updateUserAttributeResponse to match expectations in Dart
> fix(auth): update user attribute serialization

- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterSignInResult.kt
- packages/amplify_auth_cognito/ios/Classes/FlutterSignInResult.swift
- packages/amplify_auth_plugin_interface/lib/src/SignIn/AuthNextSignInStep.dart
Uses nextStep helper for signInResult on Android
> fix(auth): uses nextStep helper for signInResult on Android

- example/pubspec.yaml
- packages/amplify_analytics_pinpoint/CHANGELOG.md
- packages/amplify_analytics_pinpoint/pubspec.yaml
- packages/amplify_analytics_plugin_interface/CHANGELOG.md
- packages/amplify_analytics_plugin_interface/pubspec.yaml
- packages/amplify_api/CHANGELOG.md
- packages/amplify_api/pubspec.yaml
- packages/amplify_api_plugin_interface/CHANGELOG.md
- packages/amplify_api_plugin_interface/pubspec.yaml
- packages/amplify_auth_cognito/CHANGELOG.md
- packages/amplify_auth_cognito/pubspec.yaml
- packages/amplify_auth_plugin_interface/CHANGELOG.md
- packages/amplify_auth_plugin_interface/pubspec.yaml
- packages/amplify_core/CHANGELOG.md
- packages/amplify_core/pubspec.yaml
- packages/amplify_datastore/CHANGELOG.md
- packages/amplify_datastore/pubspec.yaml
- packages/amplify_datastore_plugin_interface/CHANGELOG.md
- packages/amplify_datastore_plugin_interface/pubspec.yaml
- packages/amplify_flutter/CHANGELOG.md
- packages/amplify_flutter/lib/amplify.dart
- packages/amplify_flutter/pubspec.yaml
- packages/amplify_storage_plugin_interface/CHANGELOG.md
- packages/amplify_storage_plugin_interface/pubspec.yaml
- packages/amplify_storage_s3/CHANGELOG.md
- packages/amplify_storage_s3/pubspec.yaml
chore: release 0.2.0 with support for null safety
> chore: release 0.2.0

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
- packages/amplify_analytics_pinpoint/pubspec.yaml
- packages/amplify_analytics_plugin_interface/pubspec.yaml
- packages/amplify_api/pubspec.yaml
- packages/amplify_api_plugin_interface/pubspec.yaml
- packages/amplify_auth_cognito/pubspec.yaml
- packages/amplify_auth_plugin_interface/pubspec.yaml
- packages/amplify_core/pubspec.yaml
- packages/amplify_datastore/pubspec.yaml
- packages/amplify_datastore_plugin_interface/pubspec.yaml
- packages/amplify_flutter/pubspec.yaml
- packages/amplify_storage_plugin_interface/pubspec.yaml
- packages/amplify_storage_s3/pubspec.yaml
*Description of changes:* Changes the default branch name to "main" by changing references in pipeline files as well as documentation and pubspecs.
**Note:** should not be merged until git branch name and gh default branch updated.
> chore: change default branch name to 'main'

- packages/amplify_api/pubspec.yaml
- packages/amplify_api_plugin_interface/pubspec.yaml
- packages/amplify_core/pubspec.yaml
- packages/amplify_datastore/pubspec.yaml
- packages/amplify_flutter/pubspec.yaml
*Issue #, if available:* N/A
- Update package descriptions to follow dart conventions
> update descriptions to follow dart conventions

- packages/amplify_authenticator/.gitignore
- packages/amplify_authenticator/.metadata
- packages/amplify_authenticator/CHANGELOG.md
- packages/amplify_authenticator/LICENSE
- packages/amplify_authenticator/README.md
- packages/amplify_authenticator/lib/amplify_authenticator.dart
- packages/amplify_authenticator/pubspec.yaml
- packages/amplify_authenticator/test/amplify_authenticator_test.dart
no issues
First snippet for the amplify flutter authenticator 
> feat(amplify_auth_cognito): first snippet for the amplify authenticator

- packages/amplify_analytics_pinpoint/android/build.gradle
- packages/amplify_api/android/build.gradle
- packages/amplify_auth_cognito/android/build.gradle
- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterSignUpRequest.kt
- packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPluginTest.kt
- packages/amplify_auth_cognito/example/ios/unit_tests/amplify_auth_cognito_tests.swift
- packages/amplify_auth_cognito/ios/Classes/FlutterSignUpRequest.swift
- packages/amplify_auth_cognito/lib/src/CognitoSignUp/CognitoSignUpOptions.dart
- packages/amplify_core/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_flutter/android/build.gradle
- packages/amplify_storage_s3/android/build.gradle
Enables clientMetadata for signUp
> feat(amplify_auth_cognito): enables clientMetadata for signUp

- packages/amplify_authenticator/lib/src/text_customization/navigation_resolver.dart
Removes a dummy value that was accidentally included.
> fix(amplify_authenticator): removes test default value

- packages/amplify_api/example/integration_test/graph_ql_tests.dart
- packages/amplify_api/lib/method_channel_api.dart
- packages/amplify_api/lib/src/graphql/graphql_request_factory.dart
This PR contains fixes for issues I've come across in testing.
> fix(amplify_api): GraphQL Helper Clean Up

- packages/amplify_analytics_pinpoint/CHANGELOG.md
- packages/amplify_analytics_pinpoint/pubspec.yaml
- packages/amplify_analytics_plugin_interface/CHANGELOG.md
- packages/amplify_analytics_plugin_interface/pubspec.yaml
- packages/amplify_api/CHANGELOG.md
- packages/amplify_api/pubspec.yaml
- packages/amplify_api_plugin_interface/CHANGELOG.md
- packages/amplify_api_plugin_interface/pubspec.yaml
- packages/amplify_auth_cognito/CHANGELOG.md
- packages/amplify_auth_cognito/pubspec.yaml
- packages/amplify_auth_plugin_interface/CHANGELOG.md
- packages/amplify_auth_plugin_interface/pubspec.yaml
- packages/amplify_core/CHANGELOG.md
- packages/amplify_core/pubspec.yaml
- packages/amplify_datastore/CHANGELOG.md
- packages/amplify_datastore/pubspec.yaml
- packages/amplify_datastore_plugin_interface/CHANGELOG.md
- packages/amplify_datastore_plugin_interface/pubspec.yaml
- packages/amplify_flutter/CHANGELOG.md
- packages/amplify_flutter/lib/amplify.dart
- packages/amplify_flutter/pubspec.yaml
- packages/amplify_lints/CHANGELOG.md
- packages/amplify_lints/pubspec.yaml
- packages/amplify_storage_plugin_interface/pubspec.yaml
- packages/amplify_storage_s3/CHANGELOG.md
- packages/amplify_storage_s3/pubspec.yaml
> chore(release): 0.2.3

- example/android/build.gradle
- example/ios/Flutter/AppFrameworkInfo.plist
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- example/lib/Views/ImageUploader.dart
- example/pubspec.yaml
- melos.yaml
- Fixes example app Android build
- Adds example app build to CI pipeline
> fix(example): Update dependencies

- example/lib/Views/ImageUploader.dart
- melos.yaml
- Allow packages:fix command to fail
- Also fixes the example app
> fix: Melos bootstrap should not fail

- packages/amplify_authenticator/example/lib/main.dart
- packages/amplify_authenticator/lib/amplify_authenticator.dart
- packages/amplify_authenticator/lib/src/widgets/default_forms/default_signin.dart
- packages/amplify_authenticator/lib/src/widgets/default_forms/default_signup.dart
Fixes transposition of signin and signup form fields, and two other minor fixes.
> fix(amplify_authenticator) default form typos and other fixes

- packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt
Fixes getCurrentUser happy path
> fix(amplify_auth_cognito): fixes getCurrentUser happy path

- build-support/integ_test_ios.sh
- melos.yaml
- packages/amplify_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/RunnerTests.xcscheme
- Fixes for `flutter drive` command per [issue](https://github.com/flutter/flutter/issues/90908) and [docs](https://flutter.dev/docs/cookbook/testing/integration/introduction#5a-mobile)
- Separate out special case iOS runs, distinguished by use of a "RunnerTests" scheme
> chore: Melos integration tests

- packages/amplify_datastore/CHANGELOG.md
> chore(datastore): Update changelog with preview instructions

- packages/amplify_api/android/build.gradle
- packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/AmplifyApiPlugin.kt
- packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/FlutterGraphQLApi.kt
- packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/auth/FlutterAuthProvider.kt
- packages/amplify_api/android/src/test/kotlin/com/amazonaws/amplify/amplify_api/GraphQLApiUnitTests.kt
- packages/amplify_api/example/.gitignore
- packages/amplify_flutter/android/build.gradle
- packages/amplify_flutter/android/src/main/kotlin/com/amazonaws/amplify/Amplify.kt
- packages/amplify_flutter/android/src/test/kotlin/com/amazonaws/amplify/AmplifyTest.kt
- https://github.com/aws-amplify/amplify-flutter/issues/1022
- https://github.com/aws-amplify/amplify-flutter/issues/978
- Moves `Amplify.configure` and all GraphQL API calls to a background thread
> fix(api): OIDC fixes for Android

- packages/amplify_api/CHANGELOG.md
- packages/amplify_api/android/build.gradle
- packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/AmplifyApiPlugin.kt
- packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/FlutterGraphQLApi.kt
- packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/auth/FlutterAuthProvider.kt
- packages/amplify_api/android/src/test/kotlin/com/amazonaws/amplify/amplify_api/GraphQLApiUnitTests.kt
- packages/amplify_api/example/.gitignore
- packages/amplify_api_plugin_interface/CHANGELOG.md
- packages/amplify_core/CHANGELOG.md
- packages/amplify_flutter/CHANGELOG.md
- packages/amplify_flutter/android/build.gradle
- packages/amplify_flutter/android/src/main/kotlin/com/amazonaws/amplify/Amplify.kt
- packages/amplify_flutter/android/src/test/kotlin/com/amazonaws/amplify/AmplifyTest.kt
- Rebase changes from https://github.com/aws-amplify/amplify-flutter/pull/1028
> fix(api): Rebase OIDC fixes for RC

- packages/amplify_core/android/src/main/kotlin/com/amazonaws/amplify/amplify_core/exception/ExceptionUtil.kt
> fix(api): Post exceptions on the main thread

- packages/amplify_authenticator/lib/src/enums/signin_types.dart
- packages/amplify_authenticator/lib/src/keys.dart
- packages/amplify_authenticator/lib/src/state/auth_viewmodel.dart
- packages/amplify_authenticator/lib/src/widgets/form.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/sign_in_form_field.dart
Sends the username for forgot password flow, and removes unneeded fields.
> fix(amplify_authenticator): sends username for password recovery

- packages/amplify_authenticator/lib/src/widgets/form.dart
- packages/amplify_authenticator/lib/src/widgets/form_field.dart
- packages/amplify_flutter/lib/src/config/auth/auth_block_config.dart
- packages/amplify_flutter/lib/src/config/auth/auth_block_config.g.dart
- packages/amplify_flutter/lib/src/config/auth/aws_cognito_social_providers.dart
- packages/amplify_flutter/lib/src/config/auth/aws_cognito_username_attributes.dart
This PR introduces two revised config keys names, as implemented in the soon-to-be released version of the CLI: https://www.npmjs.com/package/@aws-amplify/cli/v/6.5.0-beta.1
awsCognitoUsernameAttributes -> usernameAttributes
awsCognitoSocialProviders -> socialProviders
> chore: updates config values for new cli output

- packages/amplify_authenticator/lib/src/enums/username_input.dart
- Add doc comments for `UsernameType`
> chore(authenticator): UsernameType doc comments

- packages/amplify_auth_cognito/lib/src/CognitoSignIn/CognitoConfirmSignInOptions.dart
- packages/amplify_auth_cognito/test/amplify_auth_cognito_confirmSignIn_test.dart
> fix: serialize confirm sign up options

- packages/amplify_storage_s3/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/AmplifyStorageOperations.kt
#1043
change 12-hours based date format to 24-hours .
https://developer.android.com/reference/kotlin/java/text/SimpleDateFormat#format
> fix(storage): Storage.list DateTime formatting (Android)

- packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart
- packages/amplify_authenticator/lib/src/services/amplify_auth_service.dart
> fix: do not show verify user if at least one attribute is verified

- packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/verify_user_form_field.dart
> fix: update verify user validation message and display code sent message

- packages/amplify_authenticator/example/.gitignore
- packages/amplify_authenticator/lib/src/theme/amplify_theme.dart
- packages/amplify_authenticator/lib/src/widgets/social/social_button.dart
- Increase border width and update to match font color
> chore(authenticator): Update social buttons look

- packages/amplify_authenticator/lib/src/mixins/authenticator_date_field.dart
- move date picker icon to right side
- handle onTap
> feat(authenticator): update date time field ui and handle onTap

- packages/amplify_authenticator/lib/amplify_authenticator.dart
- packages/amplify_authenticator/lib/src/mixins/authenticator_phone_field.dart
- packages/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart
- packages/amplify_authenticator/lib/src/utils/validators.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_in_form_field.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_up_form_field.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/phone_number_field.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/reset_password_form_field.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/sign_in_form_field.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/sign_up_form_field.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/verify_user_form_field.dart
- Use username field for confirm sign up
- No validation for optional fields
- Fix validation for phone number field
- Fix `obscureText`
- Fix some required fields showing as optional
> chore(authenticator): Feedback fixes

- packages/amplify_authenticator/example/lib/main.dart
- packages/amplify_authenticator/lib/src/theme/amplify_theme.dart
- packages/amplify_authenticator/lib/src/widgets/authenticator_banner.dart
- packages/amplify_authenticator/lib/src/widgets/social/social_button.dart
- update _isDark for material theme
> fix(authenticator): update theme _isDark for material theme

- packages/amplify_authenticator/lib/src/widgets/authenticator_banner.dart
- Fixes overflow for large strings in SnackBars
> fix(authenticator): Fix SnackBar overflow

- packages/amplify_authenticator/lib/src/l10n/generated/country_localizations_en.dart
- packages/amplify_authenticator/lib/src/l10n/generated/input_localizations.dart
- packages/amplify_authenticator/lib/src/l10n/generated/input_localizations_en.dart
- packages/amplify_authenticator/lib/src/l10n/generated/message_localizations_en.dart
- packages/amplify_authenticator/lib/src/l10n/generated/title_localizations_en.dart
- packages/amplify_authenticator/lib/src/l10n/input_resolver.dart
- packages/amplify_authenticator/lib/src/l10n/src/inputs/inputs_en.arb
- packages/amplify_authenticator/lib/src/mixins/authenticator_phone_field.dart
- packages/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart
- packages/amplify_authenticator/lib/src/utils/validators.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_in_form_field.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_up_form_field.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/phone_number_field.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/reset_password_form_field.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/sign_up_form_field.dart
* Adds localizations for validator messages
* Passes dialcode to phone validator
> chore(amplify_authenticator): adds localizations for validator messages

- packages/amplify_authenticator/lib/src/widgets/form.dart
- packages/amplify_flutter/lib/src/config/auth/auth_block_config.dart
- packages/amplify_flutter/lib/src/config/auth/auth_block_config.g.dart
- Adds verification mechanisms to sign up fields
> fix(authenticator): Add verification mechanisms to sign up fields

- packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart
> fix: do not show verify user for social sign in

- packages/amplify_authenticator/example/integration_test/config.dart
- packages/amplify_authenticator/example/integration_test/sign_up_with_username_test.dart
- packages/amplify_authenticator/example/integration_test/utils/mock_data.dart
- packages/amplify_authenticator/lib/src/l10n/button_resolver.dart
- packages/amplify_authenticator/lib/src/state/auth_viewmodel.dart
- packages/amplify_authenticator/lib/src/widgets/button.dart
- Add first integration test to follow Amplify UI feature: https://github.com/aws-amplify/amplify-ui/blob/main/packages/e2e/features/ui/components/authenticator/sign-up-with-username.feature
> chore(authenticator): Add sign-up-with-username test

- packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift
Change to send proper map from iOS to Dart 
> fix (amplify_datastore): fix error map from ios

- packages/amplify_authenticator/example/integration_test/pages/confirm_verify_user_page.dart
- packages/amplify_authenticator/example/integration_test/pages/verify_user_page.dart
- packages/amplify_authenticator/example/integration_test/verify_user_test.dart
- packages/amplify_authenticator/lib/src/keys.dart
- packages/amplify_authenticator/lib/src/widgets/button.dart
- packages/amplify_authenticator/lib/src/widgets/form_fields/verify_user_form_field.dart
> test: add verify user tests for authenticator

- packages/amplify_authenticator/example/integration_test/confirm_sign_up_test.dart
- packages/amplify_authenticator/example/integration_test/pages/authenticator_page.dart
- packages/amplify_authenticator/example/integration_test/pages/sign_in_page.dart
- packages/amplify_authenticator/example/integration_test/pages/test_utils.dart
- packages/amplify_authenticator/example/integration_test/reset_password_test.dart
- packages/amplify_authenticator/example/integration_test/sign_in_mfa_test.dart
- packages/amplify_authenticator/example/integration_test/sign_in_with_email_test.dart
- packages/amplify_authenticator/example/integration_test/sign_in_with_phone_test.dart
- packages/amplify_authenticator/example/integration_test/sign_in_with_username_test.dart
- packages/amplify_authenticator/example/integration_test/sign_up_with_email_with_lambda_trigger.dart
- packages/amplify_authenticator/example/integration_test/utils/data_utils.dart
- packages/amplify_authenticator/example/integration_test/utils/mock_data.dart
- packages/amplify_authenticator/example/integration_test/utils/types/confirm_sign_up_response.dart
- packages/amplify_authenticator/example/integration_test/verify_user_test.dart
- packages/amplify_authenticator/example/pubspec.yaml
- Fix custom email lambda test
> chore(authenticator): Fix custom email test

- packages/amplify_authenticator/README.md
- packages/amplify_authenticator/example/integration_test/pages/test_utils.dart
- packages/amplify_authenticator/example/integration_test/reset_password_test.dart
- packages/amplify_authenticator/example/integration_test/sign_in_with_email_test.dart
- packages/amplify_authenticator/example/integration_test/sign_in_with_phone_test.dart
- packages/amplify_authenticator/example/integration_test/sign_in_with_username_test.dart
- packages/amplify_authenticator/example/integration_test/verify_user_test.dart
- packages/amplify_authenticator/example/lib/main.dart
- packages/amplify_authenticator/lib/amplify_authenticator.dart
- packages/amplify_authenticator/lib/src/l10n/country_resolver.dart
- packages/amplify_authenticator/lib/src/l10n/generated/button_localizations.dart
- packages/amplify_authenticator/lib/src/l10n/generated/button_localizations_en.dart
- packages/amplify_authenticator/lib/src/l10n/generated/country_localizations_en.dart
- packages/amplify_authenticator/lib/src/l10n/generated/input_localizations.dart
- packages/amplify_authenticator/lib/src/l10n/generated/input_localizations_en.dart
- packages/amplify_authenticator/lib/src/l10n/generated/message_localizations_en.dart
- packages/amplify_authenticator/lib/src/l10n/generated/title_localizations_en.dart
- packages/amplify_authenticator/lib/src/screens/authenticator_screen.dart
- packages/amplify_authenticator/lib/src/state/inherited_config.dart
- packages/amplify_authenticator/lib/src/utils/validators.dart
- packages/amplify_authenticator/lib/src/widgets/button.dart
- packages/amplify_authenticator/lib/src/widgets/component.dart
- packages/amplify_authenticator/lib/src/widgets/form.dart
- packages/amplify_authenticator/lib/src/widgets/form_field.dart
- packages/amplify_authenticator/lib/src/widgets/social/social_button.dart
- packages/amplify_authenticator/tool/generate_l10n.sh
- Clean up doc comments, exports, and example app
> chore(authenticator): Docs clean up

- packages/amplify_authenticator/lib/src/l10n/country_resolver.dart
- packages/amplify_authenticator/lib/src/l10n/input_resolver.dart
- packages/amplify_authenticator/tool/generate_country_localization.dart
* documentation for input and country resolver classes
* includes codegen change
> chore(amplify_authenticator): documentation for input and country resolver classes

- packages/amplify_authenticator/CHANGELOG.md
- packages/amplify_authenticator/README.md
- packages/amplify_authenticator/pubspec.yaml
- packages/amplify_flutter/pubspec.yaml
- Update `amplify_flutter` dependencies
- Update `amplify_authenticator` README
> chore: RC.3 release updates

- packages/amplify_authenticator/lib/amplify_authenticator.dart
- packages/amplify_authenticator/lib/src/widgets/authenticator_banner.dart
- consistently use brightness from context
> fix: consistently use brightness from context

- packages/amplify_datastore/CHANGELOG.md
Update the cli version should be used for 0.3.0-rc releases.
> fix(datastore): update changelog instruction for 0.3.0-rc release

- packages/amplify_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/amplify_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- Sets the target iOS SDK to iOS 13
> chore: Fix target iOS SDK in integration tests

- packages/amplify_authenticator/lib/src/l10n/auth_strings_resolver.dart
Exports message resolver for dart doc generation.
> chore(amplify_authenticator): export message resolver

- packages/amplify_flutter/lib/src/config/amplify_config.dart
- packages/amplify_flutter/lib/src/config/analytics/analytics_config.dart
- packages/amplify_flutter/lib/src/config/analytics/pinpoint_config.dart
- packages/amplify_flutter/lib/src/config/api/api_config.dart
- packages/amplify_flutter/lib/src/config/api/appsync/api_config.dart
- packages/amplify_flutter/lib/src/config/api/aws_api_config.dart
- packages/amplify_flutter/lib/src/config/auth/auth_config.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/appsync.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/auth.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/credentials_provider.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/oauth.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/oauth.g.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/password_protection_settings.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/pinpoint_analytics.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/pinpoint_targeting.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/s3_transfer_utility.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/user_pool.dart
- packages/amplify_flutter/lib/src/config/auth/cognito_config.dart
- packages/amplify_flutter/lib/src/config/config_map.dart
- packages/amplify_flutter/lib/src/config/storage/s3_config.dart
- packages/amplify_flutter/lib/src/config/storage/storage_config.dart
- packages/amplify_flutter/test/config/auth_config_test.dart
- packages/amplify_flutter/test/config/cli_config_test.dart
- Adds `copyWith` helpers to config classes
> chore(config): Add copyWith helpers

- packages/amplify_authenticator/CHANGELOG.md
- packages/amplify_authenticator/README.md
- packages/amplify_authenticator/example/lib/main.dart
- packages/amplify_authenticator/lib/amplify_authenticator.dart
- packages/amplify_authenticator/pubspec.yaml
Fixes https://github.com/aws-amplify/amplify-flutter/issues/1238
- Re-organizes Authenticator components to allow `Navigator` to work correctly.
> fix(authenticator): Improved navigation support

- packages/amplify_authenticator/example/android/build.gradle
- packages/amplify_storage_s3/example/pubspec.yaml
Remove stuff that may invoke jcenter in Gradle world.
> chore: wipe out jcenter

- packages/amplify_authenticator/example/integration_test/sign_out_test.dart
> fix(amplify_authenticator): bad import in tests

- .gitignore
- packages/amplify_authenticator/.pubignore
- Update gitignore as it was causing `pub publish` to fail. These env files will be included always, just as stubs instead of as real configurations.
> chore(authenticator): Update gitignore

- packages/amplify_authenticator/lib/amplify_authenticator.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/1274
> fix(amplify_authenticator): do not include authenticated app unless user is authenticated

- packages/amplify_datastore/example/tool/schema.graphql
> chore(datastore): update integration tests schema

- packages/amplify_authenticator/example/integration_test/custom_ui_test.dart
- packages/amplify_authenticator/example/integration_test/unprotected_routes_test.dart
- packages/amplify_test/pubspec.yaml
- Fix a bad import in the authenticator integ tests
> fix(amplify_authenticator): update bad import in test

- packages/amplify_authenticator/CHANGELOG.md
- packages/amplify_authenticator/example/pubspec.yaml
- packages/amplify_authenticator/pubspec.yaml
- version bum for authenticator rc.4
> chore(amplify_authenticator): version bump rc.4

- packages/amplify_flutter/lib/src/config/auth/cognito/password_protection_settings.dart
- packages/amplify_flutter/lib/src/config/auth/cognito/password_protection_settings.g.dart
- packages/amplify_flutter/test/config/e2e_config_test.dart
- packages/amplify_flutter/test/config/testdata/README.md
- packages/amplify_flutter/test/config/testdata/cli_generated.dart
- packages/amplify_flutter/test/config/testdata/e2e/latest/.gitignore
- packages/amplify_flutter/test/config/testdata/e2e/latest/amplifyconfiguration.dart
- packages/amplify_flutter/test/config/testdata/generate/generate.js
- packages/amplify_flutter/test/config/testdata/generate/package.json
- packages/amplify_flutter/test/config/testdata/generate/yarn.lock
- https://github.com/aws-amplify/amplify-cli/issues/9655
- Fixes password settings parsing in config
> fix(flutter): Password settings parsing

- packages/amplify_analytics_pinpoint/android/build.gradle
- packages/amplify_api/android/build.gradle
- packages/amplify_auth_cognito/android/build.gradle
- packages/amplify_core/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_flutter/android/build.gradle
- packages/amplify_storage_s3/android/build.gradle
- bump Kotlin version to 1.6.10
> chore: bump Kotlin version to 1.6.10

- packages/amplify_datastore/example/tool/schema.graphql
- remove comments from the schema file. The comments cause `melos run provision_integration_test_resources` to fail.
> chore: remove comments from schema file

- packages/amplify_datastore/example/integration_test/observe_test.dart
- packages/amplify_datastore/lib/amplify_datastore.dart
- packages/amplify_datastore/lib/method_channel_datastore.dart
- packages/amplify_datastore_plugin_interface/lib/amplify_datastore_plugin_interface.dart
- packages/amplify_flutter/lib/src/categories/amplify_datastore_category.dart
Add support for QueryPredicate for Datastore.Observe
> feat(datastore): Add QueryPredicate to Observe

- packages/amplify_authenticator/pubspec.yaml
> chore(amplify_authenticator): update amplify_flutter dep to >=0.3.0 <0.5.0

- packages/amplify_flutter/example/ios/unit_tests/AtomicResultTests.swift
- Timeouts of AtomicResultTest in CI pipeline
- Fixes timeouts of AtomicResultTest by reducing the number of concurrent iterations to a more reasonable number
> chore(flutter): Fix AtomicResultTest

- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePluginTest.kt
- packages/amplify_datastore/example/integration_test/delete_test.dart
- packages/amplify_datastore/example/integration_test/save_test.dart
- packages/amplify_datastore/example/ios/unit_tests/DataStorePluginUnitTests.swift
- packages/amplify_datastore/ios/Classes/DataStoreBridge.swift
- packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift
- packages/amplify_datastore/lib/amplify_datastore.dart
- packages/amplify_datastore/lib/method_channel_datastore.dart
- packages/amplify_datastore_plugin_interface/lib/amplify_datastore_plugin_interface.dart
- packages/amplify_flutter/lib/src/categories/amplify_datastore_category.dart
Add QueryPredicate support for Save/Delete
> feat(datastore): Add QueryPredicate to Save/Delete

- .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
- Noticed that bug report was missing CLI version
- Deps command output is too long
- Add CLI version
- Make deps output shorter
> chore: QOS additions to bug report template

- packages/amplify_authenticator/example/lib/customization/authenticator_with_custom_layout.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/1397
- Add SingleChildScrollView, remove Spacer
> fix:(amplify_authenticator): fix overflow in custom layout example

- .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
- Splits the issue template's API category into REST & GraphQL
> chore: Update issue template categories

- .circleci/config.yml
- Disable pana in CI
These checks were added to catch issues with pub score before publishing, but are currently causing many false positives.
> chore: disable pana in CI

- .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
Add info collector for Android API level.
> chore: add android api level info to the issue template

- packages/api/amplify_api_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/auth/FlutterAuthProvider.kt
- Fixes build failure in Flutter master
https://github.com/flutter/engine/pull/31530
> fix(auth): Fix FlutterAuthProvider.kt

- packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_in_form_field.dart
#1537 
Fixes validation on confirm password screen
> fix(authenticator): Fix confirm password validator

- packages/aws_signature_v4/README.md
- packages/aws_signature_v4/lib/src/configuration/service_configuration.dart
Change header name to `aws-sigv4-dart` reserving `aws-sdk-dart` for the SDK.
> chore(aws_signature_v4): Update user agent header name

- .circleci/config.yml
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt
> chore: Flutter 3 fixes

- example/pubspec.yaml
- packages/amplify/amplify_flutter/pubspec.yaml
- packages/amplify/amplify_flutter_android/pubspec.yaml
- packages/amplify/amplify_flutter_ios/pubspec.yaml
- packages/amplify_authenticator/pubspec.yaml
- packages/amplify_core/lib/src/category/amplify_auth_category.dart
- packages/amplify_core/pubspec.yaml
- packages/amplify_datastore/pubspec.yaml
- packages/amplify_datastore_plugin_interface/pubspec.yaml
- packages/amplify_test/pubspec.yaml
- packages/analytics/amplify_analytics_pinpoint/pubspec.yaml
- packages/analytics/amplify_analytics_pinpoint_android/pubspec.yaml
- packages/analytics/amplify_analytics_pinpoint_ios/pubspec.yaml
- packages/api/amplify_api/pubspec.yaml
- packages/api/amplify_api_android/example/pubspec.yaml
- packages/api/amplify_api_android/pubspec.yaml
- packages/api/amplify_api_ios/example/pubspec.yaml
- packages/api/amplify_api_ios/pubspec.yaml
- packages/auth/amplify_auth_cognito/example/integration_test/custom_auth_passwordless_test.dart
- packages/auth/amplify_auth_cognito/pubspec.yaml
- packages/auth/amplify_auth_cognito_android/pubspec.yaml
- packages/auth/amplify_auth_cognito_ios/pubspec.yaml
- packages/aws_common/pubspec.yaml
- packages/aws_signature_v4/pubspec.yaml
- packages/storage/amplify_storage_s3/pubspec.yaml
- packages/storage/amplify_storage_s3_android/pubspec.yaml
- packages/storage/amplify_storage_s3_ios/pubspec.yaml
Post-migration clean up of missed items, and general clean up of pubspecs
> chore: Post-migration cleanup

- packages/amplify_authenticator/pubspec.yaml
- https://github.com/aws-amplify/amplify-flutter/issues/1628
Bumps version constraints. <0.5.0 no longer works due to some linting fixes which changed types.
> fix(authenticator): Update version constraints

- packages/aws_common/lib/src/config/aws_config_value.dart
Removes dart defines from `AWSConfigValue` as a temporary solution to https://github.com/dart-lang/sdk/issues/49245
> fix(core): Remove dart define (temporary)

- packages/amplify_authenticator/lib/src/state/authenticator_state.dart
- packages/amplify_authenticator/lib/src/utils/validators.dart
- packages/aws_common/lib/src/http/aws_http_request.dart
- packages/aws_common/pubspec.yaml
- packages/aws_signature_v4/lib/src/configuration/service_configuration.dart
- packages/aws_signature_v4/lib/src/configuration/services/s3.dart
- packages/aws_signature_v4/lib/src/request/canonical_request/canonical_request.dart
- packages/aws_signature_v4/test/canonical_request_test.dart
- packages/aws_signature_v4/test/s3/s3_service_configuration_test.dart
Cherry picks from main:
- [fix(amplify_authenticator): trims strings for password confirmation d](https://github.com/aws-amplify/amplify-flutter/commit/fb84fe74b67b56c976b5b58f771dd2b290f94764)
- [fix(sigv4): Include Host header in signing](https://github.com/aws-amplify/amplify-flutter/commit/99d428193455c7736f156635a2a97ac667e5d657)
- [fix(sigv4): Do not chunk GET/HEAD on Web](https://github.com/aws-amplify/amplify-flutter/commit/c5e7a76ed59f97b9b8fc68a78332db94c7bc4204)
- [fix(aws_common): Close HTTP client when stream is done](https://github.com/aws-amplify/amplify-flutter/commit/92e4ea3258aa4712e74d31377842e1e6c2ac532a)
- [fix(aws_signature_v4): Presign Min/Max Expirations (](https://github.com/aws-amplify/amplify-flutter/commit/545c9bc5127d9f48658de1d9b9f6b49bfcaa2db1)https://github. …
> chore: Cherry picks

- packages/amplify_datastore/example/integration_test/utils/setup_utils.dart
- packages/amplify_datastore/example/integration_test/utils/wait_for_expected_event_from_hub.dart
Fixes a missed issue with hub events migration which prevents integ tests from compiling.
> chore(test): Fix DS integ tests

- packages/amplify_authenticator/example/integration_test/main_test.dart
- packages/amplify_authenticator/example/test_driver/integration_test.dart
Adds driver to authenticator example, for web integration testing.
> chore(authenticator): adds driver to authenticator integ tests

- packages/auth/amplify_auth_cognito/example/ios/Runner/Info.plist
- packages/auth/amplify_auth_cognito_ios/ios/Classes/HostedUIFlow.swift
Updates Info.plist and ensures all code paths resume the ASWebAuth continuation
> chore(auth): Hosted UI patches

- packages/aws_signature_v4/lib/src/configuration/service_configuration.dart
- packages/aws_signature_v4/test/headers_test.dart
Fixes the user agent sent with signed requests
> fix(sigv4): Correct user agent

- packages/aws_signature_v4/CHANGELOG.md
- packages/aws_signature_v4/lib/src/configuration/service_configuration.dart
- packages/aws_signature_v4/lib/src/version.dart
- packages/aws_signature_v4/pubspec.yaml
- packages/aws_signature_v4/test/headers_test.dart
Patch release for sigv4 pacakge
- ede360097c6ccd53aa6d377a2d59a42fdb18515d
> chore(version): Bump `aws_signature_v4`

- packages/amplify_authenticator/lib/src/widgets/form.dart
Collect phone number during sign up if registered as an MFA type
> fix(authenticator): Collect MFA types

- packages/amplify_core/lib/src/config/auth/cognito/auth.g.dart
- packages/amplify_core/lib/src/config/auth/cognito/authentication_flow_type.dart
- packages/auth/amplify_auth_cognito_dart/example/bin/example.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_bridge.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
Adds support for the `USER_PASSWORD_AUTH` flow
> feat(auth): Username/password flow

- packages/amplify_core/lib/src/types/auth/attribute/cognito_user_attribute_key.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
Small fixes around attribute handing
> fix(auth): Attribute handling

- packages/amplify_authenticator/example/integration_test/config.dart
- packages/amplify_authenticator/example/integration_test/confirm_sign_up_email_or_phone_test.dart
- packages/amplify_authenticator/example/integration_test/envs/auth_with_email_or_phone.dart
- packages/amplify_authenticator/example/integration_test/pages/sign_up_page.dart
- packages/amplify_authenticator/lib/amplify_authenticator.dart
- packages/amplify_authenticator/lib/src/keys.dart
- packages/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart
- packages/amplify_authenticator/lib/src/models/username_input.dart
- packages/amplify_authenticator/lib/src/state/authenticator_state.dart
- packages/amplify_authenticator/lib/src/widgets/form.dart
- packages/amplify_authenticator/lib/src/widgets/form_field.dart
- packages/amplify_test/lib/src/integration_test_utils/auth_cognito/integration_test_auth_utils.dart
- Cherry pick 666349a1ad05297b40062d45844c56a5438b4f4e
> chore(amplify_authenticator): cherry pick email or phone config fix

- packages/amplify_core/lib/amplify_core.dart
- packages/amplify_core/lib/src/types/exception/url_launcher_exception.dart
- packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_flutter.dart
- packages/auth/amplify_auth_cognito_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt
- packages/auth/amplify_auth_cognito_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/HostedUiException.kt
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_io.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/model/hosted_ui/oauth_parameters.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/event/hosted_ui_event.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart
Improves Hosted UI exception messages on Android, e.g. when no browser is available, and when the exception originated from a Lambda.
> chore(auth): Better Hosted UI exceptions

- example/android/build.gradle
- packages/amplify/amplify_flutter/example/android/app/build.gradle
- packages/amplify/amplify_flutter/example/android/build.gradle
- packages/amplify/amplify_flutter_android/android/build.gradle
- packages/amplify_authenticator/example/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_datastore/example/android/app/build.gradle
- packages/amplify_datastore/example/android/build.gradle
- packages/analytics/amplify_analytics_pinpoint/example/android/build.gradle
- packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle
- packages/analytics/amplify_analytics_pinpoint_android/example/android/build.gradle
- packages/api/amplify_api/example/android/app/build.gradle
- packages/api/amplify_api/example/android/build.gradle
- packages/api/amplify_api_android/android/build.gradle
- packages/api/amplify_api_android/example/android/build.gradle
- packages/auth/amplify_auth_cognito/example/android/app/build.gradle
- packages/auth/amplify_auth_cognito/example/android/build.gradle
- packages/auth/amplify_auth_cognito_android/android/build.gradle
- packages/secure_storage/amplify_secure_storage/android/build.gradle
- packages/secure_storage/amplify_secure_storage/example/android/build.gradle
- packages/storage/amplify_storage_s3/example/android/app/build.gradle
- packages/storage/amplify_storage_s3/example/android/build.gradle
- packages/storage/amplify_storage_s3_android/android/build.gradle
- packages/worker_bee/e2e_flutter_test/android/build.gradle
Bumps Android dependencies in all plugins
> chore: Bump Android dependencies

- .circleci/config.yml
> chore: update xcode version in CI

- .github/workflows/lint.yml
- .github/workflows/test.yml
- tool/ci.sh
Updates mono_repo which contains security improvements like dependency pinning and explicit permissions
> chore(repo): Update `mono_repo`

- packages/amplify/amplify_flutter/lib/amplify_flutter.dart
- packages/amplify/amplify_flutter/pubspec.yaml
- packages/auth/amplify_auth_cognito/lib/src/auth_plugin_impl.dart
Fixes some miscellaneous analysis issues
> chore: Fix some analysis issues

- packages/storage/amplify_storage_s3/pubspec.yaml
- Add `meta` as a dependency to storage
> chore(storage): add meta to storage deps

- packages/amplify_authenticator/lib/amplify_authenticator.dart
I came across this typo in the error messages. 
> chore(authenticator): Fix typo in error message

- packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/model/signin/cognito_sign_in_options.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/event/sign_in_event.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
- packages/auth/amplify_auth_cognito_dart/test/state/sign_in_state_machine_test.dart
> chore(auth): Rename `authFlow` to `authFlowType`

- packages/auth/amplify_auth_cognito/example/integration_test/custom_auth_passwordless_test.dart
Fixes configure call in custom auth test and removes redundant test.
> fix(authenticator): fixes configure call in custom auth test

- .github/workflows/amplify_integration_tests.yaml
- packages/auth/amplify_auth_cognito/example/tool/pull_test_backend.sh
- packages/storage/amplify_storage_s3/example/tool/pull_test_backend.sh
This PR enables integration tests in CI for storage category.
> chore(storage): enable integ tests in CI

- example/pubspec.yaml
- packages/analytics/amplify_analytics_pinpoint/pubspec.yaml
Fixes versions in analytics_pinpoint and example.
> chore: fixes versions in analytics_pinpoint and example

- packages/amplify/amplify_flutter/README.md
- packages/amplify/amplify_flutter_android/README.md
- packages/amplify/amplify_flutter_ios/README.md
- packages/amplify_authenticator/README.md
- packages/amplify_core/README.md
- packages/amplify_datastore/README.md
- packages/amplify_datastore_plugin_interface/README.md
- packages/analytics/amplify_analytics_pinpoint/README.md
- packages/analytics/amplify_analytics_pinpoint_android/README.md
- packages/analytics/amplify_analytics_pinpoint_ios/README.md
- packages/api/amplify_api/README.md
- packages/api/amplify_api/example/README.md
- packages/api/amplify_api_android/README.md
- packages/api/amplify_api_ios/README.md
- packages/auth/amplify_auth_cognito/README.md
- packages/auth/amplify_auth_cognito_android/README.md
- packages/auth/amplify_auth_cognito_dart/README.md
- packages/auth/amplify_auth_cognito_ios/README.md
- packages/secure_storage/amplify_secure_storage/README.md
- packages/secure_storage/amplify_secure_storage_dart/README.md
- packages/storage/amplify_storage_s3/README.md
- packages/storage/amplify_storage_s3_android/README.md
- packages/storage/amplify_storage_s3_ios/README.md
Adds developer preview language to READMEs.
> chore: adds developer preview language to READMEs

- .gitmodules
- example/pubspec.yaml
- packages/secure_storage/amplify_secure_storage_dart/.pubignore
- packages/secure_storage/amplify_secure_storage_dart/Makefile
- packages/secure_storage/amplify_secure_storage_dart/ffigen.cupertino.coreFoundation.config.yaml
- packages/secure_storage/amplify_secure_storage_dart/ffigen.cupertino.security.config.yaml
- packages/secure_storage/amplify_secure_storage_dart/ffigen.glib.config.yaml
- packages/secure_storage/amplify_secure_storage_dart/ffigen.libsecret.config.yaml
- packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/glib/glib.bindings.g.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/libsecret/libsecret.bindings.g.dart
- packages/secure_storage/amplify_secure_storage_dart/pubspec.yaml
- packages/storage/amplify_storage_s3/example/pubspec.yaml
- Update ffi & ffigen to latest major versions
- Add glib and libsecret as submodules
- Add make commands to generate bindings
- Regenerate bindings
> chore(secure_storage): Upgrade ffi, ffigen

- packages/amplify_lints/CHANGELOG.md
- packages/amplify_lints/README.md
- packages/amplify_lints/lib/library.yaml
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/device/confirm_device_worker.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_device_password_verifier_worker.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_init_worker.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_password_verifier_worker.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/jwt/src/alg.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/jwt/src/claims.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/jwt/src/cognito.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/jwt/src/header.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/jwt/src/key.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/jwt/src/key_ops.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/jwt/src/keyset.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/jwt/src/token.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_exception.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/cognito_state_machine.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart
- packages/aws_common/lib/src/config/aws_config_value.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/cupertino/cupertino.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/glib/glib.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/libsecret/libsecret.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/platforms/amplify_secure_storage_linux.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/worker/secure_storage_request.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/worker/secure_storage_worker.dart
- packages/worker_bee/worker_bee/lib/src/js/preamble.dart
- packages/worker_bee/worker_bee/lib/worker_bee.dart
https://dart.dev/tools/linter-rules#always_use_package_imports
> chore: Enable `always_use_package_imports` lint

- packages/smithy/smithy_test/lib/src/http/http_request_test.dart
Fixes import linting issue in `smithy_test`.
> chore(smithy): Fix relative import in smithy_test

- packages/amplify_lints/CHANGELOG.md
- packages/amplify_lints/pubspec.yaml
- packages/auth/amplify_auth_cognito_dart/CHANGELOG.md
- packages/auth/amplify_auth_cognito_dart/pubspec.yaml
- packages/aws_common/CHANGELOG.md
- packages/aws_common/pubspec.yaml
- packages/aws_signature_v4/CHANGELOG.md
- packages/aws_signature_v4/lib/src/version.dart
- packages/aws_signature_v4/pubspec.yaml
- packages/smithy/smithy_aws/CHANGELOG.md
- packages/smithy/smithy_aws/lib/src/endpoint/credential_scope.dart
- packages/smithy/smithy_aws/pubspec.yaml
Fixes some issues publishing `next` packages which impact `pana` scores.
> chore: Fix package analysis issues

- packages/amplify_authenticator/CHANGELOG.md
- packages/amplify_authenticator/pubspec.yaml
- packages/auth/amplify_auth_cognito/CHANGELOG.md
- packages/auth/amplify_auth_cognito/pubspec.yaml
Fixes issue where pana thought this package only supported iOS/Android
> chore(auth): Fix platform support analysis

- packages/auth/amplify_auth_cognito/CHANGELOG.md
- packages/auth/amplify_auth_cognito/pubspec.yaml
- packages/auth/amplify_auth_cognito_android/CHANGELOG.md
- packages/auth/amplify_auth_cognito_android/pubspec.yaml
- packages/auth/amplify_auth_cognito_dart/CHANGELOG.md
- packages/auth/amplify_auth_cognito_dart/pubspec.yaml
- packages/auth/amplify_auth_cognito_ios/CHANGELOG.md
- packages/auth/amplify_auth_cognito_ios/pubspec.yaml
- fix(auth): Multi-auth DataStore bindings ([#2012](https://github.com/aws-amplify/amplify-flutter/pull/2012))
- fix(auth): Remember device metadata ([#2010](https://github.com/aws-amplify/amplify-flutter/pull/2010))
- fix(auth): Hosted UI task continuation ([#2017](https://github.com/aws-amplify/amplify-flutter/pull/2017))
- fix(auth): Hosted UI server contention ([#2002](https://github.com/aws-amplify/amplify-flutter/pull/2002))
> chore(version): 1.0.0.next.0+3

- packages/auth/amplify_auth_cognito/CHANGELOG.md
- packages/auth/amplify_auth_cognito/pubspec.yaml
- packages/auth/amplify_auth_cognito_dart/CHANGELOG.md
- packages/auth/amplify_auth_cognito_dart/pubspec.yaml
- packages/aws_common/CHANGELOG.md
- packages/aws_common/pubspec.yaml
Fixes #2024 by publishing `zAssertsEnabled` flag in `aws_common`
> chore(version): 1.0.0-next.0+4

- packages/amplify/amplify_flutter_android/android/build.gradle
- packages/amplify_core/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_datastore/example/lib/models/CpkPostTags.dart
- packages/amplify_datastore/example/lib/models/PostTags.dart
- packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle
- packages/api/amplify_api_android/android/build.gradle
- packages/auth/amplify_auth_cognito_android/android/build.gradle
- packages/storage/amplify_storage_s3_android/android/build.gradle
* update generated many-to-many models using the latest codegen
* bump amplify-android to 1.37.2 (new version should be available on 8/15/2022)
> chore: custom primary key dependency update

- packages/worker_bee/worker_bee_builder/lib/src/type_visitor.dart
- packages/worker_bee/worker_bee_builder/lib/src/worker_generator.dart
Fixes errors encountered due to recent changes in the `analyzer` package.
> chore(worker_bee): Fix analyzer errors

- README.md
- packages/amplify/amplify_flutter/README.md
- packages/amplify_core/README.md
- packages/amplify_datastore/README.md
- packages/analytics/amplify_analytics_pinpoint/README.md
- packages/analytics/amplify_analytics_pinpoint/lib/amplify_analytics_pinpoint.dart
- packages/analytics/amplify_analytics_pinpoint/pubspec.yaml
- packages/api/amplify_api/README.md
- packages/auth/amplify_auth_cognito/README.md
- packages/storage/amplify_storage_s3/README.md
Clarifies category/platform support on developer preview.
>  fix(analytics): clarifies lack of android support

- aft.yaml
- packages/aft/pubspec.yaml
- packages/aft/pubspec_overrides.yaml
- packages/auth/amplify_auth_cognito_dart/lib/src/model/hosted_ui/oauth_parameters.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_user_pool_tokens.dart
- packages/auth/amplify_auth_cognito_dart/pubspec.yaml
- packages/auth/amplify_auth_cognito_test/pubspec.yaml
- packages/secure_storage/amplify_secure_storage_dart/lib/src/types/keychain_attribute_accessible.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/types/web_secure_storage_options.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/worker/secure_storage_action.dart
- packages/secure_storage/amplify_secure_storage_dart/pubspec.yaml
- packages/smithy/goldens/lib/awsJson1_0/pubspec.yaml
- packages/smithy/goldens/lib/awsJson1_1/pubspec.yaml
- packages/smithy/goldens/lib/restJson1/pubspec.yaml
- packages/smithy/goldens/lib/restXml/pubspec.yaml
- packages/smithy/goldens/lib/restXmlWithNamespace/pubspec.yaml
- packages/smithy/smithy/pubspec.yaml
- packages/smithy/smithy_aws/pubspec.yaml
- packages/smithy/smithy_codegen/lib/src/util/pubspec.dart
- packages/smithy/smithy_codegen/pubspec.yaml
- packages/smithy/smithy_test/pubspec.yaml
- packages/worker_bee/e2e/pubspec.yaml
- packages/worker_bee/e2e_test/pubspec.yaml
- packages/worker_bee/worker_bee/pubspec.yaml
- packages/worker_bee/worker_bee_builder/pubspec.yaml
Updates dependencies to latest versions
> chore: Update dependencies

- packages/amplify_core/lib/src/hub/amplify_hub_impl.dart
Removes unnecessary code from the Hub impl which was a remnant from an older implementation
> chore(core): Clean up hub impl

- aft.yaml
- packages/aft/lib/src/models.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/device/confirm_device_worker.worker.js.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_device_password_verifier_worker.worker.js.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_init_worker.worker.js.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_password_verifier_worker.worker.js.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/workers/workers.debug.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/workers/workers.release.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/worker/secure_storage_worker.worker.js.dart
- packages/smithy/smithy_codegen/lib/src/generator/operation_test_generator.dart
- packages/smithy/smithy_codegen/lib/src/generator/serialization/structure_rest_xml_serializer_generator.dart
- packages/smithy/smithy_codegen/lib/src/generator/serialization/structure_serializer_generator.dart
- packages/smithy/smithy_codegen/lib/src/generator/serialization/union_serializer_generator.dart
- packages/smithy/smithy_codegen/lib/src/generator/service_server_generator.dart
- packages/smithy/smithy_codegen/lib/src/generator/structure_generator.dart
- packages/smithy/smithy_codegen/lib/src/generator/union_generator.dart
- packages/smithy/smithy_codegen/lib/src/generator/waiter_generator.dart
- packages/smithy/smithy_codegen/pubspec.yaml
- packages/worker_bee/e2e/lib/e2e_worker.worker.js.dart
- packages/worker_bee/e2e/lib/e2e_worker_no_result.worker.js.dart
- packages/worker_bee/e2e/lib/e2e_worker_null_result.worker.js.dart
- packages/worker_bee/e2e/lib/e2e_worker_throws.worker.js.dart
- packages/worker_bee/e2e/lib/e2e_worker_void_result.worker.js.dart
- packages/worker_bee/e2e/lib/workers.debug.dart
- packages/worker_bee/e2e/lib/workers.release.dart
- packages/worker_bee/worker_bee_builder/lib/src/impl/js.dart
- packages/worker_bee/worker_bee_builder/pubspec.yaml
And re-run `build_runnner` for all packages.
> chore: Update `code_builder` dependency

- packages/amplify_core/lib/amplify_core.dart
- packages/amplify_core/lib/src/types/datastore/models/query_snapshot.dart
- packages/amplify_core/lib/src/types/models/model.dart
- packages/amplify_core/lib/src/types/models/model_index.dart
- packages/amplify_core/lib/src/types/models/model_schema.dart
- packages/amplify_core/lib/src/types/models/model_schema_definition.dart
- packages/amplify_core/lib/src/types/query/query_field_operators.dart
- packages/amplify_core/lib/src/types/query/query_model_identifier.dart
- packages/amplify_core/lib/src/types/query/query_predicate.dart
- Add ModelIndex ModelIdentifier interface
- Make Model non-abstract class to prevent unnecessary breaking changes
- Add indexes to model schema
- Add query by model identifier interface
> feat(core): custom primary key supporting interface changes

- packages/amplify_test/analysis_options.yaml
- packages/amplify_test/lib/test_models/many_to_many/FirstMtmRelation.dart
- packages/amplify_test/lib/test_models/many_to_many/ManyToManyPrimary.dart
- packages/amplify_test/lib/test_models/many_to_many/ManyToManySecondary.dart
- packages/amplify_test/lib/test_models/many_to_many/MtmModelProvider.dart
- packages/amplify_test/lib/test_models/many_to_many/SecondMtmRelation.dart
- packages/amplify_test/lib/test_models/many_to_many/schema.graphql
- packages/api/amplify_api/lib/src/graphql/graphql_request_factory.dart
- packages/api/amplify_api/lib/src/graphql/utils.dart
- packages/api/amplify_api/test/graphql_helpers_mtm_test.dart
- packages/api/amplify_api/test/graphql_helpers_test.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/1814
*Description of changes:* Support multiple belongsTo
> fix(api): support multiple belongsTo

- packages/amplify_core/lib/src/category/amplify_storage_category.dart
- packages/amplify_core/lib/src/types/storage/get_url_request.dart
- packages/storage/amplify_storage_s3_dart/example/bin/example.dart
- packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart
- packages/storage/amplify_storage_s3_dart/lib/src/exception/s3_storage_exception.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_get_properties_operation.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_get_properties_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_get_properties_result.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_get_url_operation.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_get_url_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_get_url_result.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_item.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart
- packages/storage/amplify_storage_s3_dart/test/exception/s3_storage_exception_test.dart
- packages/storage/amplify_storage_s3_dart/test/storage_s3_service.dart/storage_s3_service_test.dart
- packages/storage/amplify_storage_s3_dart/test/utils/mocks.dart
* Implemented `getUrl` and `getProperties` APIs for Storage S3 plugin
* Added relevant unit tests
* Updated the dart command line example App to show the APIs usage
> feat(storage): implement getUrl and getProperties APIs

- README.md
- packages/amplify/amplify_flutter/README.md
- packages/amplify_core/README.md
- packages/amplify_datastore/README.md
- packages/api/amplify_api/README.md
- packages/auth/amplify_auth_cognito/README.md
- packages/storage/amplify_storage_s3/README.md
- Updates the category support tables to improve readability
**Current**
**Updated**
> chore: update next category support tables

- packages/analytics/amplify_analytics_pinpoint/example/backend/.gitignore
- packages/analytics/amplify_analytics_pinpoint/example/backend/.npmignore
- packages/analytics/amplify_analytics_pinpoint/example/backend/README.md
- packages/analytics/amplify_analytics_pinpoint/example/backend/bin/app.ts
- packages/analytics/amplify_analytics_pinpoint/example/backend/cdk.context.json
- packages/analytics/amplify_analytics_pinpoint/example/backend/cdk.json
- packages/analytics/amplify_analytics_pinpoint/example/backend/jest.config.js
- packages/analytics/amplify_analytics_pinpoint/example/backend/lib/schema.graphql
- packages/analytics/amplify_analytics_pinpoint/example/backend/lib/stack.kinesis-consumer.ts
- packages/analytics/amplify_analytics_pinpoint/example/backend/lib/stack.ts
- packages/analytics/amplify_analytics_pinpoint/example/backend/package-lock.json
- packages/analytics/amplify_analytics_pinpoint/example/backend/package.json
- packages/analytics/amplify_analytics_pinpoint/example/backend/tool/create_config.dart
- packages/analytics/amplify_analytics_pinpoint/example/backend/tsconfig.json
- packages/analytics/amplify_analytics_pinpoint/example/integration_test/events_test.dart
- packages/analytics/amplify_analytics_pinpoint/example/integration_test/main_test.dart
- packages/analytics/amplify_analytics_pinpoint/example/ios/Flutter/AppFrameworkInfo.plist
- packages/analytics/amplify_analytics_pinpoint/example/ios/Runner/Info.plist
- packages/analytics/amplify_analytics_pinpoint/example/pubspec.yaml
- packages/analytics/amplify_analytics_pinpoint/example/tool/provision_integration_test_resources.sh
> test(analytics): Integration test backend [CP]

- packages/secure_storage/amplify_secure_storage_dart/pubspec.yaml
- bump `win32` to latest version
> chore(secure_storage): bump win32 to 3.0.0

- .github/dependabot.yaml
- regenerate `dependabot.yaml` file.
> chore: regenerate `dependabot.yaml`

- .circleci/config.yml
- packages/datastore/amplify_datastore/example/ios/Podfile
- packages/datastore/amplify_datastore/example/ios/Runner.xcodeproj/project.pbxproj
- packages/datastore/amplify_datastore/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/datastore/amplify_datastore/example/ios/RunnerTests/RunnerTests.m
**Stack**:
- #2187
- #2186
- #2181
- #2180
- #2178 ⬅
- #2177
- #2170
> chore(datastore): Enable iOS integration tests

- packages/smithy/smithy/lib/src/serialization/stream_serializer.dart
Adds temporary fix for build issue caused by https://github.com/dart-lang/sdk/issues/49851
> fix(storage): Temporary build fix

- packages/amplify_core/lib/src/types/datastore/datastore_types.dart
> chore(core): remove duplicate exports

- packages/amplify/amplify_flutter/lib/src/hybrid_impl.dart
- packages/amplify/amplify_flutter/lib/src/method_channel_amplify.dart
- packages/amplify_core/lib/amplify_core.dart
- packages/amplify_core/lib/src/amplify_class_impl.dart
- packages/amplify_core/lib/src/category/amplify_categories.dart
- packages/amplify_core/lib/src/category/amplify_datastore_category.dart
- packages/amplify_core/lib/src/plugin/amplify_plugin_interface.dart
- packages/amplify_core/lib/src/types/api/auth/api_authorization_type.dart
- packages/amplify_core/lib/src/types/common/amplify_auth_provider.dart
- packages/amplify_core/test/amplify_auth_provider_test.dart
- packages/amplify_core/test/plugin/auth_providers_test.dart
- packages/amplify_core/test/plugin/plugin_key_test.dart
- packages/analytics/amplify_analytics_pinpoint/lib/method_channel_amplify.dart
- packages/api/amplify_api/lib/src/method_channel_api.dart
- packages/api/amplify_api/test/graphql_helpers_test.dart
- packages/auth/amplify_auth_cognito/lib/src/auth_plugin_impl.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/util/cognito_iam_auth_provider.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/auth_providers_test.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/delete_user_test.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/sign_out_test.dart
- packages/storage/amplify_storage_s3/lib/method_channel_storage_s3.dart
- packages/storage/amplify_storage_s3/test/amplify_storage_s3_transferprogress_test.dart
Adds the auth providers interface for registering/retrieving auth providers across categories from a central repository.
> feat(core): Auth providers

- packages/smithy/smithy_codegen/lib/src/util/shape_ext.dart
Long values need to be wrapped in `Int64` types but this was not handled before when using `literal`
> fix(smithy): Default long

- .github/workflows/amplify_integration_tests.yaml
- packages/analytics/amplify_analytics_pinpoint/example/tool/pull_test_backend.sh
Runs analytics integ tests in CI.
> chore(analytics): run integ tests in CI

- packages/storage/amplify_storage_s3_dart/lib/src/exception/s3_storage_exception.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_item.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart
- packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
> feat(storage): use AmplifyHttpClient with S3Client

- aft.yaml
- packages/auth/amplify_auth_cognito_dart/pubspec.yaml
- packages/aws_common/pubspec.yaml
- packages/aws_sdk/smoke_test/pubspec.yaml
- packages/secure_storage/amplify_secure_storage_dart/pubspec.yaml
- packages/smithy/goldens/lib/awsJson1_0/pubspec.yaml
- packages/smithy/goldens/lib/awsJson1_1/pubspec.yaml
- packages/smithy/goldens/lib/restJson1/pubspec.yaml
- packages/smithy/goldens/lib/restXml/pubspec.yaml
- packages/smithy/goldens/lib/restXmlWithNamespace/pubspec.yaml
- packages/smithy/goldens/lib2/awsJson1_0/pubspec.yaml
- packages/smithy/goldens/lib2/awsJson1_1/pubspec.yaml
- packages/smithy/goldens/lib2/custom/pubspec.yaml
- packages/smithy/goldens/lib2/restJson1/pubspec.yaml
- packages/smithy/goldens/lib2/restXml/pubspec.yaml
- packages/smithy/goldens/lib2/restXmlWithNamespace/pubspec.yaml
- packages/smithy/smithy/pubspec.yaml
- packages/smithy/smithy_aws/pubspec.yaml
- packages/smithy/smithy_codegen/pubspec.yaml
- packages/worker_bee/e2e/pubspec.yaml
- packages/worker_bee/e2e_test/pubspec.yaml
- packages/worker_bee/worker_bee/pubspec.yaml
> chore: bump built_value_generator version to 8.4.2

- packages/amplify_authenticator/pubspec.yaml
Updates `homepage` link which no longer points to the correct UI docs.
> chore(authenticator): Update `homepage` URL

- packages/storage/amplify_storage_s3_dart/example/bin/example.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_list_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_list_result.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart
> feat(storage): add listAll option of the list API

- packages/amplify_core/lib/src/category/amplify_storage_category.dart
- packages/amplify_core/lib/src/io/aws_file.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_data_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_file_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_get_properties_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_get_url_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_item_with_access_level.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_list_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
> chore(storage): improve Dart comment documentations

- packages/amplify/amplify_flutter/test/amplify_test.dart
Fixes failing test due to configuration changes in #2303
> chore(amplify_flutter): Fix test

- README.md
- packages/amplify/amplify_flutter/README.md
- packages/amplify_core/README.md
- packages/amplify_datastore/README.md
- packages/analytics/amplify_analytics_pinpoint/README.md
- packages/api/amplify_api/README.md
- packages/auth/amplify_auth_cognito/README.md
- packages/storage/amplify_storage_s3/README.md
Updates READMEs for categories to have updated platform matrices with API/Storage (will do Analytics separately depending on timing).
> chore: update platform matrices in READMEs

- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart
- packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
> fix(storage): add missing contentType uploading AWSFile < 5MB

- aft.yaml
- packages/aft/README.md
- packages/aft/lib/src/commands/amplify_command.dart
- packages/aft/lib/src/commands/deps_command.dart
- packages/aft/pubspec.yaml
- packages/amplify/amplify_flutter/pubspec.yaml
- packages/amplify_authenticator/example/pubspec.yaml
- packages/amplify_core/pubspec.yaml
- packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_user_pool_tokens.g.dart
- packages/auth/amplify_auth_cognito_dart/pubspec.yaml
- packages/aws_common/pubspec.yaml
- packages/aws_common/tool/test_models.g.dart
- packages/aws_signature_v4/pubspec.yaml
- packages/smithy/smithy/pubspec.yaml
- packages/smithy/smithy_aws/pubspec.yaml
- packages/smithy/smithy_codegen/pubspec.yaml
Renames `aft deps update` to `aft deps apply` and repurposes `aft deps update` to update dependency constraints in `aft.yaml` to match the latest versions on `pub.dev`.
> feat(aft): Update + apply deps

- packages/worker_bee/worker_bee_builder/lib/src/type_visitor.dart
- packages/worker_bee/worker_bee_builder/lib/src/worker_generator.dart
- packages/worker_bee/worker_bee_builder/pubspec.yaml
Fixes CI failures in `dev` tests
> chore(worker_bee): Bump `analyzer` dependency

- packages/storage/amplify_storage_s3/README.md
> chore(storage): add developer preview upgrade instruction to README

- packages/auth/amplify_auth_cognito/example/backend/package-lock.json
- packages/auth/amplify_auth_cognito/example/backend/package.json
- packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_up_test.dart
Adds tests to cover use cases for sending and resending confirmation codes at sign up.
> test(auth): Add `confirmSignUp` tests

- example/android/app/build.gradle
- packages/amplify/amplify_flutter/example/android/app/build.gradle
- packages/amplify/amplify_flutter_android/android/build.gradle
- packages/amplify_authenticator/example/android/app/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterSubscriptionDataProcessedEvent.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/hub/FlutterSyncMetaData.kt
- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/model/FlutterSerializedModel.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStoreHubTest.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePluginTest.kt
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/FlutterSerializedModelData.kt
- packages/amplify_datastore/example/android/app/build.gradle
- packages/analytics/amplify_analytics_pinpoint/example/android/app/build.gradle
- packages/api/amplify_api/example/android/app/build.gradle
- packages/api/amplify_api_android/android/build.gradle
- packages/api/amplify_api_android/android/src/test/kotlin/com/amazonaws/amplify/amplify_api/AuthProviderTests.kt
- packages/api/amplify_api_android/example/android/app/build.gradle
- packages/auth/amplify_auth_cognito/example/android/app/build.gradle
- packages/auth/amplify_auth_cognito_android/android/build.gradle
- packages/auth/amplify_auth_cognito_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/NativeAuthPlugin.kt
- packages/common/amplify_db_common/example/android/app/build.gradle
- packages/secure_storage/amplify_secure_storage/android/build.gradle
- packages/secure_storage/amplify_secure_storage/example/android/app/build.gradle
- packages/storage/amplify_storage_s3/example/android/app/build.gradle
- packages/worker_bee/e2e_flutter_test/android/app/build.gradle
Update Android dependencies to GA
> chore(repo): Bump Android dependencies to 2.0.0

- packages/aws_common/lib/src/io/aws_file.dart
> fix(aws_common): AWSFile doc example

- README.md
- packages/amplify/amplify_flutter/README.md
Update tables for new dev preview categories.
> chore: update platform support tables

- aft.yaml
- packages/analytics/amplify_analytics_pinpoint_dart/lib/src/impl/drift/drift_tables.g.dart
- packages/analytics/amplify_analytics_pinpoint_dart/pubspec.yaml
- packages/auth/amplify_auth_cognito/example/pubspec.yaml
- packages/common/amplify_db_common/example/lib/db.g.dart
- packages/common/amplify_db_common/example/pubspec.yaml
- packages/common/amplify_db_common/pubspec.yaml
- packages/common/amplify_db_common_dart/example/bin/database.g.dart
- packages/common/amplify_db_common_dart/example/pubspec.yaml
- packages/common/amplify_db_common_dart/example/web/database.g.dart
- packages/common/amplify_db_common_dart/pubspec.yaml
- packages/common/amplify_db_common_dart/test/database.g.dart
- packages/storage/amplify_storage_s3/example/pubspec.yaml
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/database/database.g.dart
- packages/storage/amplify_storage_s3_dart/pubspec.yaml
> chore(repo): update drift dependency constraints

- packages/storage/amplify_storage_s3_dart/pubspec.yaml
> chore(storage): fix repo link in pubspec.yaml

- packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_up_test.dart
- packages/auth/amplify_auth_cognito/example/integration_test/sign_up_test.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/model/signup/cognito_sign_up_result.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/event/sign_up_event.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/generated/sign_up_state_machine_base.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_up_state_machine.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/state/sign_up_state.dart
- packages/auth/amplify_auth_cognito_test/test/state/sign_up_state_machine_test.dart
Return the user ID for calls to `Amplify.Auth.signUp`.
> feat(auth): Add user ID to `CognitoSignUpResult`

- packages/amplify_authenticator/lib/amplify_authenticator.dart
`autenticator` => `authenticator`
Thanks for all the work on this package!
> chore(auth): Fix comment typo

- packages/amplify_test/analysis_options.yaml
- packages/amplify_test/lib/test_models/many_to_many/FirstMtmRelation.dart
- packages/amplify_test/lib/test_models/many_to_many/ManyToManyPrimary.dart
- packages/amplify_test/lib/test_models/many_to_many/ManyToManySecondary.dart
- packages/amplify_test/lib/test_models/many_to_many/MtmModelProvider.dart
- packages/amplify_test/lib/test_models/many_to_many/SecondMtmRelation.dart
- packages/amplify_test/lib/test_models/many_to_many/schema.graphql
- packages/api/amplify_api/lib/src/graphql/factories/graphql_request_factory.dart
- packages/api/amplify_api/lib/src/graphql/utils.dart
- packages/api/amplify_api/test/graphql_helpers_mtm_test.dart
- packages/api/amplify_api/test/graphql_helpers_test.dart
*Same Issue #2277 and #1814 on the amplify_api 1.0.0-next.1,
It's #2087 for next branch. Thanks for @fjnoyp
> Support multiple belongsTo for next branch

- packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart
- packages/auth/amplify_auth_cognito_test/lib/amplify_auth_cognito_test.dart
- packages/auth/amplify_auth_cognito_test/pubspec.yaml
- packages/auth/amplify_auth_cognito_test/test/common/matchers.dart
- packages/auth/amplify_auth_cognito_test/test/common/mock_clients.dart
- packages/auth/amplify_auth_cognito_test/test/credentials/auth_plugin_credentials_provider_test.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/delete_user_test.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/fetch_user_attributes_test.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/reset_password_test.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/sign_out_test.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/sign_up_test.dart
- packages/auth/amplify_auth_cognito_test/test/state/fetch_auth_session_state_machine_test.dart
- packages/auth/amplify_auth_cognito_test/test/state/sign_in_state_machine_test.dart
- packages/auth/amplify_auth_cognito_test/test/state/sign_up_state_machine_test.dart
Improves unit test coverage in a few areas to align with other platforms' test suites.
> test(auth): Improve unit test coverage

- infra/lib/auth/custom-sender.ts
- infra/lib/auth/stack.custom-email-sender.ts
- infra/lib/auth/stack.ts
- packages/auth/amplify_auth_cognito/example/integration_test/main_test.dart
- packages/auth/amplify_auth_cognito/example/integration_test/reset_password_test.dart
Adds e2e test for `Amplify.Auth.resetPassword` and `Amplify.Auth.confirmResetPassword`.
> test(auth): Reset password (e2e)

- packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_in_test.dart
- packages/auth/amplify_auth_cognito/example/integration_test/main_test.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/event/sign_in_event.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
Issue #2467
Fix authenticate with invalid verification code and after that authenticating with correct verification code fails.
> fix(auth): Can't resubmit verification code

- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart
> fix(storage): to create new credential scope on each presign url

- packages/storage/amplify_storage_s3/CHANGELOG.md
- packages/storage/amplify_storage_s3/pubspec.yaml
- packages/storage/amplify_storage_s3_dart/CHANGELOG.md
- packages/storage/amplify_storage_s3_dart/pubspec.yaml
- fix(storage): to create new credential scope on each presign url
> chore(version): Storage hotfix

- packages/smithy/goldens/lib/awsJson1_0/analysis_options.yaml
- packages/smithy/goldens/lib/awsJson1_0/pubspec.yaml
- packages/smithy/goldens/lib/awsJson1_1/analysis_options.yaml
- packages/smithy/goldens/lib/awsJson1_1/pubspec.yaml
- packages/smithy/goldens/lib/restJson1/analysis_options.yaml
- packages/smithy/goldens/lib/restJson1/pubspec.yaml
- packages/smithy/goldens/lib/restXml/analysis_options.yaml
- packages/smithy/goldens/lib/restXml/pubspec.yaml
- packages/smithy/goldens/lib/restXmlWithNamespace/analysis_options.yaml
- packages/smithy/goldens/lib/restXmlWithNamespace/pubspec.yaml
- packages/smithy/goldens/lib2/awsJson1_0/analysis_options.yaml
- packages/smithy/goldens/lib2/awsJson1_0/pubspec.yaml
- packages/smithy/goldens/lib2/awsJson1_1/analysis_options.yaml
- packages/smithy/goldens/lib2/awsJson1_1/pubspec.yaml
- packages/smithy/goldens/lib2/custom/analysis_options.yaml
- packages/smithy/goldens/lib2/custom/pubspec.yaml
- packages/smithy/goldens/lib2/restJson1/analysis_options.yaml
- packages/smithy/goldens/lib2/restJson1/pubspec.yaml
- packages/smithy/goldens/lib2/restXml/analysis_options.yaml
- packages/smithy/goldens/lib2/restXml/pubspec.yaml
- packages/smithy/goldens/lib2/restXmlWithNamespace/analysis_options.yaml
- packages/smithy/goldens/lib2/restXmlWithNamespace/pubspec.yaml
- packages/smithy/goldens/tool/update_goldens.dart
- packages/smithy/smithy/lib/src/behavior/retryer.dart
- packages/smithy/smithy_codegen/bin/smithy_codegen.dart
- packages/smithy/smithy_codegen/lib/src/generator/service_client_generator.dart
- packages/smithy/smithy_codegen/lib/src/util/pubspec.dart
- Updates dependencies
- Renames fields correctly for non-AWS services
- Fixes retry behavior for non-AWS services
- Update analysis options
> fix(smithy): Minor issues

- packages/authenticator/amplify_authenticator/README.md
Fixes a dead link to the example app for the Authenticator. 
> fix(authenticator): Example Dead Link

- packages/analytics/amplify_analytics_pinpoint/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/analytics/amplify_analytics_pinpoint/pubspec.yaml
To improve pub.dev score.
Update pubspec deps 
To improve pub.dev score.
> chore(analytics): pubspec version bump 

- packages/storage/amplify_storage_s3/example/integration_test/main_test.dart
> fix(storage): update expected exception types in integ tests

- packages/api/amplify_api_ios/pubspec.yaml
- Fixes `The package description is too short` [ref](https://pub.dev/packages/amplify_api_ios/versions/1.0.0-next.2/score)
> chore(api): API iOS pub Improvement

- .github/composite_actions/setup_firefox/action.yaml
- .github/workflows/amplify_auth_cognito_test.yaml
- .github/workflows/amplify_authenticator.yaml
- .github/workflows/amplify_core.yaml
- .github/workflows/amplify_db_common_dart.yaml
- .github/workflows/amplify_secure_storage_test.yaml
- .github/workflows/aws_common.yaml
- .github/workflows/aws_json1_0_v1.yaml
- .github/workflows/aws_json1_0_v2.yaml
- .github/workflows/aws_json1_1_v1.yaml
- .github/workflows/aws_json1_1_v2.yaml
- .github/workflows/aws_signature_v4.yaml
- .github/workflows/dart_dart2js.yaml
- .github/workflows/rest_json1_v1.yaml
- .github/workflows/rest_json1_v2.yaml
- .github/workflows/rest_xml_v1.yaml
- .github/workflows/rest_xml_v2.yaml
- .github/workflows/rest_xml_with_namespace_v1.yaml
- .github/workflows/rest_xml_with_namespace_v2.yaml
- packages/aft/lib/src/commands/generate/generate_workflows_command.dart
Since the setup action does not authenticate GitHub requests which leads to constant rate limiting issues.
> ci(repo): Use custom bash for `geckodriver`

- tool/license.sh
Updates `addlicense` version and changes to SPDX-only format.
> chore(repo): Update license script

- packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_flutter.dart
- packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_stub.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_html.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_io.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_stub.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/model/signout/cognito_sign_out_with_web_ui_options.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/model/signout/cognito_sign_out_with_web_ui_options.g.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart
- packages/auth/amplify_auth_cognito_test/test/common/mock_hosted_ui.dart
- packages/auth/amplify_auth_cognito_test/test/flows/hostedui/hosted_ui_platform_io_test.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/sign_out_test.dart
- packages/auth/amplify_auth_cognito_test/test/state/hosted_ui_state_machine_test.dart
> chore(auth)!: Remove `isPreferPrivateSession` from `CognitoSignOutWithWebUIOptions`

- infra/pnpm-lock.yaml
`pnpm-lock.json` updated by
1. `rm -rf node_modules`
2. `pnpm install`
> chore(infra): update json5 to 2.2.3

- packages/amplify/amplify_flutter_android/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStoreHubTest.kt
- packages/api/amplify_api_android/android/build.gradle
- packages/auth/amplify_auth_cognito_android/android/build.gradle
- fixes customer issue: https://github.com/aws-amplify/amplify-flutter/issues/2193
> chore: bump amplify-android dep to 2.1.0

- packages/amplify_test/lib/src/integration_test_utils/auth_cognito/integration_test_auth_utils.dart
- packages/amplify_test/pubspec.yaml
>  chore(amplify_test): Remove `graphql` dependency

- infra/tool/create_configs.dart
Instead of just the Flutter examples
> chore(infra): Output integration test config to Dart example apps

- packages/amplify_test/lib/src/stubs/amplify_auth_cognito_stub.dart
- packages/auth/amplify_auth_cognito_dart/lib/amplify_auth_cognito_dart.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_auth_session.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/auth_providers_test.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/2623
- Export AuthResult from amplify_auth_cognito_dart
> chore(auth): export AuthResult from amplify_auth_cognito_dart

- packages/aft/lib/src/util.dart
- packages/aft/test/util_test.dart
Consider transitive dependencies (not just direct) when determining the publish precedence for packages.
> fix(aft): Topo sort transitive deps

- packages/common/amplify_db_common_dart/example/README.md
- packages/common/amplify_db_common_dart/pubspec.yaml
[Pub score ](https://pub.dev/packages/amplify_db_common_dart/score) improvements 
- Longer pubspec.yaml description
- Example App
- Updated Deps
> chore(common): DB Common Dart pub score fixes

- packages/amplify_core/lib/src/state_machine/event.dart
- packages/amplify_core/lib/src/state_machine/state_machine.dart
- packages/amplify_core/test/state_machine/my_state_machine.dart
- packages/amplify_core/test/state_machine/state_machine_test.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/credentials/auth_plugin_credentials_provider.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/cognito_state_machine.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/event/credential_store_event.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/configuration_state_machine.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/credential_store_state_machine.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
- packages/auth/amplify_auth_cognito_test/test/common/mock_hosted_ui.dart
- packages/auth/amplify_auth_cognito_test/test/state/credential_store_state_machine_test.dart
- packages/auth/amplify_auth_cognito_test/test/state/fetch_auth_session_state_machine_test.dart
- packages/aws_common/lib/src/js/readable_stream.dart
Clean up to address comments on #2482.
> chore(auth): State machine cleanup

- packages/analytics/amplify_analytics_pinpoint/lib/amplify_analytics_pinpoint.dart
- packages/analytics/amplify_analytics_pinpoint_dart/lib/amplify_analytics_pinpoint_dart.dart
Export missing files for Push Notifications.
> chore(analytics): export missing files

- packages/authenticator/amplify_authenticator/README.md
- packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_date_field.dart
- packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_phone_field.dart
- packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_text_field.dart
- packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart
- packages/authenticator/amplify_authenticator/lib/src/state/authenticator_state.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_field.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_in_form_field.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_up_form_field.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/phone_number_field.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/reset_password_form_field.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/sign_in_form_field.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/sign_up_form_field.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/verify_user_form_field.dart
- cherry pick 59413a708675856225ce8f390535a922fb06f569 to next
> feat(authenticator): Add AutoFill Capabilities

- packages/amplify_authenticator/example/lib/l10n/amplify_en.arb
- packages/amplify_authenticator/example/lib/l10n/amplify_es.arb
- packages/amplify_authenticator/example/lib/resolvers/localized_button_resolver.dart
Remove unncessary commas
- cherry pick db69ccecd2daf2e20c043fd625931176fc617b5d to main
> fix(authenticator): ARB syntax

- packages/amplify/amplify_flutter_android/android/build.gradle
- packages/amplify_core/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle
- packages/api/amplify_api_android/android/build.gradle
- packages/auth/amplify_auth_cognito_android/android/build.gradle
- packages/storage/amplify_storage_s3_android/android/build.gradle
- Integrate fix aliasing of column names
- Integrate recoverability improvements
https://github.com/aws-amplify/amplify-flutter/issues/2632
May resolve with the recoverability improvements released along with amplify-android [1.38.0](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.38.0).
https://github.com/aws-amplify/amplify-flutter/issues/2652
> chore: bump amplify-android to 1.38.1

- .circleci/config.yml
> chore(repo): pin melos version to 2.9.0

- packages/secure_storage/amplify_secure_storage/lib/src/amplify_secure_storage.vm.dart
Fixes initialization due to changes in #2744.
> fix(secure_storage): Only init Windows config on Windows

- packages/analytics/amplify_analytics_pinpoint_dart/lib/src/impl/analytics_client/event_client/event_client.dart
- packages/analytics/amplify_analytics_pinpoint_dart/test/common/mocktail_mocks.dart
- packages/analytics/amplify_analytics_pinpoint_dart/test/event_client_test.dart
Add logic to:
1) Treat AWSHttpException as retryable to fix no internet case
2) Retryable statusCode is 500-600
3) If a specific event fails 3 times, delete it.
> fix(analytics): event retry logic & max fail tries

- .github/workflows/amplify_integration_tests.yaml
- infra/package.json
- infra/pnpm-lock.yaml
- packages/authenticator/amplify_authenticator/example/integration_test/config.dart
- packages/authenticator/amplify_authenticator/example/integration_test/sign_in_with_username_test.dart
- packages/authenticator/amplify_authenticator/example/tool/pull_test_backend.sh
Enables Authenticator E2E tests in CI
> ci(authenticator): Enable E2E tests

- packages/amplify/amplify_flutter_android/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/amplify_datastore/example/android/app/build.gradle
- packages/api/amplify_api_android/android/build.gradle
- packages/auth/amplify_auth_cognito_android/android/build.gradle
https://github.com/aws-amplify/amplify-flutter/issues/2632
> chore(repo): bump amplify-android to v2.3.0

- packages/aws_signature_v4/example/web/index.html
Pin the version of external pico css file, and add integrity check.
> chore(sigv4): add integrity check on the external css used in example

- packages/notifications/push/amplify_push_notifications/lib/src/amplify_push_notifications_impl.dart
- packages/notifications/push/amplify_push_notifications_pinpoint/example/lib/main.dart
- packages/notifications/push/amplify_push_notifications_pinpoint/lib/src/pinpoint_provider.dart
- packages/notifications/push/amplify_push_notifications_pinpoint/pubspec.yaml
Update analytics integration with latest changes from next:
1) Removing Analytics prefix in UserProfile types
2) Use direct package imports
3) Throw ConfigurationError
> chore(push): update analytics integration

- packages/amplify_core/lib/src/types/storage/upload_data_options.dart
- packages/amplify_core/lib/src/types/storage/upload_file_options.dart
- packages/storage/amplify_storage_s3/example/integration_test/use_case_test.dart
- packages/storage/amplify_storage_s3_dart/example/bin/example.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_data_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_data_plugin_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_data_plugin_options.g.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_file_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_file_plugin_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_file_plugin_options.g.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart
- packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
- update uploadData and uploadFile APIs to move metadata from plugin options to category level options.
> feat(storage)!: update upload APIs options to add metadata field

- .github/workflows/amplify_integration_tests.yaml
- Adds `fix/**` and `test/**` branch patterns for integration tests
- Fixes issues introduced by https://github.com/aws-amplify/amplify-flutter/pull/2803.
> test(auth): Sign out users after tests

- packages/amplify_core/lib/src/config/analytics/pinpoint_config.dart
- packages/amplify_core/lib/src/config/analytics/pinpoint_config.g.dart
- packages/amplify_core/test/config/cli_config_test.dart
- packages/amplify_core/test/config/testdata/cli_generated.dart
- packages/amplify_core/test/config/testdata/generate/generate.js
- packages/amplify_core/test/config/testdata/test_values.dart
- packages/analytics/amplify_analytics_pinpoint_dart/lib/src/analytics_plugin_impl.dart
- packages/analytics/amplify_analytics_pinpoint_dart/lib/src/impl/analytics_client/stoppable_timer.dart
- packages/analytics/amplify_analytics_pinpoint_dart/test/analytics_plugin_config_test.dart
- packages/analytics/amplify_analytics_pinpoint_dart/test/common/mocktail_mocks.dart
Configurable analytics flush interval in amplifyConfiguration.dart
> chore(core): configurable analytics flush interval

- packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart
- packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart
> fix(storage): metadata gets lost while converting upload options

- .github/workflows/amplify_push_notifications.yaml
- .github/workflows/amplify_push_notifications_pinpoint.android.yaml
- .github/workflows/amplify_push_notifications_pinpoint.ios.yaml
- .github/workflows/amplify_push_notifications_pinpoint.yaml
- aft.yaml
- packages/notifications/push/amplify_push_notifications/lib/src/amplify_push_notifications_impl.dart
- packages/notifications/push/amplify_push_notifications/pubspec.yaml
- packages/notifications/push/amplify_push_notifications_pinpoint/example/android/app/google-services.json
- packages/notifications/push/amplify_push_notifications_pinpoint/example/pubspec.yaml
- packages/notifications/push/amplify_push_notifications_pinpoint/lib/src/event_info_type.dart
- packages/notifications/push/amplify_push_notifications_pinpoint/lib/src/push_notifications_background_processing.dart
- packages/notifications/push/amplify_push_notifications_pinpoint/pubspec.yaml
> chore(notifications): enable GH workflows

- .github/workflows/flutter_vm.yaml
- packages/notifications/push/amplify_push_notifications/Makefile
Since `flutter format` is deprecated.
> ci(repo): Use `dart format` instead of `flutter format`

- packages/storage/amplify_storage_s3_dart/lib/src/error/invalid_bytes_range_error.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_copy_plugin_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_data_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_file_operation.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_move_plugin_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_remove_plugin_options.dart
Fix Storage S3 API doc rendering issues.
Amplify Push Notification plugin implementation.
> fix(storage): API doc errors

- packages/amplify_core/lib/src/types/api/graphql/graphql_response.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/jwt/src/token.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_item.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_item.g.dart
- Override `toString` on `GraphQLResponse`
- Override `toString` on `S3Item`
> chore: Override `toString`

- README.md
- packages/amplify/amplify_flutter/README.md
- packages/amplify/amplify_flutter_android/README.md
- packages/amplify/amplify_flutter_ios/README.md
- packages/amplify_core/README.md
- packages/amplify_datastore/README.md
- packages/amplify_datastore_plugin_interface/README.md
- packages/analytics/amplify_analytics_pinpoint/README.md
- packages/analytics/amplify_analytics_pinpoint_dart/README.md
- packages/api/amplify_api/README.md
- packages/api/amplify_api_android/README.md
- packages/api/amplify_api_dart/README.md
- packages/api/amplify_api_ios/README.md
- packages/auth/amplify_auth_cognito/README.md
- packages/auth/amplify_auth_cognito_android/README.md
- packages/auth/amplify_auth_cognito_dart/README.md
- packages/auth/amplify_auth_cognito_ios/README.md
- packages/authenticator/amplify_authenticator/README.md
- packages/aws_signature_v4/README.md
- packages/notifications/push/amplify_push_notifications/README.md
- packages/notifications/push/amplify_push_notifications_pinpoint/README.md
- packages/storage/amplify_storage_s3/README.md
- packages/storage/amplify_storage_s3_dart/README.md
Removes developer preview references and updates any example code snippets.
> chore(repo): Update READMEs

- packages/amplify/amplify_flutter_ios/ios/amplify_flutter_ios.podspec
- packages/amplify_datastore/ios/amplify_datastore.podspec
- packages/amplify_native_legacy_wrapper/ios/amplify_native_legacy_wrapper.podspec
- packages/api/amplify_api_ios/ios/amplify_api_ios.podspec
- packages/auth/amplify_auth_cognito_ios/ios/amplify_auth_cognito_ios.podspec
> chore(ios): bump amplify-swift to 1.29.2

- packages/notifications/push/amplify_push_notifications_pinpoint/example/ios/unit_tests/AmplifyPushNotificationsPluginTest.swift
> chore(push): Fix iOS test

- .circleci/config.yml
- canaries/dummy_amplifyconfiguration.dart
- canaries/integration_test/app_test.dart
- canaries/main.dart
- canaries/models/ModelProvider.dart
- Copies over `canaries/` folder from `main-v0`
- Adds Flutter 3.3.0 canary
> ci: Fix canaries

- infra/lib/cleanup-users.ts
Even at 5 min, this is timing out. This batches/parallelizes the calls to improve performance while avoiding rate limiting issues.
> infra: Improve clean up performance

- .github/workflows/aws_query_v1.yaml
- .github/workflows/aws_query_v2.yaml
- packages/aft/lib/src/commands/generate/generate_workflows_command.dart
Use `git diff` to check whether workflows have changed and also to print a nice diff when they have. Based on https://github.com/kevmoo/build_verify/blob/master/lib/src/impl.dart
> chore: Update workflows

- packages/worker_bee/worker_bee_builder/pubspec.yaml
- update source_gen version constraints to `">=1.2.1 <1.3.0"`
> chore: update source_gen version constraints

- aft.yaml
- packages/aws_sdk/smoke_test/pubspec.yaml
- packages/smithy/goldens/lib/restXml/pubspec.yaml
- packages/smithy/goldens/lib/restXmlWithNamespace/pubspec.yaml
- packages/smithy/goldens/lib2/restXml/pubspec.yaml
- packages/smithy/goldens/lib2/restXmlWithNamespace/pubspec.yaml
- packages/smithy/smithy/lib/src/serialization/xml/smithy_xml_plugin.dart
- packages/smithy/smithy/pubspec.yaml
- packages/smithy/smithy_aws/lib/src/protocol/aws_query_serializer.dart
- packages/smithy/smithy_aws/pubspec.yaml
- packages/smithy/smithy_codegen/lib/src/util/pubspec.dart
- packages/smithy/smithy_codegen/pubspec.yaml
- packages/smithy/smithy_test/pubspec.yaml
> chore(deps): Bump `xml` to `<=6.3.0`

- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt
- packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift
Tracks DS usage via the native user agent.
> chore(datastore): Add DS identifier to native user agent

- packages/auth/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPlugin.kt
- packages/auth/amplify_auth_cognito/example/ios/Podfile
> chore(auth): Fix consolidation logic

- .github/workflows/verify_pub_constraints.yaml
- packages/aft/README.md
- packages/aft/lib/src/commands/amplify_command.dart
- packages/aft/lib/src/commands/constraints_command.dart
- packages/aft/pubspec.yaml
Adds command to validate constraints against the top X pub.dev packages.
> feat(aft): Add `aft constraints pub-verify`

- infra/lib/auth/stack.create-user.ts
- packages/amplify_core/lib/src/types/exception/network_exception.dart
- packages/auth/amplify_auth_cognito/example/.gitignore
- packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_in_test.dart
- packages/auth/amplify_auth_cognito/example/integration_test/native_auth_bridge_test.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
- packages/test/amplify_integration_test/lib/src/integration_test_utils/auth_cognito/integration_test_auth_utils.dart
Currently, the map entry is being serialized instead of the key.
> fix(auth): User attribute serialization

- .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
Add "Notifications (Push)" as an option in the GH issue template.
> chore(repo): add notifications (push) as an option in issue template

- packages/auth/amplify_auth_cognito/example/pubspec.yaml
> chore: remove test_api override

- packages/smithy/smithy_codegen/bin/smithy_codegen.dart
Fix usage of deprecated constructor
> chore(smithy_codegen): Fix deprecated usage

- packages/amplify/amplify_flutter_android/android/build.gradle
- packages/amplify_core/android/build.gradle
- packages/amplify_datastore/android/build.gradle
- packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle
- packages/api/amplify_api_android/android/build.gradle
- packages/auth/amplify_auth_cognito_android/android/build.gradle
- packages/storage/amplify_storage_s3_android/android/build.gradle
- Fixes #2710
- Improves #3017
> chore: bump amplify-android to 1.38.6

- packages/aws_common/lib/src/config/aws_service.dart
Regenerates `AWSService` class and makes it possible to use services not automatically generated.
> chore(aws_common): Update `AWSService`

- .github/workflows/smoke_test.yaml
- packages/aws_sdk/smoke_test/test/api_gateway_test.dart
- packages/aws_sdk/smoke_test/workflow.yaml
A bug currently exists which is causing test failures (https://github.com/localstack/localstack/issues/8553).
> test(smoke_test): Skip failing

- .github/workflows/amplify_canaries.yaml
> fix(canaries): add missing channel to e2e-ios

- packages/aft/lib/src/commands/generate/generate_sdk_command.dart
Makes `aft generate sdk` behave more like other commands where it can be run with no arguments for all packages and now works with `--include`/`--exclude` as well. This means the models only need to be downloaded once if they're not already cloned, which is the most expensive part of the operation.
> chore(aft): Improve SDK generation command

- packages/amplify_core/lib/src/types/api/graphql/graphql_request.dart
- packages/api/amplify_api_dart/lib/src/graphql/web_socket/blocs/web_socket_bloc.dart
- packages/api/amplify_api_dart/lib/src/graphql/web_socket/types/subscriptions_event.dart
- packages/api/amplify_api_dart/lib/src/graphql/web_socket/types/web_socket_event.dart
Improves logging in the WebSocketBloc so that events have metadata logged as well. Since this is currently done with `debug` log level, there should be no new information exposed in production logs.
> chore(api): Improve WS logging

- README.md
Adds a v0 deprecation notice to main README same as was added to v0 branch.
> chore: v0 notice in README

- .github/workflows/amplify_integration_tests.yaml
Resolves issues with Web e2e tests by updating `setup-chromedriver` action.
> ci: Update chromedriver

- packages/auth/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPlugin.kt
Improves logging in the native Android code which should help resolve customer issues more easily when they occur in the future.
e.g.
```
D/AmplifyAuthCognitoPlugin( 8645): [browserPackageName] Resolved activity info: ResolveInfo{b51f3b7 com.android.chrome/com.google.android.apps.chrome.IntentDispatcher m=0x208000 userHandle=UserHandle{0}}
D/AmplifyAuthCognitoPlugin( 8645): [browserPackageName] Resolved default package: com.android.chrome
D/AmplifyAuthCognitoPlugin( 8645): [browserPackageName] Resolved custom tabs handlers: [com.android.chrome]
D/AmplifyAuthCognitoPlugin( 8645): [launchUrl] Using browser package: com.android.chrome
```
> chore(auth): Improve native Android logs

- CONTRIBUTING.md
- README.md
Adds callout for semantic versioning around sealed classes and enums.
> docs(repo): Add semantic versioning callout

- packages/auth/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPlugin.kt
The current implementation of Hosted UI on Android relies on a timer to trigger the cancellation of any pending sign-in/out operations. This is because of limitations with the Custom Tab intent, but leads to inherent flakiness.
Thinking about it again, we can leverage the same intent mechanism used in the success case to ensure that in either the success or cancellation case, the right choice is made on how to proceed.
Tested On: Android 9 (physical), 11, 13, 14 (emulator)
> fix(auth): Android Hosted UI flakiness

- infra/package.json
- infra/pnpm-lock.yaml
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/security/dependabot/14
*Description of changes:* 
- Update `@aws-sdk/client-cognito-identity-provider` to latest version
> chore: update client-cognito-identity-provider

- packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/DataStoreHubEventStreamHandler.kt
*Issue #, if available:* #3307
- make event history list thread safe
> fix(datastore): make event history list thread safe

- infra/package.json
- infra/pnpm-lock.yaml
A full update of infra deps. The dependabot updates left some inconsistencies.
Command run: `pnpm upgrade --latest`
> chore(deps): Update infra deps

- packages/amplify_datastore/android/build.gradle
- packages/notifications/push/amplify_push_notifications/android/build.gradle
Incorporates https://github.com/aws-amplify/amplify-android/pull/2545 to fix custom list serialization and deserialization on Android.
> fix(datastore): Custom list serde

- infra/lib/stack.ts
- infra/package.json
- infra/pnpm-lock.yaml
- packages/auth/amplify_auth_cognito/example/integration_test/custom_auth_test.dart
- packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
Allows device SRP to be performed as part of the custom auth flow. Adds an e2e test to verify.
> fix(auth): Pass deviceKey in custom auth challenge

- .github/dependabot.yaml
- .github/workflows/aws_logging_cloudwatch.yaml
- packages/logging_cloudwatch/aws_logging_cloudwatch/analysis_options.yaml
- packages/logging_cloudwatch/aws_logging_cloudwatch/example/bin/main.dart
- packages/logging_cloudwatch/aws_logging_cloudwatch/example/web/main.dart
- packages/logging_cloudwatch/aws_logging_cloudwatch/example/web/styles.css
- packages/logging_cloudwatch/aws_logging_cloudwatch/lib/aws_logging_cloudwatch.dart
- packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/queued_item_store/in_memory_queued_item_store.dart
- packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/queued_item_store/queued_item_store.dart
- packages/logging_cloudwatch/aws_logging_cloudwatch/test/aws_logging_cloudwatch_test.dart
- packages/logging_cloudwatch/aws_logging_cloudwatch/test/queued_item_store/queued_item_store_test.dart
- add QueuedItemStore interface and InMemoryQueuedItemStore implementation.
- next is to implement isFull method. 
> feat(logging): add queued item store

- .github/workflows/flutter_vm.yaml
- packages/amplify_datastore/example/lib/models/BelongsToChildExplicit.dart
- packages/amplify_datastore/example/lib/models/BelongsToChildImplicit.dart
- packages/amplify_datastore/example/lib/models/CpkHasManyChildBidirectionalExplicit.dart
- packages/amplify_datastore/example/lib/models/CpkHasManyChildBidirectionalImplicit.dart
- packages/amplify_datastore/example/lib/models/CpkHasManyUnidirectionalParent.dart
- packages/amplify_datastore/example/lib/models/CpkHasOneUnidirectionalChild.dart
- packages/amplify_datastore/example/lib/models/CpkHasOneUnidirectionalParent.dart
- packages/amplify_datastore/example/lib/models/CpkManyToManyPost.dart
- packages/amplify_datastore/example/lib/models/CpkManyToManyTag.dart
- packages/amplify_datastore/example/lib/models/CpkOneToOneBidirectionalParentCD.dart
- packages/amplify_datastore/example/lib/models/CpkOneToOneBidirectionalParentID.dart
- packages/amplify_datastore/example/lib/models/HasManyChildBiDirectionalExplicit.dart
- packages/amplify_datastore/example/lib/models/HasManyChildBiDirectionalImplicit.dart
- packages/amplify_datastore/example/lib/models/HasManyChildExplicit.dart
- packages/amplify_datastore/example/lib/models/HasManyChildImplicit.dart
- packages/amplify_datastore/example/lib/models/HasManyParentBiDirectionalExplicit.dart
- packages/amplify_datastore/example/lib/models/HasManyParentBiDirectionalImplicit.dart
- packages/amplify_datastore/example/lib/models/ModelWithAppsyncScalarTypes.dart
- packages/amplify_datastore/example/lib/models/ModelWithCustomType.dart
- packages/amplify_datastore/example/lib/models/MultiRelatedAttendee.dart
- packages/amplify_datastore/example/lib/models/MultiRelatedMeeting.dart
- packages/amplify_datastore/example/lib/models/MultiRelatedRegistration.dart
Format fixes missed in Dart 3.1 PR.
> chore(datastore): Format fixes

- build-support/build_canary.sh
- packages/amplify_datastore/CHANGELOG.md
- packages/amplify_datastore/ios/amplify_datastore.podspec
- packages/amplify_datastore/pubspec.yaml
- fix(datastore): Pin `Starscream`
Updated-Components: amplify_datastore
> chore(version): Bump version

- packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/index_db/indexed_db_adapter.dart
> chore(logging): fix indexed db adapter was failing browser tests

- packages/aft/pubspec.yaml
- packages/authenticator/amplify_authenticator/pubspec.yaml
- packages/smithy/smithy_codegen/pubspec.yaml
- packages/worker_bee/worker_bee_builder/pubspec.yaml
- pubspec.yaml
Bumps `code_builder` to `4.6.0`
> chore(deps): Bump `code_builder`

- actions/lib/bootstrap.mjs
- actions/lib/src/node/actions/github.dart
- actions/package.json
- actions/pnpm-lock.yaml
Adds interop code for the `@actions/github` package which contains helpers for getting the context of the current action.
> feat(actions): Add GitHub interop

- packages/amplify/amplify_flutter/CHANGELOG.md
- packages/amplify/amplify_flutter/pubspec.yaml
- packages/amplify_core/CHANGELOG.md
- packages/amplify_core/pubspec.yaml
- packages/amplify_datastore_plugin_interface/CHANGELOG.md
- packages/amplify_datastore_plugin_interface/pubspec.yaml
- packages/analytics/amplify_analytics_pinpoint/CHANGELOG.md
- packages/analytics/amplify_analytics_pinpoint/pubspec.yaml
- packages/api/amplify_api/CHANGELOG.md
- packages/api/amplify_api/pubspec.yaml
- packages/api/amplify_api_dart/CHANGELOG.md
- packages/api/amplify_api_dart/pubspec.yaml
- packages/common/amplify_db_common/CHANGELOG.md
- packages/common/amplify_db_common/pubspec.yaml
- packages/common/amplify_db_common_dart/CHANGELOG.md
- packages/common/amplify_db_common_dart/pubspec.yaml
- packages/notifications/push/amplify_push_notifications/CHANGELOG.md
- packages/notifications/push/amplify_push_notifications/pubspec.yaml
- packages/notifications/push/amplify_push_notifications_pinpoint/CHANGELOG.md
- packages/notifications/push/amplify_push_notifications_pinpoint/pubspec.yaml
- packages/secure_storage/amplify_secure_storage/CHANGELOG.md
- packages/secure_storage/amplify_secure_storage/pubspec.yaml
- packages/secure_storage/amplify_secure_storage_dart/CHANGELOG.md
- packages/secure_storage/amplify_secure_storage_dart/pubspec.yaml
- packages/storage/amplify_storage_s3/CHANGELOG.md
- packages/storage/amplify_storage_s3/pubspec.yaml
- packages/worker_bee/worker_bee/CHANGELOG.md
- packages/worker_bee/worker_bee/pubspec.yaml
- packages/worker_bee/worker_bee_builder/CHANGELOG.md
- packages/worker_bee/worker_bee_builder/pubspec.yaml
> chore(repo): Merge missing version updates

- packages/amplify_core/doc/pubspec.yaml
- packages/amplify_core/pubspec.yaml
> chore(docs): Pin `code_excerpter`

- packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/cloudwatch_logger_plugin.dart
- packages/logging_cloudwatch/aws_logging_cloudwatch/test/cloudwatch_logger_plugin_test.dart
- packages/logging_cloudwatch/aws_logging_cloudwatch/test/mocks.dart
- clear logs when user is signed out, session is expired or user is deleted
> feat(logging): clear logs on user sign out

- THIRD_PARTY
Adds a file disclosing our third party dart dependencies and their licenses. This was generated using an AFT command that is still a WIP.
> chore(repo): third party notice

- .github/workflows/dart_dart2js.yaml
- .github/workflows/dart_ddc.yaml
- .github/workflows/dart_vm.yaml
- .github/workflows/flutter_android.yaml
- .github/workflows/flutter_ios.yaml
- .github/workflows/flutter_vm.yaml
excludes flutter/dart sdk beta testing on PRs
> chore(repo): excludes flutter/dart sdk beta testing on PRs

- packages/logging_cloudwatch/amplify_logging_cloudwatch/example/lib/main.dart
- logger example app to sign-out user on main page
> chore(logging): logger example app to sign-out user on main page

- packages/logging_cloudwatch/amplify_logging_cloudwatch/example/macos/Runner.xcodeproj/project.pbxproj
- remove development team from macos runner
> chore(logging): remove development team from macos runner

- packages/analytics/amplify_analytics_pinpoint/example/backend/package-lock.json
Main-v0 babel vulnerability fix
> Main-v0 babel vulnerability fix

- packages/analytics/amplify_analytics_pinpoint/example/backend/package-lock.json
> chore: bump @babel/traverse

- packages/common/amplify_db_common/CHANGELOG.md
- packages/common/amplify_db_common/pubspec.yaml
> chore: bump amplify_db_common

- packages/amplify/amplify_flutter/CHANGELOG.md
- packages/amplify/amplify_flutter/pubspec.yaml
- packages/amplify_datastore/CHANGELOG.md
- packages/amplify_datastore/pubspec.yaml
- packages/amplify_datastore_plugin_interface/CHANGELOG.md
- packages/amplify_datastore_plugin_interface/pubspec.yaml
- packages/analytics/amplify_analytics_pinpoint/CHANGELOG.md
- packages/analytics/amplify_analytics_pinpoint/pubspec.yaml
- packages/api/amplify_api/CHANGELOG.md
- packages/api/amplify_api/pubspec.yaml
- packages/auth/amplify_auth_cognito/CHANGELOG.md
- packages/auth/amplify_auth_cognito/pubspec.yaml
- packages/authenticator/amplify_authenticator/pubspec.yaml
- packages/notifications/push/amplify_push_notifications/CHANGELOG.md
- packages/notifications/push/amplify_push_notifications/pubspec.yaml
- packages/notifications/push/amplify_push_notifications_pinpoint/CHANGELOG.md
- packages/notifications/push/amplify_push_notifications_pinpoint/pubspec.yaml
- packages/storage/amplify_storage_s3/CHANGELOG.md
- packages/storage/amplify_storage_s3/pubspec.yaml
Pub will not allow publishing x.y.1 if x.y.0 is not already published.
> chore: bump version back to 1.5.0

- packages/amplify_core/lib/src/config/amplify_plugin_config.dart
- packages/amplify_core/lib/src/state_machine/exception.dart
- packages/amplify_core/lib/src/types/models/auth_rule.dart
- packages/analytics/amplify_analytics_pinpoint_dart/lib/src/impl/flutter_provider_interfaces/legacy_native_data_provider.dart
- packages/smithy/smithy/lib/src/types/timestamp.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/database/transfer_record.dart
- packages/worker_bee/worker_bee/lib/src/common.dart
> chore(repo): fix beta lints issues

- packages/amplify/amplify_flutter/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/analytics/amplify_analytics_pinpoint/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/api/amplify_api/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/auth/amplify_auth_cognito/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/authenticator/amplify_authenticator/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/authenticator/amplify_authenticator_test/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/storage/amplify_storage_s3/example/macos/Flutter/GeneratedPluginRegistrant.swift
updated generated swift files across multiple packages.
> chore: updated generated swift files

- .github/dependabot.yaml
- .github/workflows/amplify_logging_cloudwatch.yaml
- .github/workflows/amplify_logging_cloudwatch_example.yaml
- .github/workflows/aws_logging_cloudwatch.yaml
- packages/amplify_core/lib/amplify_core.dart
- packages/amplify_core/lib/src/category/amplify_categories.dart
- packages/amplify_core/lib/src/category/amplify_logging_category.dart
- packages/amplify_core/lib/src/plugin/amplify_logging_plugin_interface.dart
- packages/amplify_core/lib/src/plugin/amplify_plugin_key.dart
- packages/amplify_core/lib/src/types/logging/logger.dart
- packages/logging_cloudwatch/amplify_logging_cloudwatch/pubspec.yaml
- add a new logging category
- add a new logging plugin interface
- add a new logger interface
> feat(logging): add a new logging category and plugin interface

- packages/amplify_core/CHANGELOG.md
- packages/amplify_core/lib/src/version.dart
- packages/amplify_core/pubspec.yaml
- packages/amplify_lints/CHANGELOG.md
- packages/amplify_lints/pubspec.yaml
- packages/analytics/amplify_analytics_pinpoint/CHANGELOG.md
- packages/analytics/amplify_analytics_pinpoint/pubspec.yaml
- packages/analytics/amplify_analytics_pinpoint_dart/CHANGELOG.md
- packages/analytics/amplify_analytics_pinpoint_dart/lib/src/version.dart
- packages/analytics/amplify_analytics_pinpoint_dart/pubspec.yaml
- packages/api/amplify_api/CHANGELOG.md
- packages/api/amplify_api/pubspec.yaml
- packages/auth/amplify_auth_cognito_dart/CHANGELOG.md
- packages/auth/amplify_auth_cognito_dart/pubspec.yaml
- packages/authenticator/amplify_authenticator/CHANGELOG.md
- packages/authenticator/amplify_authenticator/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/authenticator/amplify_authenticator/lib/src/version.dart
- packages/authenticator/amplify_authenticator/pubspec.yaml
- packages/secure_storage/amplify_secure_storage_dart/CHANGELOG.md
- packages/secure_storage/amplify_secure_storage_dart/pubspec.yaml
- packages/smithy/smithy/CHANGELOG.md
- packages/smithy/smithy/pubspec.yaml
- packages/storage/amplify_storage_s3_dart/CHANGELOG.md
- packages/storage/amplify_storage_s3_dart/pubspec.yaml
- packages/worker_bee/worker_bee/CHANGELOG.md
- packages/worker_bee/worker_bee/pubspec.yaml
- packages/worker_bee/worker_bee_builder/CHANGELOG.md
- packages/worker_bee/worker_bee_builder/pubspec.yaml
> Chore: cherry pick stable to main: 1.6.1

- packages/aws_common/test/http/bad_certificate_test.dart
- Adds a unit test for an expired cert
> test: add a test for an expired cert

- packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_phone_field.dart
- packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart
- packages/authenticator/amplify_authenticator/lib/src/utils/validators.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_in_form_field.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/phone_number_field.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/sign_up_form_field.dart
- packages/authenticator/amplify_authenticator/test/sign_up_form_test.dart
This reverts commit eb6e68b1e098f7103b3a6e68a319a47be8815122.
> chore: Revert "fix(authenticator): required phone number validator (#4106)"

- packages/authenticator/amplify_authenticator/example/integration_test/sign_in_force_new_password_test.dart
- packages/authenticator/amplify_authenticator/example/integration_test/sign_in_mfa_sms_test.dart
- packages/authenticator/amplify_authenticator/example/integration_test/sign_in_with_phone_test.dart
- packages/authenticator/amplify_authenticator/example/integration_test/sign_up_with_phone_test.dart
- packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_phone_field.dart
- packages/authenticator/amplify_authenticator_test/lib/src/pages/authenticator_page.dart
Fix for missing keys on the authenticators country selector. 
> chore(authenticator): added missing widget keys

- packages/auth/amplify_auth_cognito_dart/lib/src/platform/macos_bindings.g.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/cupertino/security.bindings.g.dart
- packages/smithy/goldens/lib/restJson1/lib/src/rest_json_protocol/operation/http_request_with_labels_and_timestamp_format_operation.dart
- packages/smithy/goldens/lib/restJson1/lib/src/rest_json_protocol/operation/malformed_content_type_without_body_empty_input_operation.dart
- packages/smithy/goldens/lib/restXml/lib/src/rest_xml_protocol/model/http_request_with_labels_and_timestamp_format_input.dart
- packages/smithy/goldens/lib/restXml/lib/src/rest_xml_protocol/operation/http_request_with_labels_and_timestamp_format_operation.dart
- packages/smithy/goldens/lib2/restJson1/lib/src/rest_json_protocol/operation/http_request_with_labels_and_timestamp_format_operation.dart
- packages/smithy/goldens/lib2/restJson1/lib/src/rest_json_protocol/operation/malformed_content_type_without_body_empty_input_operation.dart
- packages/smithy/goldens/lib2/restXml/lib/src/rest_xml_protocol/model/http_request_with_labels_and_timestamp_format_input.dart
- packages/smithy/goldens/lib2/restXml/lib/src/rest_xml_protocol/operation/http_request_with_labels_and_timestamp_format_operation.dart
Ran dart format to fix CI tests
> chore: ran dart format

- packages/smithy/goldens/lib/awsJson1_0/pubspec.yaml
- packages/smithy/goldens/lib/awsJson1_1/pubspec.yaml
- packages/smithy/goldens/lib/awsQuery/pubspec.yaml
- packages/smithy/goldens/lib/ec2Query/pubspec.yaml
- packages/smithy/goldens/lib/restJson1/lib/src/rest_json_protocol/operation/http_request_with_labels_and_timestamp_format_operation.dart
- packages/smithy/goldens/lib/restJson1/lib/src/rest_json_protocol/operation/malformed_content_type_without_body_empty_input_operation.dart
- packages/smithy/goldens/lib/restJson1/pubspec.yaml
- packages/smithy/goldens/lib/restXml/lib/src/rest_xml_protocol/model/http_request_with_labels_and_timestamp_format_input.dart
- packages/smithy/goldens/lib/restXml/lib/src/rest_xml_protocol/operation/http_request_with_labels_and_timestamp_format_operation.dart
- packages/smithy/goldens/lib/restXml/pubspec.yaml
- packages/smithy/goldens/lib/restXmlWithNamespace/pubspec.yaml
- packages/smithy/goldens/lib2/awsJson1_0/pubspec.yaml
- packages/smithy/goldens/lib2/awsJson1_1/pubspec.yaml
- packages/smithy/goldens/lib2/awsQuery/pubspec.yaml
- packages/smithy/goldens/lib2/custom/pubspec.yaml
- packages/smithy/goldens/lib2/ec2Query/pubspec.yaml
- packages/smithy/goldens/lib2/restJson1/lib/src/rest_json_protocol/operation/http_request_with_labels_and_timestamp_format_operation.dart
- packages/smithy/goldens/lib2/restJson1/lib/src/rest_json_protocol/operation/malformed_content_type_without_body_empty_input_operation.dart
- packages/smithy/goldens/lib2/restJson1/pubspec.yaml
- packages/smithy/goldens/lib2/restXml/lib/src/rest_xml_protocol/model/http_request_with_labels_and_timestamp_format_input.dart
- packages/smithy/goldens/lib2/restXml/lib/src/rest_xml_protocol/operation/http_request_with_labels_and_timestamp_format_operation.dart
- packages/smithy/goldens/lib2/restXml/pubspec.yaml
- packages/smithy/goldens/lib2/restXmlWithNamespace/pubspec.yaml
- packages/test/amplify_integration_test/pubspec.yaml
- packages/test/pub_server/pubspec.yaml
- run aft constraints apply to update dependancy versions based on pubspec.yaml 
> chore(deps): run aft constraints apply

- build-support/build_canary.sh
- updated the canary build script in order to fit the change in `minSdk` build.gradle file in flutter beta
> chore: update canary

- packages/auth/amplify_auth_cognito/example/tool/VerifyAuthChallengeLambda/src/yarn.lock
- update axios version to latest in response to [the dependabot alert](https://github.com/aws-amplify/amplify-flutter/security/dependabot/21)
> chore(deps): update auth example app deps for verify auth challenge

- packages/auth/amplify_auth_cognito/example/integration_test/sign_out_test.dart
- packages/auth/amplify_auth_cognito/example/pubspec.yaml
- packages/auth/amplify_auth_cognito_dart/example/pubspec.yaml
Bumps `checks` to ^0.3.0 to resolve failing beta tests
> chore: bump `checks` to ^0.3.0

- .github/workflows/e2e_web.yaml
Missed a runner. Should be using ubuntu-latest. 
> chore(workflows): E2E Web Use ubuntu-latest

- packages/amplify_core/lib/amplify_core.dart
- packages/amplify_core/lib/src/category/amplify_storage_category.dart
- packages/amplify_core/lib/src/plugin/amplify_storage_plugin_interface.dart
- packages/amplify_core/lib/src/types/storage/download_data_options.dart
- packages/amplify_core/lib/src/types/storage/download_file_options.dart
- packages/amplify_core/lib/src/types/storage/get_properties_options.dart
- packages/amplify_core/lib/src/types/storage/get_url_options.dart
- packages/amplify_core/lib/src/types/storage/list_options.dart
- packages/amplify_core/lib/src/types/storage/remove_many_options.dart
- packages/amplify_core/lib/src/types/storage/remove_options.dart
- packages/amplify_core/lib/src/types/storage/storage_item.dart
- packages/amplify_core/lib/src/types/storage/upload_data_options.dart
- packages/amplify_core/lib/src/types/storage/upload_data_request.dart
- packages/amplify_core/lib/src/types/storage/upload_file_options.dart
- packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart
- packages/storage/amplify_storage_s3_dart/lib/src/model/s3_item.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart
- packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart
- packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
- packages/storage/amplify_storage_s3_dart/test/test_utils/test_path_resolver.dart
> feat: Gen 2 Upload APIs

- packages/amplify_core/lib/src/types/storage/storage_path.dart
- packages/amplify_core/lib/src/types/storage/storage_path_with_identity_id.dart
- packages/storage/amplify_storage_s3_dart/lib/src/path_resolver/s3_path_resolver.dart
- packages/storage/amplify_storage_s3_dart/test/path_resolver/path_resolver_test.dart
> chore: refactor StoragePath

- packages/auth/amplify_auth_cognito/CHANGELOG.md
- packages/auth/amplify_auth_cognito/pubspec.yaml
- packages/auth/amplify_auth_cognito_dart/CHANGELOG.md
- packages/auth/amplify_auth_cognito_dart/pubspec.yaml
Cherry picks version bump commit from stable
> chore(version): cherry pick Bump version

- .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
- Update bug report to make repro steps required and update flutter/amplify versions
> chore: Update BUG-REPORT.yaml

- packages/analytics/amplify_analytics_pinpoint/CHANGELOG.md
- packages/analytics/amplify_analytics_pinpoint/pubspec.yaml
- packages/authenticator/amplify_authenticator/CHANGELOG.md
- packages/authenticator/amplify_authenticator/lib/src/version.dart
- packages/authenticator/amplify_authenticator/pubspec.yaml
- pubspec.yaml
- fix: correct package_info_plus version constraint
> chore(version): Version bump

- packages/auth/amplify_auth_cognito_dart/lib/src/asf/asf_device_info_collector.windows.dart
- packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/win32/data_protection.dart
- ignore use of deprecated members from win32
> chore(auth): ignore use of deprecated members

- packages/amplify_core/lib/src/types/analytics/analytics/analytics_event.dart
- packages/amplify_core/lib/src/types/analytics/analytics/custom_properties.dart
- packages/amplify_core/lib/src/types/analytics/analytics/user_profile.dart
- packages/amplify_core/lib/src/types/analytics/analytics/user_profile_location.dart
- remove analytics apis that were marked as Deprecated
> chore(analytics)!: remove deprecated apis

- packages/authenticator/amplify_authenticator/lib/src/l10n/auth_strings_resolver.dart
- packages/authenticator/amplify_authenticator/lib/src/l10n/dial_code_resolver.dart
- remove authenticator deprecated apis
> chore(authenticator)!: remove deprecated apis

- packages/amplify_core/lib/src/amplify_class.dart
- packages/amplify_core/test/amplify_class_test.dart
- packages/auth/amplify_auth_cognito/example/integration_test/sign_out_test.dart
- packages/auth/amplify_auth_cognito_dart/example/web/components/app_component.dart
- packages/authenticator/amplify_authenticator/lib/amplify_authenticator.dart
- packages/authenticator/amplify_authenticator/lib/src/services/amplify_auth_service.dart
- packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart
- make make asyncConfig api internal
> chore(core)!: make asyncConfig api internal

- packages/amplify_core/lib/src/types/query/query_sort.dart
Removes try/catch fallback for toJson method. 
> chore(core)!: removed toJson fallback

- packages/aws_common/CHANGELOG.md
- packages/aws_common/lib/src/io/aws_file_platform_html.dart
- packages/aws_common/pubspec.yaml
- packages/aws_common/test/io/aws_file_html_test.dart
- packages/secure_storage/amplify_secure_storage/CHANGELOG.md
- packages/secure_storage/amplify_secure_storage/ios/Resources/PrivacyInfo.xcprivacy
- packages/secure_storage/amplify_secure_storage/ios/amplify_secure_storage.podspec
- packages/secure_storage/amplify_secure_storage/macos/Resources/PrivacyInfo.xcprivacy
- packages/secure_storage/amplify_secure_storage/macos/amplify_secure_storage.podspec
- packages/secure_storage/amplify_secure_storage/pubspec.yaml
- fix: properly handle 16-bit code units ([#4717](https://github.com/aws-amplify/amplify-flutter/pull/4717))
- Add Apple privacy manifest file ([#4794](https://github.com/aws-amplify/amplify-flutter/pull/4794))
> chore(version): bump version and update change logs

- packages/aws_common/CHANGELOG.md
- packages/aws_common/pubspec.yaml
- packages/secure_storage/amplify_secure_storage/CHANGELOG.md
- packages/secure_storage/amplify_secure_storage/pubspec.yaml
> chore(version): cherry pick version bump

- packages/aws_common/CHANGELOG.md
- packages/aws_common/pubspec.yaml
- packages/secure_storage/amplify_secure_storage/CHANGELOG.md
- packages/secure_storage/amplify_secure_storage/pubspec.yaml
>  chore(version): cherry pick version bump

- packages/amplify_datastore/ios/Classes/FlutterApiPlugin.swift
- packages/amplify_datastore/ios/Classes/api/GraphQLRequest+Extension.swift
- packages/amplify_datastore/ios/Classes/api/GraphQLResponse+Decode.swift
- packages/amplify_datastore/ios/Classes/api/Publisher+Extension.swift
> [datastore-spm] some code cleanup

- packages/analytics/amplify_analytics_pinpoint/example/integration_test/no_unauth_test.dart
- Updates analytics tests to pass on flutter beta
Analytics tests are failing on flutter beta. The way some errors are raised during tests seems to have changed. The errors that are raised are expected and should not result in a failing test. See https://github.com/aws-amplify/amplify-flutter/pull/4835/files#diff-58d82beff25c137fdc5c6da376f90837fdd03bfd88e104430b2f7d5340fb98b4R54 for more info.
> chore: ignore errors that are not the result of `Amplify.configure()`

- packages/amplify_datastore/example/lib/queries_display_widgets.dart
- packages/authenticator/amplify_authenticator/lib/src/widgets/social/social_button.dart
- packages/storage/amplify_storage_s3/example/lib/main.dart
- ignore MaterialStateProperty deprecation warnings
> chore: ignore MaterialStateProperty warnings

- packages/common/amplify_db_common_dart/pubspec.yaml
- pubspec.yaml
*Issue #, if available:* #4874
- set upper bound limit for sqlite version to fix ci build failures
> fix(common): set upper bound limit for sqlite version to fix ci build failures

- CONTRIBUTING.md
https://github.com/aws-amplify/amplify-flutter/issues/5013
> chore: update expired link

- packages/amplify_core/test/config/amplify_outputs_mapping/amplify_outputs_mapping_test.dart
- packages/amplify_core/test/config/amplify_outputs_mapping/app/package-lock.json
- packages/amplify_core/test/config/amplify_outputs_mapping/app/package.json
- packages/amplify_core/test/config/amplify_outputs_mapping/data/amplifyconfiguration.g.dart
- Updates the gen2 version used in tests
- regenerate the configs used in tests
- remove workarounds that are no longer needed
> chore: update gen2 version and config mapping tests

- packages/amplify_core/lib/src/config/amplify_outputs/auth/auth_outputs.g.dart
- packages/amplify_core/lib/src/config/amplify_outputs/auth/oauth_outputs.dart
- packages/amplify_core/lib/src/config/amplify_outputs/auth/oauth_outputs.g.dart
- packages/amplify_core/lib/src/config/auth/auth_config.dart
- packages/amplify_core/test/config/amplify_outputs_mapping/amplify_outputs_mapping_test.dart
This PR fixes a few items in the oAuth Outputs:
- add signInUri and signOutUri
- rename signInUriUriQueryParameters and signOutUriQueryParameters
- regenerate files
> chore: fix oauth outputs

- packages/analytics/amplify_analytics_pinpoint/example/backend/package-lock.json
-Updating dependency "braces" to fix vulnerability
> chore(analytics): updated dependency vulnerability

- infra/pnpm-lock.yaml
- Updates infra deps to resolve https://github.com/aws-amplify/amplify-flutter/security/dependabot/25
> chore: update infra package lockfile

- packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart
Adding unit tests for s3 list delimiter changes
> chore(storage): changing storage_s3_service_test to reflect delim changes

- packages/auth/amplify_auth_cognito_test/test/plugin/remember_device_test.dart
Added unit test suite for `rememberDevice` API
> Chore: rememberDevice API Unit Test suite

- infra-gen2/tool/deploy_gen2.dart
Allows a single category to be specified when running the deploy script.
> chore(infra): add arg to specify category

- packages/api/amplify_api_dart/test/graphql_test.dart
- packages/api/amplify_api_dart/test/plugin_configuration_test.dart
- packages/api/amplify_api_dart/test/rest_methods_test.dart
- packages/api/amplify_api_dart/test/test_data/fake_amplify_configuration.dart
- packages/api/amplify_api_dart/test/test_data/fake_amplify_configuration_iam_with_api_key.dart
- packages/auth/amplify_auth_cognito_test/lib/common/mock_config.dart
- packages/auth/amplify_auth_cognito_test/test/flows/hostedui/hosted_ui_platform_io_test.dart
- packages/auth/amplify_auth_cognito_test/test/flows/hostedui/hosted_ui_platform_test.dart
- packages/auth/amplify_auth_cognito_test/test/flows/srp/srp_device_password_verifier_worker_test.dart
- packages/auth/amplify_auth_cognito_test/test/flows/srp/srp_password_verifier_worker_test.dart
- packages/auth/amplify_auth_cognito_test/test/plugin/sign_out_test.dart
- packages/auth/amplify_auth_cognito_test/test/state/configuration_state_machine_test.dart
- packages/auth/amplify_auth_cognito_test/test/state/fetch_auth_session_state_machine_test.dart
- packages/auth/amplify_auth_cognito_test/test/state/hosted_ui_state_machine_test.dart
- packages/auth/amplify_auth_cognito_test/test/state/sign_in_state_machine_test.dart
- packages/notifications/push/amplify_push_notifications/test/amplify_push_notifications_impl_test.dart
- packages/notifications/push/amplify_push_notifications/test/test_data/fake_amplify_configuration.dart
- packages/notifications/push/amplify_push_notifications/test/test_data/fake_defective_configuration.dart
- update unit tests to use Amplify Gen 2 config
> chore(test): use Amplify Gen 2 config in unit tests

- packages/auth/amplify_auth_cognito/example/integration_test/native_auth_bridge_test.dart
- add testUrlScheme back to tests
> chore: add testUrlScheme back to test

- packages/analytics/amplify_analytics_pinpoint/pubspec.yaml
- packages/authenticator/amplify_authenticator/pubspec.yaml
- pubspec.yaml
- https://github.com/aws-amplify/amplify-flutter/issues/5255
> chore(dependencies): bump package_info_plus

- packages/authenticator/amplify_authenticator/example/integration_test/sign_in_mfa_sms_totp_test.dart
- packages/authenticator/amplify_authenticator/example/integration_test/sign_in_mfa_totp_test.dart
- Fix failing tests in the authenticator package
> chore: update authenticator tests

- actions/pubspec.yaml
- actions/test/node/interop_test.dart
- actions/test/node/process_manager_test.dart
- packages/aft/pubspec.yaml
- packages/aft/test/config/config_loader_test.dart
> chore(bump): checks package

- infra-gen2/backends/api/api-multi-auth/amplify/data/resource.ts
Extends to API key expiration to the previous duration of 365.
> chore(infra): Extend API key expiration

- .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
- Update issue template to include Gen 2 and update flutter and amplify flutter versions.
> chore: update issue template

- packages/amplify_datastore/android/build.gradle
- packages/notifications/push/amplify_push_notifications/android/build.gradle
Part of #4173 
Updated Amplify Android to 2.21.1
> chore(deps): Amplify Android 2.21.1

- infra-gen2/package-lock.json
Fixes the following error when running `npm i` within the infra gen 2 project. 
`npm ERR! Cannot read properties of undefined (reading 'extraneous')`
> chore(infra): regen lock file

- infra-gen2/backends/storage/main/amplify/backend.ts
- infra-gen2/backends/storage/main/amplify/storage/resource.ts
updated resource.ts and backend.ts for multiple buckets in the infra-gen2 directory
> Multi bucket infra update

- packages/aft/test/version_bump/data/repo_snapshot/packages/aws_common/pubspec.yaml
- packages/aft/test/version_bump/data/repo_snapshot/packages/notifications/push/amplify_push_notifications/pubspec.yaml
- packages/aws_common/pubspec.yaml
- packages/aws_common/test/config/file_location_test.dart
- packages/aws_common/tool/generate_tests.dart
- packages/notifications/push/amplify_push_notifications/pubspec.yaml
- packages/notifications/push/amplify_push_notifications/test/amplify_push_notifications_impl_test.dart
- packages/notifications/push/amplify_push_notifications/test/push_notification_flutter_api_test.dart
Updated os_detect to version 2.0.2 to account for breaking changes.
> chore(common,notifications): update os_detect to 2.0.2

- infra/pnpm-lock.yaml
https://github.com/aws-amplify/amplify-flutter/security/dependabot/35
Updated micromatch version to avoid a vulnerability.
> chore(infra): Updated micromatch version

- infra-gen2/package-lock.json
- infra-gen2/package.json
updated amplify-backend and amplify-backend-cli devDependencies in infra-gen2
> Chore(infra): update amplify dependencies

- README.md
Updating the amplify-flutter readme to Gen 2 instructions 
> chore(main): readme update

- .github/dependency-review-config.yml
- actions/package.json
- actions/pnpm-lock.yaml
- infra-gen2/package-lock.json
- infra-gen2/package.json
- infra/package.json
- infra/pnpm-lock.yaml
Updated octokit via githib
Updated aws-cdk-lib
> chore(): bumped packages for security vulnerabilities

- .github/workflows/issue_comment.yml
- .github/workflows/issue_opened.yml
Added Slack Webhooks for Github issues opened and Github issue comments
> chore(): Added Slack webhooks
