.circleci/test_all_plugins.sh
* Add `set -o pipefail` to test script, so the return value of `flutter test` is properly read by the script.
=> ci: fix flutter test workflow passing in circleci when tests fail

packages/amplify_core/android/build.gradle, packages/amplify_core/android/src/main/kotlin/com/amazonaws/amplify/amplify_core/Core.kt, packages/amplify_core/ios/Classes/SwiftCore.swift, packages/amplify_core/ios/amplify_core.podspec, packages/amplify_core/lib/amplify_core.dart, packages/amplify_core_plugin_interface/lib/amplify_core_plugin_interface.dart, packages/amplify_core_plugin_interface/lib/method_channel_amplify.dart, packages/amplify_storage_s3/ios/amplify_storage_s3.podspec
I'm concerned that the AWSPluginsCore version won't be set properly for developers. 
I set the following in podspec but am unsure what will happpen: 
s.dependency 'AWSPluginsCore', '1.1.1'
If the user had already installed AWSPluginsCore 
=> UserAgents

packages/amplify_auth_cognito/example/ios/Podfile
Removed a duplicate `platform :ios, '11.0'` line in the example app Podfile.
=> fix(amplify_auth_cognito): fix example app Podfile

README.md
Currently, it is necessary to use a custom version of the Amplify CLI, in order to use Flutter:
```console
npm install -g @aws-amplify/cli@flutter-preview
```
The `README.md` contained a link to the _generic_ CLI installation instructions, which won't work, here, right now.
Resolves: https://github.com/aws-amplify/amplify-flutter/issues/126
=> fix: update incorrect link in readme

packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/model/FlutterModelFieldType.kt, packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePluginTest.kt, packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/SchemaData.kt, packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/types/query/QueryPredicateBuilderTest.kt, packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/types/query/QuerySortBuilderTest.kt, packages/amplify_datastore/lib/method_channel_datastore.dart
- fixed android java.lang.ClassNotFoundException: int bug in the logs
- fixed android unit tests to use “post.id” instead of “id”
- deactivated call to datastore configure method (waiting of observe api changes for Android)
=> fix(amplify_datastore): android bug + unit tests

packages/amplify_storage_s3/android/build.gradle, packages/amplify_storage_s3/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/types/FlutterDownloadFileRequest.kt, packages/amplify_storage_s3/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/types/FlutterGetUrlRequest.kt, packages/amplify_storage_s3/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/types/FlutterListRequest.kt, packages/amplify_storage_s3/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/types/FlutterRemoveRequest.kt, packages/amplify_storage_s3/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/types/FlutterUploadFileRequest.kt, packages/amplify_storage_s3/example/android/app/build.gradle
With this change, the whole library builds in android and the tests are successful.
PS: `minSdkVersion` is increased because of increasing >64K methods limit. 
=> Fix(amplify_storage_s3): Compile errors after upgrading amplify-android library

packages/amplify_analytics_pinpoint/android/build.gradle, packages/amplify_auth_cognito/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/amplify_storage_s3/android/build.gradle
So that we get latest and greatest of android without any release. This will be reverted to use fixed/pinned versions in the future.
=> Upgrade android to use loose version numbers

packages/amplify_datastore/example/lib/main.dart, packages/amplify_datastore/lib/amplify_datastore.dart
Makes hub event listener a static member of the plugin.
=> fix(amplify_datastore) static hub listener

packages/amplify_datastore/example/lib/main.dart
=> fix(amplify_datastore) use hub event 'ready' before querying

packages/amplify_core/android/build.gradle, packages/amplify_core/android/src/main/kotlin/com/amazonaws/amplify/amplify_core/Core.kt, packages/amplify_core/ios/Classes/SwiftCore.swift, packages/amplify_core/ios/amplify_core.podspec, packages/amplify_datastore/android/build.gradle, packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt, packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift, packages/amplify_datastore/ios/amplify_datastore.podspec
This is intended as a workaround until we have a GraphQL API category in flutter which would be added by the flutter users. This whole thing will go away before GA.
=> chore(amplify_datastore): conditionally add API plugin if api configuration exists

packages/amplify_datastore/ios/Classes/types/model/FlutterSerializedModel.swift
Very small change to remove an unnecessary log line message in iOS that was spamming the log with: 
`Decoder Foundation.(unknown context at $7fff5407fe98).__JSONDecoder
`
=> fix(amplify_datastore) remove unnecessary ios logs

packages/amplify_datastore_plugin_interface/lib/src/types/temporal/datetime_parse.dart, packages/amplify_datastore_plugin_interface/lib/src/types/utils/parsers.dart, packages/amplify_datastore_plugin_interface/test/amplify_utility_test.dart
*Issue #, if available:* #241 
*Description of changes:* Handle optional nullable enum types in parser
=> fix(amplify_datastore): Handle optional nullable enum types in parser

.circleci/config.yml
Refer: https://circleci.com/docs/2.0/java-oom/
Refer: https://discuss.circleci.com/t/circleci-android-build-randomly-falls/29394
=> fix: prevent android test exhausting jvm memory

packages/amplify_api/ios/Classes/FlutterRestApi.swift
Quick fix to get operations to be removed on failed rest operations in iOS 
=> fix(amplify_api): Remove cancelled operations iOS

packages/amplify_datastore_plugin_interface/lib/src/types/utils/parsers.dart, packages/amplify_datastore_plugin_interface/test/amplify_utility_test.dart
*Issue #, if available:* #279
Tested on both iOS and Android
=> fix(amplify_datastore): Send null instead of empty string for nullable enum

README.md, example/lib/Pages/LandingPage.dart, example/lib/Views/ImageLineItem.dart, example/lib/Views/ImageUploader.dart, example/lib/Views/SignInView.dart, example/lib/Views/SignUpView.dart, example/lib/Views/UserView.dart, packages/amplify_analytics_pinpoint/example/lib/main.dart, packages/amplify_api/example/lib/graphql_api_view.dart, packages/amplify_api/example/lib/main.dart, packages/amplify_api/example/lib/rest_api_view.dart, packages/amplify_auth_cognito/example/lib/Widgets/ConfirmResetWidget.dart, packages/amplify_auth_cognito/example/lib/Widgets/ConfirmSignInWidget.dart, packages/amplify_auth_cognito/example/lib/Widgets/ConfirmSignUpWidget.dart, packages/amplify_auth_cognito/example/lib/Widgets/SignInWidget.dart, packages/amplify_auth_cognito/example/lib/Widgets/SignUpWidget.dart, packages/amplify_auth_cognito/example/lib/Widgets/UpdatePasswordWidget.dart, packages/amplify_auth_cognito/example/lib/main.dart, packages/amplify_datastore/example/lib/main.dart, packages/amplify_datastore/example/lib/save_model_widgets.dart, packages/amplify_storage_s3/example/lib/main.dart
`RaisedButton` https://api.flutter.dev/flutter/material/RaisedButton-class.html is obsolete. we should use `ElevatedButton` https://api.flutter.dev/flutter/material/ElevatedButton-class.html instead.
We should use `DO use collection literals when possible.`
https://dart.dev/guides/language/effective-dart/usage#do-use-collection-literals-when-possible
=> RaisedButton is obsolete

packages/amplify_datastore/example/lib/queries_display_widgets.dart
The `raisedButton` is obsolete. https://api.flutter.dev/flutter/material/RaisedButton-class.html
=> Added elevatedButton along with style

packages/amplify_flutter/lib/amplify.dart, packages/amplify_flutter/lib/amplify_hub.dart, packages/amplify_flutter/test/amplify_test.dart
*Issue #, if available:* Revert https://github.com/aws-amplify/amplify-flutter/pull/303
After discussing internally, we decided against adding this new API. Rather amplify will throw a new `AmplifyAlreadyConfiguredException` when customers try to configure Amplify again. The exception will be added in the next release.
=> chore(amplify_flutter): Revert isConfigured in favor of throwing specific exception in future

packages/amplify_auth_plugin_interface/lib/src/SignUp/SignUpOptions.dart
Changes interface to only allows Strings for user attribute on signup. This accomodates amplify-android signUp API, and avoids the need to either expand our API surface or do extensive parsing on platform side. Custom attributes that are 'Numbers' will still be created as such, and will still be parsed as such when customers request them.
=> fix(amplify_auth_cognito): force user attribute to be string

packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt
This PR makes Android throw SessionExpiredException instead of SignedOutException, when session fails. This creates consistency with amplify-ios (and also makes logical sense).
=> fix(amplify_auth_cognito): android throws SessionExpiredException

packages/amplify_datastore/ios/Classes/types/model/FlutterModelFieldType.swift
*Issue #, if available:* fixes: https://github.com/aws-amplify/amplify-flutter/issues/363
*Description of changes:* Save enum lists properly in iOS
=> fix(amplify_datastore): Save enum lists properly in iOS

packages/amplify_analytics_pinpoint/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsBridge.kt, packages/amplify_analytics_pinpoint/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsBuilder.kt, packages/amplify_analytics_pinpoint/android/src/test/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPluginTest.kt, packages/amplify_analytics_pinpoint/example/ios/unit_tests/AnalyticsUnitTests.swift, packages/amplify_analytics_pinpoint/example/lib/main.dart, packages/amplify_analytics_pinpoint/ios/Classes/AmplifyAnalyticsBuilder.swift, packages/amplify_analytics_pinpoint/ios/Classes/FlutterAnalytics.swift, packages/amplify_analytics_pinpoint/lib/method_channel_amplify.dart, packages/amplify_analytics_plugin_interface/lib/src/Analytics/AnalyticsProperties.dart, packages/amplify_analytics_plugin_interface/lib/src/Analytics/AnalyticsUserProfile.dart
Fix sending of AnalyticsProperties in iOS 
Before iOS was converting Dart maps representing AnalyticsProperties to blank maps every time. 
=> fix(amplify_analytics): fix analyticsProperties

packages/amplify_analytics_pinpoint/android/build.gradle, packages/amplify_api/android/build.gradle, packages/amplify_auth_cognito/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/amplify_flutter/android/build.gradle, packages/amplify_storage_s3/android/build.gradle
Bumps amplify-android version to 1.16.13.
=> chore: bump amplify-android version to 1.16.13

packages/amplify_flutter/lib/amplify.dart, packages/amplify_flutter/test/amplify_test.dart
*Issue #, if available:* fixes #412
*Description of changes:* Add a new API that customers can call to check if Amplify is already configured rather than having to catch a specific `AmplifyAlreadyConfiguredException`
=> chore(amplify_flutter): Add isConfigured API to Amplify

packages/amplify_analytics_pinpoint/pubspec.yaml, packages/amplify_api/pubspec.yaml, packages/amplify_auth_cognito/pubspec.yaml, packages/amplify_core/pubspec.yaml, packages/amplify_datastore/pubspec.yaml, packages/amplify_flutter/pubspec.yaml, packages/amplify_storage_s3/pubspec.yaml
Update  plugin_platform_interface: ^1.0.1 -> ^2.0.0
To fix dependency conflicts with Firebase
*Issue #, if available:* #434
#461 
Upgrade plugin platform interface to 2.0.0 to fix pubspec version conflicts with Firebase and other 3rd party dependencies. 
=> fix(amplify): upgrade plugin_platform_interface

packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthErrorHandler.kt, packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthErrorHandlerTest.kt
*Issue #, if available:* #513
- Add additional case for `LimitExceededException` from cognitoidentityprovider in AuthErrorHandler
- Add unit test for the new case
The issue can be reproduced by calling `Amplify.Auth.resetPassword()` multiple times on Android. The issue is not present on iOS for this exception.
Prior to this PR we can see the code will throw an `AuthException` instead of a `LimitExceededException`, but the details of the error message do indicate that it is a LimitExceededException.
With the changes in this PR the same code will throw a `LimitExceededException`.
=> fix: handle LimitExceededException on Android

packages/amplify_analytics_pinpoint/example/ios/unit_tests/AnalyticsUnitTests.swift, packages/amplify_analytics_pinpoint/test/amplify_analytics_pinpoint_test.dart
- chore #162 
Updates and adds some unit tests for analytics, both in dart and iOS. For dart side, adds assertions for future completion, assertions for method channel serialization and some cases for enable/disable. On iOS unit tests, just adds trivial enable/disable cases.
=> Analytics chore 162 tests

packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterSignInResult.kt, packages/amplify_auth_cognito/lib/method_channel_auth_cognito.dart
See details in issue #544
I'm submitting this mostly as an FYI since I was able to track down the issue(s), which span both amplify-flutter and amplify-ios. I'm not familiar with these code bases (or Swift for that matter), but I do know that these two changes resolve the issue. What I don't know is if these changes will break other use cases. So, let me know if there's another way of resolving this or additional changes needed.
There is a dependent fix in `amplify-ios` that is needed in order for this change to resolve the issue:
https://github.com/aws-amplify/amplify-ios/pull/1190
The problem here appears to be that `res["nextStep"]["additionalInfo"]` is never a String because it has already been json decoded into an object.
Also, there is one other place in the code …
=> fix(amplify_auth_cognito): Pass additionalInfo to AuthNextSignUpStep

packages/amplify_auth_cognito/ios/Classes/AuthCognitoBridge.swift
Issue: #577 
Description of changes: fix: address issue #577 by changing custom iOS error to AWSCognitoAuthError.userNotConfirmed so that iOS throws UserNotConfirmedException instead of more generic AuthError (like Android) when trying to signIn unconfirmed user
=> fix: address issue #577 by changing iOS error to UserNotConfirmedException

packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt, packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterUpdateUserAttributeResult.kt, packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPluginTest.kt, packages/amplify_auth_cognito/example/ios/unit_tests/amplify_auth_cognito_tests.swift, packages/amplify_auth_cognito/ios/Classes/FlutterFetchCognitoSessionResult.swift, packages/amplify_auth_cognito/ios/Classes/FlutterUpdateUserAttributeResult.swift
Fixes null-safety related auth issues found during testing.
=> fix(amplify_auth_cognito): fixes auth null safety issues

packages/amplify_api/lib/method_channel_api.dart, packages/amplify_auth_cognito/lib/amplify_auth_error_handling.dart, packages/amplify_auth_cognito/lib/method_channel_auth_cognito.dart, packages/amplify_datastore_plugin_interface/lib/src/types/models/model.dart, packages/amplify_datastore_plugin_interface/lib/src/types/temporal/temporal_date.dart, packages/amplify_datastore_plugin_interface/lib/src/types/temporal/temporal_datetime.dart, packages/amplify_datastore_plugin_interface/lib/src/types/temporal/temporal_time.dart, packages/amplify_datastore_plugin_interface/test/testData/Blog.dart, packages/amplify_datastore_plugin_interface/test/testData/Comment.dart, packages/amplify_datastore_plugin_interface/test/testData/ModelProvider.dart, packages/amplify_datastore_plugin_interface/test/testData/Post.dart, packages/amplify_datastore_plugin_interface/test/testData/PostAuthComplex.dart, packages/amplify_flutter/test/amplify_test.dart, packages/amplify_storage_s3/lib/method_channel_storage_s3.dart
Fix unit tests issues in Dart and remove redundant exception. 
=> Null safety master fixes pr

CONTRIBUTING.md, melos.yaml
*Issue #, if available:* N/A
- add `--no-pub` to integration tests so that `flutter pub get` is not run. `flutter pub get` will cause issues in our mono repo. Dependencies need to be installed with melos.
=> fix(tests): add --no-pub to integration tests

packages/amplify_analytics_pinpoint/android/build.gradle, packages/amplify_api/android/build.gradle, packages/amplify_auth_cognito/android/build.gradle, packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterConfirmSignInRequest.kt, packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyAuthCognitoPluginTest.kt, packages/amplify_auth_cognito/example/ios/unit_tests/amplify_auth_cognito_tests.swift, packages/amplify_auth_cognito/ios/Classes/FlutterConfirmSignInRequest.swift, packages/amplify_auth_cognito/lib/src/CognitoSignIn/CognitoConfirmSignInOptions.dart, packages/amplify_auth_cognito/test/amplify_auth_cognito_confirmSignIn_test.dart, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/amplify_flutter/android/build.gradle, packages/amplify_storage_s3/android/build.gradle
#576 
#598 
Adds userAttributes to CognitoConfirmSignInOptions. 
=> fix(amplify_auth_cognito): adds userAttributes to confirmSignIn

packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt
Fixes the issue with:
e: /Users//Development/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.2.0-nullsafety.0/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt: (45, 38): Type mismatch: inferred type is Map<String, Any> but Comparable<{Boolean & String}>? was expected
e: /Users//Development/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.2.0-nullsafety.0/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt: (45, 38): Type mismatch: inferred type is Map<String, Any> but Serializable? was expected
e: /Users//Development/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.2.0-nullsafety.0/android/src/main/kotlin/com/amazon …
=> fix(auth_auth_cognito): Type mismatch: inferred type

packages/amplify_analytics_pinpoint/ios/amplify_analytics_pinpoint.podspec, packages/amplify_api/ios/amplify_api.podspec, packages/amplify_auth_cognito/ios/amplify_auth_cognito.podspec, packages/amplify_datastore/ios/amplify_datastore.podspec, packages/amplify_flutter/ios/amplify_flutter.podspec, packages/amplify_storage_s3/ios/amplify_storage_s3.podspec
** Note: This PR should not be released until the next version of amplify-ios is released and the version number verified.**
Includes bug fix for amplify-ios Datastore.delete
=> fix: amplify-ios version bump ~> 1.11.0

packages/amplify_datastore/lib/types/DataStoreHubEvents/HubEventElement.dart, packages/amplify_datastore/lib/types/DataStoreHubEvents/HubEventElementWithMetadata.dart, packages/amplify_datastore/lib/types/DataStoreHubEvents/OutboxMutationEvent.dart, packages/amplify_datastore/test/amplify_datastore_stream_controller_test.dart, packages/amplify_datastore/test/outbox_mutation_event_test.dart, packages/amplify_datastore/test/resources/hub/outboxMutationEnqueuedEvent.json, packages/amplify_datastore/test/resources/hub/outboxMutationProcessedEvent.json
`_deleted` can be null on `HubEventWithMetadata`. This is by design, and is shared between both iOS and Android. Both platforms interpret this as being `false`.
- Default to `_deleted = false`.
- Refactor HubEvent/HubEventWithMetadata for better testing.
- Add unit tests.
- Prefer `.cast()` or plain `Map` instead of `Map.from` which creates a new Map.
=> bug(datastore): HubEvent null check

packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt, packages/amplify_core/android/src/main/kotlin/com/amazonaws/amplify/amplify_core/exception/ExceptionUtil.kt
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/675
- Remove use of TypeToken from FlutterFetchCognitoAuthSessionResult
- Remove use of TypeToken from ExceptionUtil
=> fix(Auth): Remove use of TypeToken

packages/amplify_datastore_plugin_interface/lib/src/types/utils/parsers.dart
Exception if decoding an null enum string, like the line below from `AllTypeOptionalModel` where `json['enumType']` is null.
- Make argument nullable
=> Fix enum string function

packages/amplify_api_plugin_interface/lib/src/GraphQL/GraphQLResponseError.dart, packages/amplify_api_plugin_interface/lib/src/util.dart
- Overrides the `toString` method on `GraphQLResponseError`
- Adds missing fields for use in the future (`locations`, `path`)... is `extensions` used by AppSync?
=> chore(api): Override `toString` on `GraphQLResponseError`

packages/amplify_analytics_pinpoint/android/build.gradle, packages/amplify_api/android/build.gradle, packages/amplify_auth_cognito/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/amplify_flutter/android/build.gradle, packages/amplify_storage_s3/android/build.gradle
Subscription timeout related issues:
#602 | #467 
Upgrade `amplify-android` to `1.20.1` to integrate the fix for subscription timeout issue on slow network [#1389](https://github.com/aws-amplify/amplify-android/pull/1389).
----
=> chore: upgrade amplify-android to 1.20.1

packages/amplify_api/example/integration_test/graph_ql_tests.dart, packages/amplify_api/example/integration_test/main_test.dart, packages/amplify_api/example/lib/graphql_api_view.dart, packages/amplify_api/example/lib/main.dart, packages/amplify_api/example/lib/rest_api_view.dart, packages/amplify_api/example/pubspec.yaml, packages/amplify_api/example/test_driver/integration_test.dart, packages/amplify_api/example/tool/add_api_request.json, packages/amplify_api/example/tool/provision_integration_test_resources.sh
Adds minimal integration test suite to api category. Here, it's just a GraphQL query along with related provisioning script.
There are also some changes to API example app to make it run with sound null safety.
=> chore(amplify_api): add GraphQL API integration tests

packages/amplify_datastore/example/integration_test/main_test.dart, packages/amplify_datastore/example/integration_test/query_test.dart, packages/amplify_datastore/example/integration_test/save_test.dart, packages/amplify_datastore/example/integration_test/utils/setup_utils.dart, packages/amplify_datastore/example/pubspec.yaml, packages/amplify_datastore/example/test_driver/integration_test.dart
- add basic integration tests for the datastore save/query
=> chore(datastore): add integration tests for datastore

example/pubspec.yaml, packages/amplify_analytics_pinpoint/CHANGELOG.md, packages/amplify_analytics_pinpoint/pubspec.yaml, packages/amplify_analytics_plugin_interface/CHANGELOG.md, packages/amplify_analytics_plugin_interface/pubspec.yaml, packages/amplify_api/CHANGELOG.md, packages/amplify_api/pubspec.yaml, packages/amplify_api_plugin_interface/CHANGELOG.md, packages/amplify_api_plugin_interface/pubspec.yaml, packages/amplify_auth_cognito/CHANGELOG.md, packages/amplify_auth_cognito/pubspec.yaml, packages/amplify_auth_plugin_interface/CHANGELOG.md, packages/amplify_auth_plugin_interface/pubspec.yaml, packages/amplify_core/CHANGELOG.md, packages/amplify_core/pubspec.yaml, packages/amplify_datastore/CHANGELOG.md, packages/amplify_datastore/pubspec.yaml, packages/amplify_datastore_plugin_interface/CHANGELOG.md, packages/amplify_datastore_plugin_interface/pubspec.yaml, packages/amplify_flutter/CHANGELOG.md, packages/amplify_flutter/lib/amplify.dart, packages/amplify_flutter/pubspec.yaml, packages/amplify_storage_plugin_interface/CHANGELOG.md, packages/amplify_storage_plugin_interface/pubspec.yaml, packages/amplify_storage_s3/CHANGELOG.md, packages/amplify_storage_s3/pubspec.yaml
Update Changelog 
Update Pubspec.yaml's to use 0.2.1
Update amplify.dart version method to return 0.2.1 string 
=> Release updates 0.2.1

packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt, packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/query/QueryOptionsBuilder.kt, packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/query/QueryPredicateBuilder.kt, packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/types/query/QueryPredicateBuilderTest.kt, packages/amplify_datastore/test/resources/query_predicate/relation_field_lookup.json
*Issue #, if available:* #444
1. Passing query predicate corresponding `modelSchema` to `QueryPredicateBuilder.fromSerialziedMap`
2. If predicate field is a nested model, replace it with the actual model field 
Note: the [second commit](https://github.com/aws-amplify/amplify-flutter/commit/22057609c7816d08fab5a74b56f09a8e61bb6d3c) in this PR presents the actual code change
e.g. run below query 
```dart
final res = await Amplify.DataStore.query(Post.classType,
where: Post.BLOG.eq("5eff14cf-9a67-4fe3-8457-11a30f5e3a86"));
print(res);
```
with schema
```graphql
type Post @model @key(name: "byBlog", fields: ["blogID"]) {
id: ID!
title: String!
rating: Int!
created: AWSDateTime
blogID: ID!
blog: Blog @connection(fields: ["blogID"])
comments: [Comment] …
```
=> fix(datastore): Query nested model causes column not found sql error

packages/amplify_analytics_pinpoint/android/src/main/AndroidManifest.xml, packages/amplify_analytics_pinpoint/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPlugin.kt, packages/amplify_analytics_pinpoint/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/EmptyActivity.kt, packages/amplify_analytics_pinpoint/ios/Classes/SwiftAmplifyAnalyticsPinpointPlugin.swift, packages/amplify_analytics_pinpoint/lib/amplify_analytics_pinpoint.dart, packages/amplify_analytics_pinpoint/lib/method_channel_amplify.dart, packages/amplify_analytics_plugin_interface/lib/amplify_analytics_plugin_interface.dart, packages/amplify_flutter/lib/method_channel_amplify.dart
- Internal ticket: P50379527
- Summary of issue:
The [AutoSessionTracker](https://github.com/aws-amplify/amplify-android/blob/main/aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AutoSessionTracker.java) in the Pinpoint plugin listens for lifecycle changes and starts and stops session tracking accordingly. It is registered during the call to `Amplify.configure`. In native Android apps, this call is made before launching the main activity and thus receives the initial onResume event, kicking off session tracking. However, in Flutter, the call to `Amplify.configure` is made sometime later. The initial onResume event is not received by the AutoSessionTracker, and no session tracking occurs.
The startSession/stopSession calls made by the …
=> bug(analytics): Force session start

packages/amplify_auth_cognito/android/build.gradle, packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt, packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthErrorHandler.kt, packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/base/AtomicResult.kt, packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/device/Device.kt, packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/device/DeviceHandler.kt, packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/base/AtomicResultTest.kt, packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/base/CoroutineTestRule.kt, packages/amplify_auth_cognito/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/device/DeviceHandlerTest.kt, packages/amplify_auth_cognito/example/ios/Runner.xcodeproj/project.pbxproj, packages/amplify_auth_cognito/example/ios/unit_tests/AtomicResultTests.swift, packages/amplify_auth_cognito/ios/Classes/Base/AtomicResult.swift, packages/amplify_auth_cognito/ios/Classes/Device/AWSAuthDevice+Codable.swift, packages/amplify_auth_cognito/ios/Classes/Device/DeviceHandler.swift, packages/amplify_auth_cognito/ios/Classes/SwiftAuthCognito.swift, packages/amplify_auth_cognito/lib/amplify_auth_cognito.dart, packages/amplify_auth_cognito/lib/amplify_auth_error_handling.dart, packages/amplify_auth_cognito/lib/method_channel_auth_cognito.dart, packages/amplify_auth_cognito/lib/src/CognitoDevice/cognito_device.dart, packages/amplify_auth_cognito/lib/src/types.dart, packages/amplify_auth_plugin_interface/lib/amplify_auth_plugin_interface.dart, packages/amplify_auth_plugin_interface/lib/src/Exceptions/AuthException.dart, packages/amplify_auth_plugin_interface/lib/src/Exceptions/device_not_tracked_exception.dart, packages/amplify_auth_plugin_interface/lib/src/Exceptions/invalid_user_pool_configuration_exception.dart, packages/amplify_auth_plugin_interface/lib/src/types.dart, packages/amplify_auth_plugin_interface/lib/src/types/auth_device.dart, packages/amplify_flutter/lib/categories/amplify_auth_category.dart
The following Devices API:
- `Amplify.Auth.rememberDevice`
- `Amplify.Auth.forgetDevice`
- `Amplify.Auth.fetchDevices`
This PR uses the escape hatch on Android to bring parity between the platforms. The long-term strategy is to change amplify-android for all users, so this marked as DRAFT in the meantime, although the changes needed will be very minor and the PR should be reviewed as-is.
=> feat(amplify_auth_cognito): Auth Devices API

packages/amplify_api/lib/method_channel_api.dart, packages/amplify_api/lib/src/graphql/graphql_request_factory.dart, packages/amplify_api/lib/src/graphql/graphql_response_decoder.dart, packages/amplify_api/test/amplify_api_graphql_helpers_test.dart, packages/amplify_api/test/amplify_api_query_test.dart, packages/amplify_api_plugin_interface/lib/src/GraphQL/GraphQLRequest.dart
*Problem Statement:*
Developers should be able to use types specified to the Model helpers when a response is returned by the API.
This provides a type safe experience when using the Model based helpers. The Dart compiler will recognize and enforce Model types. For example: 
Before: 
```Dart
Amplify.API.query<String>(request:  ModelQueries.get<String>(Blog.classType, id));
```
After:
```Dart
Amplify.API.query<Blog>(request: ModelQueries.get<Blog>(Blog.classType, id));
```
=> feat(amplify_api): GraphQL Response Decoding

packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/FlutterApiRequest.kt, packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/rest_api/FlutterRestApi.kt, packages/amplify_api/android/src/test/kotlin/com/amazonaws/amplify/amplify_api/AmplifyApiRestTest.kt
*Issue #, if available:* #612
*Description of changes:* In android, PUT, POST, and PATCH methods throw a fatal error if no body is included (iOS works fine) https://github.com/aws-amplify/amplify-android/issues/1355. This is because of okhttp3 library, underlying HTTP library for amplify-android. This PR smoothes that over by making it an API exception in android that will not crash the app.
Alternatively, this could be changed to just add a blank body in this scenario but that might have some unexpected behavior for customers if they are not aware. It could also have some handling in dart layer to make it consistent across platforms. However, I would rather not change the iOS behavior here to introduce an exception for something that does not currently throw one.
By submitting this pull …
=> fix(amplify_api): throw ApiException in android when PUT, POST, and PATCH REST requests have no body to prevent fatal error

packages/amplify_api/lib/src/graphql/graphql_request_factory.dart, packages/amplify_api/lib/src/graphql/model_queries_factory.dart, packages/amplify_api/lib/src/graphql/paginated_modelType_impl.dart, packages/amplify_api/lib/src/graphql/paginated_model_type_impl.dart, packages/amplify_api/lib/src/graphql/paginated_result_impl.dart, packages/amplify_api/test/amplify_api_graphql_helpers_test.dart, packages/amplify_api/test/amplify_api_query_test.dart, packages/amplify_api/test/graphql_helpers_test.dart, packages/amplify_api_plugin_interface/lib/src/types.dart, packages/amplify_api_plugin_interface/lib/src/types/pagination/paginated_modelType.dart, packages/amplify_api_plugin_interface/lib/src/types/pagination/paginated_model_type.dart, packages/amplify_api_plugin_interface/lib/src/types/pagination/paginated_result.dart
This adds `ModelQueries.list()`, allows for proper response decoding of PaginatedResults, and relevant unit tests.
=> feat(amplify_api): GraphQL Query Helper - List 

packages/amplify_api/lib/amplify_api.dart, packages/amplify_api/lib/model_mutations.dart, packages/amplify_api/lib/src/graphql/graphql_request_factory.dart, packages/amplify_api/lib/src/graphql/model_mutations_factory.dart, packages/amplify_api/test/amplify_api_mutate_test.dart, packages/amplify_api/test/graphql_helpers_test.dart
This adds `ModelMutations.create()` and relevant unit tests.
=> feat(amplify_api): GraphQL Mutate Helper - Create

packages/amplify_api/lib/model_mutations.dart, packages/amplify_api/lib/src/graphql/model_mutations_factory.dart, packages/amplify_api/test/amplify_api_mutate_test.dart, packages/amplify_api/test/graphql_helpers_test.dart
This adds `ModelMutations.update()` and relevant unit tests.
=> feat(amplify_api): GraphQL Mutate Helper - Update

packages/amplify_api/lib/model_mutations.dart, packages/amplify_api/lib/src/graphql/graphql_request_factory.dart, packages/amplify_api/lib/src/graphql/model_mutations_factory.dart, packages/amplify_api/lib/src/graphql/model_queries_factory.dart, packages/amplify_api/test/amplify_api_mutate_test.dart, packages/amplify_api/test/graphql_helpers_test.dart, packages/amplify_api_plugin_interface/lib/src/GraphQL/GraphQLHelpers.dart
This adds `ModelMutations.delete()` and relevant unit tests.
=> feat(amplify_api): GraphQL Mutate Helper - Delete

packages/amplify_api/example/integration_test/graph_ql_tests.dart, packages/amplify_api/example/integration_test/main_test.dart, packages/amplify_api/example/integration_test/resources/Blog.dart, packages/amplify_api/example/integration_test/resources/ModelProvider.dart, packages/amplify_api/example/pubspec.yaml, packages/amplify_api/lib/src/graphql/graphql_response_decoder.dart, packages/amplify_api/lib/src/graphql/model_mutations_factory.dart, packages/amplify_api/test/graphql_helpers_test.dart
This PR introduces integration tests to validate the GraphQL helpers against a real endpoint. Includes tests for: `get`, `list`, `create`, `update`, and `delete`
=> feat(amplify_api): GraphQL Helpers Integration Tests

packages/amplify_analytics_pinpoint/android/build.gradle, packages/amplify_api/android/build.gradle, packages/amplify_auth_cognito/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/amplify_flutter/android/build.gradle, packages/amplify_storage_s3/android/build.gradle
*Issue #, if available:* [#511](https://github.com/aws-amplify/amplify-flutter/issues/511)
Upgrade amplify-android to 1.24.1 to integrate the fix for not being able to query by null values.
----
=> chore: upgrade amplify-android 1.24.1

packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/amplify_authenticator/lib/src/enums/signup_types.dart, packages/amplify_authenticator/lib/src/keys.dart, packages/amplify_authenticator/lib/src/text_customization/input_resolver.dart, packages/amplify_authenticator/lib/src/views/signin_viewmodel.dart, packages/amplify_authenticator/lib/src/views/signup_viewmodel.dart, packages/amplify_authenticator/lib/src/widgets/default_forms.dart, packages/amplify_authenticator/lib/src/widgets/form_fields.dart
* Adds a passwordConfirmation field and ability to validate against password field.
* Directs user to the widget for resetting a password with a verification code after signing into an account for which a Cognito admin has forced a password reset.
=> fix(amplify_authenticator): Confirm password field

packages/amplify_datastore/ios/Classes/types/model/FlutterSerializedModel.swift
iOS ONLY fix.  Android was unaffected.
Ensure nested model int types are returned as int instead of double
Consolidate duplicated code for extracting values from Json during serialization step
*Issue #, if available:* 
https://github.com/aws-amplify/amplify-flutter/issues/800
=> fix(amplify_datastore): iOS json deserialization

example/pubspec.yaml, packages/amplify_storage_plugin_interface/CHANGELOG.md
Updates amplify dependencies in example app and fixed storage interface changelog.
=> fix(example) updates amplify dependencies

example/android/build.gradle, packages/amplify_analytics_pinpoint/android/build.gradle, packages/amplify_analytics_pinpoint/example/android/build.gradle, packages/amplify_api/android/build.gradle, packages/amplify_api/example/android/build.gradle, packages/amplify_auth_cognito/android/build.gradle, packages/amplify_auth_cognito/example/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_core/example/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/amplify_datastore/example/android/build.gradle, packages/amplify_flutter/android/build.gradle, packages/amplify_flutter/example/android/build.gradle, packages/amplify_storage_s3/android/build.gradle, packages/amplify_storage_s3/example/android/build.gradle
- JCenter is no longer available: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
- Builds are failing due to JCenter being offline: https://github.com/aws-amplify/amplify-flutter/issues/890
- Replaces JCenter with recommended replacement, Maven Central
=> Replace JCenter with Maven Central

packages/amplify_datastore/example/integration_test/query_test/pagination_test.dart, packages/amplify_datastore/example/ios/unit_tests/DataStorePluginUnitTests.swift, packages/amplify_datastore/example/ios/unit_tests/QueryPaginationUnitTests.swift, packages/amplify_datastore/ios/Classes/types/query/QueryPaginationBuilder.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/891
- remove the default behavior in QueryPaginationBuilder on iOS to use a page of 0 and a limit of 100
Amplify-flutter, Amplify-iOS, and Amplify-Android all allow for null/nil page sizes in the `query()` API. Amplify-iOS and Amplify-iOS do not provide any default behavior if null/nil is provided. Currently in Amplify-flutter there are default values used on iOS, but not Android.
=> fix(datastore): remove default pagination behavior on iOS

packages/amplify_auth_cognito/example/ios/unit_tests/amplify_auth_cognito_tests.swift, packages/amplify_auth_cognito/ios/Classes/AuthCognitoBridge.swift, packages/amplify_auth_cognito/ios/Classes/FlutterSignInWithWebUIRequest.swift, packages/amplify_auth_cognito/ios/Classes/SwiftAuthCognito.swift, packages/amplify_auth_cognito/lib/src/CognitoSignIn/CognitoSignInWithWebUIOptions.dart, packages/amplify_auth_cognito/lib/src/types.dart, packages/amplify_auth_plugin_interface/lib/src/SignIn/SignInWithWebUIOptions.dart, packages/amplify_auth_plugin_interface/lib/src/SignIn/SignInWithWebUIRequest.dart, packages/amplify_auth_plugin_interface/lib/src/types.dart, packages/amplify_flutter/lib/categories/amplify_auth_category.dart
=> feat(Auth) support preferPrivateSession flag

CONTRIBUTING.md, melos.yaml
- update `test:integration:ios/android` to run for a single package (with a prompt) by default, with the ability to override with `--no-select`
- update `test:integration` to use the `--no-select` package so that `test:integration` still runs tests all packages
- update the contributing docs
The melos commands for integ tests run tests for all packages by default. There is no easy way to choose a single package. This update makes running the tests for a single package & platform easier, while still allowing them to be run on for all packages with the option `--no-select`.
Note: Previously the melos commands were updated to *not* use prompts (https://github.com/aws-amplify/amplify-flutter/pull/711) in order to make running them all at once …
=> chore: update integration test commands to allow selection

packages/amplify_api/example/integration_test/graphql_tests.dart, packages/amplify_api/example/lib/graphql_api_view.dart, packages/amplify_api/lib/method_channel_api.dart, packages/amplify_api/lib/src/graphql/graphql_response_decoder.dart, packages/amplify_api/test/amplify_api_mutate_test.dart, packages/amplify_api/test/amplify_api_query_test.dart, packages/amplify_api/test/graphql_error_test.dart, packages/amplify_api/test/graphql_helpers_test.dart, packages/amplify_api_plugin_interface/lib/src/graphql/graphql_response.dart
BREAKING CHANGE: data field nullable in GraphQLResponse
This PR makes the data field nullable in graphql responses for the graphql helper branch. Eventually, it will get merged into release-candidate and go out with 0.3.x release. It has the type change as well as some changes to the decoder for models in API responses, and lots of null check operators in tests (kinda like a user would have to start doing with this change). There is also a small change to the API example app for null checking responses.
To recap reason for this, it's in the Graphql spec that data can be null on responses. AppSync sends null data responses in lots of normal situations, like fetching a blog that does not exist (think 404). For simple string responses, we default to empty string right now, which is not only …
=> chore(amplify_api): make data nullable in graphql responses

packages/amplify_datastore/example/integration_test/model_type_test.dart, packages/amplify_datastore_plugin_interface/lib/src/types/temporal/temporal_datetime.dart, packages/amplify_datastore_plugin_interface/lib/src/types/temporal/temporal_time.dart, packages/amplify_datastore_plugin_interface/test/amplify_temporal_datetime_test.dart
Add padding in fromString method for TemporalDateTime and TemporalTime to replace trailing “0”s removed by Android.
Fixes issues: 
https://github.com/aws-amplify/amplify-flutter/issues/817
https://github.com/aws-amplify/amplify-flutter/issues/579
Fix suggested by @martinzuccotti
=> fix(datastore): Android TemporalTime Save Issue

melos.yaml, packages/amplify_analytics_pinpoint/ios/amplify_analytics_pinpoint.podspec, packages/amplify_api/ios/amplify_api.podspec, packages/amplify_auth_cognito/ios/amplify_auth_cognito.podspec, packages/amplify_datastore/ios/amplify_datastore.podspec, packages/amplify_flutter/ios/amplify_flutter.podspec, packages/amplify_storage_s3/ios/amplify_storage_s3.podspec
- update amplify-ios to 1.15.5 to bring in https://github.com/aws-amplify/amplify-ios/pull/1494
- add melos script intended to be run after updating amplify pod versions
=> chore: update amplify pods to 1.15.5

packages/amplify_datastore/example/integration_test/query_test/query_predicate_test/aws_date_query_predicate_test.dart, packages/amplify_datastore/example/integration_test/query_test/query_predicate_test/aws_date_time_query_predicate_test.dart, packages/amplify_datastore/example/integration_test/query_test/query_predicate_test/aws_time_query_predicate_test.dart, packages/amplify_datastore/example/integration_test/query_test/query_predicate_test/aws_timestamp_query_predicate_test.dart, packages/amplify_datastore/test/query_predicate_test.dart, packages/amplify_datastore/test/resources/query_predicate/temporal_predicate.json, packages/amplify_datastore_plugin_interface/lib/src/types/query/query_field.dart, packages/amplify_datastore_plugin_interface/lib/src/types/query/query_field_operators.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/837
- serialize temporal date/time types in query predicates
- add unit test for the new serialization
- add integ tests for all temporal date/time types
=> fix(datastore): fix temporal date/time query predicates

packages/amplify_authenticator/lib/src/widgets/form_fields/sign_up_form_field.dart
Makes SignUpField.custom hintText required.
=> fix(amplify_authenticator): Makes SignUpField.custom hintText required

packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart
- Check that a user's attributes are verified after confirm sign in. Currently this is only done after sign in, not _confirm_ sign in.
=> fix: check attribute verification after confirm sign in

CONTRIBUTING.md
- Current pre-sign up trigger does not work in latest CLI. Gives following error:
```
LambdaException(message: Sign up failed, recoverySuggestion: See attached exception for more details., underlyingException: com.amazonaws.services.cognitoidentityprovider.model.UserLambdaValidationException: PreSignUp failed with error callback is not a function. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserLambdaValidationException; Request ID: 21307ea4-f716-4f7f-94d7-aae754d58eb3))
```
- See ex. [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/email-filter-allowlist.js)
By submitting this pull request, I confirm that you can …
=> fix(docs): Update custom pre-sign up handler

packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/amplify_authenticator/lib/src/blocs/auth/auth_data.dart, packages/amplify_authenticator/lib/src/enums/confirm_signin_types.dart, packages/amplify_authenticator/lib/src/keys.dart, packages/amplify_authenticator/lib/src/l10n/generated/input_localizations.dart, packages/amplify_authenticator/lib/src/l10n/generated/input_localizations_en.dart, packages/amplify_authenticator/lib/src/l10n/input_resolver.dart, packages/amplify_authenticator/lib/src/l10n/src/inputs/inputs_en.arb, packages/amplify_authenticator/lib/src/services/amplify_auth_service.dart, packages/amplify_authenticator/lib/src/state/auth_viewmodel.dart, packages/amplify_authenticator/lib/src/widgets/button.dart, packages/amplify_authenticator/lib/src/widgets/form.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_in_form_field.dart
- create a newPassword field for confirm sign up
- separate MFA confirm sign up and force password reset confirm sign up
- update the language for the hint text
=> fix: create newPassword field for confirm sign up

packages/amplify_analytics_pinpoint/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPlugin.kt, packages/amplify_analytics_pinpoint/ios/Classes/SwiftAmplifyAnalyticsPinpointPlugin.swift, packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/AmplifyApiPlugin.kt, packages/amplify_api/ios/Classes/SwiftAmplifyApiPlugin.swift, packages/amplify_auth_cognito/android/build.gradle, packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt, packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/device/DeviceHandler.kt, packages/amplify_auth_cognito/example/ios/Runner.xcodeproj/project.pbxproj, packages/amplify_auth_cognito/ios/Classes/Device/DeviceHandler.swift, packages/amplify_auth_cognito/ios/Classes/SwiftAuthCognito.swift, packages/amplify_core/android/build.gradle, packages/amplify_core/android/src/main/kotlin/com/amazonaws/amplify/amplify_core/AtomicResult.kt, packages/amplify_core/android/src/test/kotlin/com/amazonaws/amplify/amplify_core/AtomicResultTest.kt, packages/amplify_core/android/src/test/kotlin/com/amazonaws/amplify/amplify_core/CoroutineTestRule.kt, packages/amplify_core/ios/Classes/Support/AtomicResult.swift, packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt, packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift, packages/amplify_flutter/android/src/main/kotlin/com/amazonaws/amplify/Amplify.kt, packages/amplify_flutter/example/ios/Runner.xcodeproj/project.pbxproj, packages/amplify_flutter/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, packages/amplify_flutter/example/ios/unit_tests/AtomicResultTests.swift, packages/amplify_flutter/ios/Classes/SwiftAmplify.swift, packages/amplify_storage_s3/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/AmplifyStorageS3Plugin.kt, packages/amplify_storage_s3/ios/Classes/SwiftAmplifyStorageS3Plugin.swift
- https://github.com/aws-amplify/amplify-flutter/issues/1022
- https://github.com/aws-amplify/amplify-flutter/issues/791
- https://github.com/aws-amplify/amplify-flutter/issues/340
- https://github.com/aws-amplify/amplify-flutter/issues/140
- Long overdue migration to AtomicResult to prevent "reply already submitted" crashes
=> fix: "Reply already submitted" crashes

packages/amplify_authenticator/lib/src/l10n/input_resolver.dart, packages/amplify_authenticator/lib/src/mixins/authenticator_radio_field.dart, packages/amplify_authenticator/lib/src/widgets/form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/verify_user_form_field.dart
- removes the title from the verify user screen
- updates the ordering so that email always displays before phone
- properly sets the default attribute
**Before**
**After**
=> fix(authenticator): remove the label from verify user screen and display email first

packages/amplify_storage_s3/ios/Classes/AmplifyStorageOperations.swift
- Mentioned here: https://github.com/aws-amplify/amplify-flutter/issues/1059#issuecomment-964385325
Issue: Converting DateTime -> String using `Date.description` instead of a formatter
- Use a built-in Amplify ISO8601 formatter
=> fix(storage): Fix DateTime parsing

packages/amplify_storage_s3/example/.gitignore, packages/amplify_storage_s3/ios/Classes/AmplifyStorageOperations.swift, packages/amplify_storage_s3/ios/Classes/FlutterListRequest.swift
- https://github.com/aws-amplify/amplify-flutter/issues/1059
Issue: Omitting the `options` cause a crash on iOS due to improper null checks
- Fix crash on null "options" dict
- Remove validation which did not do anything
=> fix(storage): Storage.list crash on null "options"

packages/amplify_datastore/example/integration_test/model_type_test.dart, packages/amplify_datastore/example/integration_test/query_test/standard_query_operations_test.dart, packages/amplify_datastore/test/amplify_datastore_delete_test.dart, packages/amplify_datastore_plugin_interface/test/amplify_temporal_date_test.dart, packages/amplify_datastore_plugin_interface/test/amplify_temporal_datetime_test.dart, packages/amplify_datastore_plugin_interface/test/amplify_temporal_time_test.dart, packages/amplify_datastore_plugin_interface/test/query_snapshot_test.dart
- remove calls to DateTime.now() from tests to prevent flaky tests
Note: I left a call to DateTime.now() in the storage integ tests that check the DateTime of file uploads. I think the use there is reasonable and I don't think there is an easy alternative.
=> chore: remove DateTime.now() from tests

packages/amplify_datastore/android/build.gradle, packages/amplify_datastore/android/proguard-rules.pro
- https://github.com/aws-amplify/amplify-flutter/issues/1048
- https://github.com/aws-amplify/amplify-flutter/issues/828
- Add ProGuard rules to prevent class splitting which causes crashes on startup for DataStore in release mode.
=> fix(datastore): Fix DataStore release mode crash (Android)

packages/amplify_authenticator/lib/amplify_authenticator.dart
- remove scaffold from the widget tree if state == authenticated
=> fix: remove scaffold if state is authenticated

packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt, packages/amplify_datastore/example/lib/main.dart, packages/amplify_datastore/ios/Classes/FlutterDataStoreErrorHandler.swift, packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift, packages/amplify_datastore/lib/amplify_datastore.dart, packages/amplify_datastore/lib/method_channel_datastore.dart, packages/amplify_datastore/test/amplify_datastore_custom_error_handler_test.dart, packages/amplify_datastore_plugin_interface/lib/amplify_datastore_plugin_interface.dart, packages/amplify_flutter/lib/categories/amplify_datastore_category.dart
Custom ErrorHandler support 
I haven't written integration tests for this.  Should be a small code change but a bit tricky to figure out as I don't know how to trigger the Datastore Exceptions that would in turn trigger the custom error handler (I've just manually triggered it from native atm) 
Update November 8: 
We should include integration tests for this code change in a separate PR.  Writing integration tests will require enabling cloud sync and thus reworking all existing integration tests in Datastore as well.  Given ongoing talks with native teams, I might also need to enable Auth as well to trigger the edge case that would get the custom error callback to be called in the first place.  As this could require significantly more …
=> feat(datastore): Custom Error Handler

packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/amplify_authenticator/lib/src/services/amplify_auth_service.dart
With this PR we no longer use getCurrentUser when deciding to display the SignIn form or the customer app, as this method has inconsistent behavior between platforms (on main) and returns an AuthUser even when the session has expired (RC). We now use fetchAuthSession.
=> fix(amplify_authenticator) uses session for _authLoad

packages/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart
The username mixin is resetting username to `''` on a change of state in the swich component, but the user may have already input their email and phone. This results in empty username being sent to the signUp API.
Updates viewModel.username with the attribute corresponding to the switch state (falls back to empty string).
=> fix(amplify_authenticator): updates username on switch state

packages/amplify_auth_cognito/lib/src/CognitoSignIn/CognitoSignInWithWebUIOptions.dart, packages/amplify_authenticator/lib/amplify_authenticator.dart, packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/amplify_authenticator/lib/src/services/amplify_auth_service.dart
- Add option for `preferPrivateSession` - default to `true` within Authenticator.
=> chore(authenticator): Prefer private session for iOS

packages/amplify_authenticator/lib/amplify_authenticator.dart, packages/amplify_authenticator/lib/src/mixins/authenticator_text_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_in_form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/sign_in_form_field.dart
- support the ability to customize the confirm sign in screen
- add email and phone attributes to the confirm sign in screen
With these changes, the following code snippet will produce the screenshot below it.
```dart
final authenticator = Authenticator(
confirmSignInNewPasswordForm: ConfirmSignInNewPasswordForm.custom(
fields: [
ConfirmSignInFormField.email(required: true),
ConfirmSignInFormField.custom(
required: true,
attributeKey: CognitoUserAttributeKey.name,
title: 'Name',
hintText: 'Enter your name'),
],
),
child: const SignedInScreen(),
);
```
=> feat: support email & phone in confirm sign in

packages/amplify_authenticator/lib/src/l10n/generated/input_localizations.dart, packages/amplify_authenticator/lib/src/l10n/generated/input_localizations_en.dart, packages/amplify_authenticator/lib/src/l10n/input_resolver.dart, packages/amplify_authenticator/lib/src/l10n/src/inputs/inputs_en.arb
- update hint text for confirm password. The previous hint text said "Re-enter your _confirm_ password." The new text says "Re-enter your password." See before and after.
**Before**
**After**
=> fix: update confirm password hint text

packages/amplify_api/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_flutter/android/build.gradle
- https://github.com/aws-amplify/amplify-flutter/issues/1124
- The coroutines library being used currently is incorrect - we need to be using the Android-specific version to prevent a runtime crash in release mode.
=> fix(android): Fix coroutines crash

packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/device/DeviceHandler.kt
- There is a duplicate AtomicResult in the DeviceHandler. The result being passed in is already an AtomicResult.
=> fix(auth): Remove duplicate AtomicResult

packages/amplify_analytics_pinpoint/android/build.gradle, packages/amplify_analytics_pinpoint/ios/amplify_analytics_pinpoint.podspec, packages/amplify_api/android/build.gradle, packages/amplify_api/ios/amplify_api.podspec, packages/amplify_auth_cognito/android/build.gradle, packages/amplify_auth_cognito/ios/amplify_auth_cognito.podspec, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/amplify_datastore/ios/amplify_datastore.podspec, packages/amplify_flutter/android/build.gradle, packages/amplify_flutter/ios/amplify_flutter.podspec, packages/amplify_storage_s3/android/build.gradle, packages/amplify_storage_s3/ios/amplify_storage_s3.podspec
- amplify-android to 1.29.1
- amplify-ios pin to 1.15.6
Upgrade amplify-ios and amplify-android version to bring in `ModelSyncMetadata` table migration for DataStore plugin.
NOTE: the upgraded versions are not the latest versions but the minimum version required to migrate `ModelSyncMetadata` table.
=> chore: upgrade dependencies

packages/amplify_authenticator/lib/src/mixins/authenticator_date_field.dart, packages/amplify_authenticator/lib/src/mixins/authenticator_text_field.dart, packages/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart, packages/amplify_authenticator/lib/src/theme/amplify_theme.dart, packages/amplify_authenticator/lib/src/widgets/form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/phone_number_field.dart
- Use label/labelText for material theme
**Before**
**After**
**Before**
**After**
**Before**
**After**
**Before**
**After**
=> chore: refactor labels to use TextFormField InputDecoration

packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/AmplifyApiPlugin.kt, packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/auth/FlutterAuthProvider.kt, packages/amplify_api/ios/Classes/Auth/FlutterAuthProvider.swift, packages/amplify_api/ios/Classes/SwiftAmplifyApiPlugin.swift, packages/amplify_api/lib/src/method_channel_api.dart, packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/types/model/FlutterAuthRule.kt
- API auth providers triggering false positives internally (no OIDC/Lambda provider but native SDK thinks there is)
- Need default auth rule provider on Android to prevent null exception crash
- Pass registered auth providers to `addPlugin`
- Fallback to default auth provider for rule strategy
=> fix(api): 0.3.0 fixes

packages/amplify_authenticator/lib/src/widgets/form.dart, packages/amplify_authenticator/lib/src/widgets/social/social_button.dart
- Apple button should be sorted first
- Logos are not aligned
- Aligned logos
- Sorted Apple first
=> chore(authenticator): Align logos and sort Apple first

packages/amplify_authenticator/example/integration_test/envs/auth_with_email.dart, packages/amplify_authenticator/example/integration_test/envs/auth_with_phone.dart, packages/amplify_authenticator/example/integration_test/envs/auth_with_username.dart, packages/amplify_authenticator/example/integration_test/pages/authenticator_page.dart, packages/amplify_authenticator/example/integration_test/pages/confirm_sign_in_page.dart, packages/amplify_authenticator/example/integration_test/sign_in_force_new_password_test.dart, packages/amplify_authenticator/lib/src/enums/confirm_signin_types.dart, packages/amplify_authenticator/lib/src/keys.dart, packages/amplify_authenticator/lib/src/l10n/generated/input_localizations.dart, packages/amplify_authenticator/lib/src/l10n/generated/input_localizations_en.dart, packages/amplify_authenticator/lib/src/l10n/input_resolver.dart, packages/amplify_authenticator/lib/src/l10n/src/inputs/inputs_en.arb, packages/amplify_authenticator/lib/src/mixins/authenticator_phone_field.dart, packages/amplify_authenticator/lib/src/widgets/form.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_in_form_field.dart
- Minor l10n spacing fix
- Add confirm new password field
- Add sign-in-force-new-password test
=> chore(authenticator): Force new password test

packages/amplify_auth_cognito/example/integration_test/user_attributes_test.dart, packages/amplify_auth_cognito/example/lib/Widgets/ConfirmUserAttribute.dart, packages/amplify_auth_cognito/example/lib/Widgets/UpdateUserAttribute.dart, packages/amplify_auth_cognito/example/lib/Widgets/ViewUserAttributes.dart, packages/amplify_auth_cognito/test/amplify_auth_cognito_fetchUserAttributes_test.dart, packages/amplify_auth_plugin_interface/lib/src/Attribute/AuthUserAttribute.dart
*Issue #, if available:* #1164
- removes the attempt to convert the attribute value to an int.
=> fix(amplify_auth_cognito): remove int.parse from AuthUserAttribute

packages/amplify_authenticator/example/integration_test/config.dart, packages/amplify_authenticator/example/integration_test/envs/auth_with_email_lambda_signup_trigger.dart, packages/amplify_authenticator/example/integration_test/pages/authenticator_page.dart, packages/amplify_authenticator/example/integration_test/pages/confirm_sign_in_page.dart, packages/amplify_authenticator/example/integration_test/pages/sign_in_page.dart, packages/amplify_authenticator/example/integration_test/pages/sign_up_page.dart, packages/amplify_authenticator/example/integration_test/pages/test_utils.dart, packages/amplify_authenticator/example/integration_test/sign_in_force_new_password_test.dart, packages/amplify_authenticator/example/integration_test/sign_in_mfa_test.dart, packages/amplify_authenticator/example/integration_test/sign_in_with_phone_test.dart, packages/amplify_authenticator/example/integration_test/sign_in_with_username_test.dart, packages/amplify_authenticator/example/integration_test/sign_up_with_email_with_lambda_trigger.dart, packages/amplify_authenticator/example/integration_test/sign_up_with_phone_test.dart, packages/amplify_authenticator/example/integration_test/utils/data_utils.dart, packages/amplify_authenticator/example/integration_test/utils/mock_data.dart
- sign-up-with-email-with-lambda-trigger test
- Some helpers clean up/re-org
=> chore(authenticator): Sign up with email (lambda trigger) test

packages/amplify_authenticator/example/integration_test/config.dart, packages/amplify_authenticator/example/integration_test/pages/authenticator_page.dart, packages/amplify_authenticator/example/integration_test/pages/confirm_sign_up_page.dart, packages/amplify_authenticator/example/integration_test/pages/confirm_verify_user_page.dart, packages/amplify_authenticator/example/integration_test/pages/forgot_password_page.dart, packages/amplify_authenticator/example/integration_test/pages/sign_in_page.dart, packages/amplify_authenticator/example/integration_test/pages/verify_user_page.dart, packages/amplify_authenticator/example/integration_test/reset_password_test.dart, packages/amplify_authenticator/example/integration_test/sign_in_with_email_test.dart, packages/amplify_authenticator/example/integration_test/utils/types/confirmation_code_response.dart
* sign_in_with_email test
* reset password test
=> test(amplify_authenticator): sign in with email and reset password tests

packages/amplify_authenticator/example/integration_test/config.dart, packages/amplify_authenticator/example/integration_test/confirm_sign_up_test.dart, packages/amplify_authenticator/example/integration_test/pages/authenticator_page.dart, packages/amplify_authenticator/example/integration_test/utils/data_utils.dart, packages/amplify_authenticator/example/integration_test/verify_user_test.dart
=> test: confirm sign in tests

packages/amplify_authenticator/lib/amplify_authenticator.dart, packages/amplify_authenticator/lib/src/l10n/button_resolver.dart, packages/amplify_authenticator/lib/src/l10n/generated/button_localizations.dart, packages/amplify_authenticator/lib/src/l10n/generated/button_localizations_en.dart, packages/amplify_authenticator/lib/src/l10n/generated/country_localizations_en.dart, packages/amplify_authenticator/lib/src/l10n/generated/input_localizations.dart, packages/amplify_authenticator/lib/src/l10n/generated/input_localizations_en.dart, packages/amplify_authenticator/lib/src/l10n/generated/message_localizations_en.dart, packages/amplify_authenticator/lib/src/l10n/generated/title_localizations_en.dart, packages/amplify_authenticator/lib/src/l10n/input_resolver.dart, packages/amplify_authenticator/lib/src/l10n/title_resolver.dart, packages/amplify_authenticator/tool/generate_l10n.sh
- All exports needed for localization should be exported (CXs should not need to know where to locate these symbols).
=> chore(authenticator): Missing exports

packages/amplify_datastore/example/integration_test/relationship_type_test.dart, packages/amplify_datastore/example/ios/unit_tests/AmplifySerializedModelUnitTests.swift, packages/amplify_datastore/example/ios/unit_tests/resources/SchemaData.swift, packages/amplify_datastore/ios/Classes/FlutterModels.swift
https://github.com/aws-amplify/amplify-flutter/issues/1198
Make the registered model decoder capable to handle decoding json string that presents a single object besides an array of objects.
- Updated relevant integration tests to test the use cases.
----
=> fix(datastore): cascade delete not working in iOS

packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt, packages/amplify_datastore/lib/method_channel_datastore.dart, packages/amplify_datastore/test/amplify_datastore_observe_test.dart
*Issue #, if available:* #736
Originally below code is executed within `DataStore.configure`.
```
_channel.invokeMethod('setUpObserve', {})
```
This method channel call invokes `observe()` method of native DataStore plugins, which triggers `API_SYNC`. This behavior is undesired especially when data model authorization requires valid user session.
Moving the method call to each DataStore operation process, the actually logic of `setUpObserve` will only be invoked once.
----
=> fix(datastore): configure function triggers initial sync unexpectedly

packages/amplify_api/ios/Classes/Auth/FlutterAuthProvider.swift, packages/amplify_authenticator/example/ios/Runner.xcodeproj/project.pbxproj, packages/amplify_authenticator/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Authenticator example does not build in release mode on iOS. Requires Xcode project updates. Discovered via unpub pipeline: https://app.circleci.com/pipelines/github/aws-amplify/amplify-flutter/2619/workflows/3bb2a7c9-935c-4cac-94f8-716fbfc0d009/jobs/9903
- Update Xcode project
- Bump deployment target to iOS 11.0 (was 9.0)
- Swift file in `amplify_api` needed re-formatting
=> fix(authenticator): Fix Xcode project

packages/amplify_datastore/ios/Classes/DataStoreHubEventStreamHandler.swift
- Hub history tracking is consuming too much memory
- Only store necessary hub events
- Disable for release mode
=> fix(datastore): Hub memory usage

packages/amplify_api/lib/src/graphql/graphql_request_factory.dart, packages/amplify_api/test/graphql_helpers_test.dart
Model helpers, do not include null parent ID in mutation inputs to allow mutation child without parent ID when schema permits.
I had mistakenly thought that all models with parents required parent ID in mutation due to graphql transformer. However, that was just bc of the schema I was always testing with. Users can make a schema that does not require this. In this situation, parent ID is sent as null in the mutation variables, which causes an appsync error as null not an acceptable value for an ID type.
This PR just checks the value of the parent ID to see if non null before putting in the variables so it can be omitted when the schema permits.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> fix(amplify_api): model helpers, fix for mutations with no parent ID

packages/amplify_flutter/lib/amplify_flutter.dart, packages/amplify_flutter/lib/src/amplify_impl.dart, packages/amplify_flutter/lib/src/method_channel_amplify.dart, packages/amplify_flutter/test/amplify_test.dart
*Issue #, if available:* n/a
*Goal:*
- Allow Amplify Auth to be stubbed for use in the browser, so that a live Amplify Authenticator demo (with a stubbed backend) can be imbedded in the docs website.
*Issue description:*
`AmplifyClass` has a setter for the private `_instance` field. This allows a customer to pass in their own AmplifyClass implementation. However, the instance they pass in isn't used (except in one location, where a private method is invoked, and private methods can't be overridden from outside the lib anyway). This means that customers can technically create their own AmplifyClass implementation, but they can't override any of the methods, which defeats the whole point.
- Move all implementations from AmplifyClass to MethodChannelAmplify.
- …
=> feat(amplify_flutter): allow customers to override AmplifyClass methods

example/pubspec.yaml, packages/amplify_analytics_pinpoint/CHANGELOG.md, packages/amplify_analytics_pinpoint/pubspec.yaml, packages/amplify_analytics_plugin_interface/CHANGELOG.md, packages/amplify_analytics_plugin_interface/pubspec.yaml, packages/amplify_api/CHANGELOG.md, packages/amplify_api/pubspec.yaml, packages/amplify_api_plugin_interface/CHANGELOG.md, packages/amplify_api_plugin_interface/pubspec.yaml, packages/amplify_auth_cognito/CHANGELOG.md, packages/amplify_auth_cognito/pubspec.yaml, packages/amplify_auth_plugin_interface/CHANGELOG.md, packages/amplify_auth_plugin_interface/pubspec.yaml, packages/amplify_core/CHANGELOG.md, packages/amplify_core/pubspec.yaml, packages/amplify_datastore/CHANGELOG.md, packages/amplify_datastore/pubspec.yaml, packages/amplify_datastore_plugin_interface/CHANGELOG.md, packages/amplify_datastore_plugin_interface/pubspec.yaml, packages/amplify_flutter/CHANGELOG.md, packages/amplify_flutter/lib/src/method_channel_amplify.dart, packages/amplify_flutter/pubspec.yaml, packages/amplify_lints/CHANGELOG.md, packages/amplify_storage_plugin_interface/CHANGELOG.md, packages/amplify_storage_plugin_interface/pubspec.yaml, packages/amplify_storage_s3/CHANGELOG.md, packages/amplify_storage_s3/pubspec.yaml
- revert the changes made for amplify_flutter 0.3.3 version bump. This reverts the changes from 117191e8656b6bee66df08f6d81e5d0f5a22678c, with the exception of the authenticator version bump and logs.
=> chore: revert 0.3.3 version bump

packages/amplify_api/pubspec.yaml
Adds meta as a direct dependency in amplify_api to prevent a publish-time error about transitive dependencies.
=> chore(amplify_api): add meta as dependency

packages/amplify_authenticator/lib/src/widgets/authenticator_banner.dart, packages/amplify_authenticator/pubspec.yaml
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/1381
- Remove use of onInverseSurface to support flutter versions prior to 2.10.0
=> fix(amplify_authenticator): remove use of onInverseSurface to support older flutter versions

packages/amplify_core/android/src/main/kotlin/com/amazonaws/amplify/amplify_core/AtomicResult.kt, packages/amplify_core/android/src/test/kotlin/com/amazonaws/amplify/amplify_core/AtomicResultTest.kt
https://github.com/aws-amplify/amplify-flutter/issues/1396
The issue is that the CX is using Flutter master and they just recently updated the annotations on the `Result` interface to make `errorCode` non-null.
The same error has been experienced in Firebase and seems to be due to how Kotlin assumes every Java type is nullable unless explicitly marked with the `@NonNull` annotation. 
- https://github.com/flutter/engine/pull/31530
- https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20firebase_abstract_method_smoke_test/25243/overview
- Make `errorCode` non-null to match new Java interface: https://github.com/flutter/engine/blame/main/shell/platform/android/io/flutter/plugin/common/MethodChannel.java#L217
By submitting this pull …
=> fix(core): Implement Result in AtomicResult

packages/amplify_authenticator/lib/src/widgets/form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_up_form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/sign_in_form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/sign_up_form_field.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/1398
- Add clarification to username API docs
=> chore(amplify_authenticator): add more detail to api docs for username

packages/amplify_datastore/example/integration_test/save_test.dart, packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift
https://github.com/aws-amplify/amplify-flutter/issues/1400
For `delete` API, if the query predicate is not provide, leave it as nil and not using `QueryPredicateConstant.all`, which causes the deletion validation query returns all record instead of the record that is with the specific id.
=> fix(datastore): delete default predicate causes deletion failure

packages/auth/amplify_auth_cognito/pubspec.yaml, packages/auth/amplify_auth_cognito_android/pubspec.yaml, packages/auth/amplify_auth_cognito_ios/pubspec.yaml, packages/auth/amplify_auth_plugin_interface/pubspec.yaml
Fixes `auth` package pubspec's with valid `homepage` values.
=> chore(auth): fix pubspec urls

packages/amplify_api/example/tool/provision_integration_test_resources.sh, packages/amplify_datastore/example/tool/provision_integration_test_resources.sh, packages/auth/amplify_auth_cognito/example/tool/provision_integration_test_resources.sh
As written, provision scripts for integration test resources assume default profile in local AWS configuration. This PR lets the caller specify the AWS profile with an env variable `AWS_PROFILE`, similar to existing change in auth example script.
=> chore: update integ provision scripts to use AWS profile

packages/amplify_datastore/example/integration_test/query_test/query_predicate_test/float_query_predicate_test.dart, packages/amplify_datastore/example/integration_test/utils/query_predicate_utils.dart
#830 
- enable skipped tests
- using actual number instead of `double.maxFinite` and `double.minPositive` or `double.negativeInfinity` as Android SQLite engine cannot handle `-Infinity`, `Infinity` while generating SQL command. As this is not a concern of this test suites, so just use actual number instead
=> chore(datastore): enable query predicate integ tests for float values

packages/analytics/amplify_analytics_pinpoint_android/example/pubspec.yaml, packages/analytics/amplify_analytics_pinpoint_ios/example/pubspec.yaml
Adds the flutter sdk as dependency to analytics example apps.
Fixes the following melos error:
```terminal
Running "flutter pub get" in workspace packages...
Note: this may take a while in large workspaces such as this one.
✓ amplify_analytics_pinpoint
└> packages/analytics/amplify_analytics_pinpoint
✓ amplify_analytics_pinpoint_android
└> packages/analytics/amplify_analytics_pinpoint_android
- amplify_analytics_pinpoint_android_example
└> packages/analytics/amplify_analytics_pinpoint_android/example
└> Failed to install.
Resolving dependencies...
Because amplify_analytics_pinpoint_android_example requires the Flutter SDK, version solving failed.
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
=> fix(analytics): adds flutter sdk to example apps

packages/amplify_api/ios/amplify_api.podspec, packages/amplify_datastore/ios/amplify_datastore.podspec, packages/amplify_flutter/ios/amplify_flutter.podspec, packages/analytics/amplify_analytics_pinpoint_ios/ios/amplify_analytics_pinpoint_ios.podspec, packages/auth/amplify_auth_cognito_ios/ios/amplify_auth_cognito_ios.podspec, packages/storage/amplify_storage_s3_android/.gitignore, packages/storage/amplify_storage_s3_ios/.gitignore, packages/storage/amplify_storage_s3_ios/ios/amplify_storage_s3_ios.podspec
Bump amplify-ios to version [1.22.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.22.0).
Also add missing `.gitignore` files for `storage` packages.
=> chore: bump amplify-ios to 1.22.0

packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt, packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePluginTest.kt, packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift, packages/amplify_datastore/lib/amplify_datastore.dart, packages/amplify_datastore/lib/method_channel_datastore.dart, packages/amplify_datastore_plugin_interface/lib/amplify_datastore_plugin_interface.dart, packages/amplify_datastore_plugin_interface/lib/src/publicTypes.dart, packages/amplify_datastore_plugin_interface/lib/src/types/models/auth_mode_strategy.dart
#815 
- Adds multi-auth option to DataStore configuration
=> feat(datastore): Multi-auth

packages/api/amplify_api_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/AmplifyApi.kt, packages/api/amplify_api_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/GraphQLSubscriptionStreamHandler.kt, packages/api/amplify_api_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/auth/FlutterAuthProvider.kt
https://github.com/aws-amplify/amplify-flutter/issues/1504
Handles closure of method and event channels when sending apps to the background and adds reattach logic for each
=> fix(api): JNI issues

packages/auth/amplify_auth_cognito/lib/amplify_auth_cognito_stream_controller.dart
Removes dupe switch case in Auth Hub.
=> chore(auth): remove redundant switch case

packages/amplify_core/lib/src/types/query/query_pagination.dart
*Issue #, if available:* #842
*Description of changes:* This PR updates the default constructor for `QueryPagination`s to supply a default value of `0` for the `page` field. The Kotlin version of the `QueryPaginationBuilder` checks to see if the serialized map passed to it contains the `page` key, but since the `serializeAsMap()` method *always* adds the page key, a `NullPointerException` can arise as a result.
Another fix considered was to update the `serializeAsMap()` method to only add the `page` key if page is defined. This would be a reasonable fix but only when coupled with the current `QueryPaginationBuilder` utilities. Opting for the default value would not require the "is the `page` key defined check.
* Also of note - Rather than removing these checks from the utilities, opting …
=> fix(core): Update QueryPagination page field to default to 0

.github/workflows/lint.yml, .github/workflows/test.yml, packages/aws_common/pubspec.yaml, packages/aws_signature_v4/example/mono_pkg.yaml, packages/aws_signature_v4/lib/src/signer/aws_signer.dart, packages/aws_signature_v4/mono_pkg.yaml, packages/aws_signature_v4/pubspec.yaml, packages/aws_signature_v4/test/build_verify_test.dart, tool/ci.sh
- Bumps the minimum SDK version to 2.15 (from 2.12). This is to align with the rest of Amplify Dart.
- Updates mono_repo config for the AWS packages
=> chore(aws): Bump min SDK version

packages/aws_signature_v4/lib/src/configuration/service_configuration.dart, packages/aws_signature_v4/lib/src/configuration/services/s3.dart, packages/aws_signature_v4/lib/src/request/canonical_request/canonical_path.dart, packages/aws_signature_v4/lib/src/request/canonical_request/canonical_request.dart, packages/aws_signature_v4/lib/src/signer/aws_signer.dart, packages/aws_signature_v4/test/build_verify_test.dart, packages/aws_signature_v4/test/c_test_suite/request_parser.dart, packages/aws_signature_v4/test/c_test_suite/test_data.dart, packages/aws_signature_v4/test/common.dart, packages/aws_signature_v4/test/headers_test.dart, packages/aws_signature_v4/test/s3/s3_service_configuration_test.dart, packages/aws_signature_v4/test/s3/single_chunk_test.dart, packages/aws_signature_v4/test/s3/testdata/multiple_chunks_testdata.dart, packages/aws_signature_v4/test/s3/testdata/single_chunk_testdata.dart, packages/aws_signature_v4/test/service_configuration_test.dart, packages/aws_signature_v4/test/signer_html_test.dart, packages/aws_signature_v4/test/streamed_request_test.dart
- Fixes a problem with S3 path normalization (S3 paths should be un-normalized)
- Fixes a problem with S3 path encoding. S3 path segments should be encoded once, every other service expects double-encoding. The confusion was that the test suite expects single-encoding like S3.
- Fixes a problem with S3 options (chunked/signPayload). Adds tests to verify permutations work as expected.
- Removes `Host` and `Content-Length` headers on Web after signing to prevent browser errors warning against setting these manually
=> fix(aws_signature_v4): Various fixes

packages/aws_common/lib/src/util/uuid.dart, packages/aws_common/pubspec.yaml
- Pentest discovered that `package:uuid` is not crypto-secure by default.
- Adds a top-level helper for retrieving crypto-secure UUIDs, to be used in Amplify Dart code
=> chore(aws_common): Crypto-secure UUID

packages/amplify/amplify_flutter_android/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle, packages/api/amplify_api_android/android/build.gradle, packages/auth/amplify_auth_cognito_android/android/build.gradle, packages/storage/amplify_storage_s3_android/android/build.gradle
#1131 
Bump amplify-android version to [1.35.3](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.35.3), which include a fix to resolve the issue described in #1131 .
=> chore: bump amplify-android version to 1.35.3

packages/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart
This PR addresses a case in which the customer creates a signup form in which the username is a phone or email, and the value is expected to be persisted to the next confirmSignUpScreen. 
Currently, the persistence only works if the customer ALSO uses a secondary attribute field to capture the email or phone (again), because the state for these values are not set by the username `onChanged` method, yet the username field's `initialValue` getter attempts to retrieve them (email or phone) from state when setting the initial value of the new username field.
An alternative to this fix (which changes the initialValue getter) might be to update the email/phone state values in the username fields `onChanged`. 
I am not 100% sure that either of these are the correct …
=> fix: email/phonenumber username not persisted to next component

packages/amplify/amplify_flutter_android/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle, packages/api/amplify_api_android/android/build.gradle, packages/auth/amplify_auth_cognito_android/android/build.gradle, packages/storage/amplify_storage_s3_android/android/build.gradle
downgrade amplify-android to 1.33.0
=> fix: downgrade amplify-android to 1.33.0

packages/amplify/amplify_flutter/lib/src/categories/amplify_datastore_category.dart, packages/amplify_datastore/example/integration_test/observe_query_test.dart, packages/amplify_datastore/example/integration_test/observe_test.dart, packages/amplify_datastore/example/integration_test/utils/setup_utils.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/1590
- Update `observe` and `observeQuery` tests
- Update API docs for DataStore. While looking into the race condition, I was using the native teams API docs to understand what stop/start/clear do. I figured we should have more info on those.
=> chore(dataStore): Update datastore API docs and fix race conditions in tests

packages/api/amplify_api/lib/src/graphql/graphql_request_factory.dart, packages/api/amplify_api/test/query_predicate_graphql_filter_test.dart
Issue #1567 
Model helpers for GraphQL accepts query predicates for some requests. The predicates get serialized into JSON objects which are included as request variables at runtime. There is a nasty error in the library when someone passes an enum into the query predicates. This small PR just calls `describeEnum` to convert them to a string.
Note that there is still a CLI issue at play here https://github.com/aws-amplify/amplify-cli/issues/10370 which makes the compiled schema look for int values instead of strings. That has been identified as a bug and this PR fixes the amplify-flutter end of it and will work if either a) the bug in CLI is fixed b) the appsync compiled schema is manually modified to accept strings.
By submitting this pull request, I confirm that you can use, modify, …
=> fix(api): support enums in query predicates for model helpers

.circleci/config.yml, .circleci/test_all_plugins.sh, packages/api/amplify_api_ios/example/ios/Podfile, packages/api/amplify_api_ios/example/ios/Runner.xcodeproj/project.pbxproj, packages/api/amplify_api_ios/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/api/amplify_api_ios/example/ios/Runner/Info.plist, packages/api/amplify_api_ios/example/ios/unit_tests/FlutterURLSessionTests.swift, packages/api/amplify_api_ios/ios/Classes/OperationsManager.swift
- #1574 
- Fixes iOS crash due to concurrent access of an array
- Enabled thread sanitizer in API unit tests
=> fix(api): OperationsManager crash

packages/amplify_core/lib/src/types/query/query_field.dart, packages/amplify_core/lib/src/types/query/query_predicate.dart, packages/amplify_core/lib/src/types/query/query_sort.dart, packages/amplify_core/lib/src/types/query/query_utils.dart, packages/amplify_datastore/test/query_predicate_test.dart, packages/amplify_datastore/test/query_sort_test.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/1594
- remove model name from ID fields for in-memory field comparisons
=> fix(dataStore): update in memory sorts and filters for IDs

packages/secure_storage/amplify_secure_storage_dart/lib/src/platforms/amplify_secure_storage_web.dart
- make `_database` a late initializer rather than returning it as a future
This is a workaround for https://github.com/dart-lang/sdk/issues/48835
=> fix(secure_storage): make database late initializer

packages/amplify_authenticator/lib/src/state/authenticator_state.dart, packages/amplify_authenticator/lib/src/utils/validators.dart
This PR potentially fixed #1592, but we will need additional feedback from the customer to confirm. The change is valid regardless of whether it fixes this particular issue.
Trims strings in password confirmation comparison.
=> fix(amplify_authenticator): trims strings for password confirmation diffs

packages/aws_common/lib/src/http/aws_http_request.dart, packages/aws_common/pubspec.yaml, packages/aws_signature_v4/lib/src/configuration/service_configuration.dart, packages/aws_signature_v4/lib/src/configuration/services/s3.dart, packages/aws_signature_v4/lib/src/request/canonical_request/canonical_request.dart, packages/aws_signature_v4/test/canonical_request_test.dart, packages/aws_signature_v4/test/s3/s3_service_configuration_test.dart
- Fix to include `Host` header during signing, even for presigned URLs
- Fix to not chunk requests on Web for GET/HEAD requests since browser APIs disallow sending a body for these methods
- Fix for prematurely closing an HTTP client
=> fix(aws): Minor fixes

packages/aws_signature_v4/example/bin/example.dart, packages/aws_signature_v4/lib/src/request/canonical_request/canonical_request.dart
According to the [doc]( https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html), minimum exp value is one second, and maximum exp value is 7 days. 
- change `>` to `>=` and `<` to `<=`
- modify examples to print seven days and one second link
=> fix(aws_signature_v4): Presign Min/Max Expirations

packages/amplify_authenticator/example/integration_test/sign_in_with_username_test.dart, packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_in_sign_out_test.dart
The authenticator on web was not allowing a second sign in attempt after a failure, nor was it allowing the 'Forgot Password' button.
This PR yields the UnauthenticatedStep.signIn state after a sign in failure.
=> fix(authenticator): allow second signin attempt on web

packages/amplify_core/lib/src/config/auth/cognito/authentication_flow_type.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/signin/cognito_sign_in_options.dart, packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_bridge.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/sign_in_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart, packages/auth/amplify_auth_cognito_dart/test/state/sign_in_state_machine_test.dart
Adds Dart implementation of the runtime auth flow switch to allow customizing a flow other than the default.
---
**Stack**:
- #1720
- #1719
=> feat(auth): Switch auth flow at runtime

packages/amplify_authenticator/lib/amplify_authenticator.dart, packages/auth/amplify_auth_cognito/example/lib/main.dart, packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_flutter.dart, packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_stub.dart, packages/auth/amplify_auth_cognito/lib/src/native_auth_plugin.dart, packages/auth/amplify_auth_cognito/pigeons/native_auth_plugin.dart, packages/auth/amplify_auth_cognito_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt, packages/auth/amplify_auth_cognito_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/NativeAuthPluginBindings.java, packages/auth/amplify_auth_cognito_dart/lib/amplify_auth_cognito_dart.dart, packages/auth/amplify_auth_cognito_dart/lib/src/credentials/cognito_keys.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_html.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_io.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_stub.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/signin/cognito_sign_in_with_web_ui_options.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/signin/cognito_sign_in_with_web_ui_options.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/signout/cognito_sign_out_with_web_ui_options.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/signout/cognito_sign_out_with_web_ui_options.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart, packages/auth/amplify_auth_cognito_dart/test/common/mock_hosted_ui.dart, packages/auth/amplify_auth_cognito_dart/test/plugin/sign_out_test.dart, packages/auth/amplify_auth_cognito_dart/test/state/hosted_ui_state_machine_test.dart, packages/auth/amplify_auth_cognito_ios/ios/Classes/NativeAuthPlugin.h, packages/auth/amplify_auth_cognito_ios/ios/Classes/NativeAuthPlugin.m, packages/auth/amplify_auth_cognito_ios/ios/Classes/SwiftAuthCognito.swift
Preserves the hosted UI options selected at sign in for use in sign out by saving the options in secure storage.
---
**Stack**:
- #1722
- #1721
- #1720
- #1719
=> fix(auth): Preserve Hosted UI options

packages/amplify_core/lib/src/state_machine/state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/credentials/auth_plugin_credentials_provider.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
Fixes issue where multiple successive calls to fetchAuthSession were not being sequenced properly due to the state machine needing two event loops to process an event. This is by design but was not accurately captured in the sign in and fetch auth session state machines.
---
**Stack**:
- #1723
- #1722
- #1721
- #1720
- #1719
=> fix(auth): Credential refresh on sign in

packages/auth/amplify_auth_cognito_ios/example/ios/unit_tests/amplify_auth_cognito_ios_tests.swift, packages/auth/amplify_auth_cognito_ios/ios/Classes/Device/AWSAuthDevice+Codable.swift, packages/auth/amplify_auth_cognito_ios/ios/Classes/Device/DeviceHandler.swift
Fixes #1696.
Fixes device serialization on iOS when just an ID is passed. I confirmed this issue does not exist on Android.
=> fix(auth): Fix device serialization

packages/auth/amplify_auth_cognito_dart/lib/src/credentials/auth_plugin_credentials_provider.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/fetch_auth_session_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/auth_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart, packages/auth/amplify_auth_cognito_dart/test/credentials/auth_plugin_credentials_provider_test.dart
Use same credentials provider for both SDK clients which delegates to the fetch auth session state machine to retrieve credentials for SDK requests. And ensure that we fail only in the very specific case that credentials are already being refreshed and we're making a call from the state machine.
=> fix(auth): Fix fetch auth session

packages/auth/amplify_auth_cognito/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito/lib/src/native_auth_plugin.dart, packages/auth/amplify_auth_cognito/pigeons/native_auth_plugin.dart, packages/auth/amplify_auth_cognito_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt, packages/auth/amplify_auth_cognito_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/NativeAuthPluginBindings.java, packages/auth/amplify_auth_cognito_android/android/src/test/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AmplifyHostedUiPluginTest.kt, packages/auth/amplify_auth_cognito_ios/ios/Classes/NativeAuthPlugin.h, packages/auth/amplify_auth_cognito_ios/ios/Classes/NativeAuthPlugin.m, packages/auth/amplify_auth_cognito_ios/ios/Classes/SwiftAuthCognito.swift
Adds iOS validation data to sign up as the current iOS SDK does: <a href="https://github.com/aws-amplify/amplify-ios/blob/979e39fc1437f7aeeebab1cb91a99e0fd007aa82/AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignUp/InitiateSignUp.swift#L122">https://github.com/aws-amplify/amplify-ios/blob/979e39fc1437f7aeeebab1cb91a99e0fd007aa82/AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignUp/InitiateSignUp.swift#L122</a>
Currently, Android does not add any automatically
---
**Stack**:
- #1726
- #1725
- #1724
- #1723
- #1722
- #1721
- #1720
- #1719
=> feat(auth): Validation data

packages/aws_common/lib/src/config/aws_config_value.dart
Removes dart defines from `AWSConfigValue` as a temporary solution to <a href="https://github.com/dart-lang/sdk/issues/49245">https://github.com/dart-lang/sdk/issues/49245</a>
commit-id:c75e6257
**Issue references**: 
- https://github.com/dart-lang/sdk/issues/49245---
**Stack**:
- #1728 ⬅
- #1727
- #1726
- #1725
- #1724
- #1723
- #1722
- #1721
- #1720
- #1719
=> fix(core): Remove dart define (temporary)

packages/auth/amplify_auth_cognito_dart/example/bin/example.dart
Fixes example which was throwing for user pools without device tracking enabled
=> chore(auth): Fix device tracking example

packages/api/amplify_api_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/AmplifyApi.kt, packages/api/amplify_api_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/OperationsManager.kt, packages/api/amplify_api_android/android/src/test/kotlin/com/amazonaws/amplify/amplify_api/AmplifyApiRestTest.kt, packages/api/amplify_api_android/android/src/test/kotlin/com/amazonaws/amplify/amplify_api/OperationsManagerTests.kt
Fixes concurrent access to the `OperationsManager` by using a `ConcurrentHashMap` and prevents blocking the main thread by launching cancellations in a background thread.
- https://github.com/aws-amplify/amplify-flutter/pull/1649
=> fix(api): Fix Android operation cancellation

packages/amplify_authenticator/lib/amplify_authenticator.dart, packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/amplify_authenticator/lib/src/models/authenticator_exception.dart, packages/amplify_authenticator/pubspec.yaml
Parse `message` from all thrown exceptions in Authenticator. Don't show `e.toString()` since this is probably never what we want to do. Instead, print "an unknown error has occurred" and log the message to the console.
=> chore(authenticator): Exception handling

.circleci/config.yml, canaries/dummy_amplifyconfiguration.dart, canaries/integration_test/app_test.dart, canaries/main.dart, canaries/models/ModelProvider.dart
Added canary workflow for getting started workflow(https://docs.amplify.aws/start/q/integration/flutter/). The new circleci job essentially doing the same step as described in the tutorial. 
After merging:
We will set up a trigger to run once a day(https://circleci.com/docs/2.0/scheduled-pipelines/#project-settings)
Note: We are using inline orb for now, we will extract the implementation and put in an actual orb after we've confirmed it runs successfully for couple of days, and when orb's namespace is ready to use
=> chore: add canary workflow

packages/amplify_authenticator/example/integration_test/config.dart, packages/amplify_authenticator/example/integration_test/confirm_sign_up_email_or_phone_test.dart, packages/amplify_authenticator/example/integration_test/envs/auth_with_email_or_phone.dart, packages/amplify_authenticator/example/integration_test/pages/sign_up_page.dart, packages/amplify_authenticator/lib/amplify_authenticator.dart, packages/amplify_authenticator/lib/src/keys.dart, packages/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart, packages/amplify_authenticator/lib/src/models/username_input.dart, packages/amplify_authenticator/lib/src/state/authenticator_state.dart, packages/amplify_authenticator/lib/src/widgets/form.dart, packages/amplify_authenticator/lib/src/widgets/form_field.dart, packages/amplify_test/lib/src/integration_test_utils/auth_cognito/integration_test_auth_utils.dart
- Update state management of username selection
- Add integration test for Email OR Phone configs 
=> fix(amplify_authenticator): authenticator phone OR email confirmation

packages/secure_storage/amplify_secure_storage_dart/lib/src/types/web_secure_storage_options.dart
Hosted UI requires an asynchronous exchange so some state must be persisted in between these sessions. The inMemory option cannot accommodate this currently.
=> chore(auth): Make IndexedDB default on web

packages/auth/amplify_auth_cognito/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito/lib/src/native_auth_plugin.dart, packages/auth/amplify_auth_cognito/pigeons/native_auth_plugin.dart, packages/auth/amplify_auth_cognito_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt, packages/auth/amplify_auth_cognito_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/NativeAuthPluginBindings.java, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_html.dart, packages/auth/amplify_auth_cognito_ios/ios/Classes/NativeAuthPlugin.h, packages/auth/amplify_auth_cognito_ios/ios/Classes/NativeAuthPlugin.m
Some Android custom tabs will relaunch the app on completion, requiring a different mechanism for capturing the intent data. The same was already true for Web, so that mechanism is re-leveraged in mobile (Android).
=> fix(auth): Add initial route parameters for mobile platforms

packages/auth/amplify_auth_cognito_dart/lib/src/crypto/oauth.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart
The redirect used in the exchange call for an asynchronous Hosted UI login was not matching the one used to get the authorization code which was causing the login to fail with an obtuse `unauthorized_client` error. The methods used to create/restore the grant have been moved inside HostedUiPlatform so that the internal `signInRedirectUri` getter can be used.
If runtime override of the redirect URI is ever supported, some slight changes will be required to this setup. But right now, it's not something we need to worry about.
commit-id:e0e46724
---
**Stack**:
- #1751 ⬅
- #1750
- #1749
=> fix(auth): Use same redirect for all interactions

packages/aws_signature_v4/lib/src/configuration/service_configuration.dart, packages/aws_signature_v4/test/headers_test.dart
Fixes the user agent which was not pulled in correctly from `main`: https://github.com/aws-amplify/amplify-flutter/pull/1561
=> fix(sigv4): Correct user agent

packages/amplify/amplify_flutter/lib/amplify_flutter.dart, packages/amplify/amplify_flutter/pubspec.yaml, packages/amplify_authenticator/example/lib/main.dart, packages/auth/amplify_auth_cognito/example/lib/main.dart, packages/auth/amplify_auth_cognito/lib/src/auth_plugin_impl.dart
Exposes secure-storage as an auth plugin constructor parameter.
=> feat: exposes secure-storage as plugin constructor parameter

packages/aws_signature_v4/README.md, packages/aws_signature_v4/example/bin/example.dart, packages/aws_signature_v4/example/web/main.dart, packages/aws_signature_v4/lib/src/configuration/services/s3.dart
This was made the default since it's much more efficient, especially on web for large uploads, but some S3 operations do not support it so it should not be the default. Instead, it will be selectively enabled in the SDK layer for operations which allow it.
Also cleans up example.
=> fix(sigv4): Makes chunking opt-in

packages/amplify_core/lib/src/types/auth/sign_in/auth_provider.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/1827
- Add `toString()` override to AuthProvider so that it works in localization.
=> fix(auth): add toString override of AuthProvider

packages/amplify_core/lib/src/types/auth/attribute/cognito_user_attribute_key.dart
- Add sub and identities attributes
This is a subset of the changes that went into next in https://github.com/aws-amplify/amplify-flutter/pull/1768 and https://github.com/aws-amplify/amplify-flutter/pull/1804. I did not include the rest of the changes since the changes to the `parse` constructor is breaking.
=> fix(auth): add sub and identities as standard attributes

packages/amplify_authenticator/lib/src/widgets/form.dart
- Fix an issue in the authenticator where duplicate phone fields are displayed when SMS is set as the MFA method and phone is used as the login identifier.
=> fix(authenticator): duplicate phone showing for SMS MFA

packages/amplify/amplify_flutter_android/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle, packages/api/amplify_api_android/android/build.gradle, packages/auth/amplify_auth_cognito_android/android/build.gradle, packages/storage/amplify_storage_s3_android/android/build.gradle
Upgrade amplify-android version to [1.36.1](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.36.1).
=> chore: upgrade amplify-android to 1.36.1

.github/composite_actions/fetch_backends/action.yaml, .github/composite_actions/install_dependencies/action.yaml, .github/workflows/amplify_integration_tests.yaml, .gitignore, build-support/create_integration_test_profile.sh, build-support/integ_test_android.sh, build-support/integ_test_ios.sh, build-support/pull_backend_by_app_id.sh, packages/api/amplify_api/example/tool/pull_test_backend.sh
This PR has the central config files/scripts to enable integration tests in github actions. It only actually runs them for API with the plan to enable the other categories once API passing.
=> chore: enable integration tests in gh actions

packages/amplify/amplify_flutter/lib/src/amplify_impl.dart, packages/amplify_authenticator/lib/src/utils/validators.dart, packages/amplify_lints/CHANGELOG.md, packages/amplify_lints/lib/library.yaml, packages/amplify_lints/lib/library_core.yaml, packages/auth/amplify_auth_cognito/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_flutter.dart, packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_html.dart
This is generally okay for libraries (especially when referencing our own). However, when building apps, this is usually a poor practice.
=> chore(lints): Ignore `implementation_imports` for libraries

packages/amplify_core/lib/amplify_core.dart, packages/amplify_core/lib/src/state_machine/event.dart, packages/amplify_core/lib/src/state_machine/exception.dart, packages/amplify_core/lib/src/state_machine/state_machine.dart, packages/amplify_core/test/state_machine/my_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/exception/auth_precondition_exception.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/auth_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/credential_store_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/fetch_auth_session_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/hosted_ui_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/sign_in_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/state.dart
Currently, events which do not meet preconditions are just printed and then silently ignored. However, there are good reasons that some of these precondition failures should be translated to real exceptions. For example, when the user calls `confirmSignIn` when there's no active sign-in. Before, the call would never finish because the state machine was not reporting the precondition failure as an exception. 
This PR allows state machines to surface precondition failures as exceptions so that they can be handled appropriately by users of the state machine. The previous behavior is still available as needed and this is controlled via the `shouldEmit` flag.
=> fix(core): Emit precondition errors

packages/amplify_datastore/example/integration_test/delete_test.dart
Fixes datastore delete test by expecting a DatastoreException on non-matching predicate failure.
=> fix(datastore): delete test fix

packages/amplify/amplify_flutter_ios/ios/Classes/SwiftAmplify.swift, packages/amplify/amplify_flutter_ios/ios/amplify_flutter_ios.podspec, packages/auth/amplify_auth_cognito_ios/ios/Classes/SwiftAuthCognito.swift, packages/auth/amplify_auth_cognito_ios/ios/amplify_auth_cognito_ios.podspec, packages/storage/amplify_storage_s3_ios/ios/Classes/AmplifyStorageOperations.swift, packages/storage/amplify_storage_s3_ios/ios/Classes/SwiftStorageS3.swift
Remove redundant pod dependency `AWSCognitoAuthPlugin` from `amplify` and `auth` packages. This amplify-ios plugin package should not be used going forward.
Remove unused reference of `AWSMobileClient` from s3 iOS implementation.
=> chore(amplify): remove redundant AWSCognitoAuthPlugin dependency

packages/auth/amplify_auth_cognito_dart/lib/src/state/event/credential_store_event.dart
Integration tests were failed on a 'Credential store is busy` exception. The event to clear credentails was being rejected instead of queued in the sign in state machine because the storeCredentials event was still processing.
=> fix(auth): removes success precondition from CredentialStoreClearCredentials event

packages/amplify_core/lib/src/types/auth/attribute/auth_user_attribute.dart, packages/amplify_core/lib/src/types/auth/attribute/confirm_user_attribute_request.dart, packages/amplify_core/lib/src/types/auth/attribute/fetch_user_attributes_request.dart, packages/amplify_core/lib/src/types/auth/attribute/resend_user_attribute_confirmation_code_request.dart, packages/amplify_core/lib/src/types/auth/attribute/update_user_attribute_request.dart, packages/amplify_core/lib/src/types/auth/attribute/update_user_attributes_request.dart, packages/amplify_core/lib/src/types/auth/password/confirm_reset_password_request.dart, packages/amplify_core/lib/src/types/auth/password/reset_password_request.dart, packages/amplify_core/lib/src/types/auth/password/update_password_request.dart, packages/amplify_core/lib/src/types/auth/session/auth_session_request.dart, packages/amplify_core/lib/src/types/auth/sign_in/auth_next_sign_in_step.dart, packages/amplify_core/lib/src/types/auth/sign_in/confirm_sign_in_request.dart, packages/amplify_core/lib/src/types/auth/sign_in/sign_in_request.dart, packages/amplify_core/lib/src/types/auth/sign_in/sign_in_result.dart, packages/amplify_core/lib/src/types/auth/sign_in/sign_in_with_web_ui_request.dart, packages/amplify_core/lib/src/types/auth/sign_up/confirm_sign_up_request.dart, packages/amplify_core/lib/src/types/auth/sign_up/resend_sign_up_code_request.dart, packages/amplify_core/lib/src/types/auth/sign_up/sign_up_request.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_bridge.dart
**ISSUE**: https://github.com/dart-lang/sdk/issues/49484
Workaround for DDC compiler issue. Compares classes with generic arguments on their subclass and not on the base class (which would be preferable in cases where the exact subtype is erased).
=> fix: DDC compile issue

packages/amplify_authenticator/example/integration_test/pages/confirm_sign_in_page.dart, packages/amplify_authenticator/example/integration_test/pages/sign_up_page.dart
Fixes 3 integ test failures on desktop. These tests passed on mobile, but on macos integ tests there appeared to be some sort of race condition preventing text from being entered into fields.
=> fix(authenticator): taps on widgets before entering text

packages/amplify/amplify_flutter_android/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle, packages/api/amplify_api_android/android/build.gradle, packages/auth/amplify_auth_cognito_android/android/build.gradle, packages/storage/amplify_storage_s3_android/android/build.gradle
Bumps android version to 1.36.6 to address REST API fatal exception.
=> chore: bump amplify-android dep to 1.36.3

packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart
Fixes a typo in the options type for `resetPassword`
=> fix(auth): Fix typo

packages/amplify_core/lib/src/logger/simple_printer.dart
Before
```
flutter: ERROR | SignUpStateMachine | Emitted error
flutter: ERROR | Authenticator | Error in AuthBloc
```
After
```
flutter: ERROR | SignUpStateMachine | Emitted error: InvalidParameterException [Attributes did not conform to the schema: email: The attribute is required, null, null]
#0      HttpOperation.deserializeOutput
package:smithy/…/http/http_operation.dart:278
<asynchronous suspension>
#1      AWSRetryer.retry
package:smithy_aws/…/retry/aws_retryer.dart:160
<asynchronous suspension>
#2      WrappedCognitoIdentityProviderClient.signUp
package:amplify_auth_cognito_dart/…/sdk/sdk_bridge.dart:516
<asynchronous suspension>
#3      SignUpStateMachine.onInitiate
package:amplify_auth_cognito_dart/…/machines/sign_up_state_machine.dart:42
<asynchronous suspension>
#4 …
```
=> chore(core): Emit errors/stack traces in logger

packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart, packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_exception.dart, packages/auth/amplify_auth_cognito_dart/test/sdk/sdk_exception_test.dart
Adds better error handling around Lambda errors thrown from non-hosted UI methods. Un-deprecates the `LambdaException` class since it actually provides a lot of utility and makes it easy for users to catch when they're only concerned with whether an error originated in a lambda.
=> chore(auth): Better Lambda error handling

packages/amplify/amplify_flutter_android/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle, packages/api/amplify_api_android/android/build.gradle, packages/auth/amplify_auth_cognito_android/android/build.gradle, packages/storage/amplify_storage_s3_android/android/build.gradle
#1916 
Updates to latest amplify-android with transfer service fix.
=> chore: bump amplify-android dep to 1.36.4

packages/secure_storage/amplify_secure_storage/example/pubspec.yaml, packages/secure_storage/amplify_secure_storage/example/pubspec_overrides.yaml, packages/secure_storage/amplify_secure_storage_dart/example/pubspec.yaml, packages/secure_storage/amplify_secure_storage_dart/example/pubspec_overrides.yaml, packages/secure_storage/amplify_secure_storage_dart/lib/src/interfaces/amplify_secure_storage_interface.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/mixins/amplify_secure_storage_mixin.web.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/platforms/amplify_secure_storage_web.dart, packages/secure_storage/amplify_secure_storage_dart/pubspec.yaml, packages/secure_storage/amplify_secure_storage_dart/pubspec_overrides.yaml
- Check that indexedDB can open without exceptions, add in-memory as fallback
=> chore(secure_storage): use in-memory when indexedDB fails to open

packages/amplify_core/lib/src/types/api/graphql/graphql_request.dart, packages/api/amplify_api/lib/src/graphql/send_graphql_request.dart
https://github.com/aws-amplify/amplify-flutter/issues/1217
Allows devs to pass custom headers for GraphQL http requests. 
=> feat(api): GraphQL Custom Request Headers

packages/amplify_authenticator/lib/amplify_authenticator.dart, packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/amplify_authenticator/lib/src/services/amplify_auth_service.dart, packages/amplify_authenticator/lib/src/state/authenticator_state.dart, packages/amplify_authenticator/pubspec.yaml, packages/amplify_authenticator/test/ui/tab_view_test.dart, packages/amplify_core/lib/src/config/auth/auth_config.dart, packages/amplify_core/lib/src/config/auth/cognito/credentials_provider.dart, packages/amplify_core/lib/src/config/config_map.dart, packages/amplify_core/lib/src/hub/amplify_hub_impl.dart, packages/amplify_core/lib/src/state_machine/dependency_manager.dart, packages/amplify_core/lib/src/state_machine/state_machine.dart, packages/amplify_core/test/hub/hub_test.dart, packages/auth/amplify_auth_cognito/example/lib/main.dart, packages/auth/amplify_auth_cognito/example/macos/Runner/DebugProfile.entitlements, packages/auth/amplify_auth_cognito/example/macos/Runner/Release.entitlements, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_io.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/hosted_ui_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart, packages/auth/amplify_auth_cognito_dart/test/common/mock_config.dart, packages/auth/amplify_auth_cognito_dart/test/common/mock_hosted_ui.dart, packages/auth/amplify_auth_cognito_dart/test/credentials/auth_plugin_credentials_provider_test.dart, packages/auth/amplify_auth_cognito_dart/test/flows/hostedui/hosted_ui_platform_io_test.dart, packages/auth/amplify_auth_cognito_dart/test/state/auth_state_machine_test.dart, packages/auth/amplify_auth_cognito_dart/test/state/fetch_auth_session_state_machine_test.dart, packages/auth/amplify_auth_cognito_dart/test/state/hosted_ui_state_machine_test.dart, packages/auth/amplify_auth_cognito_dart/test/state/sign_up_state_machine_test.dart
Allows multiple calls to `signInWithWebUI` so that, for example, desktop UIs do not have to be aware of the state of the launched browser. Users can launch a Hosted UI browser only to close it and re-initiate a new sign-in.
=> feat(auth): Allow multiple Hosted UI sign-in attempts

packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart
- do not return new state on sign in hub event
=> fix(authenticator): do not return new state on sign in hub event

packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_io.dart, packages/auth/amplify_auth_cognito_test/test/common/mock_config.dart, packages/auth/amplify_auth_cognito_test/test/flows/hostedui/hosted_ui_platform_io_test.dart
Fixes https://github.com/aws-amplify/amplify-flutter/issues/2011
Fixes an issue where, on certain platforms, the open server connection is not closed before trying to force close the server.
=> fix(auth): Hosted UI server contention

packages/api/amplify_api/lib/src/decorators/authorize_http_request.dart, packages/api/amplify_api/test/authorize_http_request_test.dart, packages/api/amplify_api/test/util.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/util/cognito_user_pools_auth_provider.dart, packages/auth/amplify_auth_cognito_dart/test/plugin/auth_providers_test.dart
This PR enables cognito user pools auth mode in HTTP requests for API category, thus enabling REST and query/mutate in GraphQL. It does so by defining an auth provider in the auth plugin that provides the access token as a header to HTTP requests. In API plugin, that auth provider is used to authorize HTTP requests.
=> feat(auth,api): cognito user pools auth provider & auth mode for API HTTP requests

packages/auth/amplify_auth_cognito_ios/ios/Classes/HostedUIFlow.swift, packages/auth/amplify_auth_cognito_ios/ios/Classes/SwiftAuthCognito.swift
Fixes #2015
Use callbacks instead of async/await in Hosted UI flow to avoid task continuation errors from mishandled async code.
=> fix(auth): Hosted UI task continuation

packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/credentials/cognito_keys.dart, packages/auth/amplify_auth_cognito_dart/lib/src/credentials/device_metadata_repository.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/device/confirm_device_worker.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/device/confirm_device_worker.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_device_password_verifier_worker.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_helper.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_password_verifier_worker.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/cognito_device_secrets.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/cognito_device_secrets.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/cognito_user.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/cognito_user.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_user_pool_tokens.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/cognito_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/credential_store_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/credential_store_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/state/credential_store_state.dart, packages/auth/amplify_auth_cognito_test/test/common/mock_config.dart, packages/auth/amplify_auth_cognito_test/test/common/mock_secure_storage.dart, packages/auth/amplify_auth_cognito_test/test/flows/device/confirm_device_worker_test.dart, packages/auth/amplify_auth_cognito_test/test/flows/hostedui/hosted_ui_platform_test.dart, packages/auth/amplify_auth_cognito_test/test/flows/srp/srp_helper_test.dart, packages/auth/amplify_auth_cognito_test/test/state/credential_store_state_machine_test.dart
Fixes issue 1 of #2009 by not clearing the device credentials on log out, only when uninstalling the app or calling `forgetDevice`. Refactors the internal device metadata as well. Related to #1929.
=> fix(auth): Remember device metadata

packages/amplify/amplify_flutter_android/android/build.gradle, packages/amplify/amplify_flutter_ios/ios/amplify_flutter_ios.podspec, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/amplify_datastore/example/ios/unit_tests/QueryPredicateBuilderUnitTests.swift, packages/amplify_datastore/ios/Classes/types/model/FlutterSerializedModel.swift, packages/amplify_datastore/ios/Classes/types/query/QueryPredicateBuilder.swift, packages/amplify_datastore/ios/amplify_datastore.podspec, packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle, packages/analytics/amplify_analytics_pinpoint_ios/ios/amplify_analytics_pinpoint_ios.podspec, packages/api/amplify_api_android/android/build.gradle, packages/api/amplify_api_ios/ios/amplify_api_ios.podspec, packages/auth/amplify_auth_cognito_android/android/build.gradle, packages/auth/amplify_auth_cognito_ios/ios/amplify_auth_cognito_ios.podspec, packages/storage/amplify_storage_s3_android/android/build.gradle, packages/storage/amplify_storage_s3_ios/ios/amplify_storage_s3_ios.podspec
* Adapt [this amplify-ios change](https://github.com/aws-amplify/amplify-ios/pull/2077) for custom primary key feature 
* [chore: bump amplify-ios to 1.28.0](https://github.com/aws-amplify/amplify-flutter/pull/2005/commits/ff1a16ec297ec15f8c9b7a2509c9163db0d36615)
* [chore: bump amplify-android to 1.37.0](https://github.com/aws-amplify/amplify-flutter/pull/2005/commits/8a5b424e3cc8426748cec33a2342bb9ad56b43ce)
Do not merge until amplify-ios fix is released.
=> fix(datastore): adapt amplify-ios CPK fix breaking change

packages/amplify_datastore/example/integration_test/separate_integration_tests/cpk_has_many_bidirectional_implicit_test.dart, packages/amplify_datastore/example/integration_test/separate_integration_tests/cpk_one_to_one_bidirectional_implicit_belongs_to_custom_id_test.dart, packages/amplify_datastore/example/integration_test/utils/test_cloud_synced_model_operation.dart, packages/amplify_datastore/example/tool/schema.graphql
* Add tests for caught issues.
* Update the integration test provision schema
=> chore(datastore): improve custom primary key integration tests

.github/workflows/amplify_integration_tests.yaml, packages/auth/amplify_auth_cognito/example/tool/pull_test_backend.sh
Enables integration tests in CI for auth category.
=> chore(auth): enable integration tests in CI

.github/ISSUE_TEMPLATE/BUG-REPORT.yaml
Adds the following info to the bug report template:
- Whether the CLI or another mechanism was used to deploy their backend
- Their sanitized amplifyconfig
These both seem to provide a lot of insight and they can be missed in the conversation, especially the first one. We cannot assume that people filing issues are using pristine Amplify-generated backends.
=> chore(repo): Update bug report to include deployment option

packages/auth/amplify_auth_cognito_dart/lib/src/model/cognito_user.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/cognito_user.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart, packages/auth/amplify_auth_cognito_test/test/state/sign_in_state_machine_test.dart
Fixes #2029
Fixes a regression caused by #2010 for non-device flows where the state machine expects device secrets even though none are present.
=> fix(auth): CognitoDeviceSecrets attempts to build without secrets

packages/auth/amplify_auth_cognito_dart/CHANGELOG.md, packages/auth/amplify_auth_cognito_dart/lib/src/model/cognito_user.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/cognito_user.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart, packages/auth/amplify_auth_cognito_dart/pubspec.yaml, packages/auth/amplify_auth_cognito_test/test/state/sign_in_state_machine_test.dart
Depends on #2021
- fix: CognitoDeviceSecrets attempts to build without secrets ([#2021](https://github.com/aws-amplify/amplify-flutter/pull/2021))
=> chore(amplify_auth_cognito_dart): v0.1.5

packages/amplify_core/lib/src/http/amplify_http_client.dart
Distinguishes Amplify Flutter users from those using Amplify outside of Flutter, e.g. in a Dart web or server application, in the user agent for reporting purposes.
=> chore(core): Distinguish user agent

packages/auth/amplify_auth_cognito_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt
Fixes an issue discovered while investigating #2013
Fixes a redirect issue in older versions of Chrome which is resolved by adding a certain set of flags to launch the custom tab in a new window.
=> fix(auth): Android redirect in older Chromes

packages/amplify/amplify_flutter/lib/src/hybrid_impl.dart, packages/amplify_authenticator/lib/src/models/authenticator_exception.dart, packages/amplify_core/lib/src/amplify_class.dart, packages/amplify_core/lib/src/types/analytics/exceptions/analytics_exception.dart, packages/amplify_core/lib/src/types/api/exceptions/api_exception.dart, packages/amplify_core/lib/src/types/datastore/exception/datstore_exception.dart, packages/amplify_core/lib/src/types/exception/amplify_already_configured_exception.dart, packages/amplify_core/lib/src/types/exception/amplify_exception.dart, packages/amplify_core/lib/src/types/exception/auth/auth_exception.dart, packages/amplify_core/lib/src/types/exception/codegen_exception.dart, packages/amplify_core/lib/src/types/storage/exceptions/storage_exception.dart, packages/auth/amplify_auth_cognito/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_io.dart, packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_exception.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/exception/secure_storage_exception.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/utils/dynamic_library_utils.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/platforms/amplify_secure_storage_cupertino.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/platforms/amplify_secure_storage_windows.dart
This allows both strings and raw `Exception`/`Error` types to be passed which can support `is` checks in the future after all code is migrated.
=> chore: Use `Object?` for `underlyingException`

packages/auth/amplify_auth_cognito_ios/ios/Classes/HostedUIFlow.swift, packages/auth/amplify_auth_cognito_ios/ios/Classes/SwiftAuthCognito.swift
This reverts commit c16e4dd424afcbb91e6b40bd545d8449b1e56d30.
Originally proposed as a fix to #2015 which turned out to be not needed. Async/await provides a much cleaner syntax and is good to gain exposure with.
=> Revert "fix(auth): Hosted UI task continuation (#2017)"

packages/amplify_authenticator/example/integration_test/pages/authenticator_page.dart, packages/amplify_authenticator/example/integration_test/verify_user_test.dart, packages/amplify_authenticator/lib/amplify_authenticator.dart, packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/amplify_authenticator/lib/src/state/auth_state.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/2041
- Add a new state for pending verification
- Emit new state when verification is started 
=> feat(authenticator): handle `AuthHubEventType.signedIn`

packages/api/amplify_api/example/tool/schema.graphql
API integration tests were failing. This was because they use codegen models from amplify_test package, where another field was added to the schema. The provisioned backend didn't have that field, so appsync was giving some errors when trying to include in a selection set (which the model helpers will do from codegen models). To fix it, you can just add that field to the backend. This PR adds in provision script so it will be fixed in any newly provisioned backend.
=> chore(api): add field to schema in provision script

build-support/dependencies.rb, melos.yaml, packages/amplify/amplify_flutter_ios/ios/amplify_flutter_ios.podspec, packages/amplify/amplify_flutter_ios/ios/dependencies.rb, packages/amplify_authenticator/test/ui/theme_test.dart, packages/amplify_core/ios/amplify_core.podspec, packages/amplify_core/ios/dependencies.rb, packages/api/amplify_api_ios/ios/amplify_api_ios.podspec
Fixes build issue by pinning SwiftLint to an older version which supports macOS 11, Swift < 5.6. See https://github.com/realm/SwiftLint/issues/4131.
=> chore(ci): Pin SwiftLint version

packages/auth/amplify_auth_cognito_test/test/jwt/util_test.dart
Fixes analyzer error for calling `toString` in a String interpolation.
=> chore(auth): Fix analyzer error

packages/amplify_core/ios/amplify_core.podspec
Fixes https://github.com/aws-amplify/amplify-flutter/issues/2098.
Fixes an issue surfaced in Flutter 3.3.0 which configures XCode projects based off this value. Previously, if the value was <9, the logic would apply. Now if the value is <11, the logic applies. We don't want this logic to apply.
The previous value was incorrect anyway so it's a good change to make regardless.
=> fix(core): Podspec deployment target

packages/aft/lib/src/commands/bootstrap_command.dart
vs. pub get. This provides a better experience in most cases esp since this is how tests are configured to run - so this will prevent build errors due simply to an outdated dependency.
=> chore(aft): Make `pub upgrade` the default

.github/composite_actions/fetch_backends/action.yaml, .github/composite_actions/install_dependencies/action.yaml, .github/workflows/amplify_integration_tests.yaml, .gitignore, build-support/create_integration_test_profile.sh, build-support/integ_test_android.sh, build-support/integ_test_ios.sh, build-support/pull_backend_by_app_id.sh, packages/api/amplify_api/example/tool/pull_test_backend.sh
This PR cherry picks https://github.com/aws-amplify/amplify-flutter/commit/31a5a0daf1dd79d34648d6291b63d230b0811367 from main to next to enable integ tests in next branch. I also had to make another commit to run `aft bs` instead of `melos bs`.
=> chore: enable integration tests in gh actions (#1754)

packages/amplify_core/lib/amplify_core.dart
And, by extension `amplify_flutter` which already exports `amplify_core`. This aligns the exports with `next`.
Fixes #2092.
=> chore(core): Export `safePrint` from amplify_core

packages/worker_bee/worker_bee/lib/src/common.dart, packages/worker_bee/worker_bee/lib/src/js/impl.dart
Reduce log level of internal messages to `debug` to avoid printing expected events as errors. For example, workers closing was reporting as error but this happens when hot restarting in Flutter. Since the result also completes with an error, there's no need to report it if the result value is not needed.
Likewise, the one in `impl.dart` is expected in certain cases and will print when falling back to a different JS file. In the case no files are usable it will throw an Error which is surfaced through the appropriate mechanisms.
=> chore(worker_bee): Soften log level of internal messages

packages/storage/amplify_storage_s3/lib/amplify_storage_s3.dart, packages/storage/amplify_storage_s3/lib/method_channel_storage_s3.dart, packages/storage/amplify_storage_s3/lib/src/s3_prefix_resolver/amplify_storage_s3_prefix_resolver.dart, packages/storage/amplify_storage_s3/test/amplify_storage_s3_prefix_test.dart, packages/storage/amplify_storage_s3/test/amplify_storage_s3_transferprogress_test.dart, packages/storage/amplify_storage_s3_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/StorageS3.kt, packages/storage/amplify_storage_s3_android/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/types/FlutterPrefixResolver.kt, packages/storage/amplify_storage_s3_ios/ios/Classes/FlutterPrefixResolver.swift, packages/storage/amplify_storage_s3_ios/ios/Classes/SwiftStorageS3.swift
Modify method channels to call native layer support for custom prefix.
https://github.com/aws-amplify/amplify-flutter/issues/416
Call custom prefix in native side. 
=> feat(storage) : Support custom prefix

packages/amplify_core/lib/src/category/amplify_datastore_category.dart
There is a bug on next where adding Datastore plugin throws an error which can be reproduced simply by trying to run example app. This is related to changes for multiple plugins per category where `plugins` is unmodifiable. This PR just changes to `_plugins` so it can be modified (added to).
Verified by running example app and integration tests.
=> fix(datastore): correct plugin configuration

packages/auth/amplify_auth_cognito/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart
Since plugin types are erased via the category wrappers, do not use them in the input signature since generics cannot be reified this way. Perform casts within the plugin to revive the types.
=> fix(auth): Erase plugin interface input types

.github/workflows/amplify_integration_tests.yaml, packages/auth/amplify_auth_cognito/example/tool/pull_test_backend.sh, packages/storage/amplify_storage_s3/example/integration_test/main_test.dart, packages/storage/amplify_storage_s3/example/tool/pull_test_backend.sh
Cherry picks commits e4ceb156cf9eb6d203db56648cbdb416e793822d and f0e5480b1040df5a20899a83030941c4813138cb off main to enable auth and storage integ tests in next branch on merge in gh actions. Added another commit to comment out an assertion that was causing failure.
Plan to merge this PR w rebase option so all 3 commits end up on next same as main.
=> chore(auth,storage): enable integ tests in CI

packages/amplify_core/lib/src/types/auth/session/auth_session_options.dart, packages/auth/amplify_auth_cognito/example/integration_test/force_refresh_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_session_options.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_session_options.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart, packages/auth/amplify_auth_cognito_test/test/state/fetch_auth_session_state_machine_test.dart
Adds a `forceRefresh` parameter which allows overriding the default refresh logic to perform refreshes on an as-needed basis.
=> feat(auth): Force refresh

packages/amplify_authenticator/lib/src/mixins/authenticator_date_field.dart, packages/amplify_authenticator/lib/src/mixins/authenticator_phone_field.dart, packages/amplify_authenticator/lib/src/mixins/authenticator_radio_field.dart, packages/amplify_authenticator/lib/src/mixins/authenticator_text_field.dart, packages/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart, packages/amplify_authenticator/lib/src/widgets/form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_in_form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_up_form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/phone_number_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/reset_password_form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/sign_in_form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/sign_up_form_field.dart, packages/amplify_authenticator/lib/src/widgets/form_fields/verify_user_form_field.dart
Due to ongoing issues with DDC which rear their head in certain unavoidable cases (like using zapp.run which compiles apps as a single DDC module)
=> chore(authenticator): simplify use of generics

packages/amplify/amplify_flutter/build.yaml, packages/api/amplify_api/build.yaml
Fixes errors running `build_runner` when a package's example has nested symlink'd directories. This should be the default for all Flutter packages using `build_runner`.
=> chore: Add build.yaml

packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift
https://github.com/aws-amplify/amplify-flutter/issues/2108
Exclude custom type from amplify-ios primary key parsing.
=> fix(datastore): cpk errors on a custom type

packages/amplify/amplify_flutter/CHANGELOG.md, packages/amplify/amplify_flutter/pubspec.yaml, packages/amplify/amplify_flutter_ios/CHANGELOG.md, packages/amplify/amplify_flutter_ios/pubspec.yaml, packages/amplify_datastore/CHANGELOG.md, packages/amplify_datastore/pubspec.yaml, packages/amplify_datastore_plugin_interface/CHANGELOG.md, packages/amplify_datastore_plugin_interface/pubspec.yaml, packages/analytics/amplify_analytics_pinpoint/CHANGELOG.md, packages/analytics/amplify_analytics_pinpoint/pubspec.yaml, packages/api/amplify_api/CHANGELOG.md, packages/api/amplify_api/pubspec.yaml, packages/api/amplify_api_ios/CHANGELOG.md, packages/api/amplify_api_ios/pubspec.yaml, packages/auth/amplify_auth_cognito_ios/CHANGELOG.md, packages/auth/amplify_auth_cognito_ios/pubspec.yaml, packages/storage/amplify_storage_s3/CHANGELOG.md, packages/storage/amplify_storage_s3/pubspec.yaml
Dependency pinning is no longer needed - packages are allowed to individually vary and be published as needed and new aft commands make sure it all works.
Fixes #2152.
=> chore: Unpin dependencies

.circleci/config.yml
Enhancement for the getting started workflow in circleCI(https://github.com/aws-amplify/amplify-flutter/pull/1656). We added cloudwatch monitoring for the workflow, so the devops team could get notified right away if there's any issues with the workflow. The change should not alter any existing behavior.
=> chore: add cloudwatch monitoring for getting started smoke test

packages/amplify_core/lib/src/types/storage/remove_result.dart, packages/storage/amplify_storage_s3_dart/example/bin/example.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_get_properties_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_get_url_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_list_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_models.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_remove_many_operation.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_remove_many_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_remove_many_result.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_remove_operation.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_remove_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_remove_result.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service.dart/storage_s3_service_test.dart, packages/storage/amplify_storage_s3_dart/test/utils/custom_matchers.dart, packages/storage/amplify_storage_s3_dart/test/utils/mocks.dart
1. Implemented `remove` and `removeMany` APIs
2. Added relevant unit tests
3. Added `remove` API usage example in `example.dart` (remove any will be added later when `S3Client.deleteObjects` issue gets resolved)
4. Fixes and adjustments here and there
=> feat(storage): implement remove and removeMany APIs

packages/aws_common/lib/src/http/aws_http_client_io.dart, packages/aws_common/test/http/client_conformance_tests/response_body_test.dart
The heuristics here for automatically reading a response body were based off internal discussions with the team for how a general-purpose HTTP client should behave.
In HTTP/1.1, the streaming mechanism is called [chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) - the idea with the previous behavior was to ensure that non-streaming responses would complete with an `AWSHttpResponse` instead of an `AWSStreamedHttpResponse`. However, the heuristic seems incomplete, at best. While several resources point to this being the sole way of differentiating a streaming from non-streaming responses, like [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding), practical experience with S3 shows that it may not always be accurate. And …
=> chore(http): Do not automatically read responses

packages/api/amplify_api/lib/src/graphql/ws/web_socket_connection.dart, packages/api/amplify_api/test/ws/web_socket_connection_test.dart
Adds unit test coverage for reconnection workflows: wifi on/off, and failed pings. 
=> Chore(API): GraphQL Reconnection Unit Tests

packages/amplify_core/lib/src/types/storage/get_properties_result.dart, packages/amplify_core/lib/src/types/storage/list_operation.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_get_properties_result.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_storage_get_url_result.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service.dart/storage_s3_service_test.dart
1. Fixed typos in the codebase
2. Added missed `expiresAt` field to `S3StorageGetUrlResult`
=> fix(storage): add missing expiresAt of S3StorageGetUrlResult

packages/auth/amplify_auth_cognito_dart/lib/amplify_auth_cognito_dart.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/auth_user_ext.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
Makes getting Cognito items from JWTs easier, e.g. Cognito groups (https://github.com/aws-amplify/amplify-flutter/discussions/2221):
Before
```dart
final session =
await Amplify.Auth.fetchAuthSession() as CognitoAuthSession;
final idToken = session.userPoolTokens!.idToken;
final userGroups =
(idToken.claims.customClaims['cognito:groups'] as List?)
?.cast<String>() ??
const [];
```
After
```dart
final session =
await Amplify.Auth.fetchAuthSession() as CognitoAuthSession;
final idToken = session.userPoolTokens!.idToken;
final userGroups = idToken.groups;
```
=> chore(auth): Export Cognito JWT helpers

packages/amplify_test/lib/test_models/Comment.dart, packages/amplify_test/lib/test_models/Post.dart
- Adds a field back to a generated model that was removed in https://github.com/aws-amplify/amplify-flutter/pull/2043
=> chore(api): add `targetName` to generated models used in tests

.circleci/config.yml, packages/amplify_datastore_plugin_interface/test/amplify_modelschema_to_map_test.dart
- enable DataStore plugin interface tests in CI
- fix failing tests
=> chore(datastore): enable DataStore plugin interface tests in CI

packages/auth/amplify_auth_cognito/example/analysis_options.yaml, packages/auth/amplify_auth_cognito/example/backend/tool/create_config.dart, packages/auth/amplify_auth_cognito/example/integration_test/custom_auth_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/delete_user_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/fetch_auth_session_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/get_current_user_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/hub_events_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/main_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_in_sign_out_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/update_password_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/user_attributes_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/utils/setup_utils.dart, packages/auth/amplify_auth_cognito/example/lib/main.dart, packages/auth/amplify_auth_cognito/example/lib/screens/confirm_reset.dart, packages/auth/amplify_auth_cognito/example/lib/screens/confirm_sign_in.dart, packages/auth/amplify_auth_cognito/example/lib/screens/confirm_sign_up.dart, packages/auth/amplify_auth_cognito/example/lib/screens/confirm_user_attribute.dart, packages/auth/amplify_auth_cognito/example/lib/screens/sign_in.dart, packages/auth/amplify_auth_cognito/example/lib/screens/sign_up.dart, packages/auth/amplify_auth_cognito/example/lib/screens/update_password.dart, packages/auth/amplify_auth_cognito/example/lib/screens/update_user_attributes.dart, packages/auth/amplify_auth_cognito/example/lib/screens/view_user_attributes.dart, packages/auth/amplify_auth_cognito/example/pubspec.yaml
Enables amplify_lints in Auth integration tests and example app. Cleans up a few incorrect integration tests.
=> test(auth): Enable lints for integration tests

packages/aws_common/lib/src/http/aws_http_client.dart, packages/aws_common/test/http/http_client_test.dart
Fixes #2241. Fixes an infinite loop by referencing `super` instead of `this`.
=> fix(http): `transformRequest` results in loop

.github/composite_actions/fetch_backends/action.yaml
Fixes error during `amplify pull` in integ tests in CI.
We changed the dummy config produced by aft and that throws an error from Amplify CLI pull command. This PR just removes those dummy files before running amplify pull.
=> chore: fix CI integ tests by removing dummy config

packages/aws_common/lib/src/http/aws_http_client.dart, packages/aws_common/lib/src/http/aws_http_client_io.dart, packages/aws_common/test/http/downgrade_server.dart, packages/aws_common/test/http/downgrade_server_vm.dart, packages/aws_common/test/http/downgrade_server_web.dart, packages/aws_common/test/http/downgrade_test.dart, packages/aws_common/test/http/http_common.dart
Improve usability of the HTTP client by downgrading to HTTP/1.1 when HTTP/2 is unavailable. This allows setting the default to a more reasonable 1/2/3 setting so that things will _generally_ work as expected.
=> feat(http): Downgrade to HTTP/1.1 when possible

packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_device_password_verifier_worker.dart, packages/auth/amplify_auth_cognito_test/test/flows/srp/srp_device_password_verifier_worker_test.dart
Adds missing serializers to `SrpDevicePasswordVerifierWorker` required by #2220.
=> fix(auth): Add serializers to `SrpDevicePasswordVerifierWorker`

packages/auth/amplify_auth_cognito/example/backend/bin/backend.ts, packages/auth/amplify_auth_cognito/example/integration_test/device_tracking_bypass_mfa_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/device_tracking_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart
Device credential caching is updated in accordance with [Cognito docs](https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/) around when device credentials are cleared:
> The credentials provided to the device should be persistent and will be stored by the AWS Mobile SDKs, so any logic you build on top of the device key as an identifier can assume it will not change. The only way it could change is if the user wipes the device’s storage, if the user uninstalls the application, or if the ForgetDevice API is called for a device (this API removes all tracked devices for a user).
=> fix(auth): Device credential caching

packages/smithy/goldens/lib2/custom/lib/s3.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/common/serializers.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/model/copy_object_error.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/model/copy_object_error.g.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/model/copy_object_output.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/model/copy_object_output.g.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/model/copy_object_request.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/model/copy_object_request.g.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/model/copy_object_result.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/model/copy_object_result.g.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/operation/copy_object_operation.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/s3_client.dart, packages/smithy/goldens/lib2/custom/lib/src/s3/s3_server.dart, packages/smithy/goldens/lib2/custom/test/s3/copy_object_operation_test.dart, packages/smithy/goldens/models2/custom/s3.smithy, packages/smithy/smithy_aws/lib/smithy_aws.dart, packages/smithy/smithy_aws/lib/src/http/interceptors/s3/check_error_on_success.dart, packages/smithy/smithy_aws/lib/src/protocol/rest_xml.dart, packages/smithy/smithy_codegen/lib/src/generator/types.dart, packages/smithy/smithy_codegen/lib/src/util/protocol_ext.dart
Some S3 operations return an error in a 2xx response. Since this mechanism is not supported in Smithy, we need to add a manual check, as is done in other S3 clients (e.g. https://github.com/aws/aws-sdk-go-v2/blob/76d88204196e5d5513fb1845e0cc50ec84ffeada/service/s3/internal/customizations/handle_200_error.go#L21)
=> fix(smithy): Add check for 2xx errors in S3 client

.circleci/config.yml
Here is the error from the log
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.version-check'.
> Minimum supported Gradle version is 7.3.3. Current version is 7.2. If using the gradle wrapper, try editing the distributionUrl in /home/circleci/flutter-canaries/amplified_todo/android/gradle/wrapper/gradle-wrapper.properties to gradle-7.3.3-all.zip
Upgrading to a newer android executor to use newer version of gradle to fix the problem 
Spec for this version: https://discuss.circleci.com/t/android-machine-executor-images-2022-july-update/44874
Tested in personal circleci project: https://app.circleci.com/pipelines/github/yeung-wah/amplify-flutter/598/workflows/3e939579-1de3-4ae7-bb36-e7f993c4e3b9 …
=> chore: fix android canary test

.github/composite_actions/fetch_backends/action.yaml, .github/workflows/amplify_integration_tests.yaml, packages/amplify_datastore/example/tool/pull_test_backend.sh, packages/api/amplify_api/example/tool/pull_test_backend.sh, packages/auth/amplify_auth_cognito/example/tool/pull_test_backend.sh, packages/storage/amplify_storage_s3/example/tool/pull_test_backend.sh
Migrates integration test secrets from github action secrets to AWS Secrets Manager.
=> chore: use AWS secrets manager for CI integ secrets

packages/smithy/goldens/lib/restJson1/lib/src/api_gateway/api_gateway_client.dart, packages/smithy/goldens/lib/restXml/lib/src/s3/s3_client.dart, packages/smithy/goldens/lib2/restJson1/lib/src/api_gateway/api_gateway_client.dart, packages/smithy/goldens/lib2/restXml/lib/src/s3/s3_client.dart, packages/smithy/smithy/lib/src/behavior/paginated_result.dart, packages/smithy/smithy/lib/src/http/http_operation.dart, packages/smithy/smithy_codegen/lib/src/generator/service_client_generator.dart, packages/smithy/smithy_codegen/lib/src/generator/types.dart
Support a larger variety of use cases by exposing the `nextContinuationToken` which can be used to make further requests to the service as needed.
=> feat(smithy): Expose `nextContinuationToken` from `PaginatedResult`

packages/api/amplify_api/example/integration_test/graphql/api_key_test.dart, packages/api/amplify_api/example/integration_test/graphql/iam_test.dart, packages/api/amplify_api/example/integration_test/graphql/user_pools_test.dart, packages/api/amplify_api/example/integration_test/rest_test.dart, packages/api/amplify_api/example/integration_test/util.dart, packages/api/amplify_api/example/test_driver/integration_test.dart, packages/api/amplify_api/lib/src/graphql/utils.dart
This PR does 2 things:
1) fixes issue with API model helpers in web due to "$" added to name conversion in dart on web
2) adds web support for integration tests and some changes to integ test utils
=> fix(api): fix model helper util on web

.github/composite_actions/fetch_backends/action.yaml, .github/workflows/amplify_integration_tests.yaml, packages/api/amplify_api/example/tool/pull_test_backend.sh, packages/auth/amplify_auth_cognito/example/tool/pull_test_backend.sh, packages/storage/amplify_storage_s3/example/tool/pull_test_backend.sh
A few fixes for integration tests:
* cherry-picks https://github.com/aws-amplify/amplify-flutter/commit/66542af4792618fe586e805bad63a48ac3b622b9 off main to start using secrets from AWS secrets manager
* changes auth integration test pull script to get new auth backend config from s3
* runs auth tests on web in CI
=> chore: integration test improvements

packages/amplify_core/lib/src/types/storage/list_options.dart, packages/amplify_core/lib/src/types/storage/list_result.dart, packages/storage/amplify_storage_s3_dart/example/bin/example.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_list_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_list_result.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_download_task_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart, packages/storage/amplify_storage_s3_dart/test/test_utils/mocks.dart
1. refactored `S3Client` SDK API calls to adapt the `SmithyOperation`
2. Revised `list` API to align with other amplify library Storage `list` API interface
=> fix(storage): refactor codebase for SDK changes returning SmithyOperation

packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_bridge.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/auth_state_machine.dart
Supports a custom Cognito endpoint as described here: https://aws.amazon.com/blogs/security/protect-public-clients-for-amazon-cognito-by-using-an-amazon-cloudfront-proxy/
=> fix(auth): Support Cognito proxies

packages/aws_common/lib/src/http/aws_http_client.dart, packages/aws_common/lib/src/http/aws_http_request.dart, packages/aws_common/lib/src/http/mock.dart, packages/aws_common/test/http/aws_http_request_test.dart, packages/aws_common/test/http/http_client_test.dart, packages/aws_signature_v4/test/s3/testdata/e2e_test.dart, packages/aws_signature_v4/test/streamed_request_test.dart, packages/smithy/smithy/lib/src/behavior/retryer.dart, packages/smithy/smithy/lib/src/http/http_operation.dart, packages/smithy/smithy/lib/src/http/http_request.dart, packages/smithy/smithy/test/http/http_operation_test.dart, packages/smithy/smithy_aws/lib/src/http/retry/aws_retryer.dart
- Fixes an issue where progress listeners had events added to them after closing.
- Adds tests for `HttpOperation`
=> test(smithy): Add HttpOperation tests

packages/smithy/smithy/lib/src/http/http_operation.dart, packages/smithy/smithy_aws/lib/src/endpoint/partition.dart
The logic for choosing a protocol from the partition's supported protocols was incorrect resulting in `http` taking precedence over `https`.
=> fix(smithy): Incorrect port/scheme

packages/aws_common/lib/src/http/aws_http_client.dart, packages/aws_common/test/http/http_client_transform_test.dart
2 fixes for `AWSHttpClient`:
1) fixes issue when canceling a request if the progress steam has data
2) brings in fix from API branch on https://github.com/aws-amplify/amplify-flutter/pull/2148/files#diff-10c115ad022b838f8361e9a6adae79bb0f61d30e82984f616124997694e53ae0 to properly handle errors during response transformation
=> fix(aws_common): fix HTTP cancel error/transform error

packages/auth/amplify_auth_cognito/example/backend/lib/stack.ts
This PR removes some WAF rules that are causing CI integ tests to fail bc auth requests are blocked by the firewall.
=> chore(auth): change WAF for integ test stack

packages/aft/lib/src/commands/bootstrap_command.dart
`build_runner` only needs to run for packages which require assets built for development. The other packages only need it run on publish.
=> chore(aft): Speed up bootstrap

.github/composite_actions/fetch_backends/action.yaml, .github/workflows/amplify_integration_tests.yaml, build-support/integ_test_android.sh, build-support/integ_test_ios.sh, packages/amplify_datastore/example/integration_test/model_type_test.dart, packages/amplify_datastore/example/integration_test/query_test/query_predicate_test/aws_time_query_predicate_test.dart, packages/amplify_datastore/example/integration_test/query_test/sort_order_test.dart, packages/amplify_datastore/example/integration_test/utils/sort_order_utils.dart, packages/amplify_datastore/example/tool/pull_test_backend.sh
Cherry picks 7307233838d9acd323b614242477c74596429e3f off main and adds another commit to skip tests on android for tests related to `AWSTime` which are failing due to https://github.com/aws-amplify/amplify-flutter/issues/2214
=> chore(datastore): run integ tests in CI on next

.github/composite_actions/fetch_backends/action.yaml, .github/composite_actions/install_dependencies/action.yaml, .github/workflows/amplify_integration_tests.yaml, build-support/integ_test.sh, build-support/integ_test_ios.sh, melos.yaml
This PR does the following:
* enables linux integ tests in CI (just auth for now)
* enables macos integ tests in CI (just auth for now)
* various optimizations/cleanups in integ tests scripts/configs like updating community actions, removing unnecessary steps, etc...
=> chore: enable linux/macos integ tests in CI

packages/aws_signature_v4/lib/src/configuration/service_configuration.dart, packages/aws_signature_v4/lib/src/configuration/services/s3.dart, packages/aws_signature_v4/lib/src/signer/aws_signer.dart, packages/aws_signature_v4/test/c_test_suite/test_data.dart, packages/aws_signature_v4/test/s3/s3_service_configuration_test.dart
Adds `signBody` as a parameter to `ServiceConfiguration` so that it can be configured on a per-client basis, as suggested by the test suite.
=> fix(sigv4): Make body signing configurable

packages/amplify_core/lib/amplify_core.dart, packages/amplify_core/lib/src/types/common/amplify_auth_provider.dart, packages/api/amplify_api/example/integration_test/rest_test.dart, packages/api/amplify_api/lib/src/api_plugin_impl.dart, packages/api/amplify_api/lib/src/decorators/authorize_http_request.dart, packages/api/amplify_api/lib/src/graphql/ws/web_socket_connection.dart, packages/api/amplify_api/pubspec.yaml, packages/api/amplify_api/test/authorize_http_request_test.dart, packages/api/amplify_api/test/util.dart, packages/auth/amplify_auth_cognito_dart/lib/src/util/cognito_iam_auth_provider.dart, packages/auth/amplify_auth_cognito_test/test/plugin/auth_providers_test.dart
This PR fixes an issue for REST API on web in IAM auth mode where requests with bodies are signed with the `signBody` option that generates an HTTP header `x-amz-content-sha256` that is not allowed by default CORS policies of Amplify API Gateway endpoints. The end user gets a CORS error for any request with a body on web with IAM mode (without manually changing API Gateway CORS policies).
This PR changes the signer settings for REST API gateway so that the body is not signed and this header is never added. The result is that REST API works on web without manual API Gateway changes. The majority of REST integration tests are thus enabled here on web.
There is also a small change to the pubspec file for API to prep for release and some import sorting.
By submitting this pull request, I …
=>  fix(api): do not signBody for REST IAM

.github/workflows/build.yml, .github/workflows/test.yml, packages/storage/amplify_storage_s3_dart/mono_pkg.yaml
* changed `build_test` of amplify_storage_s3_dart package to run on macos instead of linux to get around of the compiler crash issue
* Enable `unit_test` amplify_storage_s3_dart package running on windows and macos
=> chore(storage): enable storage s3 unit tests on macos

packages/amplify_authenticator/lib/src/state/auth_state.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/2311
- Remove an unnecessary assertion in PendingVerificationCheckState. This assertion checked that current step was signIn or confirmSignUp. There is no reason to have this assertion, and it was problematic after a password reset.
=> fix(authenticator): remove unnecessary assertion in PendingVerificationCheckState constructor

packages/aws_common/lib/src/js/indexed_db.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/platforms/amplify_secure_storage_web.dart
Fixes some errors in latest Dart versions where `external` properties fail to work in `staticInterop` extensions. Since these are just syntactic sugar for `js_util` calls, we replace them inline and that seems to fix it.
Failing tests: https://github.com/aws-amplify/amplify-flutter/actions/runs/3415095778/jobs/5683932363
=> fix(secure_storage): IndexedDB interop issues

packages/api/amplify_api/test/graphql_helpers_test.dart
Fixes a call to `addPlugin` which is expected to fail when extending from MethodChannelAPI in tests
=> fix(api): MockAmplifyAPI `addPlugin` call

packages/amplify/amplify_flutter_ios/ios/amplify_flutter_ios.podspec, packages/amplify_datastore/ios/amplify_datastore.podspec, packages/analytics/amplify_analytics_pinpoint_ios/ios/amplify_analytics_pinpoint_ios.podspec, packages/api/amplify_api_ios/ios/amplify_api_ios.podspec, packages/auth/amplify_auth_cognito_ios/ios/amplify_auth_cognito_ios.podspec, packages/storage/amplify_storage_s3_ios/ios/amplify_storage_s3_ios.podspec
=> chore: Bump iOS dependency

.gitmodules
Use github mirror of `libsecret` instead of (what appears to be) a self-hosted gitlab instance which is unreliable
=> chore(repo): Update `libsecret` submodule URL

packages/amplify_core/lib/src/types/storage/base/storage_controllable_operation.dart, packages/amplify_core/lib/src/types/storage/download_data_operation.dart, packages/amplify_core/lib/src/types/storage/download_file_operation.dart, packages/amplify_core/lib/src/types/storage/upload_data_operation.dart, packages/amplify_core/lib/src/types/storage/upload_file_operation.dart, packages/storage/amplify_storage_s3_dart/example/bin/example.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_data_operation.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_file_operation.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_get_url_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_transfer_progress.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_data_operation.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_file_operation.dart, packages/storage/amplify_storage_s3_dart/lib/src/platform_impl/download_file/download_file_html.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart, packages/storage/amplify_storage_s3_dart/test/platform_impl/download_file_io_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
* Calling `SmithyOperation.cancel` to cancel underlying http requests on upload operation pause and cancel.
=> feat(storage): cancel SmithyOperation on upload pause and cancel

packages/amplify_authenticator/lib/amplify_authenticator.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/2332
- Only place a `Navigator` widget in the tree for Unauthenticated states
Note: This does not solve the issue for customers using `AuthenticatedView`. To solve this, `Localizations.override()` needs to be removed from `AuthenticatedView`, but this leads to a new issue - https://github.com/flutter/flutter/issues/115159. Future changes related to navigation in the Authenticator may resolve this issue though.
=> chore(authenticator): remove navigator from tree for AuthenticatedState

packages/amplify/amplify_flutter_ios/ios/amplify_flutter_ios.podspec, packages/amplify_datastore/ios/amplify_datastore.podspec, packages/analytics/amplify_analytics_pinpoint_ios/ios/amplify_analytics_pinpoint_ios.podspec, packages/api/amplify_api_ios/ios/amplify_api_ios.podspec, packages/auth/amplify_auth_cognito_ios/ios/amplify_auth_cognito_ios.podspec, packages/storage/amplify_storage_s3_ios/ios/amplify_storage_s3_ios.podspec
- fixing DataStore not syncing records after network reconnection
=> chore: bump amplify-ios to 1.28.3

README.md, packages/amplify/amplify_flutter/README.md, packages/amplify_core/README.md, packages/amplify_datastore/README.md, packages/analytics/amplify_analytics_pinpoint/README.md, packages/api/amplify_api/README.md, packages/auth/amplify_auth_cognito/README.md, packages/storage/amplify_storage_s3/README.md
Adds Analytics to green checks in platform support to the tables that were previously only modified for API/Storage.
=> chore: add analytics to platform support tables

aft.yaml, packages/amplify/amplify_flutter/pubspec.yaml, packages/amplify_test/pubspec.yaml, packages/analytics/amplify_analytics_pinpoint/pubspec.yaml, packages/analytics/amplify_analytics_pinpoint_dart/pubspec.yaml, packages/api/amplify_api/pubspec.yaml, packages/common/amplify_db_common/example/pubspec.yaml, packages/common/amplify_db_common/pubspec.yaml, packages/common/amplify_db_common_dart/example/pubspec.yaml, packages/common/amplify_db_common_dart/pubspec.yaml, packages/storage/amplify_storage_s3/example/pubspec.yaml, packages/storage/amplify_storage_s3/pubspec.yaml, packages/storage/amplify_storage_s3_dart/pubspec.yaml
Updates dependencies throughout the repo. `pub` does not approve of setting version constraints to `any` as we were doing before. `aft.yaml` is leveraged to keep `drift` dependency in sync.
`dev_dependencies` versions are conflicting with `dependencies` versions on publish. New rule is don't list a version for repo packages in `dev_dependencies` since it will be handled by `pubspec_overrides` anyway.
=> chore(repo): Update dependencies

packages/amplify/amplify_flutter/CHANGELOG.md, packages/amplify/amplify_flutter/lib/src/hybrid_impl.dart, packages/amplify/amplify_flutter/pubspec.yaml
Configure all plugins in hybrid impl. That this was not done originally for all plugins was a miss due to earlier implementations of the `configure` method.
=> fix(core): Configure all plugins

packages/auth/amplify_auth_cognito/example/integration_test/sign_in_sign_out_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
Reverts part of f050f3b99da6d5631b35c4dbefb1feef2dfb2bc8. The reason for the initial change was a faulty assumption about unauthenticated identities and how they should be retained during a transition from signed out to signed in.
Since unauthenticated identities are vended at the start of most sessions, upgrading each unauthenticated identity to an authenticated identity would create many disparate identities. Instead, we want a singular authenticated identity to be assigned per user.
=> revert(auth): "fix(auth): Retain unauthenticated identities"

packages/analytics/amplify_analytics_pinpoint/example/lib/main.dart, packages/analytics/amplify_analytics_pinpoint/example/macos/Runner.xcodeproj/project.pbxproj, packages/analytics/amplify_analytics_pinpoint/example/macos/Runner/DebugProfile.entitlements, packages/analytics/amplify_analytics_pinpoint/example/macos/Runner/Release.entitlements, packages/api/amplify_api/example/lib/main.dart, packages/api/amplify_api/example/macos/Runner.xcodeproj/project.pbxproj, packages/api/amplify_api/example/macos/Runner/DebugProfile.entitlements, packages/api/amplify_api/example/macos/Runner/Release.entitlements, packages/auth/amplify_auth_cognito/example/lib/main.dart, packages/aws_common/lib/src/io/aws_file.dart, packages/storage/amplify_storage_s3/example/lib/main.dart, packages/storage/amplify_storage_s3/example/macos/Runner/DebugProfile.entitlements, packages/storage/amplify_storage_s3/example/macos/Runner/Release.entitlements
- Aligns all example apps to share the same secure storage settings and warnings suggesting alternate usage in production cases.
- Aligns macOS Xcode settings to have Keychain Sharing disabled, Network permissions enabled, and deployment target set to 10.15.
=> chore(repo): Align example app secure storage settings

.github/workflows/amplify_integration_tests.yaml, build-support/integ_test.sh, packages/api/amplify_api/example/integration_test/util.dart, packages/api/amplify_api/example/macos/Podfile
Enables integ tests in CI for API category on MacOS and linux. There are some config changes to make that work in the API example app as well as a change to a test script from https://github.com/aws-amplify/amplify-flutter/pull/2388.
=> chore(api): integ tests in CI for mac/linux

.github/composite_actions/setup_firefox/action.yaml, .github/workflows/dart_dart2js.yaml, .github/workflows/dart_ddc.yaml
GitHub Actions runners have moved from Ubuntu 20.04 -> 22.04 for `ubuntu-latest` and no longer set up Firefox+Geckodriver by default.
=> ci: Set up Firefox in ubuntu-latest

packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_user_pool_tokens.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart, packages/auth/amplify_auth_cognito_test/test/state/fetch_auth_session_state_machine_test.dart
Since access and ID tokens can have different expiration times, refresh all tokens when either token expires.
=> fix(auth): Refresh tokens when either access or ID token expires

.github/workflows/amplify_integration_tests.yaml, packages/analytics/amplify_analytics_pinpoint/example/integration_test/events_test.dart, packages/analytics/amplify_analytics_pinpoint/example/test_driver/integration_test.dart, packages/analytics/amplify_analytics_pinpoint/example/tool/pull_test_backend.sh, packages/analytics/amplify_analytics_pinpoint/lib/src/analytics_plugin_impl.dart
Cherry picks 026cc9daa4582a4ecc9fc1d0117e9beddde83a07 from main to enable analytics tests in CI for Android/iOS and then adds another commit to enable in mac/web/linux.
=> chore(analytics): integ tests in CI

packages/api/amplify_api/lib/src/graphql/ws/web_socket_connection.dart
This PR fixes a race condition in API GraphQL subscriptions that is causing auth integ tests to fail. The issue arises when establishing a subscription on a connection that is in the process of being closed, causing an error from trying to send over a closed socket. This PR fixes it by moving some async logic so that the check of connection open/closed while establishing a subscription happens later and will open a new connection.
This fix is a little hacky and would usually have some more unit tests. I didn't do that here because 1) all this will be replaced by subscription state machine 2) the auth integ tests are already serving a sort of check here.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> fix(api): fix subscription race condition from previous connection close

packages/amplify_core/lib/src/category/amplify_api_category.dart
Issue: https://github.com/aws-amplify/amplify-flutter/issues/2412
Adds missing queryParameters arg to the amplify API RestOperations
=> fix(api): Missing query parameters in REST operations

packages/amplify_core/lib/src/category/amplify_auth_category.dart, packages/amplify_core/lib/src/plugin/amplify_auth_plugin_interface.dart, packages/amplify_core/lib/src/plugin/amplify_plugin_key.dart, packages/amplify_core/lib/src/types/auth/attribute/auth_user_attribute.dart, packages/amplify_core/lib/src/types/auth/attribute/auth_user_attribute.g.dart, packages/amplify_core/lib/src/types/auth/attribute/auth_user_attribute_key.dart, packages/amplify_core/lib/src/types/auth/attribute/cognito_user_attribute_key.dart, packages/amplify_core/lib/src/types/auth/attribute/confirm_user_attribute_request.dart, packages/amplify_core/lib/src/types/auth/attribute/confirm_user_attribute_request.g.dart, packages/amplify_core/lib/src/types/auth/attribute/resend_user_attribute_confirmation_code_request.dart, packages/amplify_core/lib/src/types/auth/attribute/resend_user_attribute_confirmation_code_request.g.dart, packages/amplify_core/lib/src/types/auth/attribute/update_user_attribute_request.dart, packages/amplify_core/lib/src/types/auth/attribute/update_user_attribute_request.g.dart, packages/amplify_core/lib/src/types/auth/attribute/update_user_attributes_request.dart, packages/amplify_core/lib/src/types/auth/attribute/update_user_attributes_request.g.dart, packages/amplify_core/lib/src/types/auth/auth_types.dart, packages/amplify_core/lib/src/types/auth/sign_in/auth_next_sign_in_step.dart, packages/amplify_core/lib/src/types/auth/sign_in/auth_next_sign_in_step.g.dart, packages/amplify_core/lib/src/types/auth/sign_in/sign_in_result.dart, packages/amplify_core/lib/src/types/auth/sign_in/sign_in_result.g.dart, packages/auth/amplify_auth_cognito/example/integration_test/user_attributes_test.dart, packages/auth/amplify_auth_cognito/example/lib/screens/confirm_user_attribute.dart, packages/auth/amplify_auth_cognito_dart/example/lib/common.dart
For consistency with other platforms
=> chore(auth): Rename `UserAttributeKey` to `AuthUserAttributeKey`

.circleci/test_all_plugins.sh
Are you tired of all PR/merge builds failing no matter how awesome they are? Do you want it to stop? This PR is for you.
Datastore flutter unit tests consistently fail in Circle CI. No one has been able to repro or explain it. The same tests run in Github actions without issue. This PR just makes the datastore flutter unit tests skip and exit w status 0 in Circle CI. We need to actually remove them as a check in the repo settings, but access to repo settings is limited so this will help builds be green until that happens.
=> chore(datastore): skip flutter unit tests in Circle CI

packages/amplify_core/lib/src/types/auth/sign_out/sign_out_result.dart, packages/auth/amplify_auth_cognito_dart/lib/amplify_auth_cognito_dart.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/signout/cognito_sign_out_result.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart, packages/auth/amplify_auth_cognito_test/test/plugin/sign_out_test.dart
Align with other platforms and support cases where sign out only partially succeeds/fails.
=> feat(auth)!: Support partial sign out cases

packages/amplify_core/lib/src/config/auth/cognito/auth.g.dart, packages/amplify_core/lib/src/config/auth/cognito/authentication_flow_type.dart, packages/amplify_core/test/config/cli_config_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/signin/cognito_sign_in_options.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_bridge.dart, packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_exception.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/sign_in_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart, packages/auth/amplify_auth_cognito_test/test/state/sign_in_state_machine_test.dart
In favor of more precise `customAuthWithSrp` and `customAuthWithoutSrp`. Retain old behavior for `customAuth` since the new values do not have corresponding `amplifyconfiguration.dart` values.
=> chore(auth): Deprecate customAuth flow type

packages/amplify_core/lib/src/types/auth/sign_up/sign_up_result.dart, packages/amplify_core/lib/src/types/auth/sign_up/sign_up_result.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/signup/cognito_sign_up_result.dart
Moves `userId` to the category-level result.
=> chore(auth): Fix SignUpResult interface

.github/composite_actions/fetch_backends/action.yaml, .github/composite_actions/install_dependencies/action.yaml, .github/workflows/amplify_integration_tests.yaml, build-support/pull_backend_by_app_id.sh, packages/api/amplify_api/example/integration_test/graphql/api_key_test.dart, packages/api/amplify_api/example/integration_test/graphql/iam_test.dart, packages/api/amplify_api/example/integration_test/graphql/user_pools_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/device_tracking_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/get_current_user_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/mfa_sms_test.dart
This PR enables running integration tests in Windows for applicable packages.
I noticed there is an issue closing WebSocket connections related to GraphQL subscriptions (something related to https://pub.dev/packages/connectivity_plus) so skipping those tests on Windows here until I figure that out.
=> chore: run integ tests for Windows in CI

packages/aws_common/lib/src/http/aws_http_client_js.dart, packages/aws_common/test/http/cancellation_test.dart
Fixes issues with multiple synchronous calls to `cancel` on JS
=> fix(http): Synchronous cancellations on JS

.github/workflows/amplify_integration_tests.yaml, build-support/integ_test.sh, packages/amplify_authenticator/example/integration_test/confirm_sign_up_email_or_phone_test.dart, packages/amplify_authenticator/example/integration_test/confirm_sign_up_test.dart, packages/amplify_authenticator/example/integration_test/sign_in_with_email_test.dart, packages/amplify_test/lib/src/integration_test_utils/auth_cognito/integration_test_auth_utils.dart, packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/device_tracking_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/mfa_sms_test.dart
There is some flakiness in CI with auth integ tests in web where they timeout. Although it's tough to tell exactly where/why they timeout in CI bc the output is opaque, I have been able to reproduce a timeout locally with those tests (likely due to my high latency network). While I'm not certain this PR will fix the CI flakiness, it has a few things to help:
1) adds establish completers to GQL subscriptions related to OTP codes to ensure subscription established before calling the auth method that will cause the code to be sent. (This eliminated the timeouts from my local env.)
2) Uses the integ test script for web in CI so that it will retry like the other platforms.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> chore(auth): reduce race conditions in integ test GQL subscriptions

packages/api/amplify_api/example/analysis_options.yaml, packages/api/amplify_api/example/integration_test/graphql/api_key_test.dart, packages/api/amplify_api/example/integration_test/graphql/iam_test.dart, packages/api/amplify_api/example/integration_test/graphql/user_pools_test.dart, packages/api/amplify_api/example/integration_test/util.dart, packages/api/amplify_api/example/lib/graphql_api_view.dart, packages/api/amplify_api/example/lib/main.dart, packages/api/amplify_api/example/lib/rest_api_view.dart
Formatting changes only here with a small type change. Vast majority were done automatically with a few manual changes.
This PR changes analysis_options.yaml from app_core.yaml to app.yaml and makes necessary changes to pass stricter requirements.
=> chore(api): change example app to app.yaml analysis_options

packages/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/amplify_core/lib/src/types/auth/sign_in/sign_in_result.dart, packages/amplify_core/lib/src/types/auth/sign_in/sign_in_result.g.dart, packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/custom_auth_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/device_tracking_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/federated_sign_in_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/force_refresh_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/get_current_user_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/mfa_sms_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_in_sign_out_test.dart, packages/auth/amplify_auth_cognito/example/lib/screens/confirm_sign_in.dart, packages/auth/amplify_auth_cognito/example/lib/screens/sign_in.dart, packages/auth/amplify_auth_cognito_dart/example/bin/example.dart, packages/auth/amplify_auth_cognito_dart/example/web/components/app_component.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/signin/cognito_sign_in_result.dart
To align with other platforms and improve DX.
=> chore(auth)!: Make sign in result's `nextStep` non-null

packages/amplify_core/lib/src/types/auth/attribute/auth_user_attribute_key.dart, packages/amplify_core/lib/src/types/auth/attribute/cognito_user_attribute_key.dart
Adds standard OIDC claims (https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) to the generic `AuthUserAttributeKey` to align with other platforms.
=> chore(auth): Add standard claims to `AuthUserAttributeKey`

packages/aft/lib/src/commands/generate/generate_sdk_command.dart
to create and use flattened model files for local copy of models same as what is done for models’ git repo.
=> chore(aft): fix temp model dir structure for using local models

packages/authenticator/amplify_authenticator/lib/amplify_authenticator.dart, packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_date_field.dart, packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_text_field.dart, packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart, packages/authenticator/amplify_authenticator/lib/src/widgets/form_field.dart, packages/authenticator/amplify_authenticator/test/authenticated_view_test.dart, packages/authenticator/amplify_authenticator_test/lib/src/mock_authenticator_app.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/1999
- Add `onFieldSubmitted` callback to form fields to handle form submission via keyboard enter key
- wrap AuthenticatedView in a FocusTraversalGroup to ensure consistent tab order even when used alongside other widgets
- Add widget tests for AuthenticatedView keyboard navigation
=> fix(authenticator): keyboard navigation

packages/amplify_core/CHANGELOG.md, packages/amplify_core/pubspec.yaml, packages/api/amplify_api/CHANGELOG.md, packages/api/amplify_api/pubspec.yaml, packages/auth/amplify_auth_cognito/CHANGELOG.md, packages/auth/amplify_auth_cognito/pubspec.yaml, packages/auth/amplify_auth_cognito_dart/CHANGELOG.md, packages/auth/amplify_auth_cognito_dart/pubspec.yaml, packages/authenticator/amplify_authenticator/CHANGELOG.md, packages/authenticator/amplify_authenticator/pubspec.yaml, packages/aws_common/CHANGELOG.md, packages/aws_common/pubspec.yaml, packages/smithy/smithy/CHANGELOG.md, packages/smithy/smithy/pubspec.yaml, packages/smithy/smithy_aws/CHANGELOG.md, packages/smithy/smithy_aws/pubspec.yaml
- fix(api): Race condition at bloc close
- fix(auth): Add `no-store` cache control header
- fix(authenticator): keyboard navigation ([#2473](https://github.com/aws-amplify/amplify-flutter/pull/2473))
Updated-Components: Smithy, Amplify Dart, amplify_core, amplify_api, amplify_auth_cognito
=> chore(version): vNext release

packages/authenticator/amplify_authenticator/lib/src/screens/authenticator_screen.dart, packages/authenticator/amplify_authenticator/lib/src/state/authenticator_state.dart, packages/authenticator/amplify_authenticator/test/sign_in_form_test.dart, packages/authenticator/amplify_authenticator_test/lib/src/pages/sign_in_page.dart, packages/authenticator/amplify_authenticator_test/lib/src/pages/sign_up_page.dart
Currently, navigation via the `TabBar` does not change the internal step which causes issues submitting forms after navigation.
**Repro**
- Fill in username/password on signIn page
- Press tab to go to signUp
- Fill in remaining fields & press Enter to submit
- Notice signIn is called instead of signUp
=> fix(authenticator): Navigation via TabBar

.github/workflows/amplify_integration_tests.yaml
There's currently a single retry for integ tests on all platforms. A few people pointed our this might obscure errors so I removed them here for every platform expect Android (which has issues w emulator starting). I also added a timeout to all platforms. 
=> chore(test): remove integ test retries and add timeouts

packages/api/amplify_api/lib/src/graphql/web_socket/blocs/web_socket_bloc.dart, packages/api/amplify_api/test/util.dart, packages/api/amplify_api/test/web_socket/web_socket_bloc_test.dart
This PR prevents a race condition error in GraphQL subscriptions. Sometimes, when a bloc is closing (which closes the underlying websocket) there will be a brief period of time where the bloc's internal event stream controller is closed but it still gets events from the websocket channel. This throws an error bc the stream controller is already closed.
This PR fixes it by ignoring events when the controller is closed and shutdown is pending/complete.
=> fix(api): prevent GQL subscription race condition error after shutdown

packages/api/amplify_api/example/integration_test/graphql/api_key_test.dart, packages/api/amplify_api/example/integration_test/util.dart, packages/api/amplify_api/lib/src/graphql/web_socket/types/web_socket_types.dart, packages/api/amplify_api/test/web_socket/web_socket_types_test.dart
This provides a fix for an error I saw when errors were present in the SubscriptionDataPayload fromJson method. Errors come from AppSync as a List not a Map.
=> fix(api): SubscriptionDataPayload error decoding type fix

packages/api/amplify_api/example/integration_test/graphql/api_key_test.dart, packages/api/amplify_api/example/integration_test/graphql/iam_test.dart, packages/api/amplify_api/example/integration_test/graphql/user_pools_test.dart, packages/api/amplify_api/example/integration_test/util.dart
This PR modifies a few API integ tests to reduce flakiness:
* no longer looks for specific blog entries in a list request response because there is no guarantee first page of responses will have newly created entries if the backend already has a lot of data. Just checking that the list has some blogs is sufficient.
* Require all subscription tests that use a util to pass a filter callback for the events. If this is not provided, it causes issues with getting events from other clients using the backend at the same time (like tests on another platform in CI). This came up in a recently added test for errors but should be required for all similar tests in the future.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
=> chore(api): reduce integ test flakiness

packages/api/amplify_api/lib/src/graphql/web_socket/blocs/web_socket_bloc.dart, packages/api/amplify_api/test/web_socket/web_socket_bloc_test.dart
Fixes some issues I discovered while debugging https://github.com/aws-amplify/amplify-flutter/issues/2499.
While the underlying issues in above issue are 1) subscription selection set was not a subset of mutation selection set which causes AppSync error 2) error not parsed correctly, fixed in https://github.com/aws-amplify/amplify-flutter/pull/2483, I also noticed that any similar error would get completely swallowed making it difficult to debug. Further, the `WebSocketBloc` gets stuck in an error state so that user cannot make a new subscription.
This PR fixes that by calling an error utility already used other places. That error utility passes down the errors to subscription streams so that users can see them. It also disconnects the bloc (and underlying WebSocket) and cleans it up. …
=> fix(api): improve GQL subscription error visibility/recovery

packages/secure_storage/amplify_secure_storage_dart/lib/src/platforms/amplify_secure_storage_cupertino.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/types/amplify_secure_storage_config.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/types/ios_secure_storage_options.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/types/ios_secure_storage_options.g.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/types/macos_secure_storage_options.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/types/macos_secure_storage_options.g.dart
This PR fixes iOS legacy data migration which was broken when https://github.com/aws-amplify/amplify-flutter/pull/2023 was merged, which added a default `accessible` value for Keychain queries. The PR changes the default iOS/MacOS Keychain options to all be `null` when using the `byNameSpace` constructor so that keychain defaults are used. This aligns with the iOS SDK.
=> fix(auth): legacy data migration for iOS

.github/workflows/dart_dart2js.yaml, .github/workflows/dart_ddc.yaml, .github/workflows/dart_vm.yaml
Testing on the bleeding edge leads to too many false negatives in CI workflows. The `beta` channel gives us enough of a heads up for changes coming down the pipeline.
=> ci(repo): Use Dart `beta` channel instead of `dev`

packages/authenticator/amplify_authenticator/example/lib/l10n/amplify_en.arb, packages/authenticator/amplify_authenticator/example/lib/l10n/amplify_es.arb, packages/authenticator/amplify_authenticator/example/lib/resolvers/localized_button_resolver.dart
Removes unnecessary commas causing `pub get` failures on newer flutter versions
=> fix(authenticator): ARB syntax

packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/get_current_user_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/user_attributes_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/utils/mock_data.dart
Using a single mock phone number led to exceptions when multiple users were created with the same phone number. Any number in the range `555-0100` through `555-0199` are reserved for fictional use (https://en.wikipedia.org/wiki/555_(telephone_number)), so generate random numbers with this pattern.
=> test(auth): Fix mock phone numbers

.github/composite_actions/install_dependencies/action.yaml, .github/workflows/amplify_integration_tests.yaml
Broke due to changes in #2068.
=> ci(repo): Fix integration test runner

.github/workflows/amplify_auth_cognito_dart.yaml, .github/workflows/amplify_auth_cognito_test.yaml, .github/workflows/amplify_core.yaml, .github/workflows/amplify_db_common_dart.yaml, .github/workflows/amplify_secure_storage_test.yaml, .github/workflows/amplify_storage_s3_dart.yaml, .github/workflows/aws_common.yaml, .github/workflows/aws_json1_0_v1.yaml, .github/workflows/aws_json1_0_v2.yaml, .github/workflows/aws_json1_1_v1.yaml, .github/workflows/aws_json1_1_v2.yaml, .github/workflows/aws_signature_v4.yaml, .github/workflows/dart_dart2js.yaml, .github/workflows/dart_ddc.yaml, .github/workflows/dart_native.yaml, .github/workflows/dart_vm.yaml, .github/workflows/rest_json1_v1.yaml, .github/workflows/rest_json1_v2.yaml, .github/workflows/rest_xml_v1.yaml, .github/workflows/rest_xml_v2.yaml, .github/workflows/rest_xml_with_namespace_v1.yaml, .github/workflows/rest_xml_with_namespace_v2.yaml, .github/workflows/smithy.yaml, .github/workflows/smithy_aws.yaml, .github/workflows/smithy_codegen.yaml, packages/aft/lib/src/commands/generate/generate_workflows_command.dart
- Missing GITHUB_TOKEN for Firefox tests
- Enables DDC/native workflows to run on PRs by default
=> ci(repo): Enable DDC/native workflows in PRs

packages/amplify/amplify_flutter_android/android/build.gradle, packages/amplify_core/android/build.gradle, packages/amplify_datastore/android/build.gradle, packages/amplify_datastore/android/src/test/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStoreHubTest.kt, packages/analytics/amplify_analytics_pinpoint_android/android/build.gradle, packages/api/amplify_api_android/android/build.gradle, packages/auth/amplify_auth_cognito_android/android/build.gradle, packages/storage/amplify_storage_s3_android/android/build.gradle
- fixes customer issue: https://github.com/aws-amplify/amplify-flutter/issues/2193
=> chore: bump amplify-android dep to 1.37.10

packages/amplify_core/lib/src/types/analytics/analytics/analytics_user_profile.dart, packages/analytics/amplify_analytics_pinpoint/example/integration_test/identify_user_test.dart, packages/analytics/amplify_analytics_pinpoint/example/lib/main.dart, packages/analytics/amplify_analytics_pinpoint/lib/amplify_analytics_pinpoint.dart, packages/analytics/amplify_analytics_pinpoint_dart/lib/amplify_analytics_pinpoint_dart.dart, packages/analytics/amplify_analytics_pinpoint_dart/lib/src/impl/analytics_client/endpoint_client/aws_pinpoint_user_profile.dart, packages/analytics/amplify_analytics_pinpoint_dart/lib/src/impl/analytics_client/endpoint_client/endpoint_client.dart
Allow users to call `identifyUser` with an  AWSPinpointUserProfile that has an additional user attributes field so attributes can be related to users and not the endpoint.  This is to have feature parity with Amplify Android which does the same thing.  
=> chore(analytics): support Pinpoint User Attributes

packages/amplify_test/lib/src/integration_test_utils/auth_cognito/integration_test_auth_utils.dart, packages/amplify_test/pubspec.yaml
The `graphql` dependency is not really needed and is currently causing tests to break throughout due to it implementing an interface in a Dart pkg which recently changed.
=> chore(amplify_test): Remove `graphql` dependency

packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_test/test/plugin/delete_user_test.dart, packages/auth/amplify_auth_cognito_test/test/plugin/fetch_user_attributes_test.dart, packages/auth/amplify_auth_cognito_test/test/plugin/sign_out_test.dart
Currently, we are just pulling the tokens from the cache for calls not part of the state machine. This separates the API into two so that the majority funnel through `fetchAuthSession` which can handle token expiration appropriately.
=> fix(auth): Refresh token in non-state machine calls

packages/api/amplify_api/example/integration_test/util.dart
The API integration tests are failing to cleanup some blog entries which causes the backend DDB table to bloat, which eventually causes some tests to fail/get flaky. This PR fixes it by ensuring a recent test cleans up after itself.
=> chore(api): improve integ test artifact cleanup

CONTRIBUTING.md
*issue:*
- packages/aft uses git submodules. therfore we need to init and update submodules otherwise `melos bootstrap` or `aft bootstrap` will fail. 
- the contributing doc is missing instruction on init and update git submodules when cloning the repo.
- updated the contributing doc to init and update git submodules when cloning the repo.
=> chore: update contributing doc to init and update git submodules

packages/auth/amplify_auth_cognito_test/pubspec.yaml
This PR changes a test dependency that got missed in recent migration. It just leaves version/path blank bc `aft` will override with local path when linking repo.
=> chore(test): change test dep to local

packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
https://github.com/aws-amplify/amplify-flutter/issues/2591
=> fix(storage): incorrect transferred bytes emitted from upload task

infra/lib/storage/stack.ts, packages/aws_common/lib/src/io/aws_file_platform_html.dart, packages/aws_common/test/io/aws_file_html_test.dart, packages/aws_common/test/io/aws_file_io_test.dart, packages/smithy/smithy_aws/lib/src/s3/s3_client_config.dart, packages/storage/amplify_storage_s3/example/integration_test/main_test.dart, packages/storage/amplify_storage_s3/example/integration_test/transfer_acceleration/test_acceleration_config.dart, packages/storage/amplify_storage_s3/example/integration_test/transfer_acceleration/transfer_acceleration.dart, packages/storage/amplify_storage_s3_dart/example/bin/example.dart, packages/storage/amplify_storage_s3_dart/lib/src/exception/s3_storage_exception.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_data_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_file_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_get_url_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_data_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_file_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/platform_impl/download_file/download_file_html.dart, packages/storage/amplify_storage_s3_dart/lib/src/platform_impl/download_file/download_file_io.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_download_task_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
https://github.com/aws-amplify/amplify-flutter/issues/2510
1. Update infra storage stack to enable transfer acceleration for the buckets
2. Add `useAcceleration` param to corresponding operation options interface
3. Update s3 service to create `S3Client` instance per each operation and not using a singleton (S3Client configuration may changes per operation, per use case)
4. Update `DateTime` comparison in unit tests
=> feat(storage): allow configuring transfer acceleration 

packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_test/test/plugin/sign_out_test.dart
Fixes #2602.
In #2436, the logic was changed around Hosted UI to allow users to cancel the sign out flow if they dismissed the Hosted UI popup. On Web, we redirect the page, so there is no opportunity to cancel this way and we lose all state upon returning.
The more logical pathway is to clear credentials, then redirect, on Web. This aligns with JS behavior.
=> fix(auth): Clear credentials before redirect on Web

packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_test/test/plugin/fetch_auth_session_test.dart
Fixes a regression introduced by https://github.com/aws-amplify/amplify-flutter/pull/2585. When refreshing user pool tokens fail due to an expired refresh token, a hub event for Session Expired should be emitted.
=> fix(auth): SessionExpired Auth Hub event

packages/authenticator/amplify_authenticator/.pubignore
Remove example dir from `.pubignore` so Pana can find it when evaluating the pub score. 
=> chore(authenticator): Remove example dir from .pubignore

.github/ISSUE_TEMPLATE/BUG-REPORT.yaml
The current bug report template is very long and may discourage people from submitting feedback. While many of these would be great to know, only some are needed to begin triaging correctly.
I've removed the ask for their Amplify config as well. I've noticed some people are not sure how to provide it and that more often than not, it's the `schema.graphql` we need rather.
=> chore(repo): Slim down bug report template

packages/aws_common/lib/src/http/aws_http_client_io.dart, packages/aws_common/lib/src/http/aws_http_client_js.dart, packages/aws_common/lib/src/operation/aws_operation.dart, packages/aws_common/test/http/cancellation_server.dart, packages/aws_common/test/http/cancellation_test.dart, packages/aws_common/test/http/http_common.dart, packages/aws_sdk/smoke_test/test/s3_test.dart, packages/smithy/smithy/lib/src/http/http_operation.dart
Allow for the ability to cancel streamed responses via the body `Stream` only (vs. the operation, which will have already completed).
=> fix(http): Cancel streamed responses

.circleci/config.yml, melos.yaml, packages/aft/README.md, packages/aft/bin/aft.dart, packages/aft/lib/aft.dart, packages/aft/lib/src/changelog/changelog.dart, packages/aft/lib/src/changelog/commit_message.dart, packages/aft/lib/src/changelog/parser.dart, packages/aft/lib/src/changelog/printer.dart, packages/aft/lib/src/command_runner.dart, packages/aft/lib/src/commands/amplify_command.dart, packages/aft/lib/src/commands/bootstrap_command.dart, packages/aft/lib/src/commands/clean_command.dart, packages/aft/lib/src/commands/deps_command.dart, packages/aft/lib/src/commands/exec_command.dart, packages/aft/lib/src/commands/generate/generate_workflows_command.dart, packages/aft/lib/src/commands/link_command.dart, packages/aft/lib/src/commands/list_packages_command.dart, packages/aft/lib/src/commands/passthrough_command.dart, packages/aft/lib/src/commands/pub_command.dart, packages/aft/lib/src/commands/publish_command.dart, packages/aft/lib/src/commands/version_bump_command.dart, packages/aft/lib/src/options/fail_fast_option.dart, packages/aft/lib/src/options/git_ref_options.dart, packages/aft/lib/src/options/glob_options.dart, packages/aft/lib/src/pub/pub_runner.dart, packages/aft/lib/src/repo.dart, packages/aft/lib/src/util.dart, packages/aft/pubspec.yaml
Adds an `aft exec` command to run scripts in all packages or a subset of packages in the repo.
As part of this, some refactoring work is included which passes through any command not implemented by `aft` to `dart`/`flutter`. For example, `aft analyze` will run `dart analyze` or `flutter analyze` depending on the package.
Also removes dependency on `flutter_tools` package which should make working with `aft` easier.
Example usage:
- `aft exec ls` -- runs `ls` in all packages and logs the outputs
- `aft exec --include="Smithy" -- aft pub upgrade` -- runs `dart pub upgrade` in all Smithy component packages
- `aft exec --include="*example*,sample_app" -- cp -n <AFT_ROOT>/.circleci/dummy_amplifyconfiguration.dart lib/amplifyconfiguration.dart` -- copies default configuration to all example …
=> feat(aft): Add `aft exec` command

infra/lib/auth/custom-authorizer-iam/stack.ts, infra/lib/auth/schema.graphql, infra/lib/auth/stack.create-user.ts, infra/lib/auth/stack.ts, infra/lib/stack.ts, packages/amplify_test/lib/src/integration_test_utils/auth_cognito/integration_test_auth_utils.dart, packages/auth/amplify_auth_cognito/example/integration_test/device_tracking_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
When using an alias (such as email), Cognito will assign a random UUID as the "username" of the user. We should use this to track device information so that sign-in attempts with different aliases can use the same device info.
=> fix(auth): Device tracking with alias

packages/amplify_core/lib/src/plugin/amplify_plugin_key.dart, packages/amplify_core/lib/src/types/storage/download_data_operation.dart, packages/amplify_core/lib/src/types/storage/download_file_operation.dart, packages/storage/amplify_storage_s3_dart/example/bin/example.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_data_operation.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_file_operation.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart, packages/storage/amplify_storage_s3_dart/test/platform_impl/download_file_html_test.dart, packages/storage/amplify_storage_s3_dart/test/platform_impl/download_file_io_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_download_task_test.dart
Functionality of canceling a download operation depends on https://github.com/aws-amplify/amplify-flutter/pull/2545.
=> feat(storage): enable pause and cancel APIs for download operations

.vscode/launch.json
Run unit tests on Chrome by clicking codelens link in VSCode.
=> chore(repo): add shortcuts to run unit tests from IDE on Chrome

.circleci/config.yml, .circleci/test_all_plugins.sh, packages/secure_storage/amplify_secure_storage/android/build.gradle, packages/secure_storage/amplify_secure_storage/android/gradle.properties, packages/secure_storage/amplify_secure_storage/android/src/main/kotlin/com/amazonaws/amplify/amplify_secure_storage/amplify_secure_storage/EncryptedKeyValueRepository.kt, packages/secure_storage/amplify_secure_storage/android/src/test/kotlin/com/amazonaws/amplify/amplify_secure_storage/amplify_secure_storage/EncryptedKeyValueRepositoryTest.kt, packages/secure_storage/amplify_secure_storage/android/src/test/kotlin/com/amazonaws/amplify/amplify_secure_storage/amplify_secure_storage/FakeAndroidKeyStore.kt
*Issue #, if available:* #2500
**Context:** EncryptedSharedPreferences data can/will get backed up, but the keys to decrypt the data will not, meaning there is no way to decrypt the data.
- Create a file in the noBackupDir to track EncryptedSharedPreferences init after an app install, and clear SharedPreferences if the file does not exist already.
=> fix(secure_storage): clear SharedPreferences on first app launch after install

packages/amplify_core/lib/src/types/exception/auth/invalid_state_exception.dart, packages/auth/amplify_auth_cognito/example/integration_test/federated_sign_in_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/reset_password_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/security_test.dart, packages/auth/amplify_auth_cognito_dart/lib/amplify_auth_cognito_dart.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/credentials/cognito_keys.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_sign_in_details.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_sign_in_details.g.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/credential_store_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart, packages/auth/amplify_auth_cognito_test/test/state/credential_store_state_machine_test.dart, packages/auth/amplify_auth_cognito_test/test/state/fetch_auth_session_state_machine_test.dart
Some discrepancies exist in our implementation of `federateToIdentityPool`:
- `fetchAuthSession` should return `isSignedIn=true` when federated to identity pool
- User Pool APIs should throw a specific `InvalidStateException`, not a generic `SignedOutException`
=> fix(auth): `federateToIdentityPool` discrepancies

aft.yaml, packages/amplify_core/pubspec.yaml, packages/analytics/amplify_analytics_pinpoint_dart/pubspec.yaml, packages/auth/amplify_auth_cognito_dart/pubspec.yaml, packages/authenticator/amplify_authenticator/pubspec.yaml, packages/smithy/smithy/pubspec.yaml, packages/smithy/smithy_aws/pubspec.yaml
Our current constraint, `^0.17.0`, means `>=0.17.0 <0.18.0` but we should accept whichever version the customer uses (which is most often the one pinned by `flutter`).
=> chore(repo): Relax `intl` constraints

.github/workflows/lint.yml, .github/workflows/test.yml, packages/aws_common/mono_pkg.yaml, packages/aws_signature_v4/example/mono_pkg.yaml, packages/aws_signature_v4/mono_pkg.yaml
The stable packages are not expected to work on Dart beta (3.0) and will not be supported then.
=> ci: Remove Dart beta testing

packages/amplify_authenticator/pubspec.yaml, packages/amplify_core/pubspec.yaml
Fixes https://github.com/aws-amplify/amplify-flutter/issues/2642
Our current constraint, `^0.17.0`, means `>=0.17.0 <0.18.0` but we should accept whichever version the customer uses (which is most often the one pinned by `flutter`)
=> chore(repo): Relax `intl` constraint

packages/secure_storage/amplify_secure_storage/example/integration_test/cupertino_test.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/cupertino/cupertino.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/interfaces/amplify_secure_storage_interface.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/platforms/amplify_secure_storage_cupertino.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/2535
- Map KeychainAttributeAccessible value to correct values in keychain.
- Gracefully handle the scenario when KeychainAttributeAccessible changes
- Add tests for the updated behavior
=> fix(secure_storage)!: use correct values for `kSecAttrAccessible`

packages/api/amplify_api_dart/lib/src/graphql/factories/graphql_request_factory.dart, packages/api/amplify_api_dart/test/graphql_helpers_test.dart, packages/api/amplify_api_dart/test/test_models/CustomOwnerField.dart, packages/api/amplify_api_dart/test/test_models/ModelProvider.dart
This PR has a correction for some logic recently changed in https://github.com/aws-amplify/amplify-flutter/pull/2504. While the previous PR changed `ModelMutations.create()` to no longer include any null values in the input object, this PR makes it so only owner fields with null values will be removed from input and other null values will remain.
While removing null owner values is essential to fix the issue mentioned in https://github.com/aws-amplify/amplify-flutter/issues/2492, removing all null fields from create has some consequences that are difficult for users to understand or predict. Such as:
* Data created with older versions of model helpers is different than newer versions. Newer versions have empty values in DynamoDB versus explicit nulls from older entries. This makes is so …
=> fix(api): write null values in ModelMutations.create() unless owner field

packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart, packages/auth/amplify_auth_cognito_test/test/state/fetch_auth_session_state_machine_test.dart
In the fetch auth session state machine, any `NotAuthorizedException` thrown should be considered a `SessionExpiredException` since that is the only time we would get such an error.
=> fix(auth): Transform session expired exceptions

packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/database/database_html.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/database/database_io.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/database/database_io.g.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/database/database_stub.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/database/tables.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/database/transfer_record.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/database/transfer_record.g.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/transfer.dart, packages/storage/amplify_storage_s3_dart/pubspec.yaml, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/transfer/database_html_test.dart, packages/storage/amplify_storage_s3_dart/test/test_utils/mocks.dart
Add web implementation of TransferDataBase to stop using drift in web.
- add TransferDatabase stub
- add TransferData class
- update native implementation to implement the TransferDatabase stub
- implement TransferDatabase for web using local storage
- add unit tests 
=> feat(storage): web implementation of transfer database using local storage

packages/amplify_core/lib/src/state_machine/event.dart, packages/amplify_core/lib/src/state_machine/state_machine.dart, packages/amplify_core/test/state_machine/dependency_manager_test.dart, packages/amplify_core/test/state_machine/my_state_machine.dart, packages/amplify_core/test/state_machine/state_machine_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/hosted_ui_webview_test.dart, packages/auth/amplify_auth_cognito/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_flutter.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_io.dart, packages/auth/amplify_auth_cognito_test/test/common/mock_dispatcher.dart, packages/auth/amplify_auth_cognito_test/test/credentials/auth_plugin_credentials_provider_test.dart, packages/auth/amplify_auth_cognito_test/test/state/configuration_state_machine_test.dart, packages/auth/amplify_auth_cognito_test/test/state/credential_store_state_machine_test.dart, packages/auth/amplify_auth_cognito_test/test/state/fetch_auth_session_state_machine_test.dart, packages/auth/amplify_auth_cognito_test/test/state/hosted_ui_state_machine_test.dart, packages/auth/amplify_auth_cognito_test/test/state/sign_in_state_machine_test.dart, packages/auth/amplify_auth_cognito_test/test/state/sign_up_state_machine_test.dart
Event completers should be used or explicitly ignored since any errors are swallowed by them.
=> chore(core): Mark event completer methods with `@useResult`

packages/api/amplify_api_dart/lib/src/api_plugin_impl.dart
https://github.com/aws-amplify/amplify-flutter/issues/2647
The constructor of `AmplifyAPIDart` invokes `Amplify.hub` to add channel, as this happen during initiating the API plugin
```dart
final apiPlugin = AmplifyAPI();
```
https://github.com/aws-amplify/amplify-flutter/blob/d21259d326cd1ad2215d9cdba4cf6c04872f6e57/packages/api/amplify_api_dart/lib/src/api_plugin_impl.dart#L23-L33
It causes `Amplify` to be backed back wrong instance of `AmplifyClass` provided by  `amplify_core`, which should be the `AmplifyClass` provided by `amplify_flutter`. Therefore, when `Amplify.configure()` is called, the native plugins won't be configured via the `AmplifyHybridImpl.configurePlatform()` provided by `amplify_flutter`.
Moving the adding hub to …
=> fix(api): early call of Amplify creates wrong instance of AmplifyClass

packages/smithy/smithy/lib/src/http/http_operation.dart
Related to #2718.
When running a Flutter app in Debug mode w/ breakpoints on "Uncaught Exceptions", there are false negatives being tripped inside Smithy.
I'm not sure why this happens, but it's likely related to the interplay of Completer's and Zone's within CancelableOperation. Since these exceptions are already being handled properly, simply catching and rethrowing them seems to at least suppress the breakpoint trigger.
=> fix(smithy): Handle uncaught exception

packages/amplify_core/lib/src/amplify_class.dart, packages/amplify_core/lib/src/version.dart, packages/amplify_core/pubspec.yaml
Instead of manually updating the version, use `package:build_version` which gets automatically run when calling `aft version-bump`.
=> chore(core): Use `package:build_version`

packages/authenticator/amplify_authenticator/example/integration_test/confirm_sign_up_email_or_phone_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/confirm_sign_up_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/custom_ui_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/main_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/reset_password_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_force_new_password_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_mfa_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_with_email_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_with_phone_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_with_username_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_out_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_up_with_email_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_up_with_email_with_lambda_trigger_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_up_with_phone_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_up_with_username_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/unprotected_routes_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/utils/test_utils.dart, packages/authenticator/amplify_authenticator/example/integration_test/verify_user_test.dart, packages/authenticator/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_radio_field.dart, packages/authenticator/amplify_authenticator/lib/src/state/auth_state.dart, packages/authenticator/amplify_authenticator/lib/src/state/authenticator_state.dart, packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/verify_user_form_field.dart, packages/authenticator/amplify_authenticator_test/lib/amplify_authenticator_test.dart, packages/authenticator/amplify_authenticator_test/lib/src/pages/authenticator_page.dart, packages/authenticator/amplify_authenticator_test/lib/src/pages/confirm_verify_user_page.dart
Includes fixes for:
- **Hub event processing:** Hub events should not be processed while a bloc event is being processed. The previous workaround (`PendingVerificationCheckState`) meant to address this problem but there were inherent race conditions to this. Instead, we pause the Hub subscription in the bloc while any incoming event is being processed to ensure it's processed to completion.
- **Attribute verification:** State management around attribute verification was creating discrepancies in values between the `AuthenticatorState` and the local Radio field state.
=> fix(authenticator): Various fixes

packages/secure_storage/amplify_secure_storage/lib/src/amplify_secure_storage.vm.dart, packages/secure_storage/amplify_secure_storage/lib/src/path_provider_local.dart, packages/secure_storage/amplify_secure_storage/pubspec.yaml
- Use Local App Data Directory instead of Roaming dir on Windows
=> feat(secure_storage)!: Use Local App Data Directory on Windows

.github/workflows/amplify_analytics_pinpoint.yaml, .github/workflows/amplify_api.yaml, .github/workflows/amplify_auth_cognito.yaml, .github/workflows/amplify_authenticator.yaml, .github/workflows/amplify_core.yaml, .github/workflows/amplify_datastore.yaml, .github/workflows/amplify_datastore_plugin_interface.yaml, .github/workflows/amplify_flutter.yaml, .github/workflows/amplify_storage_s3.yaml, .github/workflows/flutter_format_analyze.yaml, .github/workflows/flutter_vm.yaml
This PR migrates flutter unit tests to GH actions by largely copying/modifying the generated GH actions from next and only running with stable Flutter channel. It also runs `flutter format` and `flutter analyze` in its own job (one for all packages) which is based off the current Circle CI job here.
Removing CCI equivalents should be separate PR.
=> chore: migrate Flutter unit tests to GH actions

packages/amplify/amplify_flutter_android/android/build.gradle, packages/amplify/amplify_flutter_ios/ios/amplify_flutter_ios.podspec, packages/amplify_datastore/android/build.gradle, packages/amplify_datastore/ios/amplify_datastore.podspec, packages/api/amplify_api_android/android/build.gradle, packages/api/amplify_api_ios/ios/amplify_api_ios.podspec, packages/auth/amplify_auth_cognito_android/android/build.gradle, packages/auth/amplify_auth_cognito_ios/ios/amplify_auth_cognito_ios.podspec
- Bumps Amplify iOS dependency to [1.29.1](https://github.com/aws-amplify/amplify-swift/releases/tag/1.29.1)
- Bumps Amplify Android dependency to [2.4.1](https://github.com/aws-amplify/amplify-android/releases/tag/release_v2.4.1)
=> chore(repo): Bump Amplify Android/iOS

packages/storage/amplify_storage_s3_dart/lib/src/model/s3_copy_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_data_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_download_file_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_get_properties_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_get_url_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_list_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_move_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_remove_many_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_remove_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_data_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_upload_file_plugin_options.dart
… warnings for generated codes
- add fromJson factory to all plugin options. this is to fix unused warnings for generated codes.
=> chore(storage): add fromJson factory for plugin options

infra/lib/auth/common.ts, infra/lib/auth/custom-authorizer-iam/stack.api-handler.ts, infra/lib/auth/custom-authorizer-iam/stack.ts, infra/lib/auth/custom-authorizer-user-pools/stack.api-handler.ts, infra/lib/auth/custom-authorizer-user-pools/stack.ts, infra/lib/auth/stack.ts, infra/lib/stack.ts, packages/api/amplify_api/lib/src/api_plugin_impl.dart, packages/api/amplify_api_dart/lib/src/api_plugin_impl.dart, packages/api/amplify_api_dart/lib/src/decorators/authorize_http_request.dart, packages/api/amplify_api_dart/lib/src/util/amplify_authorization_rest_client.dart, packages/auth/amplify_auth_cognito/example/integration_test/custom_authorizer_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/main_test.dart, packages/aws_common/lib/src/http/aws_http_client_io.dart, packages/aws_common/test/http/client_conformance_tests/redirect_server_test.dart, packages/aws_signature_v4/lib/src/request/canonical_request/canonical_request_util.dart, packages/aws_signature_v4/test/canonical_request_test.dart
- Adds more custom authorizer tests for query parameters, headers, and HTTP/2.
- Fixes header casing in HTTP/2 requests
- Fixes query parameter encoding issue
- Fixes API using access token instead of ID token
=> test(api): Expand custom authorizer tests

.vscode/launch.json, infra/lib/auth/custom-auth-without-srp/common.ts, infra/lib/auth/custom-auth-without-srp/create-auth-challenge.ts, infra/lib/auth/custom-auth-without-srp/define-auth-challenge.ts, packages/amplify_core/lib/src/config/auth/cognito/authentication_flow_type.dart, packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_in_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/custom_auth_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/exception/auth_precondition_exception.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/sign_in_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/state/sign_in_state.dart, packages/auth/amplify_auth_cognito_test/test/state/sign_in_state_machine_test.dart
Fixes #2794.
- Fixes a regression caused by a recent change ([8d87ea8#diff-9d1c23e771518da5d10ac1f888bd38c5f865868332b126a16ab6d19fd3ef028fR825](https://github.com/aws-amplify/amplify-flutter/commit/8d87ea871b2d8a716f0f7f087e2660b7a8e61994#diff-9d1c23e771518da5d10ac1f888bd38c5f865868332b126a16ab6d19fd3ef028fR653))
- Improves sign-in exception handling logic (now aligned with iOS/Android)
- Adds more custom auth tests
=> fix(auth): Process sign-in events once

packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_test/lib/hosted_ui/hosted_ui_server.dart, packages/auth/amplify_auth_cognito_test/test/plugin/sign_in_test.dart, packages/auth/amplify_auth_cognito_test/test/plugin/sign_out_test.dart
Calling `signIn` while authenticated should fail with an `InvalidStateException`.
Based off [docs](https://docs.amplify.aws/lib/auth/signin/q/platform/flutter/#sign-in-a-user) and [iOS impl](https://github.com/aws-amplify/amplify-swift/blob/c65904f79d1796b93cc6f43bd4794daac7f5b3bc/AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthSRPSignInTests.swift#L172)
=> chore(auth): Reject `signIn` when authenticated

packages/storage/amplify_storage_s3_dart/lib/amplify_storage_s3_dart.dart, packages/storage/amplify_storage_s3_dart/lib/src/exception/s3_storage_exception.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_item.dart, packages/storage/amplify_storage_s3_dart/lib/src/platform_impl/download_file/download_file_io.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_download_task_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart, packages/storage/amplify_storage_s3_dart/test/test_utils/helper_types.dart
* No longer export `S3Exception` where `StorageException` from amplify_core should be used to handle exceptions at runtime
* Added handling of `AWSHttpException` calling S3 SDK APIs
=> fix(storage): add handling of AWSHttpException

.github/workflows/amplify_analytics_pinpoint_dart.yaml, .github/workflows/amplify_api_dart.yaml, .github/workflows/amplify_auth_cognito_dart.yaml, .github/workflows/amplify_auth_cognito_test.yaml, .github/workflows/amplify_core.yaml, .github/workflows/amplify_db_common_dart.yaml, .github/workflows/amplify_secure_storage_test.yaml, .github/workflows/amplify_storage_s3_dart.yaml, .github/workflows/aws_common.yaml, .github/workflows/aws_json1_0_v1.yaml, .github/workflows/aws_json1_0_v2.yaml, .github/workflows/aws_json1_1_v1.yaml, .github/workflows/aws_json1_1_v2.yaml, .github/workflows/aws_signature_v4.yaml, .github/workflows/dart_native.yaml, .github/workflows/rest_json1_v1.yaml, .github/workflows/rest_json1_v2.yaml, .github/workflows/rest_xml_v1.yaml, .github/workflows/rest_xml_v2.yaml, .github/workflows/rest_xml_with_namespace_v1.yaml, .github/workflows/rest_xml_with_namespace_v2.yaml, .github/workflows/smithy.yaml, .github/workflows/smithy_aws.yaml, .github/workflows/smithy_codegen.yaml, packages/aft/lib/src/commands/generate/generate_workflows_command.dart
Packages which use DB Common (SQLite) will not work on Windows until [native assets](https://github.com/dart-lang/sdk/issues/50565) are supported.
=> ci(repo): Skip failing Windows tests

.github/workflows/smoke_test.yaml, packages/aws_sdk/smoke_test/workflow.yaml
Bucket creation is failing in localstack v2 currently
=> chore(smoke_test): Use `localstack` <2.0.0

packages/amplify_core/lib/src/types/analytics/analytics/analytics_event.dart
Clean up from #2753. Adds back a field which should be deprecated.
=> chore(analytics): Add deprecated field

packages/amplify_core/lib/src/types/storage/base/storage_operation_options.dart, packages/amplify_core/lib/src/types/storage/download_data_options.dart, packages/amplify_core/lib/src/types/storage/download_file_options.dart, packages/amplify_core/lib/src/types/storage/get_properties_options.dart, packages/amplify_core/lib/src/types/storage/get_url_options.dart, packages/amplify_core/lib/src/types/storage/list_options.dart, packages/amplify_core/lib/src/types/storage/remove_many_options.dart, packages/amplify_core/lib/src/types/storage/remove_options.dart, packages/amplify_core/lib/src/types/storage/upload_data_options.dart, packages/amplify_core/lib/src/types/storage/upload_file_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_download_task_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
- make access level optional for storage APIs
- `defaultAccessLevel` can be set by `Amplify.Amplify.configure(...)` with fallback to `guest`. 
=> feat(storage): make access level optional for storage APIs

packages/amplify_core/lib/src/category/amplify_storage_category.dart, packages/amplify_core/lib/src/plugin/amplify_plugin_key.dart, packages/amplify_core/lib/src/plugin/amplify_storage_plugin_interface.dart, packages/storage/amplify_storage_s3/lib/src/amplify_storage_s3_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart
Removes generic types from public APIs and removes the category wrapper interface for `getPlugin`.
=> refactor(storage): Remove generic types

packages/amplify_core/lib/src/types/exception/analytics/analytics_exception.dart, packages/amplify_core/lib/src/types/exception/auth/auth_exception.dart, packages/amplify_core/lib/src/types/exception/network_exception.dart, packages/amplify_core/lib/src/types/exception/storage/operation_canceled_exception.dart, packages/amplify_core/lib/src/types/storage/storage_types.dart, packages/amplify_core/lib/src/types/storage/transfer_progress.dart, packages/storage/amplify_storage_s3_dart/lib/src/exception/s3_storage_exception.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_item.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_transfer_progress.dart, packages/storage/amplify_storage_s3_dart/lib/src/platform_impl/download_file/download_file_io.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/test/platform_impl/download_file_io_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_download_task_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
This PR depends on https://github.com/aws-amplify/amplify-flutter/pull/2774
* Promoted `StorageTransferState` to amplify_core package
* No longer throwing exception on resuming already canceled task (the call of `resume()` doesn't do anything)
* Added generic `StorageOperationCanceled` exception to amplify_core
* Simplified `S3Exception` handling and remove unnecessary logics around it
=> refactor(storage)!: simplify storage s3 exceptions throwing

packages/amplify_core/lib/src/state_machine/exception.dart, packages/amplify_core/lib/src/state_machine/state_machine.dart, packages/amplify_core/test/state_machine/my_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/exception/auth_precondition_exception.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/credential_store_event.dart
Some events do not need to be logged. Adds an option for PreconditionException's to opt-out of logging to reduce verbosity around expected events.
=> chore(auth): Clean up logs

infra/lib/storage/stack.ts, packages/storage/amplify_storage_s3/example/integration_test/use_case_test.dart, packages/storage/amplify_storage_s3_dart/example/bin/example.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_get_url_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_get_url_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_get_url_plugin_options.g.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_item.dart, packages/storage/amplify_storage_s3_dart/lib/src/platform_impl/download_file/download_file_html.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/utils.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/storage_s3_service.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart, packages/storage/amplify_storage_s3_dart/test/platform_impl/download_file_html_test.dart, packages/storage/amplify_storage_s3_dart/test/platform_impl/download_file_io_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_download_task_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/utils_test.dart, packages/storage/amplify_storage_s3_dart/test/test_utils/helper_types.dart
1. Renamed `S3GetUrlPluginOptions` `checkObjectExistence` property as `validateObjectExistence`
2. enabled metadata headers in the `infra` storage stack
3. Added metadata non-ascii value encoding and decoding following [S3 recommendation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html) and integration tests
=> feat(storage): add handling of non-ascii object metadata values

packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/win32/data_protection.bindings.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/win32/data_protection.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/win32/utils.dart, packages/secure_storage/amplify_secure_storage_dart/pubspec.yaml
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/2827
- Update win32 version constraint to versions that export data protection APIs (3.1.4 and up)
- Use win32 data protection APIs, remove hand written bindings in secure_storage
- Update win32 imports to use `show`
=> chore: update win32 version, use show in win32 imports

packages/secure_storage/amplify_secure_storage_dart/lib/src/platforms/amplify_secure_storage_cupertino.dart
- Update recovery message for macOS entitlement error to point to Amplify docs
=> chore(secure_storage): macOS entitlement message

packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_in_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/custom_auth_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/custom_authorizer_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/delete_user_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/device_tracking_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/federated_sign_in_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/fetch_auth_session_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/get_current_user_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/hosted_ui_webview_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/hub_events_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/main_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/mfa_sms_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/native_auth_bridge_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/reset_password_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/security_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_in_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_out_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/update_password_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/user_attributes_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/utils/setup_utils.dart, packages/auth/amplify_auth_cognito/example/pubspec.yaml
And add stack trace demangler since we use `package:stack_trace` in Auth and `package:integration_test` expects VM-style stack traces.
=> test(auth): Consolidate initialization code

packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/sign_in_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart, packages/auth/amplify_auth_cognito_test/lib/amplify_auth_cognito_test.dart, packages/auth/amplify_auth_cognito_test/lib/src/utils.js.dart, packages/auth/amplify_auth_cognito_test/lib/src/utils.vm.dart, packages/auth/amplify_auth_cognito_test/pubspec.yaml, packages/auth/amplify_auth_cognito_test/test/plugin/sign_in_test.dart, packages/auth/amplify_auth_cognito_test/test/state/sign_in_state_machine_test.dart
Properly enqueues sign-in calls and cancels previous attempts when signing in or confirming a sign in.
=> fix(auth): Cancel sign in

aft.yaml, packages/amplify_core/analysis_options.yaml, packages/amplify_core/build.yaml, packages/amplify_core/doc/.gitignore, packages/amplify_core/doc/README.md, packages/amplify_core/doc/analysis_options.yaml, packages/amplify_core/doc/build.yaml, packages/amplify_core/doc/lib/auth.dart, packages/amplify_core/doc/pubspec.yaml, packages/amplify_core/lib/src/category/amplify_auth_category.dart, packages/amplify_core/lib/src/types/auth/attribute/auth_next_update_attribute_step.g.dart, packages/amplify_core/lib/src/types/auth/auth_next_step.dart, packages/amplify_core/lib/src/types/auth/password/reset_password_step.g.dart, packages/amplify_core/lib/src/types/auth/sign_in/auth_next_sign_in_step.g.dart, packages/amplify_core/lib/src/types/auth/sign_up/auth_next_sign_up_step.g.dart, packages/amplify_core/pubspec.yaml, packages/amplify_core/tool/setup.sh, packages/authenticator/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart
- Adds a mechanism for incorporating examples from Dart code inline in docs. Uses the [code_excerpter](https://github.com/dart-lang/site-shared/tree/main/packages/code_excerpter) library which is used internally by the Dart+Flutter teams and provides a very simple mechanism for orchestrating this flow.
- Adds inline code examples to the Auth category docs. To regenerate: `aft run build:docs --include=amplify_core`.
=> docs(auth): Add inline examples

packages/aws_common/lib/src/http/http_payload.dart
Temporary workaround until codebase is migrated to Dart 3
=> chore(aws_common): Prevent build errors in Dart 3

.github/workflows/dart_dart2js.yaml, .github/workflows/dart_ddc.yaml, .github/workflows/dart_vm.yaml, .github/workflows/flutter_android.yaml, .github/workflows/flutter_ios.yaml, .github/workflows/flutter_vm.yaml, packages/aws_common/lib/src/http/http_payload.dart, packages/aws_common/lib/src/js/readable_stream.dart
Trying to support Dart 3 right now is a game of whack-a-mole.. to be re-enabled when the repo is migrated fully.
=> ci: Disable Dart 3 checks

.github/ISSUE_TEMPLATE/BUG-REPORT.yaml
Cherry picks bug report template from `main-v0`
=> chore(github): Update BUG-REPORT template

.circleci/config.yml
Removes all but canaries from the CircleCI configuration. The canaries workflow hadn't been merged to `next`, so the diff includes the removal of unit tests + copying over the canaries from `main-v0`.
=> ci(repo): Remove CircleCI tests

.github/workflows/generate_workflows.yaml, packages/aft/lib/src/commands/generate/generate_workflows_command.dart
- Add `--set-exit-if-changed` flag to `aft generate workflows`
- Add CI workflow to run `aft generate workflows --set-exit-if-changed`
Example of failing CI: https://github.com/aws-amplify/amplify-flutter/actions/runs/4702723385/jobs/8340333238?pr=2873
=> chore: add CI check for workflows

packages/aft/lib/src/util.dart, packages/amplify/amplify_flutter/pubspec.yaml, packages/amplify/amplify_flutter/test/amplify_test.dart, packages/amplify_datastore/pubspec.yaml, packages/amplify_datastore_plugin_interface/pubspec.yaml, packages/api/amplify_api/pubspec.yaml, packages/authenticator/amplify_authenticator/example/pubspec.yaml, packages/authenticator/amplify_authenticator/pubspec.yaml, packages/authenticator/amplify_authenticator_test/pubspec.yaml, packages/notifications/push/amplify_push_notifications/pubspec.yaml, packages/notifications/push/amplify_push_notifications_pinpoint/pubspec.yaml, packages/storage/amplify_storage_s3/pubspec.yaml, packages/test/amplify_integration_test/CHANGELOG.md, packages/test/amplify_integration_test/pubspec.yaml, packages/test/amplify_test/CHANGELOG.md, packages/test/amplify_test/pubspec.yaml
When publishing, the `pub` tool uses (roughly) the following logic:
1. For all packages listed in `dependencies` and `dev_dependencies`:
a. If it's a hosted dependency (meaning a version is specified), check if the version is published and throw an error if not
b.If it's a path dependency (only applies to `dev_dependencies`), do nothing
2. Traverse into each dependency and dev_dependency and repeat
However, there's a catch in that a `dev_dependency` cannot also conflict with a regular `dependency` (either direct or transitive). Meaning the following is not allowed:
```yaml
name: amplify_auth_cognito
dependencies:
amplify_flutter: ^1.0.0
dev_dependencies:
amplify_flutter:
path: ../../amplify/amplify_flutter
```
To get around these issues, we can use the following simple heuristics:
1. …
=> chore(repo): Fix circular dependencies when publishing

packages/analytics/amplify_analytics_pinpoint_dart/lib/src/impl/analytics_client/analytics_client.dart, packages/analytics/amplify_analytics_pinpoint_dart/lib/src/sdk/sdk_bridge.dart, packages/analytics/amplify_analytics_pinpoint_dart/test/analytics_client_test.dart, packages/notifications/push/amplify_push_notifications_pinpoint/test/pinpoint_provider_test.mocks.dart
Use httpClient provided by dependencyManager. 
=> chore(analytics): mockable httpClient

packages/amplify_core/lib/src/types/auth/attribute/cognito_user_attribute_key.dart, packages/api/amplify_api/example/integration_test/util.dart, packages/auth/amplify_auth_cognito/example/integration_test/confirm_sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/device_tracking_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/fetch_auth_session_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/get_current_user_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/user_attributes_test.dart, packages/auth/amplify_auth_cognito/example/lib/screens/view_user_attributes.dart, packages/auth/amplify_auth_cognito_dart/example/web/components/attribute_component.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/authenticator/amplify_authenticator/example/integration_test/custom_ui_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_force_new_password_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_mfa_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_with_email_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_with_phone_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/verify_user_test.dart, packages/authenticator/amplify_authenticator/lib/src/services/amplify_auth_service.dart, packages/test/amplify_integration_test/lib/src/integration_test_utils/auth_cognito/integration_test_auth_utils.dart, packages/test/amplify_integration_test/lib/src/stubs/amplify_auth_cognito_stub.dart
- Properly convert `AuthUserAttribute` to `CognitoUserAttribute` in `updateUserAttributes()`
- Update example apps to use `AuthUserAttribute` by default to match docs
- Update integ tests to use `AuthUserAttribute` by default to match docs
=> fix: convert `AuthUserAttribute` to `CognitoUserAttribute` in `updateUserAttributes()`

packages/aft/lib/src/commands/publish_command.dart, packages/authenticator/amplify_authenticator_test/pubspec.yaml, packages/test/amplify_integration_test/pubspec.yaml, packages/test/amplify_test/pubspec.yaml
- Since unpublished packages' constraints are not updated as part of `aft version-bump` set their constraints to `any` to not conflict with published packages' constraints
- Fix `aft publish` to look at the maximum of the pre-release and published version instead of assuming the pre-release is higher than the published
=> chore(repo): Fix publishing errors

infra/lib/auth/stack.ts, infra/lib/cleanup-users.ts, infra/lib/common.ts, infra/lib/storage/stack.ts, packages/authenticator/amplify_authenticator/example/integration_test/confirm_sign_up_email_or_phone_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/confirm_sign_up_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_with_email_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_in_with_phone_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_up_with_email_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_up_with_email_with_lambda_trigger_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_up_with_phone_test.dart, packages/authenticator/amplify_authenticator/example/integration_test/sign_up_with_username_test.dart
- Adds teardown calls to Authenticator e2e tests. Should resolve some flakiness with phone number tests.
- Adds a scheduled cron job to the e2e infra to delete all users every day.
=> chore(repo): Clean up users in e2e tests

infra/lib/common.ts
When there's lots of users, the Lambda can get OOM exceptions.
=> chore(infra): Bump Lambda memory size

packages/secure_storage/amplify_secure_storage/android/build.gradle, packages/secure_storage/amplify_secure_storage/android/src/main/kotlin/com/amazonaws/amplify/amplify_secure_storage/amplify_secure_storage/EncryptedKeyValueRepository.kt
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/2640
- Add dependency on google/tink v1.8.0. androidx.security v1.0 depends on google/tink v1.5.0+. 1.8.0 removes a confusing log message. See [google/tink/issues/534](https://github.com/google/tink/issues/534) for more info.
- Remove temp log message from secure_storage 
=> fix: remove AndroidKeysetManager log, upgrade to google/tink 1.8.0

.github/workflows/amplify_analytics_pinpoint_dart.yaml, .github/workflows/amplify_api_dart.yaml, .github/workflows/amplify_auth_cognito_dart.yaml, .github/workflows/amplify_auth_cognito_test.yaml, .github/workflows/amplify_core.yaml, .github/workflows/amplify_db_common_dart.yaml, .github/workflows/amplify_secure_storage_test.yaml, .github/workflows/amplify_storage_s3_dart.yaml, .github/workflows/aws_common.yaml, .github/workflows/aws_json1_0_v1.yaml, .github/workflows/aws_json1_0_v2.yaml, .github/workflows/aws_json1_1_v1.yaml, .github/workflows/aws_json1_1_v2.yaml, .github/workflows/aws_signature_v4.yaml, .github/workflows/custom_v1.yaml, .github/workflows/custom_v2.yaml, .github/workflows/dart_native.yaml, .github/workflows/rest_json1_v1.yaml, .github/workflows/rest_json1_v2.yaml, .github/workflows/rest_xml_v1.yaml, .github/workflows/rest_xml_v2.yaml, .github/workflows/rest_xml_with_namespace_v1.yaml, .github/workflows/rest_xml_with_namespace_v2.yaml, .github/workflows/smithy.yaml, .github/workflows/smithy_aws.yaml, .github/workflows/smithy_codegen.yaml, packages/aft/lib/src/commands/generate/generate_workflows_command.dart
Downloads sqlite3 and adds it to the Windows PATH which is all that's needed for `package:sqlite3` to find it. Based off: https://github.com/simolus3/sqlite3.dart/blob/main/.github/workflows/main.yml
=> ci: Fix db_common tests on Windows

packages/secure_storage/amplify_secure_storage/android/gradle.properties
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/2962
- Remove `android.enableUnitTestBinaryResources=true` from gradle.properties. This was required prior to Android Studio 3.3 (released in 2019). I had added this as part of https://github.com/aws-amplify/amplify-flutter/pull/2637 as that PR uses roboelectric and [setup docs](https://robolectric.org/getting-started/) include adding this. However, the setup docs note this is not required as of v3.3
=> chore(secure_storage): remove enableUnitTestBinaryResources

packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart, packages/auth/amplify_auth_cognito_test/test/state/hosted_ui_state_machine_test.dart
Fixes #2946.
Align logic with username/password login (https://github.com/aws-amplify/amplify-flutter/blob/a010c360376d062eba2c8ac4a01d04a88b555fec/packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart#L539) and refresh AWS credentials upon succesful login.
=> fix(auth): Fetch AWS credentials after Hosted UI login

.github/composite_actions/launch_ios_simulator/action.yaml, .github/workflows/amplify_canaries.yaml
The `xcversion` command, which is preinstalled on GH runners, is being deprecated: https://github.com/xcpretty/xcode-install and no longer works on `macos-latest` which recently moved to macOS 13. This migrates to the recommended replacement `xcodes`.
=> chore(canaries): Use `xcodes`

packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_exception.dart, packages/auth/amplify_auth_cognito_dart/test/sdk/sdk_exception_test.dart, packages/auth/amplify_auth_cognito_dart/tool/generate_sdk_exceptions.dart
Transform network exceptions in the SDK layer so that individual plugin methods do not need to be wrapped.
=> fix(auth): Transform network exceptions

packages/amplify_core/lib/src/types/models/auth_rule.dart
Fix https://github.com/aws-amplify/amplify-flutter/issues/2526
The purpose of adding enum in library is to ensure the model files generated by modelgen will be compiled. However, this is not intended for Datastore usage but for those who use modelgen files along with API plugin. It is not recommended to use them in the datastore due to the prerequisite of `sync` and `listen`. This is documented in the [callout](https://github.com/aws-amplify/docs/pull/5084). 
Add granular read operation enums in model auth operation rule
Refer https://docs.amplify.aws/cli/graphql/authorization-rules/#how-it-works
=> feat(core): add granular model read operations

packages/authenticator/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/authenticator/amplify_authenticator/lib/src/services/amplify_auth_service.dart
*Issue #, if available:* Related to https://github.com/aws-amplify/amplify-flutter/issues/2989
- Periodically log warnings from the authenticator while waiting on configuration
=> chore(authenticator): add warning for delayed asyncConfig

.github/workflows/amplify_canaries.yaml, build-support/build_canary.sh, packages/aft/lib/src/models/config.dart, packages/aft/test/models/package_selector_test.dart
Flutter 3.3 does not support the current syntax, which is causing tests to fail. It also fails when adding dependencies already present, so remove `flutter_test` cmd since it's already included in new flutter projects.
Updates `compileSdkVersion` and Kotlin version since Flutter 3.3 defaults do not work.
=> chore(canaries): Use 3.3 compatible flutter pub add command

.github/workflows/amplify_api.yaml, .github/workflows/amplify_auth_cognito.yaml, .github/workflows/amplify_authenticator.yaml, .github/workflows/amplify_flutter.yaml, .github/workflows/amplify_push_notifications_pinpoint.yaml, packages/amplify/amplify_flutter/pubspec.yaml
- remove amplify_datastore_plugin_interface dependency from amplify_flutter
=> chore: remove amplify_datastore_plugin_interface dependency

packages/auth/amplify_auth_cognito_dart/lib/src/model/auth_result.dart, packages/authenticator/amplify_authenticator/lib/src/services/amplify_auth_service.dart, packages/aws_common/lib/src/result/aws_result.dart, packages/aws_common/lib/src/util/debuggable.dart
Adds pattern matching/functional capabilities to `AWSResult`.
=> chore(aws_common,3.0): Make AWSResult sealed

packages/amplify_core/lib/src/types/analytics/analytics_types.dart, packages/amplify_core/lib/src/types/api/api_types.dart, packages/amplify_core/lib/src/types/auth/auth_types.dart, packages/amplify_core/lib/src/types/exception/amplify_exception.dart, packages/amplify_core/lib/src/types/exception/analytics/analytics_exception.dart, packages/amplify_core/lib/src/types/exception/analytics/invalid_event_exception.dart, packages/amplify_core/lib/src/types/exception/api/api_exception.dart, packages/amplify_core/lib/src/types/exception/api/http_status_exception.dart, packages/amplify_core/lib/src/types/exception/api/operation_exception.dart, packages/amplify_core/lib/src/types/exception/push/push_notification_exception.dart, packages/amplify_core/lib/src/types/exception/storage/access_denied_exception.dart, packages/amplify_core/lib/src/types/exception/storage/http_status_exception.dart, packages/amplify_core/lib/src/types/exception/storage/key_not_found_exception.dart, packages/amplify_core/lib/src/types/exception/storage/local_file_not_found_exception.dart, packages/amplify_core/lib/src/types/exception/storage/operation_canceled_exception.dart, packages/amplify_core/lib/src/types/exception/storage/storage_exception.dart, packages/amplify_core/lib/src/types/notifications/notification_types.dart, packages/amplify_core/lib/src/types/storage/storage_types.dart, packages/auth/amplify_auth_cognito_dart/lib/src/workers/workers.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/worker/workers.dart, packages/worker_bee/e2e/lib/no_workers.dart, packages/worker_bee/e2e/lib/workers.dart
Makes all `AmplifyException` category subtypes sealed.
=> chore(core): Sealed exception types

packages/amplify/amplify_flutter/lib/src/hybrid_impl.dart, packages/amplify_core/lib/src/amplify_class_impl.dart, packages/amplify_core/test/amplify_class_test.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/2987
- wait for `.addPlugin()` calls to complete prior to configuring plugins
While user should await calls to addPlugins, we should gracefully handle the scenario where they do not. Currently if the .addPlugin() call is not awaited, the plugin does not get configured because the plugin has not been added at the time of configuration. However, the plugin later does get added and Amplify does successfully configure (but without the plugin). This is a weird state that we shouldn't let users get into.
=> fix: wait for addPlugin prior to configuration

packages/amplify_datastore/android/build.gradle, packages/notifications/push/amplify_push_notifications/android/build.gradle
Underlying Android Issue:
https://github.com/aws-amplify/amplify-android/issues/2263
Possible Related Amplify Flutter Datastore Issue:
https://github.com/aws-amplify/amplify-flutter/issues/3017
Bump Android versions to fix errors in Datastore.
=> fix(android): Bump Amplify Android to 2.8.3

packages/amplify_datastore/android/build.gradle, packages/notifications/push/amplify_push_notifications/android/build.gradle
This reverts commit 8ab7f12cf7695103b57d4f473ff7782c5a2a712c.
reverting because some android integration tests fails after this change. 
=> Revert "fix(android): Bump Amplify Android to 2.8.3 (#3023)"

.github/workflows/amplify_canaries.yaml, .github/workflows/dart_dart2js.yaml, .github/workflows/dart_ddc.yaml, .github/workflows/dart_vm.yaml, .github/workflows/flutter_vm.yaml, packages/amplify_core/lib/src/types/models/model_association.dart, packages/amplify_core/lib/src/types/models/model_field_definition.dart, packages/api/amplify_api/example/pubspec.yaml
One of our dependencies `code_excerpter` bumped its min SDK to 3.0.1. We could just pin to an older version, but bumping CI maintains the same contract IMO.
=> ci: Use Dart 3.0.1/Flutter 3.10.1

packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_flutter.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/3089
- Do not show launch sign out URL on iOS when `preferPrivateSession` is true.
When `preferPrivateSession` is true, nothing needs to be cleared from the browser on sign out so there is no need to launch the browser. This behavior matches amplify-swift which can be seen [here](https://github.com/aws-amplify/amplify-swift/blob/f0bc8dfc0060f69bb081126ba751a087918e1194/AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignOut/InitiateSignOut.swift#LL23C1-L23C1).
=> fix: suppress browser on sign out when preferPrivateSession is true

packages/auth/amplify_auth_cognito/darwin/Classes/HostedUIFlow.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/3089
- remove unnecessary guard for `session.start()`
While there is no apple documentation stating this, it seems that the completion handler passed into ASWebAuthenticationSession will always be called upon start, which means that handling the case that start returns false is not needed. The removes the possibility of the continuation being resumed multiple times, which will cause the app to crash when in release mode.
This is consistent with Amplify-Swift as can be seen [here](https://github.com/aws-amplify/amplify-swift/blob/758119b568aff5215997217909c68988326d7582/AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/HostedUIASWebAuthenticationSession.swift#L47).
By …
=> fix(auth): remove duplicate continuation call for hosted UI

packages/secure_storage/amplify_secure_storage_dart/ffigen.cupertino.coreFoundation.config.yaml, packages/secure_storage/amplify_secure_storage_dart/ffigen.cupertino.security.config.yaml, packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/cupertino/core_foundation.bindings.g.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/cupertino/cupertino.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/ffi/cupertino/security.bindings.g.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/platforms/amplify_secure_storage_cupertino.dart, packages/secure_storage/amplify_secure_storage_dart/pubspec.yaml, packages/secure_storage/amplify_secure_storage_test/test/mac_os_test.dart
In the Apple [docs](https://developer.apple.com/documentation/corefoundation/1542133-cfstringgetcstringptr), they suggest using `CFStringGetCString` as a fallback for `CFStringGetCStringPtr` which is failing in some instances.
=> fix(secure_storage): Fallback for CFStringRef decoding

packages/api/amplify_api/example/lib/util/util.dart, packages/api/amplify_api/example/lib/widgets/create.dart, packages/api/amplify_api/example/lib/widgets/query.dart, packages/api/amplify_api/example/lib/widgets/subscribe.dart
Fixes an overflow caused by the default button size increasing. Also adjusts the button text colors so they are more readable.
Before:
After:
=> chore(api): material 3 example app overflow fix

packages/smithy/smithy/lib/src/serialization/xml/xml_num_serializer.dart
Fixes a lint introduced in latest Dart stable for switching on a `Type`
=> chore(smithy): Fix switch lint

packages/aws_common/lib/src/js/common.dart
Dart 3.1 disallows tearoffs of JS methods.
=> fix(core): Disallowed JS tearoff

packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart
=> chore(storage): fix flaky signer scope unit tests for Windows

packages/auth/amplify_auth_cognito/example/integration_test/delete_user_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_out_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/test_runner.dart, packages/auth/amplify_auth_cognito/example/test_driver/hosted_ui_test.dart, packages/auth/amplify_auth_cognito_dart/example/integration_test/hosted_ui_test.dart, packages/auth/amplify_auth_cognito_dart/example/integration_test/hosted_ui_web_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_out_state_machine.dart, packages/test/amplify_auth_integration_test/lib/src/test_auth_plugin.dart, packages/test/amplify_integration_test/lib/src/integration_test_utils/auth_cognito/integration_test_auth_utils.dart
If a user is deleted by an administrator while logged into a device, calling `signOut` can fail when tokens have also expired. The library gets stuck because credentials are not cleared but they are also invalid and cannot be refreshed.
Fixes:  https://github.com/aws-amplify/amplify-flutter/issues/3160
=> fix(auth): `signOut` after user deletion

packages/api/amplify_api_dart/lib/src/decorators/web_socket_auth_utils.dart, packages/api/amplify_api_dart/test/util.dart, packages/api/amplify_api_dart/test/web_socket/web_socket_auth_utils_test.dart
Fixes https://github.com/aws-amplify/amplify-flutter/issues/3028
There is a bug where GraphQL subscriptions do not work with custom domains. As documented on https://docs.aws.amazon.com/appsync/latest/devguide/custom-domain-name.html., AppSync custom domains require some runtime changes to the way the connection URI is formatted. This is automatically handled in Android and users reported this as a regression with version 1.
I tested this fix manually in Android with a real endpoint w custom domain
=> fix(api): GraphQL subscription with custom domain formats URI correctly

packages/authenticator/amplify_authenticator/lib/src/widgets/form.dart, packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/sign_up_form_field.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/3154
- Log a warning when the use of a custom form and the sign in alias will cause a duplicate field to display. 
=> chore(authenticator): log a warning for duplicate fields

infra/lib/stack.ts, infra/lib/storage/stack.ts, packages/smithy/smithy_aws/lib/src/s3/s3_client_config.dart, packages/storage/amplify_storage_s3/example/integration_test/use_case_test.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/exception/s3_storage_exception.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_download_task.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_download_task_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
https://github.com/aws-amplify/amplify-flutter/issues/3147
* Update the infra stack to add a bucket that has dots in its name for integration tests
* Add support of using path style URLs when need to
* throwing exceptions when attempt to use acceleration endpoint when use path style URLs
=> feat(storage): using path style URLs when bucket name contains dots

infra/lib/common.ts, infra/lib/stack.ts, infra/lib/storage/stack.ts
Bucket names must be globally unique. To ensure the infra stacks can be deployed to multiple accounts, use the bucket name as a prefix instead of the actual bucket name.
=> infra: Fix storage bucket name

packages/aft/lib/src/commands/constraints_command.dart, packages/aft/lib/src/commands/publish_command.dart, packages/aft/lib/src/repo.dart
**fix(aft): Run pub get before build_runner if necessary**
If running in a fresh repo/worktree, pub get may not have been run yet which can cause errors. 
**fix(aft): Bump constraints on non-breaking change**
For non-breaking changes, we still need to update all constraints since we "pin" to minor versions. Before, this was leaving some outdated constraints in the repo.
=> fix(aft): Minor fixes

packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart
https://github.com/aws-amplify/amplify-flutter/issues/3275
Ensure `pageSize` and `nextToken` options fields being forwarded.
=> fix(storage): list options pageSize and nextToken params got lost

packages/storage/amplify_storage_s3/example/integration_test/use_case_test.dart
Adds some integ tests for s3 list() API.
=> chore(storage): integ test for pageSize/nextToken in list()

.github/workflows/amplify_canaries.yaml
- Adds timeout and retry logic for booting the iOS simulator
- Uses iOS 14 for iOS runs. iOS 13 is flaky for some reason (to do with the flutter tooling itself). With iOS 14 we are still testing a pre-concurrency version of iOS which should catch any issues related to our use of async/await. Otherwise, we don't expect any difference between iOS 13/14.
=> chore(canaries): Improve flakiness

.github/workflows/amplify_canaries.yaml
iOS e2e reports wrong metric name (casing is off) 
This causes those reported metrics to be missed by our CW alarms. 
=> ci: fix canaries ios metric name

packages/aws_sdk/smoke_test/lib/src/sdk/src/s3/model/analytics_filter.dart, packages/aws_sdk/smoke_test/lib/src/sdk/src/s3/model/lifecycle_rule_filter.dart, packages/aws_sdk/smoke_test/lib/src/sdk/src/s3/model/metrics_filter.dart, packages/aws_sdk/smoke_test/lib/src/sdk/src/s3/model/replication_rule_filter.dart, packages/aws_sdk/smoke_test/lib/src/sdk/src/s3/model/select_object_content_event_stream.dart, packages/smithy/goldens/lib/awsJson1_0/lib/src/json_rpc_10/model/my_union.dart, packages/smithy/goldens/lib/awsJson1_1/lib/src/json_protocol/model/my_union.dart, packages/smithy/goldens/lib/restJson1/lib/src/rest_json_protocol/model/my_union.dart, packages/smithy/goldens/lib/restXml/lib/src/rest_xml_protocol/model/xml_union_shape.dart, packages/smithy/goldens/lib2/awsJson1_0/lib/src/json_rpc_10/model/my_union.dart, packages/smithy/goldens/lib2/awsJson1_1/lib/src/json_protocol/model/my_union.dart, packages/smithy/goldens/lib2/restJson1/lib/src/rest_json_protocol/model/my_union.dart, packages/smithy/goldens/lib2/restXml/lib/src/rest_xml_protocol/model/xml_union_shape.dart, packages/smithy/smithy_codegen/lib/src/generator/structure_generator.dart, packages/smithy/smithy_codegen/lib/src/generator/union_generator.dart, packages/storage/amplify_storage_s3_dart/lib/src/sdk/src/s3/model/select_object_content_event_stream.dart
Currently to construct a union member, you need to pass an instance of the represented object, for example:
```dart
sealed class AnalyticsFilter extends SmithyUnion<AnalyticsFilter> {
const factory AnalyticsFilter.tag(Tag tag) = AnalyticsFilterTag;
}
void usage() {
final filter = AnalyticsFilter.tag(Tag(key: key, value: value));
}
```
This was uncovered as a less-than-desirable DX when exploring the config object. Instead, we can inline the parameters needed to construct the object to save the extra construction:
```dart
sealed class AnalyticsFilter extends SmithyUnion<AnalyticsFilter> {
factory AnalyticsFilter.tag({
required String key,
required String value,
}) =>
AnalyticsFilterTag(_i2.Tag(
key: key,
value: value,
));
}
void usage() {
final filter = AnalyticsFilter.tag(key: key, value: …
```
=> chore(smithy): Improve union DX

packages/aws_common/lib/src/util/recase.dart, packages/smithy/goldens/lib/restJson1/lib/src/rest_json_protocol/model/player_action.dart, packages/smithy/goldens/lib2/restJson1/lib/src/rest_json_protocol/model/player_action.dart, packages/smithy/smithy_codegen/lib/src/generate.dart, packages/smithy/smithy_codegen/lib/src/generator/context.dart, packages/smithy/smithy_codegen/lib/src/generator/enum_generator.dart, packages/smithy/smithy_codegen/lib/src/generator/serialization/structure_serializer_generator.dart, packages/smithy/smithy_codegen/lib/src/generator/serialization/structure_xml_serializer_generator.dart, packages/smithy/smithy_codegen/lib/src/generator/union_generator.dart, packages/smithy/smithy_codegen/lib/src/generator/visitors/library_visitor.dart, packages/smithy/smithy_codegen/lib/src/generator/visitors/symbol_visitor.dart, packages/smithy/smithy_codegen/lib/src/util/shape_ext.dart, packages/smithy/smithy_codegen/test/default_value_test.dart, packages/smithy/smithy_codegen/test/generator/documentation_test.dart, packages/smithy/smithy_codegen/test/naming_test.dart
- Fixes lint with unions
- Makes `CodegenContext` global to allow access from anywhere
- Adds default value support for strings and string enums
- Adds special casing rule for `AWS` to prevent recasing
- Allows overriding symbol types for certain shape IDs
=> chore(smithy): Various improvements

.github/workflows/dart_dart2js.yaml, .github/workflows/dart_ddc.yaml, .github/workflows/dart_native.yaml, .github/workflows/dart_vm.yaml, .github/workflows/flutter_android.test.yaml, .github/workflows/flutter_ios.yaml, .github/workflows/flutter_vm.yaml, .gitignore, aft.yaml, packages/aft/README.md, packages/aft/lib/aft.dart, packages/aft/lib/src/command_runner.dart, packages/aft/lib/src/commands/amplify_command.dart, packages/aft/lib/src/commands/bootstrap_command.dart, packages/aft/lib/src/commands/docs_command.dart, packages/aft/lib/src/commands/publish_command.dart, packages/aft/lib/src/models/config.dart, packages/aft/lib/src/options/glob_options.dart, packages/aft/lib/src/pub/pub_runner.dart, packages/aft/pubspec.yaml, packages/amplify_core/analysis_options.yaml, packages/amplify_core/doc/lib/auth.dart, packages/amplify_core/lib/src/category/amplify_auth_category.dart
Adds `aft docs build` and `aft docs serve` to compile docs and serve docs on a local HTTP server with auto-rebuild, respectively.
=> feat(aft): Docs commands

packages/amplify_datastore/ios/Classes/types/model/FlutterModelSchema.swift, packages/amplify_datastore/ios/amplify_datastore.podspec
https://github.com/aws-amplify/amplify-flutter/issues/663
https://github.com/aws-amplify/amplify-flutter/issues/1693
https://github.com/aws-amplify/amplify-flutter/issues/2527
https://github.com/aws-amplify/amplify-swift/issues/2873
Bumps Amplify Swift version to 1.30.4. 
The new Amplify Swift version fixes a couple of known issues. 
In particular, #663, a longstanding issue where models were not decoded/synced correctly on iOS devices when they were modified on Android devices 🎉 
Like wise some observed multi auth issues have been fixed in this release too. 
=> chore(datastore): Amplify Swift version bump to 1.30.4

.github/composite_actions/launch_ios_simulator/action.yaml, .github/workflows/amplify_canaries.yaml
- Switches to `macos-13` for iOS canaries (seems to be more reliable)
- Adds pre-build to Android to prevent timeouts
- Adds cache removal for iOS launcher action to improve flakiness
=> ci(canaries): More improvements

.github/dependabot.yaml, packages/aft/lib/src/commands/generate/generate_workflows_command.dart
It's too noisy currently and since we support ranges in our constraints only a minor/major version bump could potentially impact our customers. And if a patch bump does fix a security concern, we would expect that to be handled through the dependabot security advisories which is separate from this configuration.
=> ci(dependabot): Ignore patch versions

.github/dependabot.yaml, packages/aft/lib/src/commands/generate/generate_workflows_command.dart
Should be `kotlin_version` I think given recent dependabot PRs
=> ci(dependabot): Fix kotlin name

.vscode/settings.json
Ignores generated SDK files in the Dart analyzer which hog resources when opening the monorepo. To get analysis on these files, we can open the packages individually in VSCode, which will ignore the top-level settings.
=> chore(repo): Improve analysis speed

.github/dependabot.yaml, packages/aft/lib/src/commands/generate/generate_workflows_command.dart
For the same reason we ignore the Kotlin version itself
=> ci(dependabot): Ignore Kotlin gradle plugin

.github/workflows/amplify_integration_tests.yaml
Run integ tests in CI for v0 branch push. We moved some branches around w v1 release but never changed integ test config to match in v0.
=> chore: run integ in v0 push

README.md, packages/amplify/amplify_flutter/README.md, packages/amplify_datastore/README.md, packages/analytics/amplify_analytics_pinpoint/README.md, packages/api/amplify_api/README.md, packages/auth/amplify_auth_cognito/README.md, packages/storage/amplify_storage_s3/README.md
Adds some v0/v1 migration info in the README. See live version https://github.com/ragingsquirrel3/amplify-flutter/tree/chore/readme-v0-deprecation#supported-amplify-categories
=> chore: v0 migration/README updates

example/pubspec.yaml, packages/amplify_datastore/example/pubspec.yaml, packages/api/amplify_api/example/pubspec.yaml, packages/auth/amplify_auth_cognito/example/pubspec.yaml, packages/storage/amplify_storage_s3/example/pubspec.yaml
Old versions of cupertino icons in example apps were causing `melos bootstrap` errors in v0 so integ test apps won't build. This PR removes them so apps can be tested.
=> chore: remove some cupertino icon usage

packages/aft/lib/src/commands/publish_command.dart
Fixes issue on Windows with checking the `.dart_tool` directory by always running `pub get`.
=> ci: Fix failing native tests

packages/aft/lib/src/commands/generate/generate_sdk_command.dart, packages/aft/pubspec.yaml, packages/aws_common/lib/src/config/aws_service.dart
Generates the list of AWS services directly via the `aft generate sdk` command. Later, this will be expanded to include AWS regions and other common configuration values.
=> feat(aft): Generate AWS config

packages/amplify_core/lib/src/logger/amplify_logger.dart, packages/aws_common/lib/src/logging/aws_logger.dart, packages/aws_common/test/logging/aws_logger_test.dart, packages/notifications/push/amplify_push_notifications/test/amplify_push_noitfications_impl_test.mocks.dart, packages/notifications/push/amplify_push_notifications_pinpoint/test/push_notifications_background_processing_test.mocks.dart, packages/storage/amplify_storage_s3_dart/test/test_utils/mocks.dart
- Update registerPlugin API to allow registering one plugin per type in a logger hierarchy.
- Add getPlugin API to get plugin of an specified type registered in a logger hierarchy.
=> feat(logging): logger can register one plugin per type in a logger hierarchy

packages/amplify_datastore/android/build.gradle, packages/amplify_native_legacy_wrapper/android/build.gradle, packages/notifications/push/amplify_push_notifications/android/build.gradle
- Updates Amplify Android to `2.10.0`
- Updates legacy Android to `2.72.0`
=> chore(deps): Update Amplify Android

packages/aft/lib/src/commands/generate/generate_sdk_command.dart
`aft generate sdk -m [path to models]` to checkout models only if the local directory is a git repository.
=> fix(aft): generate sdk from local directory which is not a git repository

.github/workflows/amplify_integration_tests.yaml
Auth requires more time. This can be adjusted on a per-plugin basis when integ tests are split out.
=> ci: Bump integ tests to 60 minutes

packages/amplify_datastore/analysis_options.yaml, packages/amplify_datastore/example/lib/main.dart, packages/amplify_datastore/example/lib/queries_display_widgets.dart, packages/amplify_datastore/example/lib/save_model_widgets.dart, packages/amplify_datastore/test/amplify_datastore_stream_controller_test.dart, packages/amplify_datastore/test/stream_utils/throttle_test.dart
Removes the analysis options that only excluded the example app. This was causing friction when trying to use the example app and resolve local deps. 
=> chore(datastore): removed analysis options

packages/auth/amplify_auth_cognito_dart/lib/src/credentials/cognito_keys.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart, packages/auth/amplify_auth_cognito_dart/lib/src/jwt/src/cognito.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_user_pool_tokens.dart, packages/auth/amplify_auth_cognito_test/lib/common/jwt.dart, packages/auth/amplify_auth_cognito_test/lib/common/mock_oauth_server.dart, packages/auth/amplify_auth_cognito_test/test/flows/hostedui/hosted_ui_platform_test.dart
`nonce` was previously used to protect against replay attacks, but these are primarily a concern with the implicit OAuth grant which we do not support. To unblock potential issues with custom OIDC providers, we're removing the nonce checks.
=> fix(auth): Remove `nonce` usage

packages/amplify_core/lib/src/types/notifications/push/push_notification_message.dart, packages/notifications/push/amplify_push_notifications/test/push_notification_message_test.dart, packages/notifications/push/amplify_push_notifications/test/test_data/fake_notification_messges.dart
Fixes #3435.
Simple alerts on iOS take the shape (see [docs](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html)):
```json
{
"aps": {
"alert": "Message"
}
}
```
This case was not being handled in the deserializer (only the case where `alert` was a Map).
=> fix(push): Incorrect handling of simple alert

packages/analytics/amplify_analytics_pinpoint_dart/pubspec.yaml, packages/api/amplify_api/pubspec.yaml, packages/authenticator/amplify_authenticator/pubspec.yaml, packages/storage/amplify_storage_s3/pubspec.yaml, packages/storage/amplify_storage_s3_dart/pubspec.yaml
- Bumps mocktail to 1.0.0. Dependabot bumped to include a range in https://github.com/aws-amplify/amplify-flutter/pull/3501 but we can just increase to 1.0.0
=> chore: update mocktail to 1.0.0

packages/amplify_datastore/lib/amplify_datastore.dart
https://github.com/aws-amplify/amplify-flutter/issues/3368
Ignore platform exceptions so that authenticator no longer freezes app with datastore on hot restart.
=> fix(datastore): hot restart

packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/credential_store_state_machine.dart
When a query is made to the credential store, we currently always hit the underlying store. However, due to the queuing nature of the store, if it's in a `success` state we can immediately return since we are guaranteed to have the latest data.
=> perf(auth): Fetch auth session

.vscode/dart.code-snippets
Adds `dataclass` and `dataclassfile` code snippets for templating a JSON-serializable data class which conforms to `AWSSerializable` and `AWSDebuggable`.
=> chore(repo): Add Dart VSCode snippets

.vscode/settings.json, infra/tool/create_configs.dart, packages/amplify_core/lib/src/state_machine/event.dart, packages/amplify_core/lib/src/state_machine/state_machine.dart, packages/amplify_core/test/state_machine/my_state_machine.dart, packages/amplify_core/test/state_machine/state_machine_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/cognito_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
- Further improves analysis speed in the repo by only analyzing the projects which have files open.
- Fixes the `create_configs` script for new `aft.yaml` refactor
- Cleans up some code in the sign-in state machine and adds logging
Most importantly, this fixes an issue with Zones in the state machine code I was not aware of which effectively bricks the state machines when there is an unhandled error.
=> chore(repo): Various fixes

packages/api/amplify_api_ios/ios/amplify_api_ios.podspec
The repo added a new enum case (daltoniam/Starscream@f900d67) which is not handled by Amplify's AppSyncRealTimeClient causing build failures for Starscream >4.0.4.
Build failures: aws-amplify/amplify-flutter/actions/runs/5917560965
=>  fix(datastore): Pin Starscream

build-support/build_canary.sh, packages/amplify_datastore/ios/amplify_datastore.podspec
The repo added a new enum case (https://github.com/daltoniam/Starscream/commit/f900d67759cdd11df3dcca34af21f40f59fe4e79) which is not handled by Amplify's `AppSyncRealTimeClient` causing build failures for Starscream >4.0.4.
Build failures: https://github.com/aws-amplify/amplify-flutter/actions/runs/5917560965
=> fix(datastore): Pin `Starscream`

packages/aft/lib/src/commands/version_bump_command.dart
Fixes issue in `version-bump` where a changelog may be updated without a corresponding version bump. For example, `amplify_flutter` consolidates updates from all packages, and can collect changelog updates when its version has not been bumped causing a ghost `## NEXT` entry.
=> fix(aft): Don't write changelog updates if version was not bumped.

.github/composite_actions/fetch_backends/action.yaml, .github/composite_actions/install_dependencies/action.yaml, .github/composite_actions/log_metric/action.yaml, .github/composite_actions/setup_firefox/action.yaml, .github/dependabot.yaml, packages/aft/lib/src/commands/generate/generate_workflows_command.dart
Dependabot doesn't check this directory, by default.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#enabling-dependabot-version-updates-for-actions
=> ci: Update composite action deps

packages/aft/lib/src/commands/constraints_command.dart, packages/aft/lib/src/commands/publish_command.dart, packages/aft/lib/src/config/config.dart, packages/aft/lib/src/constraints_checker.dart, packages/aft/pubspec.yaml, packages/aft/test/constraints_checker_test.dart
There are bespoke, often confusing, rules to how inter-repo constraints must be handled such that `pub` allows packages to be published. See #2885, #2366, #2865.
This introduces a checker into both `aft constraints` and `aft publish` which validates that package constraints are configured to allow publishing and updates them (or reports an error) if not.
=> feat(aft): Validate local constraints in `aft constraints` and `aft publish`

packages/aft/lib/src/commands/amplify_command.dart, packages/aft/lib/src/commands/bootstrap_command.dart, packages/aft/lib/src/config/config.dart, packages/aft/lib/src/constraints_checker.dart, packages/aft/test/common.dart, packages/aft/test/constraints_checker_test.dart, packages/aft/test/model_test.dart
Some packages in the repo (for example, the `actions` pkg) set a pre-release Dart SDK constraint so that preview features of Dart can be leveraged. This updates `aft` so that:
1. `bootstrap` skips packages which set this constraint if the current Dart SDK doesn't support it.
2.  The constraints checker ignores preview constraints since these packages do not need to conform to the global setting.
=> chore(aft): Better handling of pre-release Dart SDK usage

.github/composite_actions/fetch_backends/action.yaml, .github/composite_actions/log_metric/action.yaml
Bumps the `configure-aws-credentials` action so that we no longer receive this error:
```
Assuming role with OIDC
Error: Could not assume role with OIDC: SecretAccessKey contains special characters.
```
=> ci: Fix AWS credentials retrieval

packages/amplify_datastore/ios/Classes/CognitoPlugin.swift
The call from Native -> Dart to retrieve Auth credentials is being performed on a background thread which results in the following warning message.
```
The 'dev.flutter.pigeon.NativeAuthPlugin.fetchAuthSession' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
```
=> fix(datastore): Use platform thread

packages/amplify_datastore/android/build.gradle, packages/amplify_datastore/example/android/build.gradle, packages/amplify_datastore/example/integration_test/utils/setup_utils.dart, packages/notifications/push/amplify_push_notifications/android/build.gradle
- https://github.com/aws-amplify/amplify-flutter/issues/3575 (fixed by https://github.com/aws-amplify/amplify-android/pull/2565)
- https://github.com/aws-amplify/amplify-flutter/issues/1693 (fixed by https://github.com/aws-amplify/amplify-android/pull/2561)
- https://github.com/aws-amplify/amplify-flutter/issues/3017 (fixed by https://github.com/aws-amplify/amplify-android/pull/2551)
- Bump Amplify Android to v2.12.0
- Increase cloud sync timeout from 2 minutes to 10 minutes. This is currently a frequent source of integ test failure.
=> chore: bump amplify android to 2.12.0

.github/composite_actions/fetch_backends/action.yaml, .github/composite_actions/log_metric/action.yaml
Basically, force a refresh. Some composite actions are failing due to stale credentials.
https://github.com/aws-actions/configure-aws-credentials#unset-current-credentials
=> ci: Unset AWS credentials

packages/authenticator/amplify_authenticator/pubspec.yaml, packages/logging_cloudwatch/amplify_logging_cloudwatch/example/bin/main.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/pubspec.yaml, packages/logging_cloudwatch/amplify_logging_cloudwatch/test/queued_item_store_test.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/aws_logging_cloudwatch.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/queued_item_store/queued_item_store.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/pubspec.yaml
- fixed comment for static method
- bumped versions for dependencies
- updated a test to prevent timeout and make it more efficient
=> chore(logging): fixed comment for static method and export

packages/auth/amplify_auth_cognito/example/integration_test/mfa_sms_totp_optional_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/mfa_sms_totp_required_test.dart
Adds some more e2e tests for the `updateMfaPreference` API
=> test(auth): MFA preference tests

infra/lib/auth/stack.ts, infra/lib/stack.ts, packages/auth/amplify_auth_cognito/example/integration_test/sign_up_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/user_attributes_test.dart
Adds tests which encode the behavior around `resendUserAttributeConfirmationCode` with and without the `keepOriginal` properties enabled in Cognito.
=> test(auth): Resend user attribute confirmation code

packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/cloudwatch_logger_plugin.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/log_stream_provider.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/stoppable_timer.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/test/cloudwatch_logger_plugin_test.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/test/mocks.dart
- add caching to log stream provider
- cleanup the sync logic
- TODO: add log rotation to queued item store
=> feat(logging): log stream provider to cache log stream

infra/lib/stack.ts, packages/auth/amplify_auth_cognito/example/integration_test/custom_auth_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
The fix in https://github.com/aws-amplify/amplify-flutter/pull/3558 assumed that device SRP would only be performed when password SRP had previously been performed as part of a custom Auth workflow. However, this is not true. In custom auth workflows without password SRP, device SRP can still be required when device tracking is enabled, and in this case it is not a requirement that password SRP have been previously performed.
=> fix(auth): Custom auth with device tracking, no SRP

packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/dart_queued_item_store.stub.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/dart_queued_item_store.vm.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/dart_queued_item_store.web.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/drift/drift_queued_item_store.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/index_db/indexed_db_adapter.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/test/queued_item_store_test.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/queued_item_store/in_memory_queued_item_store.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/queued_item_store/queued_item_store.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/test/queued_item_store/queued_item_store_test.dart
- add queue rotation
- next: to use queue rotation when log store is full
=> feat(logging): enable queue rotation

packages/auth/amplify_auth_cognito_dart/ffigen.macos.yaml, packages/auth/amplify_auth_cognito_dart/lib/src/asf/asf_device_info_collector.macos.dart, packages/auth/amplify_auth_cognito_dart/lib/src/platform/macos_bindings.g.dart
- Adds checks to results of `IOServiceGetMatchingService` and `IORegistryEntryCreateCFProperty` FFI calls to prevent trying to access bad data in cast or free calls.
- Removes accesses to `NSScreen` due to potential ffigen bug
=> fix(auth): Crash with EXC_BAD_ACCESS

.github/workflows/amplify_logging_cloudwatch.yaml, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/dart_queued_item_store.vm.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/drift/drift_queued_item_store.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/pubspec.yaml, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/cloudwatch_logger_plugin.dart
- queued item store to use path provider on vm if storage path is empty. so cloudwatch logger plugin can init the log store in the construct.
=> fix(logging): queued item store to use path provider on vm

packages/amplify_core/lib/src/state_machine/event.dart, packages/amplify_core/lib/src/state_machine/state_machine.dart, packages/auth/amplify_auth_cognito/example/integration_test/hosted_ui_webview_test.dart, packages/auth/amplify_auth_cognito/example/pubspec.yaml, packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_flutter.dart, packages/auth/amplify_auth_cognito/pubspec.yaml, packages/auth/amplify_auth_cognito/test/hosted_ui_platform_flutter_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_io.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/event/hosted_ui_event.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart, packages/auth/amplify_auth_cognito_test/test/flows/hostedui/hosted_ui_platform_test.dart
The HostedUIPlatform had a bug due to the fact that it both called `dispatcher.dispatchAndComplete` (which throws on failure states) and threw a `UserCancelledException` which triggers a failure state. This lead to the error being thrown from `signInWithWebUI` and an uncaught exception being raised at the `dispatchAndComplete` call.
This resolves the issue by only throwing from the HostedUiPlatform and letting the state machine resolving the cancellation.
This also fixes an issue where `cancelSignIn` was never being called because the state machine was in a `signingIn` state at the time the cancellation was dispatched.
=> fix(auth): Uncaught Hosted UI cancellation

packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform_io.dart, packages/auth/amplify_auth_cognito_test/test/flows/hostedui/hosted_ui_platform_io_test.dart
Fixes flaky HostedUI test by updating expectations and not relying on the timings of the event loop.
=> test(auth): Fix flaky test

.github/dependabot.yaml, packages/aft/lib/src/commands/generate/generate_workflows_command.dart
The use of the root (`/`) as the directory only has recursive behavior for some package managers. Pub + Gradle apparently don't support this 🫠
Reverts the consolidation in https://github.com/aws-amplify/amplify-flutter/pull/3668 in favor of individual package entries but leaves the groups work. The docs are not super explicit but it seems that if each entry defines the same group, that is enough to group them all together.
=> ci: Fix dependabot groups

packages/aft/lib/src/constraints_checker.dart, packages/aft/test/constraints_checker_test.dart, packages/aft/test/helpers/package_descriptor.dart, packages/auth/amplify_auth_cognito/pubspec.yaml, packages/auth/amplify_auth_cognito_test/pubspec.yaml
Fixes a couple bugs noticed in the publish yesterday and updates constraints in the repo.
=> fix(aft): Constraints edge cases

packages/aft/lib/src/models.dart, packages/aft/test/e2e_test.dart, packages/aft/test/model_test.dart
There is a seeming bug in `pub` which causes issues publishing 0-based patch versions with `+` in their versions. For now, we can just stop publishing these and prefer true SemVer patch bumps instead.
=> fix(aft): Don't use build numbers (`+`) for 0-based patch versions

packages/aft/lib/src/commands/link_command.dart
Unlike every other package, aft must work without `pubspec_overrides`. It's counter productive to generate it and and its presence can interfere with local development.
=> chore(aft): Package `aft` should not have `pubspec_overrides.yaml`

packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/dart_queued_item_store.stub.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/dart_queued_item_store.vm.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/dart_queued_item_store.web.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/drift/drift_queued_item_store.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/index_db/indexed_db_adapter.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/test/queued_item_store_test.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/cloudwatch_logger_plugin.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/queued_item_store/queued_item_store.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/test/cloudwatch_logger_plugin_test.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/test/queued_item_store/queued_item_store_test.dart
- make QueuedItemStore.isFull() sync
- enable log rotation when log store is full
- set retry on full log store sync
- handle rejectedLogEventsInfo response and do partial sync
=> feat(logging): enable log rotation and set retry on full log store sync

packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/amplify_cloudwatch_logger_plugin.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/amplify_log_stream_name_provider.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/device_info/device_info.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/device_info/device_info.stub.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/device_info/device_info.vm.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/device_info/device_info.web.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/pubspec.yaml, packages/logging_cloudwatch/amplify_logging_cloudwatch/test/amplify_log_stream_provider_test.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/cloudwatch_logger_plugin.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/log_stream_provider.dart
- add amplify cloudwatch logger plugin
- update DefaultCloudWatchLogStreamProvider to accept a Function for `defaultLogStreamNameProvider` instead of String value
Next: after remote config provider is ready apply category and user level constraints
=> feat(logging): add amplify cloudwatch logger plugin base implementation

packages/amplify_datastore/example/integration_test/clear_test.dart, packages/amplify_datastore/example/integration_test/utils/setup_utils.dart
- Remove the delay prior to starting datastore from our integration test suite. This delay is no longer needed with https://github.com/aws-amplify/amplify-android/issues/1690 resolved.
See passing test run (with all the cloud sync tests running): https://github.com/aws-amplify/amplify-flutter/actions/runs/6188100758/job/16799548931?pr=3738
Note: As mentioned in https://github.com/aws-amplify/amplify-android/issues/1690#issuecomment-1692358164, and https://github.com/aws-amplify/amplify-android/issues/1464, calling stop and then start multiple times in a row, or calling stop/clear multiple times in a row will still result in issues.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> chore: remove delay to start datastore in tests

packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/sign_up_form_field.dart, packages/authenticator/amplify_authenticator/test/sign_up_form_test.dart, packages/authenticator/amplify_authenticator_test/lib/src/mock_authenticator_app.dart, packages/authenticator/amplify_authenticator_test/lib/src/pages/sign_up_page.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/3757
- Apply custom validators to date fields 
- Add test
=> fix(authenticator): date validator

infra/lib/logging/stack.ts, infra/lib/stack.ts
- fix duplicate imports: `AuthIntegrationTestStackEnvironmentProps`, `StorageIntegrationTestStack`
- set s3bucket autoDeleteObject to true so the logging stack can be destroyed 
=> fix(logging): fix logging infra stack

packages/analytics/amplify_analytics_pinpoint_dart/pubspec.yaml, packages/common/amplify_db_common/example/pubspec.yaml, packages/common/amplify_db_common_dart/example/pubspec.yaml, packages/common/amplify_db_common_dart/pubspec.yaml, packages/storage/amplify_storage_s3_dart/pubspec.yaml, packages/test/pub_server/pubspec.yaml, pubspec.yaml
The `drift_dev` dependency follows the same versioning as `drift`. Pinning to the same range enables better awareness of when to re-run table generation.
=> chore(repo): Pin `drift_dev`

packages/amplify/amplify_flutter/lib/src/amplify_logging_cloudwatch.dart, packages/amplify_core/lib/src/logger/amplify_logging_cloudwatch.dart, packages/amplify_core/lib/src/state_machine/state_machine.dart, packages/amplify_datastore/lib/amplify_datastore.dart, packages/analytics/amplify_analytics_pinpoint_dart/lib/src/impl/analytics_client/event_client/queued_item_store/dart_queued_item_store.web.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/blocs/subscriptions_bloc.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/blocs/web_socket_bloc.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/services/web_socket_service.dart, packages/auth/amplify_auth_cognito/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/asf/asf_context_data_provider.dart, packages/auth/amplify_auth_cognito_dart/lib/src/asf/asf_device_info_collector.dart, packages/authenticator/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/example/lib/main.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/dart_queued_item_store.web.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/cloudwatch_logger_plugin.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/remote_constraint_provider.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart
- register CloudWatchLoggerPlugin to AWSLogger. AWSLogger is the root logger and so all logs will be sent to cloudwatch
- set log level to verbose so CloudWatchLoggerPlugin gets all the logs and filters based on the logging constraints
- use AmplifyLoggerMixin for amplify libraries so they have the amplify namespace added to their logger full namespace
- override get logger to use category logger
=> feat(logging):send amplify library logs to cloudwatch

packages/logging_cloudwatch/amplify_logging_cloudwatch/example/lib/main.dart
- example app to use different keys for home page for guest and auth user
- to fix exception because of Multiple widgets used the same GlobalKey.
=> chore(logging): example app to use different keys for home page for guest and auth user

packages/logging_cloudwatch/amplify_logging_cloudwatch/example/lib/amplifyconfiguration_logging.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/example/lib/homepage.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/example/lib/main.dart
Fix and clean logger example app. 
1. Initialize Amplify in stateful widget like our other example apps
2. Fix the navigation error
3. Remove redundant code by storing category loggers in a map
4. Fix UI issues with clipping overflow content by refactoring UI elements 
=> chore(logging): fixes and improvement to logging example app

packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/remote_constraint_provider.dart
- add http1 to supported protocols
- fix the request signer to not sign the empty body. it causes the remote config request to fail on the web
=> fix(logging): not sign the empty body of the get remote config request

packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/dart_queued_item_store.web.dart, packages/logging_cloudwatch/amplify_logging_cloudwatch/lib/src/queued_item_store/index_db/indexed_db_adapter.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/cloudwatch_logger_plugin.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/queued_item_store/queued_item_store.dart
- indexedDb adapter to wait for the test DB open result when checking if indexedDB is supported.
- DartQueuedItemStore web implementation to wait for indexedDb adapter and fall back to in memory if indexedDb is not supported
- indexedDb adapter getAll method to read result as Object instead of Map
=> fix(logging): use indexedDB on web if it is supported

packages/smithy/smithy/lib/src/http/http_operation.dart
Casts output to fix the following `beta` test failure:
```
Failed to build aft:aft:
packages/smithy/smithy/lib/src/http/http_operation.dart:271:16: Error: A value of type 'Object?' can't be assigned to a variable of type 'Output?'.
- 'Object' is from 'dart:core'.
output = switch (payload) {
^
```
=> fix(smithy): casts output to fix beta tests

packages/notifications/push/amplify_push_notifications/lib/src/amplify_push_notifications_impl.dart, packages/notifications/push/amplify_push_notifications/test/amplify_push_notifications_impl_test.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/3737
- Replace PushNotificationException with logger.error when fetching device token times out.
=> fix: remove exception during token timeout

packages/analytics/amplify_analytics_pinpoint/example/integration_test/no_unauth_test.dart, packages/analytics/amplify_analytics_pinpoint_dart/lib/src/analytics_plugin_impl.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/3950
- Catch and log updateEndpoint errors during configure
=> fix: catch and log updateEndpoint error during configure

packages/aws_common/lib/src/logging/log_level.dart
- having the none log level as the last value in the enum list cause the logs with none level to be logged. this fixes the enum value list to have the none as the lowest index so the compareTo method works as expected.
=> fix(logging): fix log levels to have none as the lowest level in the log level enum

packages/analytics/amplify_analytics_pinpoint_dart/lib/src/impl/analytics_client/event_client/event_client.dart
- when unauthenticated access is disabled, Analytics can record events when user is not logged-in but flush events fails due to auth exception and events are cleared from cache.
- if flush events (PutEvents request) fails due to Auth exception, do not clear cache as these events are always retryable
=> fix(analytics): event client flush events to do not discard events from cache on auth exception

packages/api/amplify_api/example/integration_test/graphql/iam_test.dart
- Add a `limit` to `ModelQueries.list` operations that expect a certain model in the response.
Tests that use `ModelQueries.list` and expect certain models in the response can fail if the DB has a large number of items in it. Models are cleaned up after tests complete, but during test execution the number of models can increase past the default limit.
=> chore: fix flaky api e2e test

packages/analytics/amplify_analytics_pinpoint_dart/pubspec.yaml, packages/common/amplify_db_common/example/pubspec.yaml, packages/common/amplify_db_common/pubspec.yaml, packages/common/amplify_db_common_dart/example/pubspec.yaml, packages/common/amplify_db_common_dart/pubspec.yaml, packages/storage/amplify_storage_s3/example/pubspec.yaml, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/transfer/database/database_io.g.dart, packages/storage/amplify_storage_s3_dart/pubspec.yaml, packages/test/pub_server/pubspec.yaml, pubspec.yaml
https://github.com/aws-amplify/amplify-flutter/pull/3976
Slide drift window to: 
- `drift: ">=2.12.0 <2.13.0"`
- `drift_dev: ">=2.12.0 <2.13.0"`
=> chore(deps): Bump the drift window 2.13.0

packages/aft/pubspec.yaml, packages/auth/amplify_auth_cognito_dart/lib/src/asf/asf_worker.worker.js.dart, packages/auth/amplify_auth_cognito_dart/lib/src/asf/asf_worker.worker.vm.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/device/confirm_device_worker.worker.js.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/device/confirm_device_worker.worker.vm.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_device_password_verifier_worker.worker.js.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_device_password_verifier_worker.worker.vm.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_init_worker.worker.js.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_init_worker.worker.vm.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_password_verifier_worker.worker.js.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/srp/srp_password_verifier_worker.worker.vm.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/worker/secure_storage_worker.worker.js.dart, packages/secure_storage/amplify_secure_storage_dart/lib/src/worker/secure_storage_worker.worker.vm.dart, packages/smithy/smithy_codegen/pubspec.yaml, packages/worker_bee/worker_bee_builder/pubspec.yaml, pubspec.yaml
- bump code_builder version for the repo
=> chore(deps): Bump code_builder version

.github/workflows/e2e_android.yaml, .github/workflows/e2e_ios.yaml, .github/workflows/e2e_linux.yaml, .github/workflows/e2e_web.yaml, .github/workflows/e2e_windows.yaml
- run integ tests against flutter beta (excluding PRs)
=> chore: run integ tests against flutter beta

packages/amplify_core/lib/src/types/datastore/models/query_snapshot.dart, packages/amplify_core/lib/src/types/datastore/models/sorted_list.dart, packages/amplify_datastore_plugin_interface/test/query_snapshot_test.dart, packages/amplify_datastore_plugin_interface/test/sorted_list_test.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/3649
- When event type is `EventType.create` and the model already exists in the list, evaluate if the model has changed
=> fix(datastore): emit observeQuery snapshot when model create mutation results in an updated model

packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_phone_field.dart, packages/authenticator/amplify_authenticator/lib/src/mixins/authenticator_username_field.dart, packages/authenticator/amplify_authenticator/lib/src/utils/validators.dart, packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/confirm_sign_in_form_field.dart, packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/phone_number_field.dart, packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/sign_up_form_field.dart, packages/authenticator/amplify_authenticator/test/sign_up_form_test.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/4079
- Drop the country code prefix before performing validation
The country code is populated from a drop down list of known valid numbers so there is no need to validate it. Including it in validation makes it challenging to check for a blank phone number since the country code is always present.
=> fix(authenticator): required phone number validator

packages/amplify_core/lib/src/category/amplify_logging_category.dart, packages/logging_cloudwatch/aws_logging_cloudwatch/lib/src/cloudwatch_logger_plugin.dart
- Moved user agent for `flushLogs` out of `cloudwatch_logger_plugin` and into amplify logging category.
=> chore: moved user agent to logging category api

.github/workflows/dart_dart2js.yaml, .github/workflows/dart_ddc.yaml
This fixes an error of browser tests not being found when using the one liner `dart run build_runner test -- -p chrome`
Broke run command into two parts. 
1. Build the test directory with args: `dart run build_runner build test`
2. Then run tests given a platform: `dart test -p`
Context: 
Dart test browser suite was failing in CI after no changes to code base. Nor any external changes were identified.
<details>
<summary>Original error log</summary>
```
$ dart run build_runner test -- -p chrome
[INFO] Generating build script completed, took 192ms
[INFO] Reading cached asset graph completed, took 185ms
[INFO] Checking for updates since last build completed, took 583ms
[INFO] Running build completed, took 115ms
[INFO] Caching finalized dependency graph completed, took 171ms
[INFO] Creating …
```
=> fix(workflows): dart browser workflows

packages/smithy/goldens/lib/restXml/pubspec.yaml, packages/smithy/goldens/lib/restXmlWithNamespace/pubspec.yaml, packages/smithy/goldens/lib2/restXml/pubspec.yaml, packages/smithy/goldens/lib2/restXmlWithNamespace/pubspec.yaml, packages/smithy/smithy/pubspec.yaml, packages/smithy/smithy_aws/pubspec.yaml, packages/smithy/smithy_codegen/pubspec.yaml, packages/smithy/smithy_test/pubspec.yaml, pubspec.yaml
fixes #4297 
- Bumps xml range to 6.5.0
- The version is no longer pinned because version 6.3.0 contained a code change that required us to bump to 6.3.0 exclusively. We can return to the window since there are no code changes needed for 6.4.0-6.5.0. 
- We also want to use the window because xml 6.5.0 requires SDK version 3.2.0, which would break us as we're using 3.0.1. Xml 6.4.0 also requires Dart 3.0 so going back to the window will allow customers to be more flexible with their dart version.
=> chore(deps): bump xml range to 6.5.0

packages/aft/test/model_test.dart
- aft sdk compatibility test has been failing due since Nov because of dart sdk 3.2 being released and the preview version is 3.3
=> chore(aft): bump dart sdk preview version to 3.3 for aft sdk compatibility test

packages/auth/amplify_auth_cognito_dart/lib/src/asf/asf_device_info_collector.windows.dart, packages/smithy/smithy/lib/src/ast/shapes/collection_shape.dart, packages/smithy/smithy/lib/src/ast/shapes/shape_map.dart, packages/smithy/smithy/lib/src/ast/shapes/trait_map.dart, packages/smithy/smithy_codegen/lib/src/util/config_parameter.dart
Dart 3.30 beta introduces new lint failures. This provides fixes for failing tests:
- https://github.com/aws-amplify/amplify-flutter/actions/runs/7556134956/job/20572507702
- https://github.com/aws-amplify/amplify-flutter/actions/runs/7556125826/job/20572480545
- https://github.com/aws-amplify/amplify-flutter/actions/runs/7556149774/job/20572552398
=> chore(smithy,auth): Dart 3.3.0 Beta Analysis Errors

packages/smithy/smithy/lib/src/http/http_operation.dart, packages/smithy/smithy_aws/lib/src/http/retry/aws_retryer.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/4345
- Replace `rethrow`/`catchError(completer.completeError)` with `return completer.completeError(e)`
- Remove a previous fix that was put in place for this that is no longer required
=> fix: uncaught exception in smithy code

.github/workflows/e2e_android.yaml, .github/workflows/e2e_ios.yaml, .github/workflows/e2e_linux.yaml, .github/workflows/e2e_web.yaml, .github/workflows/e2e_windows.yaml
- Removes an exception for auth integration tests that was added in https://github.com/aws-amplify/amplify-flutter/pull/4030.
Auth integration tests were flaky when running against flutter 3.13 due https://github.com/flutter/flutter/issues/134548. That bug was resolved in flutter 3.16. We temporarily added an exception to run auth integration tests against beta when 3.16 was still in beta so that we could get integ tests passing on PRs. Now that 3.16 is stable that exception is not needed.
=> chore: remove exception for auth integ tests

packages/amplify_core/.pubignore
Relaxes the `.pubignore` for amplify core docs folder. 
=> chore(core): relax .pubignore

packages/secure_storage/amplify_secure_storage/android/build.gradle
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/4432
- Fix the `google.crypto.tink` version constraint syntax
Android Security depends on an old version of `google.crypto.tink`. This version logs a long and confusing warning when a new keyset is created. It is not harmful, but it is confusing and clutters logs. We previously resolved this by adding a dependency on v1.8 which contains a fix (https://github.com/tink-crypto/tink/issues/534). However, this dependabot PR (https://github.com/aws-amplify/amplify-flutter/pull/3220) used the incorrect syntax for the version constraint, causing it to be ignored.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> fix: `google.crypto.tink` version constraint

.github/workflows/e2e_windows.yaml
Moves our windows e2e runner to use the windows 4 core runner, `windows-latest`.
=> chore(workflows): Use windows-latest

.github/workflows/actions.yaml, .github/workflows/amplify_canaries.yaml, .github/workflows/dart_dart2js.yaml, .github/workflows/dart_ddc.yaml, .github/workflows/e2e_android.yaml, .github/workflows/e2e_linux.yaml, .github/workflows/flutter_android.yaml
Moves our ubuntu runners to use the now equivalent `ubuntu-latest`.
=> chore(workflows): Use ubuntu-latest

packages/auth/amplify_auth_cognito/CHANGELOG.md, packages/auth/amplify_auth_cognito/pubspec.yaml, packages/auth/amplify_auth_cognito_dart/CHANGELOG.md, packages/auth/amplify_auth_cognito_dart/pubspec.yaml
cherry pick version bump on stable 1.7.1 to main
=> chore(version): cherry pick Bump version

packages/auth/amplify_auth_cognito/example/integration_test/mfa_totp_optional_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/totp_setup_state_machine.dart
https://github.com/aws-amplify/amplify-flutter/issues/4490
Throw exception when verifying the setup TOTP code for better DX/UX. 
=> fix(auth): verifyTotp throw EnableSoftwareTokenMfaException

packages/auth/amplify_auth_cognito/CHANGELOG.md, packages/auth/amplify_auth_cognito/example/integration_test/mfa_totp_optional_test.dart, packages/auth/amplify_auth_cognito/pubspec.yaml, packages/auth/amplify_auth_cognito_dart/CHANGELOG.md, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/totp_setup_state_machine.dart, packages/auth/amplify_auth_cognito_dart/pubspec.yaml
chore(version): Bump version
- fix(auth): Allow retries with verifyTotpSetup() ([https://github.com/aws-amplify/amplify-flutter/pull/4532](https://github.com/aws-amplify/amplify-flutter/pull/4532))
- fix(auth): device metadata migration ([https://github.com/aws-amplify/amplify-flutter/pull/4503](https://github.com/aws-amplify/amplify-flutter/pull/4503))
- fix(auth): verifyTotp throw EnableSoftwareTokenMfaException ([https://github.com/aws-amplify/amplify-flutter/pull/4558](https://github.com/aws-amplify/amplify-flutter/pull/4558))
Updated-Components: amplify_lints, Amplify Flutter, Amplify Dart, Amplify UI, DB Common, Secure Storage, AWS Common, Smithy, Worker Bee
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
=> chore(version): Bump version 1.7.2

packages/analytics/amplify_analytics_pinpoint/pubspec.yaml, packages/authenticator/amplify_authenticator/pubspec.yaml, pubspec.yaml
- correct `package_info_plus` version constraint
=> fix: correct `package_info_plus` version constraint

packages/amplify_core/lib/src/category/amplify_storage_category.dart, packages/amplify_core/lib/src/plugin/amplify_storage_plugin_interface.dart, packages/amplify_core/lib/src/types/storage/remove_many_options.dart, packages/amplify_core/lib/src/types/storage/remove_many_request.dart, packages/amplify_core/lib/src/types/storage/remove_options.dart, packages/amplify_core/lib/src/types/storage/remove_request.dart, packages/amplify_core/lib/src/types/storage/storage_path.dart, packages/storage/amplify_storage_s3/example/integration_test/content_type_infer/content_type_infer_html.dart, packages/storage/amplify_storage_s3/example/integration_test/content_type_infer/content_type_infer_io.dart, packages/storage/amplify_storage_s3/example/integration_test/issues/get_url_special_characters_test.dart, packages/storage/amplify_storage_s3/example/integration_test/transfer_acceleration/transfer_acceleration.dart, packages/storage/amplify_storage_s3/example/integration_test/use_case_test.dart, packages/storage/amplify_storage_s3/example/lib/main.dart, packages/storage/amplify_storage_s3_dart/example/bin/example.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_item.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_remove_many_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_remove_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/path_resolver/s3_path_resolver.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart, packages/storage/amplify_storage_s3_dart/test/path_resolver/path_resolver_test.dart, packages/storage/amplify_storage_s3_dart/test/platform_impl/download_file_html_test.dart, packages/storage/amplify_storage_s3_dart/test/platform_impl/download_file_io_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_download_task_test.dart, packages/storage/amplify_storage_s3_dart/test/test_utils/test_path_resolver.dart
=> feat(storage): update `remove` and `removeMany` APIs

packages/api/amplify_api_dart/lib/src/graphql/helpers/graphql_response_decoder.dart, packages/api/amplify_api_dart/test/graphql_helpers_test.dart
https://github.com/aws-amplify/amplify-flutter/issues/4585
`requestForNextResult ` now preserves the auth mode and api name if provided in the original request.
=> fix(api): Paginated GraphQL preserve request params

packages/test/pub_server/pubspec.yaml
- Set an upper bound on the version of package `pub_api_client`
=> chore: set upper bound on `pub_api_client` version

packages/analytics/amplify_analytics_pinpoint_dart/lib/src/impl/analytics_client/endpoint_client/endpoint_global_fields_manager.dart
- Trim key/values before logging warning to avoid the potential of excessively large values getting included in logs.
=> chore(analytics): trim key/value before logging

packages/amplify_core/lib/src/category/amplify_storage_category.dart, packages/storage/amplify_storage_s3/example/integration_test/use_case_test.dart
- deprecate Storage.move() API
=> feat: deprecate `Storage.move()` API

packages/aft/lib/src/commands/generate/generate_amplify_swift_command.dart, packages/aft/lib/src/commands/generate/generate_command.dart, packages/aft/lib/src/util.dart, packages/aft/pubspec.yaml, packages/amplify_datastore/example/ios/Podfile, packages/amplify_datastore/ios/.gitignore, packages/amplify_datastore/ios/amplify_datastore.podspec, packages/amplify_datastore/ios/internal/AWSDataStorePlugin.podspec, packages/amplify_datastore/ios/internal/AWSPluginsCore.podspec, packages/amplify_datastore/ios/internal/Amplify.podspec
Adds `aft generate amplify-swift` command
- `-b` to change target branch
- `-o` to change output
- `-d` to run a diff of current vs incoming
- Sets cloned files to read-execute. This prevents modifications, but allows `pod install`
- Added internal definitions for pods
=> chore(aft): Added generate amplify-swift

packages/amplify_core/lib/src/amplify_class.dart, packages/amplify_core/test/amplify_class_test.dart, packages/auth/amplify_auth_cognito/example/integration_test/sign_out_test.dart, packages/auth/amplify_auth_cognito_dart/example/web/components/app_component.dart, packages/authenticator/amplify_authenticator/lib/amplify_authenticator.dart, packages/authenticator/amplify_authenticator/lib/src/services/amplify_auth_service.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart
- mark asyncConfig api as deprecated and to be removed in 2.0.0
=> chore(core):mark asyncConfig api as deprecated and to be removed in 2.0.0

packages/storage/amplify_storage_s3/example/integration_test/get_properties_test.dart, packages/storage/amplify_storage_s3/example/integration_test/get_url_test.dart, packages/storage/amplify_storage_s3/example/integration_test/main_test.dart, packages/storage/amplify_storage_s3/example/integration_test/upload_data_test.dart, packages/storage/amplify_storage_s3/example/integration_test/upload_file_test.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/configure.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/create_file/create_file.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/create_file/create_file_html.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/create_file/create_file_io.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/create_file/create_file_stub.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/sign_in_new_user.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/tear_down.dart, packages/storage/amplify_storage_s3/example/pubspec.yaml
- Add e2e test for `uploadData`, `uploadFile`, `getUrl`, and `getProperties` APIs
=> chore(storage): add e2e tests for `uploadData`, `uploadFile`, `getUrl`, `getProperties`

packages/amplify_core/lib/src/types/storage/remove_many_result.dart, packages/storage/amplify_storage_s3/example/integration_test/copy_test.dart, packages/storage/amplify_storage_s3/example/integration_test/get_properties_test.dart, packages/storage/amplify_storage_s3/example/integration_test/get_url_test.dart, packages/storage/amplify_storage_s3/example/integration_test/main_test.dart, packages/storage/amplify_storage_s3/example/integration_test/remove_many_test.dart, packages/storage/amplify_storage_s3/example/integration_test/remove_test.dart, packages/storage/amplify_storage_s3/example/integration_test/upload_data_test.dart, packages/storage/amplify_storage_s3/example/integration_test/upload_file_test.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/object_exists.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_remove_many_result.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/storage_s3_service_test.dart
- Update `StorageRemoveManyResult` and `S3RemoveManyResult` to include errors in `StorageRemoveManyResult`
- Add e2e tests for `remove`, `removeMany`, `copy` APIs
- Update previous tests to use `expectLater` when appropriate
=> chore: update removeMany API, add tests for `remove`, `removeMany`, `copy`

packages/smithy/smithy/lib/src/http/http_operation.dart, packages/smithy/smithy_aws/test/http/dummy_operation.dart, packages/smithy/smithy_aws/test/http/sdk_request_test.dart, packages/storage/amplify_storage_s3/example/integration_test/copy_test.dart, packages/storage/amplify_storage_s3/example/integration_test/download_data_test.dart, packages/storage/amplify_storage_s3/example/integration_test/download_file_test.dart
- Remove logic in smithy's http operation that maps exceptions based on the http status code alone 
- Update Storage e2e tests to check for the correct exception
Prior to this change smithy contains logic to attempt to determine what type of exception should be thrown based on first the error name/shape (Ex: Access Denied) and then the http status code (ex: 403). The issue with this is that some services (S3) have operations that can return multiple errors for a single status code. For example, a 403 http status code during a GetObject operation can mean AccessDenied OR InvalidObjectState. By mapping based on the http status alone the first exception gets thrown.
With the changes smithy will throw a generic SmithyHttpException when it …
=> feat(smithy)!: remove error match on http status code

packages/storage/amplify_storage_s3/example/integration_test/list_test.dart, packages/storage/amplify_storage_s3/lib/src/amplify_storage_s3_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_list_plugin_options.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_list_plugin_options.g.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- Move `delimiter` from `AmplifyStorageS3` to `S3ListPluginOptions`
=> feat(storage)!: move `delimiter` to `S3ListPluginOptions`

packages/amplify_core/lib/src/types/storage/data_payload.dart, packages/amplify_core/lib/src/types/storage/transfer_progress.dart, packages/aws_common/lib/src/http/http_payload.dart, packages/storage/amplify_storage_s3/example/integration_test/copy_test.dart, packages/storage/amplify_storage_s3/example/integration_test/download_data_test.dart, packages/storage/amplify_storage_s3/example/integration_test/download_file_test.dart, packages/storage/amplify_storage_s3/example/integration_test/get_properties_test.dart, packages/storage/amplify_storage_s3/example/integration_test/get_url_test.dart, packages/storage/amplify_storage_s3/example/integration_test/list_test.dart, packages/storage/amplify_storage_s3/example/integration_test/main_test.dart, packages/storage/amplify_storage_s3/example/integration_test/platform_test_html.dart, packages/storage/amplify_storage_s3/example/integration_test/platform_test_io.dart, packages/storage/amplify_storage_s3/example/integration_test/remove_many_test.dart, packages/storage/amplify_storage_s3/example/integration_test/remove_test.dart, packages/storage/amplify_storage_s3/example/integration_test/upload_data_test.dart, packages/storage/amplify_storage_s3/example/integration_test/upload_file_test.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/create_file/create_file_html.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/create_file/create_file_io.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart
- remove calls to `getTemporaryDirectory()` from web e2e tests. These were causing test setup to fail which leads to false positives due to https://github.com/flutter/flutter/issues/146763.
- fix progress reporting for `uploadData`. See note below for more info.
- Add platform specific e2e tests for upload to exercise the `AWSFilePlatform.fromFile()` constructor
- Add e2e tests for progress notifications and pause/resume/cancel. 
` upoadData` cannot report progress % for streams because the total size is unknown until the stream closes. Prior to this PR all `StorageDataPayload` are treated like streams even when they are created from string/json/etc. This PR converts the string/json/etc payload to byte data and reads the length when the …
=> chore(storage): fix progress for upload, add e2e for progress, pause, resume, and cancel

packages/authenticator/amplify_authenticator/lib/src/widgets/social/social_button.dart
- update SocialSignInButtons to use textScaler instead of textScaleFactor
=> chore(authenticator): SocialSignInButtons to use textScaler instead of textScaleFactor

packages/amplify_core/lib/src/types/auth/attribute/auth_user_attribute.dart, packages/amplify_core/lib/src/types/auth/attribute/auth_user_attribute_key.dart, packages/amplify_core/lib/src/types/auth/attribute/confirm_user_attribute_options.dart, packages/amplify_core/lib/src/types/auth/attribute/fetch_user_attributes_options.dart, packages/amplify_core/lib/src/types/auth/attribute/send_user_attribute_verification_code_options.dart, packages/amplify_core/lib/src/types/auth/attribute/update_user_attribute_options.dart, packages/amplify_core/lib/src/types/auth/attribute/update_user_attributes_options.dart, packages/amplify_core/lib/src/types/auth/password/confirm_reset_password_options.dart, packages/amplify_core/lib/src/types/auth/password/reset_password_options.dart, packages/amplify_core/lib/src/types/auth/password/update_password_options.dart, packages/amplify_core/lib/src/types/auth/session/fetch_auth_session_options.dart, packages/amplify_core/lib/src/types/auth/session/get_current_user_options.dart, packages/amplify_core/lib/src/types/auth/sign_in/confirm_sign_in_options.dart, packages/amplify_core/lib/src/types/auth/sign_in/sign_in_options.dart, packages/amplify_core/lib/src/types/auth/sign_in/sign_in_with_web_ui_options.dart, packages/amplify_core/lib/src/types/auth/sign_out/sign_out_options.dart, packages/amplify_core/lib/src/types/auth/sign_up/confirm_sign_up_options.dart, packages/amplify_core/lib/src/types/auth/sign_up/resend_sign_up_code_options.dart, packages/amplify_core/lib/src/types/auth/sign_up/sign_up_options.dart, packages/amplify_core/lib/src/types/models/model_field_definition.dart
- remove `UserAttributeKey`
- remove `serializeAsMap()` from auth types
=> chore: remove `UserAttributeKey`, `serializeAsMap()`

packages/secure_storage/amplify_secure_storage/ios/Resources/PrivacyInfo.xcprivacy, packages/secure_storage/amplify_secure_storage/ios/amplify_secure_storage.podspec, packages/secure_storage/amplify_secure_storage/macos/Resources/PrivacyInfo.xcprivacy, packages/secure_storage/amplify_secure_storage/macos/amplify_secure_storage.podspec
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/4789
- Add privacy manifest for user defaults API use
see: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401
=> chore: add privacy manifest for secure_storage

packages/auth/amplify_auth_cognito/example/integration_test/custom_auth_test.dart
- Update `expectLater` to use a callback
The updated tests are skipped, but are causing failures when run with flutter beta. The failures occur because although the `expectLater` matchers are skipped, the code still executes and results in an error. There must have been a change in behavior in a recent version of flutter_test in how async exceptions are handled. However, using a cb seems like a good best practice even if not required in most cases.
=> chore: update `expectLater` to use callback

packages/auth/amplify_auth_cognito_dart/lib/src/sdk/sdk_exception.dart, packages/auth/amplify_auth_cognito_dart/test/sdk/sdk_exception_test.dart, packages/auth/amplify_auth_cognito_dart/tool/generate_sdk_exceptions.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/4693
- Update LambdaException to use a generative constructor instead of a factory so that it can be extended
- Update `InvalidLambdaResponseException` `UnexpectedLambdaException`, and `UserLambdaValidationException` to extend `LambdaException`
- Map Lambda exceptions from the Cognito SDK to the equivalent Amplify exception
- Add tests for `transformSdkException`
All Lambda exceptions from the SDK are currently mapped to a generic LambdaException. The underlying exception is an exception from the SDK which is private. As a result, customers have no way to determine what type of Lambda exception occurred (without doing something hacky like string matching on the underlying exception). …
=> fix: map Lambda exceptions correctly

packages/aft/lib/src/command_runner.dart, packages/aft/lib/src/commands/review_command.dart
Adds `review` for generating code review requests text. 
Example usage: `$ aft review -r 4793 -p high`
=> feat(aft): Adds `review` for generating code review requests text

packages/amplify_datastore/ios/Classes/FlutterApiPlugin.swift, packages/amplify_datastore/ios/Classes/api/GraphQLResponse+Decode.swift
- add error decoding for GraphQL response and GraphQL subscription event
=> [flutter-datastore-v2] port graphql error decoding logic

README.md, packages/authenticator/amplify_authenticator/README.md
=> chore: update version in readme

packages/amplify_core/lib/src/types/storage/upload_file_operation.dart, packages/storage/amplify_storage_s3/example/integration_test/download_data_test.dart, packages/storage/amplify_storage_s3/example/integration_test/download_file_test.dart, packages/storage/amplify_storage_s3/example/integration_test/upload_file_test.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart
- wait for in progress requests to cancel before completing `.pause()` and `.cancel()`. 
- add tests for multiple files sizes for pause/resume/cancel
- skip `.cancel()` tests for download. These are failing on flutter beta and it is not immediately obvious why. Further investigation is required.
The main change in this PR is to wait to complete the `.pause()` and `.cancel()` futures until in flight requests have been cancelled. There are a few motivations for this:
1. This resolved e2e test failures on Flutter beta. The cancelled networks requests which were completing after `.pause()` and `.cancel()` return are resulting in errors being thrown after tests complete. As of Flutter 3.22 these will result in test failures.
2. When a multi part upload is paused or …
=> fix: wait for in progress requests to cancel before completing `.pause()` and `.cancel()`

packages/common/amplify_db_common_dart/CHANGELOG.md, packages/common/amplify_db_common_dart/pubspec.yaml, pubspec.yaml
- fix(common): set upper bound limit for sqlite version for `drift` compatibility ([#4884](https://github.com/aws-amplify/amplify-flutter/pull/4884))
=> chore(version): Bump version

packages/amplify_datastore/example/lib/models/CustomTypeWithAppsyncScalarTypes.dart, packages/amplify_datastore/example/lib/models/ModelWithCustomType.dart, packages/api/amplify_api_dart/test/graphql_test.dart, packages/api/amplify_api_dart/test/mocks.dart, packages/api/amplify_api_dart/test/test_models/CustomTypeWithAppsyncScalarTypes.dart, packages/api/amplify_api_dart/test/test_models/ModelWithCustomType.dart
https://github.com/aws-amplify/amplify-flutter/issues/4872
- Adds a unit test for model decoding AppSync Scalar types.
- Regenerates models based off https://github.com/aws-amplify/amplify-codegen/pull/843 
=> chore(api): added unit test for GraphQL custom types

packages/amplify_datastore/example/ios/Runner.xcodeproj/project.pbxproj, packages/amplify_datastore/example/ios/unit_tests/GraphQLResponse+DecodeTests.swift, packages/amplify_datastore/ios/Classes/api/GraphQLResponse+Decode.swift
- add unit tests for GraphQLResposne decoding logic
- 
=> test(swift-datastore): add unit tests for GraphQLResposne decoding logic

packages/analytics/amplify_analytics_pinpoint_dart/test/endpoint_client_test.dart, packages/notifications/push/amplify_push_notifications_pinpoint/lib/src/pinpoint_provider.dart, packages/notifications/push/amplify_push_notifications_pinpoint/test/pinpoint_provider_test.dart
*Issue #, if available:* #4688
- updated to catch to handle `NetworkException` instead of `AWSHttpException`, since the endpoint client does not throw `AWSHttpException`; it throws `NetworkException` instead.
=> fix(notifications): allow offline configuration

packages/amplify_datastore/example/ios/Runner.xcodeproj/project.pbxproj, packages/amplify_datastore/example/ios/unit_tests/GraphQLRequestExtensionTests.swift, packages/amplify_datastore/example/ios/unit_tests/PublisherExtensionTests.swift
- add unit test cases for extension functions
=> test(swift): add unit test cases for extension functions

packages/amplify_datastore/ios/internal/AWSDataStorePlugin/Sync/InitialSync/InitialSyncOperation.swift, packages/amplify_datastore/ios/internal/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, packages/amplify_datastore/ios/internal/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, packages/amplify_datastore/ios/internal/AWSDataStorePlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, packages/amplify_datastore/ios/internal/AWSPluginsCore/Auth/AWSAuthModeStrategy.swift, packages/amplify_datastore/ios/internal/AWSPluginsCore/Auth/AmplifyAuthorizationType.swift, packages/amplify_datastore/ios/internal/Amplify/Categories/API/Operation/RetryableGraphQLOperation.swift
Regen Amplify Swift Plugin by running `aft generate amplify-swift -b flutter-datastore-v2`
=> chore(datastore): Regenerate Amplify Swift Plugins

packages/amplify_datastore/ios/Classes/FlutterApiPlugin.swift
The `Set` operations are not thread-safe.
=> fix(datastore): crash when insert cancellables

packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/pigeons/NativePluginBindings.kt, packages/amplify_datastore/example/ios/unit_tests/GraphQLResponse+DecodeTests.swift, packages/amplify_datastore/ios/Classes/FlutterApiPlugin.swift, packages/amplify_datastore/ios/Classes/api/GraphQLRequest+Extension.swift, packages/amplify_datastore/ios/Classes/api/GraphQLResponse+Decode.swift, packages/amplify_datastore/ios/Classes/pigeons/NativePluginBindings.swift, packages/amplify_datastore/ios/internal/AWSDataStorePlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventToAnyModelMapper.swift, packages/amplify_datastore/lib/amplify_datastore.dart, packages/amplify_datastore/lib/src/native_plugin.g.dart, packages/amplify_datastore/lib/src/utils/native_api_helpers.dart, packages/amplify_datastore/pigeons/native_plugin.dart
- This resolves multi auth issues by enabling the auth mode to be passed from the Swift project to Flutter. 
- Modifies subscription stream errors to conform to Swift's error Json structure. 
- Improves decoding logic by passing `modelName` which should always have a value.
- Fix for cancellables crash
- GraphQL requests response now match AppSync response payloads
- Fix to allow initial sync to complete when a model does not have sufficient permissions before a user is signed in 
=> fix(datastore): Various integration bug fixes

packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt, packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/pigeons/NativePluginBindings.kt, packages/amplify_datastore/ios/Classes/FlutterApiPlugin.swift, packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift, packages/amplify_datastore/ios/Classes/pigeons/NativePluginBindings.swift, packages/amplify_datastore/ios/Classes/types/model/FlutterModelSchema.swift, packages/amplify_datastore/ios/internal/Amplify/Categories/Logging/LogLevel.swift, packages/amplify_datastore/ios/internal/Amplify/DefaultPlugins/AWSUnifiedLoggingPlugin/Internal/OSLogWrapper.swift, packages/amplify_datastore/lib/amplify_datastore.dart, packages/amplify_datastore/lib/src/native_plugin.g.dart, packages/amplify_datastore/pigeons/native_plugin.dart
Adds missing interface and method Amplify Swift DataStore to retrieve the auth type of a endpoint.
=> fix(datastore): added missing defaultAuthType method

packages/amplify_core/lib/src/config/amplify_config.dart, packages/amplify_core/lib/src/config/amplify_outputs/amplify_outputs.dart, packages/amplify_core/lib/src/config/amplify_outputs/amplify_outputs.g.dart, packages/amplify_core/lib/src/config/amplify_outputs/rest_api/rest_api_outputs.dart, packages/amplify_core/lib/src/config/amplify_outputs/rest_api/rest_api_outputs.g.dart, packages/amplify_core/lib/src/config/analytics/analytics_config.dart, packages/amplify_core/lib/src/config/api/api_config.dart, packages/amplify_core/lib/src/config/auth/auth_config.dart, packages/amplify_core/lib/src/config/storage/storage_config.dart, packages/amplify_core/test/config/amplify_outputs_mapping/amplify_outputs_mapping_test.dart
- mark all `to*Outputs()` methods as internal
- add rest API to AmplifyOutputs, add mapping from AmplifyOutputs to AmplifyConfig
- update AmplifyOutputs to allow for multiple GraphQL APIs, add custom json mapping
- add tests for multiple API plugins
=> chore: support multiple graphql or rest APIs

packages/amplify_datastore/lib/amplify_datastore.dart, packages/amplify_datastore/test/native_amplify_api_test.dart
Description of changes:
- Made _NativeAmplifyApi visible for testing purposes
- Added @visibleForTesting annotation
- Added unit tests for DataStores native API bridge interface
- query 
- mutate
- subscribe
- unsubscribe
=> chore(datastore): added unit tests for Amplify Api Native Bridge

packages/amplify_core/lib/src/config/amplify_outputs/auth/auth_outputs.dart, packages/amplify_core/lib/src/config/amplify_outputs/auth/oauth_outputs.dart, packages/amplify_core/lib/src/config/auth/auth_config.dart, packages/amplify_core/test/config/amplify_outputs_mapping/amplify_outputs_mapping_test.dart
- add support for auth config options missing from Amplify Outputs schema
=> chore: supporting missing auth config options

packages/amplify_core/lib/src/config/auth/auth_config.dart, packages/amplify_core/test/config/amplify_outputs_mapping/amplify_outputs_mapping_test.dart
- Update config mapping to map null passwordSettings to null passwordPolicy
=> chore: map null passwordSettings to null passwordPolicy

packages/amplify_datastore/test/native_amplify_api_test.dart
Unit tests in datastore were using generics with the name 'String' rather than 'T', which was difficult to distinguish from the actual primitive String.
=> chore(datastore): cleaned up generic types shadowing the keyword String

packages/amplify_core/doc/lib/auth.dart, packages/amplify_core/lib/src/category/amplify_auth_category.dart, packages/amplify_core/lib/src/http/amplify_category_method.dart, packages/amplify_core/lib/src/plugin/amplify_auth_plugin_interface.dart
- **feat: interface implementation for fetchCurrentDevice**
- **feat: added categories for fetchCurrentDevice**
Added interface implementation for fetchCurrentDevice API.
=> Feat (Auth): Interface Implementation for fetchCurrentDevice

packages/amplify_core/lib/src/config/amplify_outputs/amplify_outputs.g.dart, packages/amplify_core/lib/src/config/amplify_outputs/analytics/amazon_pinpoint_outputs.g.dart, packages/amplify_core/lib/src/config/amplify_outputs/analytics/analytics_outputs.g.dart, packages/amplify_core/lib/src/config/amplify_outputs/auth/auth_outputs.g.dart, packages/amplify_core/lib/src/config/amplify_outputs/auth/oauth_outputs.g.dart, packages/amplify_core/lib/src/config/amplify_outputs/auth/password_policy.g.dart, packages/amplify_core/lib/src/config/amplify_outputs/data/data_outputs.g.dart, packages/amplify_core/lib/src/config/amplify_outputs/notifications/notifications_outputs.g.dart, packages/amplify_core/lib/src/config/amplify_outputs/rest_api/rest_api_outputs.g.dart, packages/amplify_core/lib/src/config/amplify_outputs/storage/storage_outputs.g.dart, packages/amplify_core/lib/src/util/serializable.dart
- set checked to true for AmplifyOutputsSerializable
- this improves amplify configure api error message similar to #5021 
=> chore(core): add validation checks for AmplifyOutputs Json deserialization

packages/amplify_core/lib/src/types/api/graphql/graphql_response.dart
This changes the output of `GraphQLResponse.toString()` to include both `data` and `error` properties regardless of the presence of errors. Since a valid GraphQL response could contain a both, users previously would be missing context when errors were present. 
=> fix(api): GraphQLResponse.toString() include data & errors

packages/auth/amplify_auth_cognito/example/integration_test/device_tracking_test.dart, packages/auth/amplify_auth_cognito_dart/example/lib/common.dart, packages/test/amplify_integration_test/lib/src/stubs/amplify_auth_cognito_stub.dart
- **feat: added integration test suite**
- **feat: added methods for integration test suite**
Added integration test suites for `fetchCurrentDevice` API
=> Feat (Auth): Integration Tests for fetchCurrentDevice API

packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart
Implemented `fetchCurrentDevice` API
=> Feat: fetchCurrentDevice API Implementation

packages/notifications/push/amplify_push_notifications_pinpoint/lib/src/pinpoint_provider.dart, packages/notifications/push/amplify_push_notifications_pinpoint/test/pinpoint_provider_test.dart
*Issue #, if available:* #5109
- this is to allow Amplify Push Notifications to configure successfully when refresh token is expired.
=> fix(notifications): allow configuration when auth token is expired

packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/NativeAuthPluginWrapper.kt
- https://github.com/aws-amplify/amplify-flutter/issues/5120
- https://github.com/aws-amplify/amplify-flutter/issues/5116
- added an override to the native auth plugin
=> fix(datastore): prevent auth plugin from throwing during configuration

packages/secure_storage/amplify_secure_storage_dart/lib/src/utils/file_key_value_store.dart, packages/secure_storage/amplify_secure_storage_test/test/file_key_value_store_test.dart
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/5190
- Update FileKeyValueStore to process tasks one at a time in the order in which they are received to prevent multiple parallel file operations from corrupting the file
- Update readAll to log an error and clear the file contents if it is corrupted as it will be unreadable and unrecoverable
- Annotate readAll/writeAll as visible for testing
- add tests for in-memory fs and local fs
=> fix(secure_storage): process file system operations one at a time on Windows

packages/amplify_core/lib/src/config/amplify_outputs/api_outputs.dart, packages/amplify_core/lib/src/config/amplify_outputs/data/data_outputs.dart, packages/amplify_core/lib/src/config/amplify_outputs/rest_api/rest_api_outputs.dart, packages/amplify_core/test/config/amplify_outputs_mapping/amplify_outputs_mapping_test.dart, packages/api/amplify_api_dart/lib/src/api_plugin_impl.dart, packages/api/amplify_api_dart/lib/src/decorators/authorize_http_request.dart, packages/api/amplify_api_dart/lib/src/decorators/web_socket_auth_utils.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/blocs/web_socket_bloc.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/state/web_socket_state.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/types/web_socket_types.dart, packages/api/amplify_api_dart/lib/src/util/amplify_api_config.dart, packages/api/amplify_api_dart/lib/src/util/amplify_authorization_rest_client.dart, packages/api/amplify_api_dart/test/amplify_api_config_test.dart, packages/api/amplify_api_dart/test/authorize_http_request_test.dart, packages/api/amplify_api_dart/test/util.dart
- add a new ApiOutputs abstract interface
- DataOutputs and RestApiOutputs to implement the ApiOutputs
- Use ApiOutputs instead of AWSApiConfig type
=> chore(api): update endpoint config to use ApiOutputs instead of AWSApiConfig type

.github/workflows/actions.yaml, actions/pubspec.yaml, packages/aft/pubspec.yaml, packages/amplify/amplify_flutter/pubspec.yaml, packages/amplify_core/lib/src/config/amplify_outputs/auth/password_policy.g.dart, packages/amplify_core/pubspec.yaml, packages/analytics/amplify_analytics_pinpoint/example/pubspec.yaml, packages/api/amplify_api_dart/pubspec.yaml, packages/auth/amplify_auth_cognito_dart/pubspec.yaml, packages/aws_common/pubspec.yaml, packages/aws_signature_v4/pubspec.yaml, packages/aws_signature_v4/test/c_test_suite/context.g.dart, packages/smithy/smithy/lib/src/ast/traits/aws/protocols/aws_query_trait.g.dart, packages/smithy/smithy/lib/src/ast/traits/core/cors_trait.g.dart, packages/smithy/smithy/lib/src/ast/traits/core/length_trait.g.dart, packages/smithy/smithy/lib/src/ast/traits/http/http_trait.g.dart, packages/smithy/smithy/lib/src/ast/traits/test/http_malformed_response_definition.g.dart, packages/smithy/smithy/lib/src/ast/traits/test/http_response_test_case.g.dart, packages/smithy/smithy/lib/src/ast/traits/waiters/waiter.g.dart, packages/smithy/smithy/pubspec.yaml, packages/smithy/smithy_aws/pubspec.yaml, packages/smithy/smithy_aws/test/http/aws_retryer_test.g.dart, packages/smithy/smithy_codegen/pubspec.yaml, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_data_bytes_range.g.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_get_url_plugin_options.g.dart, packages/storage/amplify_storage_s3_dart/lib/src/model/s3_item.g.dart, packages/storage/amplify_storage_s3_dart/pubspec.yaml, packages/test/pub_server/pubspec.yaml, pubspec.yaml
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/5196
- update the "actions" GH actions workflow to run aft link
- Increase version range for json_annotation to `">=4.9.0 <4.10.0"`
- Increase version for json_serializable to 6.8.0
=> feat: bump json_annotation dependency to v4.9

packages/secure_storage/amplify_secure_storage/example/android/build.gradle, packages/secure_storage/amplify_secure_storage/example/ios/Flutter/AppFrameworkInfo.plist, packages/secure_storage/amplify_secure_storage/example/ios/Runner.xcodeproj/project.pbxproj, packages/secure_storage/amplify_secure_storage/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/secure_storage/amplify_secure_storage/example/ios/Runner/AppDelegate.swift, packages/secure_storage/amplify_secure_storage/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/secure_storage/amplify_secure_storage/lib/src/amplify_secure_storage.android.dart, packages/secure_storage/amplify_secure_storage/lib/src/amplify_secure_storage.vm.dart, packages/secure_storage/amplify_secure_storage/lib/src/amplify_secure_storage.web.dart, packages/secure_storage/amplify_secure_storage/pubspec.yaml, packages/secure_storage/amplify_secure_storage_dart/lib/src/amplify_secure_storage_dart.dart
https://github.com/aws-amplify/amplify-flutter/issues/5165
Readdresses #5178 with correct implementation based on suggestion from Flutter team and [Flutter docs](https://docs.flutter.dev/packages-and-plugins/developing-packages#dart-only-platform-implementations).
=> chore(secure_storage): Plugin Endorsement

infra-gen2/package-lock.json, infra-gen2/package.json, infra/package.json, infra/pnpm-lock.yaml
https://github.com/aws-amplify/amplify-flutter/security/dependabot/28
- Adds override for `"fast-xml-parser"` for both infra and infra-gen2
- Bumps all deps of infra-gen2
=> chore(infra): bump deps

packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart
- update sign-in state machine to use AmplifyOutputs instead of AmplifyConfig types
=> chore(auth): sign-in state machine to use AmplifyOutputs instead of AmplifyConfig types

packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart
- update the fetch auth session state machine to use AuthOutputs instead of AmplifyConfig types
=> chore(auth): fetch auth session state machine to use AmplifyOutputs instead of AmplifyConfig types

packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_out_state_machine.dart
- update sign out state machine to use AuthOutputs instead of CognitoUserPoolConfig
=> chore(auth): sign-out state machine to use AmplifyOutputs instead of AmplifConfig types

.github/composite_actions/launch_android_emulator/action.yaml, .github/composite_actions/launch_android_emulator/dist/main.cjs, .github/workflows/e2e_android.yaml, actions/bin/launch_android_emulator.yaml, actions/lib/src/android/sdk_manager.dart
- all the android projects use compileSdk 34 but our ci e2e tests were running with api 33, this updates the ci to run with api 34
- the android command line tools to use the current latest version ([ref](https://developer.android.com/studio#command-line-tools-only))
=> chore(actions): e2e android tests to run with API 34

packages/auth/amplify_auth_cognito/example/integration_test/federated_sign_in_test.dart, packages/auth/amplify_auth_cognito_dart/example/integration_test/hosted_ui_web_test.dart, packages/auth/amplify_auth_cognito_dart/lib/src/asf/asf_context_data_provider.dart, packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/credentials/cognito_keys.dart, packages/auth/amplify_auth_cognito_dart/lib/src/credentials/device_metadata_repository.dart, packages/auth/amplify_auth_cognito_dart/lib/src/flows/hosted_ui/hosted_ui_platform.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/credential_store_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/fetch_auth_session_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart, packages/auth/amplify_auth_cognito_test/lib/common/mock_config.dart, packages/auth/amplify_auth_cognito_test/test/flows/hostedui/hosted_ui_platform_test.dart, packages/auth/amplify_auth_cognito_test/test/plugin/auth_providers_test.dart, packages/auth/amplify_auth_cognito_test/test/plugin/delete_user_test.dart, packages/auth/amplify_auth_cognito_test/test/plugin/forget_device_test.dart, packages/auth/amplify_auth_cognito_test/test/plugin/remember_device_test.dart, packages/auth/amplify_auth_cognito_test/test/plugin/reset_password_test.dart, packages/auth/amplify_auth_cognito_test/test/plugin/sign_out_test.dart, packages/auth/amplify_auth_cognito_test/test/state/hosted_ui_state_machine_test.dart
- update CognitoIdentityPoolKeys to use identity pool Id instead of CognitoIdentityCredentialsProvider
- update CognitoUserPoolKeys to use user pool client id instead of CognitoUserPoolConfig
- update CognitoDeviceKeys to use user pool client id instead of CognitoUserPoolConfig
- update HostedUiKeys to use user pool client id instead of CognitoOAuthConfig
=> chore(auth): cognito keys to not use AmplifyConfig types

packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart
- hosted ui state machine to use AuthOutputs instead of CognitoOAuthConfig and CognitoIdentityCredentialsProvider types from AmplifyConfig
=> chore(auth): hosted ui state machine to not use AmplifyConfig types

packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/pigeons/NativePluginBindings.kt, packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift, packages/amplify_datastore/ios/Classes/pigeons/NativePluginBindings.swift, packages/amplify_datastore/lib/amplify_datastore.dart, packages/amplify_datastore/lib/src/native_plugin.g.dart, packages/amplify_datastore/pigeons/native_plugin.dart
https://github.com/aws-amplify/amplify-flutter/issues/5184
- Adds onStop() call back for Swift to Flutter
- Clears the Sync subscriptions onStop 
=> fix(datastore): Clear subscriptions on Stop

packages/auth/amplify_auth_cognito_dart/lib/src/credentials/device_metadata_repository.dart, packages/auth/amplify_auth_cognito_test/test/state/sign_in_state_machine_test.dart
- device metadata repository to get AuthOutputs instead of CognitoUserPoolConfig from dependency manager
=> chore(auth): device metadata repository to use AuthOutputs instead of CognitoUserPoolConfig

packages/amplify/amplify_flutter/lib/amplify_flutter.dart, packages/amplify_core/lib/amplify_core.dart, packages/amplify_core/lib/src/types/api/api_types.dart, packages/amplify_core/lib/src/types/api/graphql/web_socket_options.dart, packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/pigeons/NativePluginBindings.kt, packages/amplify_datastore/example/ios/Runner.xcodeproj/project.pbxproj, packages/amplify_datastore/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/amplify_datastore/example/ios/Runner/Info.plist, packages/amplify_datastore/example/lib/main.dart, packages/amplify_datastore/example/lib/queries_display_widgets.dart, packages/amplify_datastore/ios/Classes/FlutterApiPlugin.swift, packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift, packages/amplify_datastore/ios/Classes/api/GraphQLResponse+Decode.swift, packages/amplify_datastore/ios/Classes/pigeons/NativePluginBindings.swift, packages/amplify_datastore/lib/amplify_datastore.dart, packages/amplify_datastore/lib/src/native_plugin.g.dart, packages/amplify_datastore/pigeons/native_plugin.dart, packages/api/amplify_api_dart/lib/amplify_api_dart.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/blocs/subscriptions_bloc.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/blocs/web_socket_bloc.dart
https://github.com/aws-amplify/amplify-flutter/issues/5217
- Added Native Swift network monitor to listen to hardware level events
- Added callback for Swift to tell Flutter network was lost
- Logic to close Web socket on network loss
- Added an internal `WebSocketOptions` as a static way to turn off reconnection logic. This allows Swift DataStore remote sync engine to control when to reestablish the subscriptions.
**Note:** Currently there exists a delay in restarting the sync engine from a network loss event if the connection is not immediately reestablished. This is due to the retry/back off logic from the Swift remote sync engine. Once network is turned back on, DataStore will eventually restart the sync engine if it was previously …
=> fix(datastore): Restart Sync Engine when network on/off

packages/auth/amplify_auth_cognito_dart/lib/src/asf/asf_context_data_provider.dart
- asf context data provider to get AuthOutputs instead of CognitoUserPoolConfig from dependency manager
=> chore(auth): asf context data provider to use AuthOutputs instead of CognitoUserPoolConfig

packages/auth/amplify_auth_cognito_test/test/plugin/fetch_current_device_test.dart
- fix the fetch current device test. this may have happened after merging the fetch current device changes and the auth refactoring change that removed the userPoolConfig from `packages/auth/amplify_auth_cognito_test/lib/common/mock_config.dart`
=> chore(auth): fix fetch current device test

.devcontainer/Dockerfile
- update the Dockerfile to use ubuntu image from the amazon ECR public gallery instead of docket hub
=> chore(dev): use ubuntu image from amazon ECR public gallery instead of docket hub

packages/api/amplify_api_dart/lib/src/graphql/web_socket/types/web_socket_types.dart, packages/api/amplify_api_dart/test/web_socket/web_socket_types_test.dart
Adds error handling when web socket error type is a Map.
=> fix(api): web socket error handling

packages/amplify_datastore/example/ios/unit_tests/AmplifySerializedModelUnitTests.swift, packages/amplify_datastore/example/ios/unit_tests/resources/FlutterSerializedModelData.swift, packages/amplify_datastore/ios/Classes/types/model/FlutterSerializedModel.swift
https://github.com/aws-amplify/amplify-flutter/issues/5162
DataStore's `FlutterSerializedModel.extractJsonValue` had the incorrect return time for a json value of `null`. [Amplify Swift library expects](https://github.com/aws-amplify/amplify-swift/blob/cb80b91c38d99932af28df6be07633ee0563be08/Amplify/Categories/DataStore/Model/JSONHelper/JSONValueHolder.swift#L33-L34) it to be `.some(nil)`. 
=> fix(datastore): FlutterSerializedModel.extractJsonValue returns `.some(nil)` instead of `nil`

.github/workflows/issue_closed.yml, .github/workflows/issue_comment.yml, .github/workflows/issue_labeled.yml, .github/workflows/issue_opened.yml
- Adds GH actions for issue open, issue close, issue comment, and issue label events
GH actions copied from Amplify Android (https://github.com/aws-amplify/amplify-android/tree/main/.github/workflows) with "notify" jobs removed  
=> chore: add GH actions for issue open, close, comment, label events

packages/secure_storage/amplify_secure_storage/pubspec.yaml
it's fixing #5361
*Issue*
#5361 
I just added macOS plugin to pubspec, it works now, I think we also need to bump new version to amplify_secure_storage: 0.5.6
=> fix(secure_storage): add missing macOS plugin

packages/amplify/amplify_flutter/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/analytics/amplify_analytics_pinpoint/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/api/amplify_api/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/auth/amplify_auth_cognito/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/authenticator/amplify_authenticator/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/authenticator/amplify_authenticator_test/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/secure_storage/amplify_secure_storage/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/storage/amplify_storage_s3/example/macos/Flutter/GeneratedPluginRegistrant.swift
- Follow up to https://github.com/aws-amplify/amplify-flutter/pull/5372 to update the plugin registrant in example apps
=> chore: update plugin registrant for example apps that depend on secure storage

packages/aws_common/lib/src/config/aws_service.dart
Simply ran `aft generate sdk --include=aws_common`. This adds new service definitions. 
=> feat(aws_common): Generated new AWSService constructors

packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/credential_store_state_machine.dart, packages/auth/amplify_auth_cognito_test/test/state/credential_store_state_machine_test.dart
- update credential store state machine to use AuthOutputs instead of AuthConfiguration from the dependency manager
=> chore(auth): credential store state machine to use AuthOutputs instead of AmplifyConfig types

packages/api/amplify_api_dart/lib/src/decorators/web_socket_auth_utils.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/services/web_socket_service.dart, packages/api/amplify_api_dart/test/util.dart, packages/api/amplify_api_dart/test/web_socket/web_socket_auth_utils_test.dart, packages/api/amplify_api_dart/test/web_socket/web_socket_service_test.dart
- move subscription headers from query params to web socket protocol
AppSync has added support for headers via ws protocol, which is now preferred over using query parameters
=> feat: move App Sync subscription headers to protocol

.github/dependabot.yaml, packages/aft/lib/src/commands/generate/generate_workflows_command.dart
- Exclude the mono repo snapshot in aft/test from dependabot.yaml generation
- regenerate dependabot.yaml
=> chore: update `aft generate workflows`, regenerate dependabot.yaml

packages/aft/lib/src/repo.dart, packages/aft/test/version_bump/data/snapshots/multi_package_update.diff, packages/aft/test/version_bump/data/snapshots/multi_package_update_with_breaking_common.diff, packages/aft/test/version_bump/data/snapshots/single_dart_package_feat.diff, packages/aft/test/version_bump/data/snapshots/single_package_feat.diff, packages/aft/test/version_bump/version_bump_test.dart
1. Propagate version bumps n levels deep (instead of only 2 levels deep) and propagate version bumps when a component's config requires propagation (opposed to only for breaking changes)
- ex: if amplify_auth_cognito receives a minor bump, this should result in a minor bump to amplify_core (since it is part of the same component) AND a patch bump to any package that depends on amplify_core (this was not happening)
2. Do not update a dependency constraints in all dependent packages for non-breaking changes (unless the dependent is part of the same component and that component requires propagation)
- ex: if amplify_auth_cognito_dart has a patch bump, the dependency constraints for amplify_auth_cognito_dart in amplify_auth_cognito do not need to be updated
3. Add a …
=> chore: fix `aft version-bump`

packages/auth/amplify_auth_cognito/lib/src/credentials/legacy_credential_provider_android.dart, packages/auth/amplify_auth_cognito/lib/src/credentials/legacy_credential_provider_impl.dart, packages/auth/amplify_auth_cognito/lib/src/credentials/legacy_credential_provider_ios.dart, packages/auth/amplify_auth_cognito/lib/src/credentials/legacy_ios_cognito_keys.dart, packages/auth/amplify_auth_cognito_dart/lib/src/credentials/legacy_credential_provider.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/credential_store_state_machine.dart, packages/auth/amplify_auth_cognito_test/lib/common/mock_legacy_credential_provider.dart, packages/auth/amplify_auth_cognito_test/test/state/credential_store_state_machine_test.dart
- legacy credential provider to use AuthOutputs instead of AmplifyConfig types
- legacy ios cognito keys to have an String field instead of CognitoUserPoolConfig
- credential store state machine to use AuthOutputs instead of AuthConfiguration
=> chore(auth): legacy credential provider to use AuthOutputs instead of AmplifyConfig types

packages/amplify_core/lib/src/types/exception/amplify_exception.dart, packages/amplify_core/lib/src/types/exception/storage/invalid_storage_bucket_exception.dart, packages/amplify_core/lib/src/types/storage/bucket_info.dart, packages/amplify_core/lib/src/types/storage/storage_bucket.dart, packages/amplify_core/lib/src/types/storage/storage_bucket_from_outputs.dart, packages/amplify_core/lib/src/types/storage/storage_types.dart
- Add StorageBucket and BucketInfo to storage types
- Add InvalidStorageBucketException to storage exceptions
=> feat(core): add storage bucket type

packages/amplify_core/lib/src/types/storage/storage_bucket_from_outputs.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/s3_client_info.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- update storage bucket from outputs to get the bucket info from storage outputs
- update storage service to create and cache s3 clients based on the bucket info
- update storage service to move sigv4 signer fields to getUrl method as they are used only by this method.
=> feat(storage): update s3 storage service to support multiple s3 client for multi-bucket support

packages/aft/test/version_bump/data/repo_snapshot/packages/aws_common/pubspec.yaml, packages/aft/test/version_bump/data/repo_snapshot/pubspec.yaml, packages/auth/amplify_auth_cognito_dart/example/pubspec.yaml, packages/aws_common/pubspec.yaml, packages/test/pub_server/lib/src/server.dart, packages/test/pub_server/pubspec.yaml, pubspec.yaml
*Issue #, if available:* #5564 
- update mime version to ^2.0.0
P.S. the range is needed bc shelf_multipart has dependecy on mime: ^1.0.0. I updated the shelf_multipart version to v2 eventhough the v2 is still using mime:^1.0.0. 
=> chore(dep): update mime version to ^2.0.0

packages/api/amplify_api/lib/amplify_api.dart, packages/api/amplify_api/lib/src/api_plugin_impl.dart, packages/api/amplify_api/lib/src/flutter_life_cycle.dart, packages/api/amplify_api_dart/lib/amplify_api_dart.dart, packages/api/amplify_api_dart/lib/src/api_plugin_impl.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/blocs/web_socket_bloc.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/types/process_life_cycle.dart, packages/api/amplify_api_dart/lib/src/graphql/web_socket/types/web_socket_event.dart, packages/api/amplify_api_dart/test/graphql_test.dart, packages/api/amplify_api_dart/test/util.dart, packages/api/amplify_api_dart/test/web_socket/web_socket_bloc_test.dart
Issue #, if available:
#5041 
Description of changes:
Added an app life cycle stream/listener to reconnect API web sockets after the app is paused and resumed.
=> fix(api): app life cycle 'resume' triggers web socket reconnection

packages/amplify_core/lib/src/types/storage/remove_options.dart, packages/storage/amplify_storage_s3/example/integration_test/remove_test.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/object_exists.dart, packages/storage/amplify_storage_s3/example/integration_test/utils/tear_down.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- Updates `StorageRemoveOptions` to have a optional bucket param to specify target for operation
- Updates S3 impl to use bucket param
- Adds E2E tests
- Adds E2E utils
=> feat(storage): multi bucket remove

packages/amplify_core/lib/src/types/storage/download_data_options.dart, packages/storage/amplify_storage_s3/example/integration_test/download_data_test.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- Updates `StorageDownloadDataOptions` to have a optional bucket param to specify target for operation
- Updates S3 impl to use bucket param
- Adds E2E tests
=> feat(storage): multi bucket download data

packages/amplify_core/lib/src/category/amplify_storage_category.dart, packages/amplify_core/lib/src/plugin/amplify_storage_plugin_interface.dart, packages/amplify_core/lib/src/types/storage/upload_data_options.dart, packages/storage/amplify_storage_s3/example/integration_test/download_data_test.dart, packages/storage/amplify_storage_s3/example/integration_test/get_properties_test.dart, packages/storage/amplify_storage_s3/example/integration_test/remove_test.dart, packages/storage/amplify_storage_s3/example/integration_test/upload_data_test.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart
- fix upload data api to move optional bucket param from api param to StorageUploadDataOptions
- update unit tests
- add e2e tests for upload data 
=> chore(storage): add e2e tests for upload data api

packages/amplify_core/lib/src/types/storage/remove_many_options.dart, packages/storage/amplify_storage_s3/example/integration_test/remove_many_test.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart
- update remove many api to support multi-bucket
- add e2e tests
=> feat(storage): multi bucket remove many api

packages/amplify_core/lib/src/types/storage/get_url_options.dart, packages/storage/amplify_storage_s3/example/integration_test/get_url_test.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart, packages/storage/amplify_storage_s3_dart/test/amplify_storage_s3_dart_test.dart
- Updated `getUrl` api to accept an optional bucket parameter
- Added Unit tests 
- Corrected previous multi bucket tests that were placed in the wrong group.
- Added E2E test
=> feat(storage): multi bucket get url

packages/authenticator/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart
https://github.com/aws-amplify/amplify-flutter/issues/5655
- Added missing `yield*` for reset password work flow
Without this the UI on web would be hard locked and unable to return or progress to other screens. 
=> fix(authenticator): recover from exceptions during reset password flow

packages/amplify_core/lib/src/types/storage/bucket_info.dart, packages/amplify_core/lib/src/types/storage/copy_buckets.dart, packages/amplify_core/lib/src/types/storage/copy_options.dart, packages/amplify_core/lib/src/types/storage/download_data_options.dart, packages/amplify_core/lib/src/types/storage/download_file_options.dart, packages/amplify_core/lib/src/types/storage/get_properties_options.dart, packages/amplify_core/lib/src/types/storage/get_url_options.dart, packages/amplify_core/lib/src/types/storage/list_options.dart, packages/amplify_core/lib/src/types/storage/remove_many_options.dart, packages/amplify_core/lib/src/types/storage/remove_options.dart, packages/amplify_core/lib/src/types/storage/storage_bucket.dart, packages/amplify_core/lib/src/types/storage/storage_bucket_from_outputs.dart, packages/amplify_core/lib/src/types/storage/storage_types.dart, packages/amplify_core/lib/src/types/storage/upload_data_options.dart, packages/amplify_core/lib/src/types/storage/upload_file_options.dart, packages/storage/amplify_storage_s3/example/integration_test/copy_test.dart, packages/storage/amplify_storage_s3_dart/lib/src/amplify_storage_s3_dart_impl.dart, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart
- Corrected toJson() for Storage Option classes
- Updated copy api to accept an optional buckets parameter
- Added tests
=> feat(storage): multi bucket copy

packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
#5670 
Only allow 1 upload batch to queue up at a time.
=> fix(storage): Only allow 1 batch to run at a time

infra-gen2/package-lock.json, infra-gen2/package.json, packages/analytics/amplify_analytics_pinpoint/CHANGELOG.md, packages/analytics/amplify_analytics_pinpoint/pubspec.yaml, packages/authenticator/amplify_authenticator/CHANGELOG.md, packages/authenticator/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/authenticator/amplify_authenticator/lib/src/version.dart, packages/authenticator/amplify_authenticator/pubspec.yaml, packages/common/amplify_db_common/CHANGELOG.md, packages/common/amplify_db_common/example/pubspec.yaml, packages/common/amplify_db_common/example/windows/CMakeLists.txt, packages/common/amplify_db_common/pubspec.yaml, packages/common/amplify_db_common/windows/CMakeLists.txt, packages/storage/amplify_storage_s3/CHANGELOG.md, packages/storage/amplify_storage_s3/pubspec.yaml, packages/storage/amplify_storage_s3_dart/CHANGELOG.md, packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/task/s3_upload_task.dart, packages/storage/amplify_storage_s3_dart/pubspec.yaml, packages/storage/amplify_storage_s3_dart/test/storage_s3_service/task/s3_upload_task_test.dart
chore(version): Bump version
- fix(authenticator): recover from exceptions during reset password flow ([#5672](https://github.com/aws-amplify/amplify-flutter/pull/5672))
- fix(common): added a flag to opt out of bundling sqlite3 for windows apps ([#5680](https://github.com/aws-amplify/amplify-flutter/pull/5680))
- fix(storage): Only allow 1 batch to run at a time ([#5704](https://github.com/aws-amplify/amplify-flutter/pull/5704))
=> chore(version): Bump version 2.5.1

infra-gen2/package-lock.json, infra-gen2/package.json, infra/pnpm-lock.yaml, packages/amplify_core/test/config/amplify_outputs_mapping/app/package-lock.json, packages/amplify_core/test/config/amplify_outputs_mapping/app/package.json
updated cross-spawn package to fix dependabot security issue
https://github.com/aws-amplify/amplify-flutter/security/dependabot/37
updated cross-spawn to 7.0.6 wherever it is used
=> chore(dependency): updated cross-spawn package to fix security issue

packages/amplify_core/lib/src/types/auth/attribute/auth_user_attribute_key.dart, packages/amplify_core/lib/src/types/auth/attribute/cognito_user_attribute_key.dart, packages/amplify_datastore/lib/src/utils/native_api_helpers.dart, packages/api/amplify_api_dart/lib/src/graphql/factories/graphql_request_factory.dart, packages/authenticator/amplify_authenticator/lib/src/blocs/auth/auth_bloc.dart, packages/authenticator/amplify_authenticator/lib/src/screens/authenticator_screen.dart, packages/authenticator/amplify_authenticator/lib/src/widgets/form_fields/sign_in_form_field.dart, packages/aws_common/lib/src/http/aws_http_client_js.dart
=> fix(aws_common): removed JS streamed requests

.github/workflows/actions.yaml, .github/workflows/aft.yaml
cleanup references to the now delete "next" branch in Github Actions
=> chore(): cleanup stale branch references in Github Actions

.github/composite_actions/setup_firefox/action.yaml, .github/workflows/dart_dart2js.yaml, .github/workflows/dart_ddc.yaml, .github/workflows/dart_native.yaml, .github/workflows/dart_vm.yaml
Updated browser-actions/setup-firefox to [v1.5.3+](https://github.com/browser-actions/setup-firefox/blob/master/CHANGELOG.md#153-2025-01-19) to support compression changes for linux downloads.
Updated actions/cache to v4.2.0 as [v3.3.2 ](https://github.com/actions/cache/blob/main/RELEASES.md#420)was deprecated
=> chore(): Updated browser-actions/setup-firefox and actions/cache version

packages/aws_signature_v4/lib/src/signer/aws_signer.dart
#6008 
Web builds send an OPTions request to verify CORS compatibility with the URL and a 404 can be returned if the URL contains unexpected query Parameters. URI.toString() appends a "?" to the URL for an empty query parameter map and we are currently setting null a query parameter to an empty map. 
This fix converts empty query parameters to null if it empty to prevent the URL from unintentionally having a "?" appended. 
=> fix(sigv4): Convert empty query parameters to null

packages/auth/amplify_auth_cognito/example/integration_test/mfa_sms_email_required_test.dart
Cognito now requires selection of MFA type as an auth step if both sms and email are enabled, updating our sms + email test to reflect these changes
=> chore(test): added mfa selection in sms mfa required test

packages/auth/amplify_auth_cognito_dart/lib/src/auth_plugin_impl.dart, packages/auth/amplify_auth_cognito_dart/lib/src/model/signout/cognito_sign_out_result.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_out_state_machine.dart, packages/auth/amplify_auth_cognito_dart/lib/src/state/state/sign_out_state.dart, packages/auth/amplify_auth_cognito_test/test/plugin/sign_out_test.dart, packages/test/amplify_auth_integration_test/lib/src/test_runner.dart
#6205 
_onInitiate in our sign out state machine function catches only two exceptions, we add a catch all that also clears the credential store in this PR to handle other cases. Notably this allows users to exit a bad state where they would be unable to sign in or out properly if they have refresh token rotation enabled (linked issue), which causes the `REFRESH_TOKEN_AUTH` flow to be disabled.
=> fix(auth): handle fallthrough exceptions in sign out state

packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/FlutterAuthProvider.kt
[6263](https://github.com/aws-amplify/amplify-flutter/issues/6263)
Updated getToken to extract the oidc token from the getLatestAuthToken result
=> fix(datastore): corrected getToken return value for oidc

packages/authenticator/amplify_authenticator/lib/amplify_authenticator.dart, packages/authenticator/amplify_authenticator/lib/src/widgets/form.dart
[#3513](https://github.com/aws-amplify/amplify-flutter/issues/3513)
export social_button to amplify_authenticator dart package for public use out of the box
=> chore(authenticator): expose social_button
